### ISSUE TITLE
【提问】如何应对Cookies中的SESSDATA和bili_jct频繁刷新

### ISSUE THREAD

**Issue by nicliuqi** [Nemo2011/bilibili-api#100]
**Python 版本：** 3.8.5

**模块版本：** 3.1.3

**运行环境：** Linux

---

无论是在3.1.3的bilibili_api.utils.Verify，抑或是当前最新版的bilibili_api.utils.Credential，用户认证都需要用到Cookies中的SESSDATA和bili_jct。尽管这种方式和大多SDK的AK/SK认证不同，但在过去两年左右时间里，我们的服务使用bilibili_api进行自动上传视频总是能成功，这归功于Cookies中的SESSDATA和bili_jct在很长一段时间保持不变。
但最近，总会因为SESSDATA和bili_jct频繁变动，导致自动上传视频失败。
因此，我想了解了解SESSDATA和bili_jct的刷新机制，以及如何去避免因SESSDATA和bili_jct刷新而造成的上传失效，或者还有其他方法能实现用户持久的认证吗？
希望能尽快收到回复，感谢！

**Comment by Nemo2011** [comment]
要么自动登录，要么（ ~~我也是这样的啊~~

**Comment by Nemo2011** [comment]
这时候只能重新导入

**Comment by Nemo2011** [comment]
可以试一下绑定邮箱等等，总之让账号变成安全的，这样子 cookies 应该不会频繁刷新

**Comment by nicliuqi** [comment]
> 可以试一下绑定邮箱等等，总之让账号变成安全的，这样子 cookies 应该不会频繁刷新

好的，请问绑定邮箱后大概一套sessdata和bili_jct能持续多久

**Comment by Nemo2011** [comment]
没测过，也许也还是没用。你可以试一试。

**Comment by Nemo2011** [comment]
有进展了，https://passport.bilibili.com/x/passport-login/web/cookie/info?csrf={bili_jct} web 刷新，正在深入研究

**Comment by nicliuqi** [comment]
好的 多谢

**Comment by Camouflager** [comment]
LZ解决了吗，能分享下怎么调用吗
