### ISSUE TITLE
【提问】有尝试过分析哪种调用可以保证每天自动登录(即获取1硬币)吗？

### ISSUE THREAD

**Issue by cabinary** [Nemo2011/bilibili-api#103]
**Python 版本：** All

**模块版本：** All

**运行环境：** All

---

我此前长期使用的方式是携带着Cookies然后使用selenium打开主页维持一段时间（但是拒绝一切的图像文件啥的接受）。然后重保存整个Cookies的。因为懒所以一直没分析过具体会是api还是主页的请求本身是一个动态页面，导致在获取template的同时就更新该会话的登录状态，还是因为发送了某个心跳请求，或是登录接口本身做校验。
简而言之，我需要最小化自动登录（签到）的手续（对于Cookies的有效性校验我有方法，但是自动登录经过上次有出错的前提下我不保证一定成功，因此废弃该方案，但凡Cookies失效就拉Error，主动更新一遍Cookies）。

**Comment by Nemo2011** [comment]
理论上携带 cookies 用 urllib 打开主页就可以了，就是 cookies 更新可能做不到。在模拟浏览器这一点上，还是用 selenium 好一点。如果想要最小化的话可以用 Chrome 加上  `--headless` 参数启动，甚至没有窗口。

**Comment by Nemo2011** [comment]
至于 API 的话，理论上随便调用任意 API 都可以的。

**Comment by cabinary** [comment]
> 

只需要请求一遍主页吗?而不是查看个人信息时会蹦出来一个ajax，然后那个作为登录？……或者我找个时间试试吧。

**Comment by Nemo2011** [comment]
有进展了，`https://passport.bilibili.com/x/passport-login/web/cookie/info?csrf={bili_jct}` web 刷新，正在深入研究
