### ISSUE TITLE
求稿件编辑功能

### ISSUE THREAD

**Issue by Naxrin** [Nemo2011/bilibili-api#105]
如标题@_@
不清楚现在有没有，翻了一下changelog好像没有

**Comment by Nemo2011** [comment]
在找，预计下周更

**Comment by Nemo2011** [comment]
在等亿等

**Comment by Naxrin** [comment]
太谢谢了！

**Comment by Naxrin** [comment]
> https://github.com/Nemo2011/bilibili-api/releases/tag/14.0.0.a1

可是v14.0.0.a1这个分支的video_uploader里也没有找到VideoEditor呀？

**Comment by Nemo2011** [comment]
我懂了，这个 tag 是对应主分支的。可以把项目克隆到本地，切换至 `dev` 分支然后手动安装。

**Comment by Nemo2011** [comment]
在研究了，目前已经找到了 cookies 刷新的接口，但是还没有测试返回值。
