### ISSUE TITLE
找不到 credential.check_valid 方法

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#106]
https://nemo2011.github.io/bilibili-api/#/modules/bilibili_api?id=async-def-check_valid
![image](https://user-images.githubusercontent.com/78744121/204062439-0d930a5e-31cb-4198-a762-9c87f070e927.png)
![image](https://user-images.githubusercontent.com/78744121/204062450-db5201fa-332f-4ff7-91c5-fd352c09770b.png)

**Comment by Nemo2011** [comment]
先升级到最新版本再试试

**Comment by Nemo2011** [comment]
https://github.com/Nemo2011/bilibili-api/releases/tag/12.5.2

**Comment by z0z0r4** [comment]
ook！
