### ISSUE TITLE
【提问】转发他人的转发动态，结果转发的是源动态

### ISSUE THREAD

**Issue by MayYouBeProsperous** [Nemo2011/bilibili-api#107]
**Python 版本：** 3.9

**模块版本：** 13.3.0

**运行环境：** Windows 

---

使用 `dynamic` 的 [repost()](https://nemo2011.github.io/bilibili-api/#/modules/dynamic?id=async-def-repost) ，转发他人的转发动态

比如我想转发ID为 [732728181152284690](https://t.bilibili.com/732728181152284690) 的动态，执行结果却转发了它的源动态 [732714338481078288](https://t.bilibili.com/732714338481078288)

应该如何解决呢？

**Comment by Nemo2011** [comment]
麻烦看看清楚，本来就是这样子的。

**Comment by Nemo2011** [comment]
要不贴一下图，我看看是不是真的有问题

**Comment by MayYouBeProsperous** [comment]
> 麻烦看看清楚，本来就是这样子的。

谢谢您，我弄明白了。
项目很好用，点赞~
