### ISSUE TITLE
【提问】限流问题

### ISSUE THREAD

**Issue by L1nYong** [Nemo2011/bilibili-api#116]
换了代理IP还是返回412，是cookie被限流了嘛

**Comment by Nemo2011** [comment]
用的是代理池还是随便找的一个代理

**Comment by L1nYong** [comment]
经过测试发现cookie也会有问题，因为这个是搜索视频接口出现的，我用的是没登录的cookie

**Comment by Nemo2011** [comment]
接口应该是限制了你的 IP，等上几个小时就解封了。上面说换了代理 IP 也还是 412，很可能你执行的是大规模、快速的操作，这种情况要不被限流只能开代理池，光在一个代理上执行就相当于换一台电脑执行，也还是要小心的

**Comment by z0z0r4** [comment]
不建议换很多代理ip，账户可能会被冻结（我前几天玩嗨了（

**Comment by Nemo2011** [comment]
所以说，不建议快速访问 API
