### ISSUE TITLE
有关 Credential 自动刷新的新功能

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#121]
未来有啥功能可做的？想帮忙维护下

**Comment by Nemo2011** [comment]
让我想想……有了！

你可以试着去找一些目前模块仍然没有被涵盖的 API 或操作，还有最近的一个问题，就是 Cookies 刷新的问题。目前已经找到了网页接口 (https://passport.bilibili.com/x/passport-login/web/cookie/info?csrf={bili_jct} (需要携带 cookies))，但是后来我才发现要用浏览器模拟！所以如果可以的话麻烦研究一下这里。(TIPS: 这里可以不采用网页接口，用移动端也行 )。

当然，修复 bug 也很重要。

**Comment by z0z0r4** [comment]
移动端的话...我手机没刷root，也不会抓包，麻了
尽力中

**Comment by z0z0r4** [comment]
> 
[https://passport.bilibili.com/x/passport-login/web/cookie/info?csrf={bili_jct}](https://passport.bilibili.com/x/passport-login/web/cookie/info?csrf=%7Bbili_jct%7D)
这个似乎是验证当前是否需要刷新 cookie 的

**Comment by Nemo2011** [comment]
要不我明天再看一看？

**Comment by z0z0r4** [comment]
> 

看麻了

**Comment by Nemo2011** [comment]
B 站写的代码就是那种神仙来了都看不懂的代码

**Comment by Nemo2011** [comment]
没事，我们照着翻译就可以了，反正他们官方估计都要看不懂的

**Comment by Nemo2011** [comment]
因为不想折腾，我也懒得用 `pyexecjs` 运行 javascript 了，直接翻译成 python 得了。

**Comment by z0z0r4** [comment]
有点邪门，我试试看

**Comment by z0z0r4** [comment]
> 没事，我们照着翻译就可以了，反正他们官方估计都要看不懂的

我在TG群问了似乎压根没人用过这种方法，没法验证：(

**Comment by Nemo2011** [comment]
那只能考虑移动端了，或者就是 selenium

**Comment by z0z0r4** [comment]
selenium 的话是时不时访问下B占来刷新 cookie？

**Comment by Nemo2011** [comment]
应该是的。我觉得，最好是在访问主页后再访问一些其他页面，这样子可以刷新cookies。还有，如果要追求使用方便的话，可以用`pyppeteer`

**Comment by z0z0r4** [comment]
这下调试脱了hhhhh，不行，得整个小号
![image](https://user-images.githubusercontent.com/78744121/210085939-60176684-2971-4467-8d05-30a7d9010458.png)

**Comment by Nemo2011** [comment]
看来可以忙一忙登录需要验证的情况了。

https://ivan.hanloth.cn/index.php/archives/530
