### ISSUE TITLE
【需求】添加对笔记的支持

### ISSUE THREAD

**Issue by Nemo2011** [Nemo2011/bilibili-api#131]
需要添加对笔记的支持。目前决定这样子来设计：

- 1. 笔记 API 单独新建 `note.py`，建立 `Note` 类。
- 2. 因为笔记的正文就是专栏，所以要在 `Article` 类中添加对笔记的支持。（如果监测到专栏为笔记时，提供转 Note 类操作。因为笔记和专栏的格式有所不同，笔记是纯 json 而普通专栏是 html）

其他功能稍后拟定。

**Comment by z0z0r4** [comment]
链接一份 [参考资料](https://github.com/SocialSisterYi/bilibili-API-collect/tree/f2f1a52b5a2001d854cf204bc471510aae2a5344/note)

**Comment by z0z0r4** [comment]
> 

似乎私有笔记的获取方式与公开不同
私有需要 oid 和 note_id，而公开只需要 cvid

**Comment by z0z0r4** [comment]
> > 需要添加对笔记的支持。目前决定这样子来设计：
> > 
> > * 1. 笔记 API 单独新建 `note.py`，建立 `Note` 类。
> > * 2. 因为笔记的正文就是专栏，所以要在 `Article` 类中添加对笔记的支持。（如果监测到专栏为笔记时，提供转 Note 类操作。因为笔记和专栏的格式有所不同，笔记是纯 json 而普通专栏是 html）
> > 
> > 其他功能稍后拟定。
> 
> 似乎私有笔记的获取方式与公开不同 私有需要 oid 和 note_id，而公开只需要 cvid

私有笔记还得对应视频也就是avid...怪

**Comment by z0z0r4** [comment]
> 

没参与过开发，请问 attributes 的定义是写在？

**Comment by z0z0r4** [comment]
> 可以这么来做：在 `Note` 类中定义一个 `note_type` 和一个 `note_id`，根据 `note_type` 决定 `note_id` 是 `cvid` 还是 `note_id`，再把每个笔记都有的 `attributes` 定义好（对应的视频，内容）。API 调用就定义两套 API，一套是公有笔记的，一套是私有笔记的，调用的时候根据 `note_type` 选择一套 API 调用。

刚刚搞完获取笔记 detail info

**Comment by Nemo2011** [comment]
`attributes` 就是指类的属性(self.xxx = yyy)

**Comment by z0z0r4** [comment]
oo，指的是这个，我以为是把 Note 的返回值格式化一份...

> `attributes` 就是指类的属性(self.xxx = yyy)，一般在 **init** 函数定义，然后在后面的方法中可以使用。

**Comment by z0z0r4** [comment]
根据稿件、用户获取 Note_ids，我应该把方法写在 Video、User 类？
https://api.bilibili.com/x/note/list/archive

**Comment by z0z0r4** [comment]
另外请问 api 里面的 verity 项是什么意思呢emmm

**Comment by z0z0r4** [comment]
> 另外请问 api 里面的 verity 项是什么意思呢emmm

是否需要登录？

**Comment by Nemo2011** [comment]
是的，是否需要凭据。

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/pull/132
note action 没做...明天要返校了呜呜

**Comment by z0z0r4** [comment]
> 

video 部分的新增函数没做测试（接口做了
不知道写的能不能过标准，没参与过库的编写（（

**Comment by Nemo2011** [comment]
后续讨论移步至 #132
