### ISSUE TITLE
【建议】直播 连接关闭 的loging.exception 降低等级

### ISSUE THREAD

**Issue by whille** [Nemo2011/bilibili-api#136]
[ERROR] [/usr/local/lib/python3.9/dist-packages/bilibili_api_python-13.3.1-py3.9.egg/bilibili_api/live.py:981] 非正常关闭连接
我运行长时间服务发现非正常关闭的情况不少见， 如果ERROR level 报警较多，是不是降为warning 比较好？
即 self.logger.exception(e) ->  self.logger.warning(e)

**Comment by Nemo2011** [comment]
可否把非正常关闭时出现的 `log` 展示一下以便判断是否` LiveDanmaku` 关闭直播的逻辑问题。

**Comment by Nemo2011** [comment]
暂时先进行修改。但是不排除是连接服务器的代码有问题。

**Comment by whille** [comment]
你好，是不是抛出异常后在984行改self.logger.exception(e)为warning比较好？ 我理解对 retry-=1 还是有用，防止无限错误循环。
