### ISSUE TITLE
【提问】关于相簿

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#143]
**Python 版本：** 3.x.y

**模块版本：** x.y.z

**运行环境：** Windows / Linux / MacOS

---
album的api中的user_albums似乎应该在user类更合适
```
"user_albums": {
      "url": "https://api.vc.bilibili.com/link_draw/v1/doc/others",
      "method": "GET",
      "params": {
        "biz": "int: 分区，0 全部，1 画友，2 摄影",
        "poster_uid": "int: uid",
        "page_num": "int: 页码",
        "page_size":"int: 每页数据大小"
      },
      "comment": "获取指定用户的投稿的相簿"
    }
```
试图帮忙写点（

**Comment by Nemo2011** [comment]
可以，但是请转至 `feature-album` 分支提交。

**Comment by z0z0r4** [comment]
emm，关于获取摄影首页列表等等操作，我应该写在相簿类内还是直接写在 `album.py`

**Comment by Nemo2011** [comment]
算了，我觉得还是这样子好一点：除了获取单个相簿的信息以外，其他所有 `album.json` 里面的函数都放在相簿模块中（直接写在 `album.py`）。包括 `user_albums` 也放在 `album.py` 中。毕竟隔壁 `favorite_list` 中获取用户的视频收藏夹不也不是放在 `user.py` 中的吗。

**Comment by Nemo2011** [comment]
要不这样子，你先把相簿类写掉，我把其他相关的函数写一下。

**Comment by z0z0r4** [comment]
> 

相簿信息pr了
https://github.com/Nemo2011/bilibili-api/pull/145

但顺便提一句，https://h.bilibili.com/ 生命周期结束了吧...
最后一张图片是2021-06-18 18:35:39上传的
`link_draw` 这些api都不会有新内容了似乎...

**Comment by z0z0r4** [comment]
> 相簿信息pr了 #145
> 
> 但顺便提一句，https://h.bilibili.com/ 生命周期结束了吧... 最后一张图片是2021-06-18 18:35:39上传的 `link_draw` 这些api都不会有新内容了似乎...

不建议留着了...已经是过去式的接口了...

**Comment by Nemo2011** [comment]
所以你觉得阿B给了我们现在进行时的接口了吗？

**Comment by Nemo2011** [comment]
你可以自己去相簿分站看一看，然后就会发现：好家伙

**Comment by z0z0r4** [comment]
emm，那随便吧...就算没新的，也没啥必要留停更一年的接口吧

> 所以你觉得阿B给了我们现在进行时的接口了吗？
