### ISSUE TITLE
[提议] 使用URL解析库以改善 parse_link

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#147]
parse_link 里面包含很多针对解析 URL 的操作，如果能够调库会更简洁点？
如果支持的话我来整一份

**Comment by Nemo2011** [comment]
先别了吧，除非万不得已，否则我是觉得重构整个函数是很冒险的行为。`parse_link` 支持的链接可没有那么少，重构的话容易遗漏，而且写完之后大量的测试/修复也很耗时间。

**Comment by z0z0r4** [comment]
> 先别了吧，除非万不得已，否则我是觉得重构整个函数是很冒险的行为。`parse_link` 支持的链接可没有那么少，重构的话容易遗漏，而且写完之后大量的测试/修复也很耗时间。

看得出，emm，那么会在整个完成并测试之后再提

**Comment by z0z0r4** [comment]
https://github.com/z0z0r4/bilibili-api/tree/parse_link

> > 先别了吧，除非万不得已，否则我是觉得重构整个函数是很冒险的行为。`parse_link` 支持的链接可没有那么少，重构的话容易遗漏，而且写完之后大量的测试/修复也很耗时间。
> 
> 看得出，emm，那么会在整个完成并测试之后再提

**Comment by Nemo2011** [comment]
注意点：1. 对于任何的资源，parse_link 需要适配任何一个那个资源对应的 url。2. 需要对传入 url 进行不断的跳转操作，例如有些 `https://www.bilibili.com/video/BVxxxxxxxxxx` 的链接其实是番剧剧集，还有短链接。3. 对一些缩写提供支持，如 `BVxxxxxxxxxx`, `avxxxxxxxxxx`, `cvxxxxxxxxx`, 因为番剧和课程共用 `epxxxxxxxxxx`, `ssxxxxxxxxxx` 这类的缩写，所以对于  `epxxxxxxxxxx`, `ssxxxxxxxxxx` 不予判断。4. 有的时候一个视频链接跳转的最终目标不是视频页面，也不是番剧页面，也不是课程页面，这个时候就无法解析，目前就发现了一类像这里条所说的视频：拜年祭视频，对于这类的视频要予以支持。 差不多这些点吧，千万不要遗漏。

**Comment by Nemo2011** [comment]
最近我这里可能也会有一部分增强 `parse_link` 的提交，会写清楚每一个增强的点。

**Comment by z0z0r4** [comment]
我的目的是把类似于 url[:8] 平滑迁移到 yarl.URL("https://bilibili.com").scheme，这样看起来可读性高些
不过途中倒是发现了不少奇怪的操作，差不多了弄好了会来说明的

**Comment by z0z0r4** [comment]
> 我的目的是把类似于 `url[:8]` 平滑迁移到 `yarl.URL("https://bilibili.com").scheme`，这样看起来可读性高些 不过途中倒是发现了不少奇怪的操作，差不多了弄好了会来说明的

不过一路适配下来，似乎不太可能既完美迁移又不进行多余的 `yarl.URL` <-> `str` 转换，因为还是调用了一些外部函数的，比如 `short.py`

**Comment by z0z0r4** [comment]
> 我的目的是把类似于 `url[:8]` 平滑迁移到 `yarl.URL("https://bilibili.com").scheme`，这样看起来可读性高些 不过途中倒是发现了不少奇怪的操作，差不多了弄好了会来说明的

类似于
```
if url.scheme == "https" and url.host == "www.bilibili.com":
# if url[:27] == "https://space.bilibili.com/":
```

**Comment by z0z0r4** [comment]
目测这种解析方式再不做掉的话，迟早谁都不知道是啥，起码给个example吧呜呜...
https://github.com/Nemo2011/bilibili-api/blob/aad4b0362299162bf7dcf889ca21898ca7ad59fc/bilibili_api/utils/parse_link.py#L433-L438

**Comment by Nemo2011** [comment]
稍等，我明天给一份整理，列一下需要支持的所有 url 类型。

**Comment by z0z0r4** [comment]
parse_link 中很多不调用现成而是直接 httpx 请求 api 的操作是出于历史遗留又或性能考量？
感觉不是很适合日后维护，我顺便改改如何？
```
                    favorite_lists = json.loads(
                        httpx.get(
                            api["url"], params=params, cookies=credential.get_cookies()
                        ).text
                    )["data"]
```

**Comment by z0z0r4** [comment]
> parse_link 中很多不调用现成而是直接 httpx 请求 api 的操作是出于历史遗留又或性能考量？ 感觉不是很适合日后维护，我顺便改改如何？
> 
> ```
>                     favorite_lists = json.loads(
>                         httpx.get(
>                             api["url"], params=params, cookies=credential.get_cookies()
>                         ).text
>                     )["data"]
> ```

另外这个 `json.loads(resp.text)` 挺魔幻的，我记得httpx 应该自带了 json 解析操作吧？...

**Comment by z0z0r4** [comment]
建议：删去无用 `else`，直接 `return -1`
![image](https://user-images.githubusercontent.com/78744121/213873396-e1217ea5-f3ac-494e-8e44-fa3b765d115f.png)

**Comment by Nemo2011** [comment]
这里主要有以下原因……反正就是能用就用。

**Comment by Nemo2011** [comment]
整理了一下 `parse_link` 目前支持的所有链接，~~也就一点点而已吗~~

**注意：解析链接之前需要确定链接为初始链接最终跳转的目标**

**注意：`parse_link` 函数需要完全适配 `Credential`**

- 视频
  - `av114514` / `AV114514`
  - `BVY3LY3LYY3L`
  - `https://www.bilibili.com/video/av114514`
  - `https://www.bilibili.com/video/BVY3Ly3LYY3L`
- 互动视频
  解析出视频之后需要判断视频是否为互动视频。
- 番剧
  - `https://www.bilibili.com/bangumi/media/md114514`
- 番剧剧集
  - `https://www.bilibili.com/bangumi/play/ss114514`
  - `https://www.bilibili.com/bangumi/play/ep1919810`
- 收藏夹
  - `ml1919810` / `ML1919810`
  - `https://space.bilibili.com/114514/favlist`
  - `https://space.bilibili.com/114514/favlist?fid=1145142023&ftype=create`
  - `https://space.bilibili.com/114514/favlist?fid=1919810&ftype=collect&ctype=11`
  - `https://space.bilibili.com/114514/favlist?fid=articles`
  - `https://space.bilibili.com/114514/favlist?fid=pugvfav`
  - `https://www.bilibili.com/medialist/detail/ml1919810`
- 课程
  - `https://www.bilibili.com/cheese/play/ss114514`
  - `https://www.bilibili.com/cheese/play/ep1919810`
- 音频
  - `au114514` / `AU114514`
  - `https://www.bilibili.com/audio/au114514`
- 歌单
  - `am114514` / `AM114514`
  - `https://www.bilibili.com/audio/am114514`
- 专栏
  - `cv114514` / `CV114514`
  - `https://www.bilibili.com/read/cv114514`
- 用户
  - `uid114514` / `UID114514`
  - `https://space.bilibili.com`
  - `https://space.bilibili.com/114514`
- 直播间
  - `https://live.bilibili.com/114514`
- 合集与列表
  - `https://space.bilibili.com/114514/channel/collectiondetail?sid=1919810` (新版合集)
  - `https://space.bilibili.com/114514/channel/seriesdetail?sid=1919810` (旧版合集)
  - `https://www.bilibili.com/list/114514?sid=1919810&desc=1&oid=66509220&bvid=BVY3LY3LYY3L` (旧版合集)
  - `https://space.bilibili.com/114514/favlist?fid=1919180&ftype=collect&ctype=21` (新版合集)
- 文集
  - `https://www.bilibili.com/read/readlist/rl114514`
- 动态
  - `https://t.bilibili.com/114514114514114514`
- 小黑屋
  - `https://www.bilibili.com/blackroom/ban/114514`
- 游戏
  - `https://www.biligame.com/detail/?id=114514`
- 话题
  - `https://www.bilibili.com/v/topic/detail/?topic_id=114514`
- 漫画
  - `https://manga.bilibili.com/detail/mc114514`
- 相簿
  - `https://h.bilibili.com/114514`

**Comment by z0z0r4** [comment]
> 整理了一下 `parse_link` 目前支持的所有链接，~也就一点点而已吗~
> 
> **注意：解析链接之前需要确定链接为初始链接最终跳转的目标**
> 
> **注意：`parse_link` 函数需要完全适配 `Credential`**
> 
> * 视频
>   
>   * `av114514` / `AV114514`
>   * `BVY3LY3LYY3L`
>   * `https://www.bilibili.com/video/av114514`
>   * `https://www.bilibili.com/video/BVY3Ly3LYY3L`
> * 互动视频
>   解析出视频之后需要判断视频是否为互动视频。
> * 番剧
>   
>   * `https://www.bilibili.com/bangumi/media/md114514`
> * 番剧剧集
>   
>   * `https://www.bilibili.com/bangumi/play/ss114514`
>   * `https://www.bilibili.com/bangumi/play/ep1919810`
> * 收藏夹
>   
>   * `ml1919810` / `ML1919810`
>   * `https://space.bilibili.com/114514/favlist`
>   * `https://space.bilibili.com/114514/favlist?fid=1145142023&ftype=create`
>   * `https://space.bilibili.com/114514/favlist?fid=1919810&ftype=collect&ctype=11`
>   * `https://space.bilibili.com/114514/favlist?fid=articles`
>   * `https://space.bilibili.com/114514/favlist?fid=pugvfav`
>   * `https://www.bilibili.com/medialist/detail/ml1919810`
> * 课程
>   
>   * `https://www.bilibili.com/cheese/play/ss114514`
>   * `https://www.bilibili.com/cheese/play/ep1919810`
> * 音频
>   
>   * `au114514` / `AU114514`
>   * `https://www.bilibili.com/audio/au114514`
> * 歌单
>   
>   * `am114514` / `AM114514`
>   * `https://www.bilibili.com/audio/am114514`
> * 专栏
>   
>   * `cv114514` / `CV114514`
>   * `https://www.bilibili.com/read/cv114514`
> * 用户
>   
>   * `uid114514` / `UID114514`
>   * `https://space.bilibili.com`
>   * `https://space.bilibili.com/114514`
> * 直播间
>   
>   * `https://live.bilibili.com/114514`
> * 合集与列表
>   
>   * `https://space.bilibili.com/114514/channel/collectiondetail?sid=1919810` (新版合集)
>   * `https://space.bilibili.com/114514/channel/seriesdetail?sid=1919810` (旧版合集)
>   * `https://www.bilibili.com/list/114514?sid=1919810&desc=1&oid=66509220&bvid=BVY3LY3LYY3L` (旧版合集)
>   * `https://space.bilibili.com/114514/favlist?fid=1919180&ftype=collect&ctype=21` (新版合集)
> * 文集
>   
>   * `https://www.bilibili.com/read/readlist/rl114514`
> * 动态
>   
>   * `https://t.bilibili.com/114514114514114514`
> * 小黑屋
>   
>   * `https://www.bilibili.com/blackroom/ban/114514`
> * 游戏
>   
>   * `https://www.biligame.com/detail/?id=114514`
> * 话题
>   
>   * `https://www.bilibili.com/v/topic/detail/?topic_id=114514`
> * 漫画
>   
>   * `https://manga.bilibili.com/detail/mc114514`
> * 相簿
>   
>   * `https://h.bilibili.com/114514`

thx，明天做test

**Comment by z0z0r4** [comment]
合集与列表这部分我根本上找不到例子，能提供个非114514的吗（（
https://www.bilibili.com/list/114514?sid=1919810&desc=1&oid=66509220&bvid=BVY3LY3LYY3L (旧版合集)
https://space.bilibili.com/114514/favlist?fid=1919180&ftype=collect&ctype=21 (新版合集)

**Comment by Nemo2011** [comment]
https://www.bilibili.com/list/660303135?sid=2908236&spm_id_from=333.999.0.0&desc=1

**Comment by Nemo2011** [comment]
>>> sync(parse_link("BV1d841177cu"))
(-1, <ResourceType.FAILED: 'failed'>)

**Comment by Nemo2011** [comment]
我觉得再放一周把函数再优化一下后再合并到 `dev` 分支，毕竟这个函数是赶出来的。

**Comment by Nemo2011** [comment]
``` python
from bilibili_api import parse_link, sync

urls = [
    "av82054919", "AV82054919", "BV1XJ41157tQ",
    "https://www.bilibili.com/video/av82054919",
    "https://www.bilibili.com/video/BV1XJ41157tQ",
    "https://www.bilibili.com/bangumi/media/md28237119",
    "https://www.bilibili.com/bangumi/play/ss41410",
    "https://www.bilibili.com/bangumi/play/ep508404",
    "ml966613735", "ML966613735",
    "https://space.bilibili.com/558830935/favlist",
    "https://space.bilibili.com/558830935/favlist?fid=966613735&ftype=create",
    "https://space.bilibili.com/558830935/favlist?fid=966613735&ftype=collect&ctype=11",
    "https://space.bilibili.com/558830935/favlist?fid=articles",
    "https://space.bilibili.com/558830935/favlist?fid=pugvfav",
    "https://www.bilibili.com/medialist/detail/ml966613735",
    "https://www.bilibili.com/cheese/play/ss61",
    "https://www.bilibili.com/cheese/play/ep790",
    "au800841", "AU800841",
    "https://www.bilibili.com/audio/au800841",
    "am10624", "AM10624",
    "https://www.bilibili.com/audio/am10624",
    "cv17809055","CV17809055",
    "https://www.bilibili.com/read/cv17809055",
    "uid558830935","UID558830935",
    "https://space.bilibili.com",
    "https://space.bilibili.com/558830935",
    "https://live.bilibili.com/558830935",
    "https://space.bilibili.com/19319172/channel/collectiondetail?sid=250818",
    "https://space.bilibili.com/558830935/channel/seriesdetail?sid=2972810",
    "https://www.bilibili.com/list/471723540?sid=849191&spm_id_from=333.999.0.0&desc=1",
    "https://space.bilibili.com/558830935/favlist?fid=56245&ftype=collect&ctype=21",
    "https://www.bilibili.com/read/readlist/rl207146",
    "https://t.bilibili.com/747943493670797385",
    "https://www.bilibili.com/blackroom/ban/2670821",
    "https://www.biligame.com/detail/?id=103009",
    "https://www.bilibili.com/v/topic/detail/?topic_id=57290",
    "https://manga.bilibili.com/detail/mc32020",
    "https://h.bilibili.com/1198098"
]

for url in urls:
    print(sync(parse_link(url)))
```

自己拿去测试吧，等不会报错了再来说吧。

**Comment by Nemo2011** [comment]
@z0z0r4 你再打开 `parse_link.py` 文件，开一下类型检查。然后你就知道我想说什么问题了。

**Comment by Nemo2011** [comment]
<img width="1078" alt="test" src="https://user-images.githubusercontent.com/91071485/213915026-f8158aac-43e8-49fd-8c4a-14e58483d9e5.png">

**Comment by z0z0r4** [comment]
才知道有这操作，在修改
另外应该将 parse_Link 传入的凭据传递到返回的类里面吗？我看 main 分支里面也只是部分有传

**Comment by Nemo2011** [comment]
main 分支是忘了传，返回的类里面理论上都要传 Credential

**Comment by z0z0r4** [comment]
顺便这个怎么说 https://github.com/Nemo2011/bilibili-api/commit/ded4a6ec1c17ab09dfa4bde5ccdd5b6f4d76df32#r97649316

**Comment by z0z0r4** [comment]
> <img alt="test" width="1078" src="https://user-images.githubusercontent.com/91071485/213915026-f8158aac-43e8-49fd-8c4a-14e58483d9e5.png">

https://github.com/Nemo2011/bilibili-api/pull/153

**Comment by Nemo2011** [comment]
@z0z0r4 目前重写的 `parse_link` 已经基本稳定，我又测试了一下，可以合并到 `dev` 分支了。如果还有后续更改请移步 `dev` 分支。

**Comment by z0z0r4** [comment]
> @z0z0r4 目前重写的 `parse_link` 已经基本稳定，我又测试了一下，可以合并到 `dev` 分支了。如果还有后续更改请移步 `dev` 分支。

okok
