### ISSUE TITLE
[漏洞] parse_link 解析错误

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#148]
**Python 版本：** 3.10.3

**模块版本：** 14.1.0

```
from bilibili_api import parse_link
from bilibili_api import Credential
from bilibili_api import sync
c = Credential(sessdata="", bili_jct="")
sync(parse_link("https://space.bilibili.com/558830935/favlist?fid=733570&ftype=collect&ctype=21"))
<bilibili_api.user.User object at 0x0000020EEE888D60>, <ResourceType.USER: 'user'>
```

---

https://space.bilibili.com/558830935/favlist?fid=733570&ftype=collect&ctype=21 被解析为 User

**Comment by z0z0r4** [comment]
`https://www.bilibili.com/cheese/play/ss61` 解析失败
>>> sync(parse_link("https://www.bilibili.com/cheese/play/ss61"))
(-1, <ResourceType.FAILED: 'failed'>)

**Comment by z0z0r4** [comment]
> `https://www.bilibili.com/cheese/play/ss61` 解析失败
> 
> ```
> >>> sync(parse_link("https://www.bilibili.com/cheese/play/ss61"))
> (-1, <ResourceType.FAILED: 'failed'>)
> ```

![image](https://user-images.githubusercontent.com/78744121/213873811-4bda9d66-fc76-4cf5-937e-15cdb63697a3.png)
似乎没更ssxx的解析

**Comment by z0z0r4** [comment]
> > `https://www.bilibili.com/cheese/play/ss61` 解析失败
> > ```
> > >>> sync(parse_link("https://www.bilibili.com/cheese/play/ss61"))
> > (-1, <ResourceType.FAILED: 'failed'>)
> > ```
> 
> ![image](https://user-images.githubusercontent.com/78744121/213873811-4bda9d66-fc76-4cf5-937e-15cdb63697a3.png) 似乎没更ssxx的解析

https://github.com/Nemo2011/bilibili-api/issues/149

**Comment by Nemo2011** [comment]
@z0z0r4 重写完并且测试完之后向 `enhancement/parse_link` 分支进行 `pull request`。
