### ISSUE TITLE
[需求] cheess类待更新

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#149]
[获取课程基本信息](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/cheese/info.md#%E8%8E%B7%E5%8F%96%E8%AF%BE%E7%A8%8B%E5%9F%BA%E6%9C%AC%E4%BF%A1%E6%81%AF) 详见 SocialSisterYi/bilibili-API-collect
https://www.bilibili.com/cheese/ 所见基本上点开来都是 ssid，找不到 epid 的视频了...
![image](https://user-images.githubusercontent.com/78744121/213874047-be64fd43-930e-4c70-bd86-53060eac3283.png)

**Comment by Nemo2011** [comment]
所以是你知道哪个值 (season_id/ep_id) 要去声明哪个类？

**Comment by z0z0r4** [comment]
> 所以你是知道哪个值 (season_id/ep_id) 要去声明哪个类？

什么意思，看似是这俩值二选一来获取课程？

**Comment by Nemo2011** [comment]
课程类 ep_id 和 season_id 任意一个传入都可以啊，具体的课程视频只能传入 ep_id，但是 ep_id 在声明课程类后就可以获取了。(CheeseList.get_list())

**Comment by z0z0r4** [comment]
> 

emm，所以如果我拿到一个season_id，直接传到课程类 ep_id 的位置？

**Comment by z0z0r4** [comment]
不理解我应该如何解析 https://www.bilibili.com/cheese/play/ss61
