### ISSUE TITLE
【漏洞】 comment类无法正常使用

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#155]
![image](https://user-images.githubusercontent.com/78744121/214004850-a9078be7-b591-4a6f-afbc-9a5f382f1aa3.png)
![image](https://user-images.githubusercontent.com/78744121/214004859-f2270174-50a1-4d45-81ae-564e1397596e.png)
page参都没了
我也不知道咋用这个功能，replies都是空的

**Comment by Nemo2011** [comment]
wtf?我记得现在的获取评论的 API 是我一周前更新的一个新发现的 API，结果现在就失效了？我把模块的版本回馈了一下发现：原来的 API 还能用！

**Comment by z0z0r4** [comment]
> wtf?我记得现在的获取评论的 API 是我一周前更新的一个新发现的 API，结果现在就失效了？我把模块的版本回馈了一下发现：原来的 API 还能用！

2333，我不懂，但是大有所悟

**Comment by Nemo2011** [comment]
bdf46dd518ae6d6c0d6adc6b88ff4002004270cb & 17057f0ee4466e15a0ecaaa89bc7b856b39b50f0，经测试目前可以正常获取评论了。

**Comment by Nemo2011** [comment]
测试不会看返回内容的，只会判断函数是否失败。

**Comment by z0z0r4** [comment]
那我close了
