### ISSUE TITLE
文档界面的UI好像有点怪

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#156]
![image](https://user-images.githubusercontent.com/78744121/214301550-28b0a07b-76d8-47e3-bd39-efa2cdf312ab.png)
我寻思之前左侧不长这样的

**Comment by Nemo2011** [comment]
因为我加了一个折叠的插件……

之后你就知道为什么要这么做了。

**Comment by z0z0r4** [comment]
> 

但现在好丑欸，emmm
就好像有图片没加载出来一样
