### ISSUE TITLE
[需求] API信息 分区介绍

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#161]
B站妈炸掉了，信息塞JS还不全，得到处翻
https://s1.hdslb.com/bfs/static/jinkela/subchannel/subchannel.02466db8e4c6122722d14e2c3caec19630b45451.js
`jinkela` -> `金坷垃`
他真的，我哭死，依托答辩

**Comment by z0z0r4** [comment]
还tm掺繁体摆烂了当作没看到吧，蚌埠住了
![image](https://user-images.githubusercontent.com/78744121/214751120-dfda1aa5-4a96-4208-9956-605c194d8cb4.png)

**Comment by Nemo2011** [comment]
wtf，我打开了网页时汉子全是乱码

**Comment by z0z0r4** [comment]
> 

编码问题，你下载了看，正常

**Comment by z0z0r4** [comment]
频道类好像还缺个获取对应tag吧，我待会提个PR

**Comment by z0z0r4** [comment]
[新番时间表](https://www.bilibili.com/anime/timeline/) 
https://api.bilibili.com/pgc/web/timeline?types=1&before=7&after=7
types=1 为番剧其他返回无有效信息
before 和 after 最大为7，为要获取的天数

**Comment by z0z0r4** [comment]
草，早说时间表已有...麻了，根本不知道
