### ISSUE TITLE
爬取到的弹幕文本出错

### ISSUE THREAD

**Issue by thuic2023** [Nemo2011/bilibili-api#173]
**Python 版本：** 3.9.1

**模块版本：** 14.2.0

**运行环境：** Windows 10

---

爬取下来的弹幕显示错误，如图
<img width="875" alt="屏幕截图 2023-01-30 111132" src="https://user-images.githubusercontent.com/123912271/215403533-a9c81885-a8ad-4769-91ba-634babccbeee.png">
<img width="877" alt="屏幕截图 2023-01-30 111557" src="https://user-images.githubusercontent.com/123912271/215403723-9297468e-da21-4b65-80d2-9bdd60319015.png">
代码如下：

`from bilibili_api import video `    
 `import asyncio`

`'''要爬取弹幕的视频的BVID以及实例化视频对象'''`
`BvId="BV1Ap4y1H7Bc"`
`v=video.Video(bvid=BvId)`
`'''定义函数获取视频信息'''`
`async def getinfo() -> None:`

    info= await v.get_info()
    print(info)
`#asyncio.get_event_loop().run_until_complete(getinfo())#可以运行，且运行结果正常`
`'''定义函数获取弹幕'''`
`async def getdanmakus()->None:`

    danmakus= await v.get_danmakus(page_index=0)
    print(str(danmakus))
`asyncio.get_event_loop().run_until_complete(getdanmakus())`

**Comment by thuic2023** [comment]
到底出了什么问题？求解

**Comment by Drelf2018** [comment]
```python
from bilibili_api import video, sync


# 要爬取弹幕的视频的BVID以及实例化视频对象
BvId = "BV1Ap4y1H7Bc"
v = video.Video(bvid=BvId)

async def getdanmakus() -> None:
    """定义函数获取弹幕"""
    danmakus= await v.get_danmakus(page_index=0)
    for danmu in danmakus:
        print(danmu.text)
        # 是不是正版才有，大家是正版吗？

sync(getdanmakus())
```

尝试使用 `Danmaku` 对象的 `text` 属性获取弹幕文本。

```python
danmakus= await v.get_danmakus(page_index=0)
```

上述代码获取的 `danmakus` 是一个 `Danmaku` 类型的列表，因此我们需要遍历后读取对象的属性。

```python
print(danmu)
# 1660657258, 2239.77, 是不是正版才有，大家是正版吗？
```

或者直接打印，得到弹幕发送的时间、在视频中的位置以及文本拼接成的字符串。

**Comment by z0z0r4** [comment]
> 到底出了什么问题？求解

这是弹幕列表，请遍历其以获取单条弹幕…

**Comment by thuic2023** [comment]
感谢提醒，已经可以了。谢谢两位
<img width="700" alt="屏幕截图 2023-01-31 142346" src="https://user-images.githubusercontent.com/123912271/215683199-d2b75ea4-f03a-4267-b5e6-608f88635040.png">
