### ISSUE TITLE
[规范] 返回原始数据还是尽可能使用已有类

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#176]
例如 dynmaic.upload_image 这样的函数，显然是面对 Picture 的，应该返回对应的类还是 API 原始数据

**Comment by z0z0r4** [comment]
@Nemo2011

**Comment by Drelf2018** [comment]
我的观点是，与Request直接有关的接口函数应该返回原始json数据。但是可以写新函数调用该接口，对结果包装或者说转换为具体对象。

**Comment by Nemo2011** [comment]
这种 API 相关的底层函数还是不要改返回值。

**Comment by z0z0r4** [comment]
emm, ok
