### ISSUE TITLE
【需求】{可以增加番剧排行榜查询嘛？}

### ISSUE THREAD

**Issue by JiaLeDe** [Nemo2011/bilibili-api#177]
想查看番剧的排行榜
![image](https://user-images.githubusercontent.com/63954316/215974518-770c8ce4-46a2-42ee-84f4-09816f4cb1ab.png)

**Comment by Nemo2011** [comment]
https://www.bilibili.com/v/popular/rank/bangumi 是指这里吗，我图片死活加载不出来

**Comment by Nemo2011** [comment]
ok

**Comment by z0z0r4** [comment]
异议，为什么要获取初始化数据...有接口吧？https://github.com/Nemo2011/bilibili-api/blob/dev/bilibili_api/rank.py#L18
https://api.bilibili.com/pgc/web/rank/list?day=3&season_type=1
