### ISSUE TITLE
【提问】上传封面的接口似乎有问题，

### ISSUE THREAD

**Issue by ldddddddl** [Nemo2011/bilibili-api#189]
windows
python3.9.7
模块版本14.2.0

图片上传老是出现这个错误，尝试各种办法都没法解决。加密都是最新的，路径也都是正确的，手动的话图片能正常上传。
希望能告知，万分感谢！
![image](https://user-images.githubusercontent.com/49769934/217893593-03bcd418-f682-4df8-841c-266f4b9c4c46.png)
![image](https://user-images.githubusercontent.com/49769934/217893843-b93ed421-44a5-4e97-a70c-fe234e68ff52.png)

**Comment by Nemo2011** [comment]
因为上传的接口出现了变动，目前使用最新的 dev 版本即可解决

**Comment by ldddddddl** [comment]
> 因为上传的接口出现了变动，目前使用最新的 dev 版本即可解决

已解决，谢谢！
