### ISSUE TITLE
`获取专栏内容并转换为 Markdown` 存在BUG

### ISSUE THREAD

**Issue by gyhyfj** [Nemo2011/bilibili-api#19]
**Python 版本：** 3.x
**运行环境：** Windows 

```python
from bilibili_api import article, sync

async def main():
    ar = article.Article(14693531)

    await ar.fetch_content()

    with open('article.md', 'w', encoding='utf8') as f:
        f.write(ar.markdown())

sync(main())
```
---

比如抓取`14693531`这篇文章，地址：https://www.bilibili.com/read/cv14693531/?from=readlist ，引用内容和引用间内容会丢失。
抓取其他文章时，出现引用内容后的一部分正文内容，也会被转为引用

**Comment by Nemo2011** [comment]
最新版本已解决。
`pip3 install --pre --upgrade bilibili-api-python`
