### ISSUE TITLE
Any more?

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#190]
还有啥活可以整的吗hhh？假释两天

**Comment by Nemo2011** [comment]
你自己不是挖了许多的坑吗，不要火葬场了[doge

**Comment by z0z0r4** [comment]
> 你自己不是挖了某个的坑吗，不要火葬场了[doge
> 
> [#182 (comment)](https://github.com/Nemo2011/bilibili-api/pull/182#issuecomment-1414585212)

那好像早就填了吧...
https://github.com/Nemo2011/bilibili-api/blob/6e953ca75b2179525e19a9db039d6986e265f8bd/bilibili_api/manga.py#L364-L388

**Comment by z0z0r4** [comment]
Any more?

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/pull/191

**Comment by z0z0r4** [comment]
明天我看看整个 https://manga.bilibili.com/updates

**Comment by z0z0r4** [comment]
> 明天我看看整个 https://manga.bilibili.com/updates

Method: POST
Url: https://manga.bilibili.com/twirp/comic.v1.Comic/GetDailyPush?device=pc&platform=web
Data: `{"date":"2023-02-10","page_num":1,"page_size":8}`

**Comment by z0z0r4** [comment]
另外对 https://member.bilibili.com/platform/data-up/video/dataCenter/video 挺感兴趣的说实话...
作为UP 会用到这个接口，我改天整
~~zzz，刚刚考完五天试，脑子不好使~~

**Comment by z0z0r4** [comment]
> 另外对 https://member.bilibili.com/platform/data-up/video/dataCenter/video 挺感兴趣的说实话... 作为UP 会用到这个接口，我改天整 ~zzz，刚刚考完五天试，脑子不好使~

https://member.bilibili.com/x/web/data/article

**Comment by z0z0r4** [comment]
> 明天我看看整个 https://manga.bilibili.com/updates

Completed
