### ISSUE TITLE
【建议】关于互动视频的几个建议

### ISSUE THREAD

**Issue by USN484259** [Nemo2011/bilibili-api#196]
以下是我在使用互动视频相关API的过程中发现的问题/提出的建议

#### `ivitools`需要python3.10+
但是其他~我用过的~模块都是python3.8+  
文档中也没有找到关于这一点的说明 ~也可能是我看漏了~  
使用python3.8运行`ivitools`，得到以下错误：
```
$ ivitools
Traceback (most recent call last):
  File "/home/username/.local/bin/ivitools", line 5, in <module>
    from bilibili_api.tools.ivitools.__main__ import main
  File "/home/username/.local/lib/python3.8/site-packages/bilibili_api/tools/ivitools/__main__.py", line 24
    match command:
          ^
SyntaxError: invalid syntax
```
似乎是`match`语句的问题。是否可以改写成多个`if`语句，以兼容python3.8

#### `ivitools download`会重复 获取/下载 节点
[*BV1K7411j7q3*](https://www.bilibili.com/video/BV1K7411j7q3)是一个特殊的互动视频，有大量的分支指向`start`节点  
log见附件[ivitools_download.log](https://github.com/Nemo2011/bilibili-api/files/10715523/ivitools_download.log)，可以看到`start`节点被重复 获取/下载 了**48次**  

* 每两个`Get node`之间会耗时大约2秒，这可能是 API/服务器 的限流机制。重复获取节点会影响整体下载进度
* `start`节点对应的视频`cid 153903973`重复下载。如果这个视频很大，会占用大量下载时间，并产生无意义的硬盘写入操作

可以参照[我的互动视频下载实现](https://github.com/USN484259/bili-archive-program/blob/056271fd5f6b35921a6fc6750c912b8c6d56d8eb/interactive.py#L83)，准确记录`node`和`edge`，避免重复 获取/下载  

#### 建议添加 保存/绘制 流程图的功能
如果能把剧情树保存成一张流程图，那么剧情的走向就一目了然了，不用反复尝试每一个选项，或者阅读晦涩的json文件  
可以在获取节点的时候将节点信息用[dot语言](https://graphviz.org/doc/info/lang.html)保存，再使用[dot工具](https://graphviz.org/doc/info/command.html)绘制流程图  
可以参照[我的实现](https://github.com/USN484259/bili-archive-program/blob/056271fd5f6b35921a6fc6750c912b8c6d56d8eb/interactive.py#L160)

**Comment by Nemo2011** [comment]
您好，感谢您提供对互动视频模块的建设性的建议。在这里我回应一下您的提议：

## ivitools需要python3.10+

这个是当时我编写时的疏忽，目前正在修改，在此深感抱歉

## ivitools download会重复 获取/下载 节点

这个是视频本身有些问题，或者是接口的问题。那个 48 次重复的节点看似的确是发生了重复获取/下载，但是每一个获取的 start 节点的节点 id 其实都不一样，所以说重复下载了 48 次的 start 节点其实每一个都不一样，这种情况不能当作特判来处理，因为很有可能会出现 48 个 start 节点中有一般的内容和其他的不一样（随即跳转按钮可能导致这种现象），所以此处并不能当作模块的漏洞。

模块在遍历所有结点的时候考虑过不再遍历已经遍历过的节点的，我用过许多复杂的互动视频做过测试（如“你被困在了10月25日”），都没有出现问题。

## 建议添加 保存/绘制 流程图的功能

这个的确是一个好的想法，我目前正在设计，感谢您提出这个点子！

---

那就这么多了，还是非常感谢你的提议。这个 issues 中提到的需要建设/优化的功能都会放在 `enhancement/ivideo` 分支进行共工作，待完成之后会合并到 `dev` 分支。

**Comment by USN484259** [comment]
感谢你的回复。关于互动视频的接口，我想分享一下我的分析与理解

### 关于[BV1K7411j7q3](https://www.bilibili.com/video/BV1K7411j7q3)
这个视频是3年前互动视频刚出的时候我上传的，当时是想测试/验证互动视频的功能。现在刚好在做互动视频相关，就拿来做测试case了

剧情树如下图，其中每一个`sel_(.)`节点的三个分支分别是
	a. ```if (random <= 80){ hex_value = $1; goto start; }```
	b. ```if (random > 80) goto start;```
	c. ```goto start;```

![BV1K7411j7q3_timeline](https://user-images.githubusercontent.com/48667071/218377065-6c8df4fc-7663-4d39-94af-c7c09e7dc073.jpg)


这一测试就发现问题了，我的第一版实现里，start节点总共获取了49次。虽然最后输出的结果没有错误，但是我感觉这里面有问题。在分析了许多`get_edge_info`返回的数据之后，我我对该API返回数据的解析如下

### 我对互动视频的解析

`get_edge_info`返回的其实混合了节点(node)信息和边(edge)信息，所以结构比较混乱

以下是BV1K7411j7q3中`get_edge_info(edge_id = 1)`的返回数据，只保留与本次解析有关的部分

```
{
	'title': 'start',	# 节点的显示名称
	'edge_id': 1,		# 本次导向该节点的边的id
	# 缺失当前节点对应的视频cid
	'story_list': ...,	# 用户当前状态（可能用于前端展示当前剧情线/变量值）
	'edges': {'questions': [{
		'id': 0,	# 暂不清楚，始终为0
		'type': 2,	# 与播放结束时的行为有关
		'start_time_r': 300,	# 暂不清楚，可能是选项在播放结束前300ms出现
		'duration': 5000,	# 当前节点倒计时选项的超时时间
		'pause_video': 1,	# 播完暂停
		'title': '',		# 暂不清楚，始终为空
		'choices': [{...}, {...},
		{				# 描述一个选项（边）
			'id': 32365746,		# 边的ID (eid)
			'platform_action': 'JUMP 32365746 153903989',	# 始终为 JUMP $eid $cid
			'native_action': '',	# 变量赋值操作
			'condition': '',	# 本选项出现的条件
			'cid': 153903989,	# 目标节点的cid
			'x': 416,		# 点定位选项的位置
			'y': 192,		# 点定位选项的位置
			'text_align': 4,	# 点定位选项的朝向
			'option': 'C 10',	# 选项的显示文本
			'is_default': 1		# 本选项为默认选项
		}, {...}]
	}]},
	'hidden_vars': [...],			# 变量列表
	'is_leaf': 0				# 当前节点是否是叶节点（没有出边）
}
```

值得注意的有以下几点：

+ API的参数是边的ID，但得到的结果是**该边导向的节点**
+ 本质上这是一个**节点**的信息，但是包含了**本次导向该节点的边信息**，而缺少了**该节点对应的视频cid**
+ 没有*节点ID*的概念。由于节点与视频是一一对应的，因此可以使用**视频cid**来指代节点
+ `choices`中的边都是**当前节点**导出的（以当前节点为*源*），每一个边的描述包含了**目标节点对应的视频cid**
+ 边ID == 1是特殊的，它只有*目标*（导向的）节点（即根节点），没有*源*节点。推测它的存在有以下原因：
	- 保持结构一致，即每次返回的节点信息中都有一个**本次导向当前节点的边**
	- 定位根节点，使用统一的`edge_id = 1`就可以获取到每一个互动视频的根节点
+ 当有多条边导向同一个节点时，对每一个这样的边，`get_edge_info(edge_id)`返回的数据除了`edge_id`字段外，应该是相同的

通过上述分析，我对互动视频**节点**和**边**的定义如下：
```
# info = await iv.get_edge_info(...)
node = {
	"cid":		node_cid,	# 节点对应的视频cid, 需要额外提供
	"title":		info["title"],	# 节点的显示名称
	"is_leaf":		info["is_leaf"],	# 是否为叶节点
	"jump_type":	info["edges"]["questions"][0]["type"],	# 视频播完后的行为
	"countdown":	info["edges"]["questions"][0]["duration"]	# 倒计时选项超时时间
}

# choice = info["edges"]["questions"][0]["choices"][choice_index]
edge = {
	"eid":		choice["id"],	# 边的ID
	"src_cid":	node_cid,	# 源节点的cid，需要额外提供
	"dst_cid":	choice["cid"],	# 目标节点的cid
	"text":		choice["option"],	# 选项的显示文本
	"is_default":	choice["is_default"],	# 是否为默认选项
	"condition":	choice["condition"],	# 选项出现的条件
	"action":		choice["native_action"],	# 选择后的变量赋值操作
	"x":			choice["x"],	# 点定位选项的位置
	"y":			choice["y"],	# 点定位选项的位置
	"align":		choice["text_align"]	# 点定位选项的朝向
}
```

### 我的互动视频遍历的实现
基于以上分析，我对互动视频剧情树的遍历方式如下，我自己测试目前没有发现问题。  
~具体实现在[这里](https://github.com/USN484259/bili-archive-program/blob/056271fd5f6b35921a6fc6750c912b8c6d56d8eb/interactive.py#L83)~

```
async def fetch_interactive_video(iv):
	edge_map = {}	# 记录边
	node_map = {}	# 记录节点

	root_edge = await iv.get_edge_info()	# 获取根节点信息
	root_cid = await iv.get_cid()	# 根节点cid

	edge_queue = deque()
	edge_queue.append((root_cid, root_edge))		# 使用广度优先搜索，根节点入队

	while len(edge_queue) > 0:
		cid, edge = edge_queue.popleft()	# 出队一个节点

		if cid in node_map:	# 跳过已存在的节点
			continue

		node = make_node(cid, edge)
		node_map[cid] = node	# 记录当前节点

		if node["is_leaf"]:
			continue	# 跳过叶节点

		for child in edge["edges"]["questions"][0]["choices"]:	# 遍历所有边
			child_cid = child["cid"]	# 边的目标cid
			eid = child["id"]	# 边的ID

			edge_map[eid] = make_edge(cid, child)	# 记录当前边

			if child_cid in node_map:
				continue	# 目标节点已记录，跳过

			child_edge = await iv.get_edge_info(eid)	# 获取当前边导向的节点信息
			assert(child_edge["edge_id"] == eid)
			edge_queue.append((child_cid, child_edge))	# 将目标节点入队

	for cid in node_map.keys():
		await download_cid(iv, cid)	# 下载每个节点的视频

	return {
		"nodes":	list(node_map.values()),
		"edges":	list(edge_map.values())
	}
```

**Comment by Nemo2011** [comment]
……其实我现在最怕的就是出现特殊，就例如 B 站设置的机制是：如果视频源相同则两个节点使用同一个 cid，这种情况下两个节点之后的选择可能会不同，如果只用 cid 判断的话无法分辨。所以我觉得可以比对 cid 相同的两个节点的所有的参数（包括跳转条件、跳转后操作、子节点），你觉得怎么样。

**Comment by Nemo2011** [comment]
那么照这么说，获取所有结点的时间也不会减少多少啊。因为同样需要获取 节点的信息和节点子节点的信息。我先把 dot 图表生成的那部分加上吧，遇到返回一个节点的情况最好不要直接连线，影响美观。

**Comment by USN484259** [comment]
我刚刚做了个试验，[BV1YD4y1P7aQ](https://www.bilibili.com/video/BV1YD4y1P7aQ)中出现了多个节点共享一个视频的情况，剧情树如下。使用我的算法获取流程图出现了错误。*节点与cid一一对应*是不成立的，是我疏忽了。

![Screenshot from 2023-02-13 19-48-22](https://user-images.githubusercontent.com/48667071/218450667-27a1505f-fdcd-437f-b97a-abdf76394ab7.png)
![graph](https://user-images.githubusercontent.com/48667071/218450831-8a46adf3-5c3b-4b30-8001-9f54dd628e24.svg)


在cid相同时，确实可以通过比较参数分辨出不同的节点，但是这样的实现比较复杂，而对于绝大多数互动视频来说并没有很大的优化。因此我觉得目前没有必要将这种策略加入到API中，我会在自己的应用中尝试实现这样的算法。

不过我认为在视频下载的阶段，筛除重复的cid，避免重复下载视频依然是一种可行的策略。

**Comment by Nemo2011** [comment]
写好了！我还用 [BV1YD4y1P7aQ](https://www.bilibili.com/video/BV1YD4y1P7aQ) 测试了一下，结果如下，没有问题。

``` dot
digraph {
	1 -> 32455918
	1 -> 32455919
	32455918 -> 32455920
	32455918 -> 32455921
	32455919 -> 32455928
	32455919 -> 32455929
	32455920 -> 32455926 [label="
Native Command: [$kojvbiuoc=$kojvbiuoc+0.00]"]
	32455921 -> 32455927 [label="
Native Command: [$kojvbiuoc=$kojvbiuoc+1.00]"]
	32455928 -> 32455924 [label="
Native Command: [$kojvbiuoc=$kojvbiuoc+2.00]"]
	32455929 -> 32455925 [label="
Native Command: [$kojvbiuoc=$kojvbiuoc+3.00]"]
	32455926 -> 32455922
	32455927 -> 32455923
	32455924 -> 32455930
	32455925 -> 32455931
	1 [label="layer_0"]
	32455918 [label="layer_1_0"]
	32455919 [label="layer_1_1"]
	32455920 [label="layer_2_0"]
	32455921 [label="layer_2_1"]
	32455928 [label="layer_2_2"]
	32455929 [label="layer_2_3"]
	32455926 [label="layer_3_0"]
	32455927 [label="layer_3_1"]
	32455924 [label="layer_3_2"]
	32455925 [label="layer_3_3"]
	32455922 [label="跳转至 layer_0"]
	32455923 [label="跳转至 layer_0"]
	32455930 [label="跳转至 layer_0"]
	32455931 [label="跳转至 layer_0"]
	label="Variables: [$1VUXGZrQMM -> 数值4 = 0, Hide]
[$6dpBGaWyx9 -> 随机值 = 10, Random]
[$jXuzbTlYVK -> 数值3 = 0, Hide]
[$kojvbiuoc -> value = 0, Hide]
[$m9LGmnq3aH -> 数值2 = 0, Hide]
"}
```

**Comment by USN484259** [comment]
> 所以我就是这样子的啊，ivi 文件中所有的视频都是以 cid 编号的

emmm我指的是在视频下载的过程中，有重复下载同一个cid的现象，log如下
```
Start download the node 32365752 (cid 153903973)(Video & Audio)
DOWNLOADING...: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 5057.73it/s]
Start download the node 32365753 (cid 153903973)(Video & Audio)
DOWNLOADING...: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 2055.60it/s]
Start download the node 32365754 (cid 153903973)(Video & Audio)
DOWNLOADING...: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 5837.00it/s]
Start download the node 32365755 (cid 153903973)(Video & Audio)
DOWNLOADING...: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 3449.67it/s]
```
应该是由于有多个边/节点共同指向了同一个cid，而同样的cid应该就是同一个视频，我认为没有必要重复下载。  
我的想法是在下载视频的时候记录每一个已经下载的视频cid，后面再遇到同样的cid时就跳过。  
以下是参考代码（基于正式版本v15.0.0）
``` diff
diff --git a/bilibili_api/interactive_video.py b/bilibili_api/interactive_video.py
index 7f49156..d3d1ee3 100644
--- a/bilibili_api/interactive_video.py
+++ b/bilibili_api/interactive_video.py
@@ -741,16 +741,21 @@ class InteractiveVideoDownloader(AsyncEvent):
             "title": (await self.__video.get_info())["title"]
         }, open(tmp_dir_name + "/bilivideo.json", "w+", encoding = "utf-8"), indent = 2)
 
+        cid_set = set()
         for key, item in edges_info.items():
-            self.dispatch("PREPARE_DOWNLOAD", {"node_id": int(key), "cid": item["cid"]})
             cid = item["cid"]
+           if cid in cid_set:
+               continue        # 跳过已经下载的视频
+            self.dispatch("PREPARE_DOWNLOAD", {"node_id": int(key), "cid": item["cid"]})
             url = await self.__video.get_download_url(cid = cid, html5 = True)
             await self.__download_func(url["durl"][0]["url"], tmp_dir_name + "/" + str(cid) + ".mp4")
+            cid_set.add(cid)
 
-        self.dispatch("PREPARE_DOWNLOAD", {"node_id": 1, "cid": await self.__video.get_cid()})
         cid = await self.__video.get_cid()
-        url = await self.__video.get_download_url(cid = cid, html5 = True)
-        await self.__download_func(url["durl"][0]["url"], tmp_dir_name + "/" + str(cid) + ".mp4")
+       if cid not in cid_set:
+            self.dispatch("PREPARE_DOWNLOAD", {"node_id": 1, "cid": await self.__video.get_cid()})
+            url = await self.__video.get_download_url(cid = cid, html5 = True)
+            await self.__download_func(url["durl"][0]["url"], tmp_dir_name + "/" + str(cid) + ".mp4")
 
         self.dispatch("PACKAGING")
         zip = zipfile.ZipFile(open(self.__out + ".ivi", "wb+"), mode = "w", compression = zipfile.ZIP_DEFLATED)  # outFullName为压缩文件的完整路径
```

**Comment by Nemo2011** [comment]
可以了

**Comment by z0z0r4** [comment]
23333！
