### ISSUE TITLE
【提问】bilibili网页端个人信息发包改名提示“csrf校验失败”

### ISSUE THREAD

**Issue by WealthyElk** [Nemo2011/bilibili-api#197]
**Python 版本：** 3.9.4

**模块版本：** 基础python内置模块

**运行环境：** Windows 

---

想请教一下，为什么确定了csrf=bili_jct=抓到的POST修改个人资料的包，然后用以下代码在IDLE中自行请求却提示csrf校验失败

```
问题已解决，代码自动隐藏

```

**传入的robber为字符串，即需要改的ID，headers为main中自定义的请求头
***各类库均已引用，并且已再三确认cookie，传入的csrf参数正确（上述代码中保护隐私置空）

status_code为200，response.text为'csrf校验失败'

**Comment by Nemo2011** [comment]
1. cookies 要加 csrf，2. 建议同时设置 `csrf_token` 项

**Comment by WealthyElk** [comment]
在header的cookie项中增加csrf=****, 就可以成功了，对吗

**Comment by WealthyElk** [comment]
> 1. cookies 要加 csrf，2. 建议同时设置 `csrf_token` 项

已经在cookies中加入csrf = ****项，仍然提示：{"code":-111,"message":"csrf 校验失败","ttl":1}

**Comment by Nemo2011** [comment]
我知道了，sessdata

**Comment by WealthyElk** [comment]
SESSDATA从(https://account.bilibili.com/account/setting)页面中cookies直接复制获得，这个怎么了？

**Comment by Nemo2011** [comment]
任何的用户相关 API 都需要加上 sessdata

**Comment by Nemo2011** [comment]
yimoxia@outlook.com，别忘记给 cookies 打码。

**Comment by WealthyElk** [comment]
已经发送，请查收

**Comment by z0z0r4** [comment]
乐，没有硬币甚至没法测试
