### ISSUE TITLE
【漏洞】上传封面错误漏洞

### ISSUE THREAD

**Issue by ldddddddl** [Nemo2011/bilibili-api#200]
**Python 版本：** 3.9

**模块版本：** 15.0 dev

**运行环境：** Windows 

**模块路径：** `\AppData\Local\Programs\Python\Python39\Lib\site-packages\bilibili_api_python-15.0.0.dev0-py3.9.egg\bilibili_api\video_uploader.py`

![image](https://user-images.githubusercontent.com/49769934/218463853-813919d6-f45c-4835-8309-fb3b436aac9d.png)

---

这里的封面上传失败是不是BUG了，我尝试了PNG和JPEG结果都是不行，如果方便，能告知一下原因吗？谢谢！

**Comment by Nemo2011** [comment]
只能用真正的上传封面 API 了……也挖出来现在的上传封面 API 了。

``` python
url = "https://member.bilibili.com/x/vu/web/cover/up"

from bilibili_api import Picture, Credential, sync
from bilibili_api.utils.network_httpx import request
import base64

pic = Picture.from_file("test.png")
CREDENTIAL = Credential(
    # 需要 cookies
)
print(sync(request("POST", url, credential=CREDENTIAL, data={
    "cover": f'data:image/jpeg;base64,{base64.b64encode(pic.convert_format("jpg").content).decode("utf-8")}'
})))
```

通过以上代码可以实现封面上传，返回的 url 格式将不再为 webp。目前正在更新。

**Comment by ldddddddl** [comment]
![image](https://user-images.githubusercontent.com/49769934/218801365-8917a4d6-56ae-49ab-b305-6d85a2bb2fe6.png)

感谢，在video_uploader中更改部分代码后，正常使用。
感谢维护！
