### ISSUE TITLE
【提问】__init__.py 删除了引用？

### ISSUE THREAD

**Issue by Drelf2018** [Nemo2011/bilibili-api#201]
在 https://github.com/Nemo2011/bilibili-api/commit/261c6c9c4a76e5ce53b6eb72a18b7fdabf371ff4 提交中

```python
from . import (album, app, article, ass, audio, bangumi, black_room, channel,
               cheese, client, comment, dynamic, emoji, favorite_list, game,
               homepage, interactive_video, live, live_area, login, login_func,
               manga, note, rank, search, session, settings, topic, user,
               video, video_uploader, vote)
```

这些引入代码被删除了，这样做会使代码提示失效

<div align="center">

![QQ截图20230217225000](https://user-images.githubusercontent.com/41439182/219689905-1be799ca-2285-4a28-99bd-aab86edf6648.png)

_左侧代码提示缺失，右侧正常_

</div>

**Comment by Nemo2011** [comment]
主要是添加了新的模块之后容易忘记在 `__init__.py` 中加上，现在应该可以加了。
