### ISSUE TITLE
[需求] 发布动态支持话题以及无文本动态

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#205]
![image](https://user-images.githubusercontent.com/78744121/219905861-ad3a37f1-2e8c-4fe4-a9b4-936309f81d79.png)
如图，添加话题 Tag 目测当前 `dynamic` 类不支持，以及无文本同样可以发动态...应该改为 Optional 
![image](https://user-images.githubusercontent.com/78744121/219905892-fa3c8058-97dc-482d-bf7d-6f177f23b1b6.png)

**Comment by z0z0r4** [comment]
但没了解过动态接口...要不你来实现，从头翻我一天估计翻不完（

**Comment by Nemo2011** [comment]
好消息：我花了半天终于成功做到了从文字中提取表情包和 at 的功能了！

**Comment by z0z0r4** [comment]
> 好消息：我花了半天终于成功做到了从文字中提取表情包和 at 的功能了！

emmm，祝好，我得润了...

**Comment by Nemo2011** [comment]
摆了

**Comment by z0z0r4** [comment]
我回来了，三天假期，我争取下

**Comment by Nemo2011** [comment]
md写不下去了那个API……

**Comment by z0z0r4** [comment]
> md写不下去了那个API……

那个，你没在整动态吧？在整我就不整了，冲突

**Comment by Nemo2011** [comment]
没整，整到一半写不下去了，没提交，本地放着

**Comment by z0z0r4** [comment]
那我来吧，先看看当前的（

> 没整，整到一半写不下去了，没提交，本地放着

**Comment by z0z0r4** [comment]
前置一枚 https://api.vc.bilibili.com/dynamic_mix/v1/dynamic_mix/at_list?uid=558830935

**Comment by z0z0r4** [comment]
投票相关 https://api.vc.bilibili.com/vote_svr/v1/vote_svr/create_vote 没在仓库搜到

**Comment by z0z0r4** [comment]
直播预约 https://api.bilibili.com/x/activity/up/reserve/create 
```powershell
Invoke-WebRequest -UseBasicParsing -Uri "https://api.bilibili.com/x/activity/up/reserve/create" `
-Method "POST" `
-ContentType "application/x-www-form-urlencoded" `
-Body "type=2&title=%E7%9B%B4%E6%92%AD%E5%86%99%E6%8E%A5%E5%8F%A3&live_plan_start_time=1677240000&stime=&from=1&csrf="
```

**Comment by z0z0r4** [comment]
我刚刚尝试发的一个
body
```json
{
  "dyn_req": {
    "content": {
      "contents": [
        {
          "raw_text": "测试，B站api",
          "type": 1,
          "biz_id": ""
        },
        {
          "raw_text": "[兔年]",
          "type": 9,
          "biz_id": ""
        },
        {
          "raw_text": "[2023]",
          "type": 9,
          "biz_id": ""
        },
        {
          "raw_text": "\n我发起了一个投票",
          "type": 1,
          "biz_id": ""
        },
        {
          "raw_text": "测试接口",
          "type": 4,
          "biz_id": "5322590"
        },
        {
          "raw_text": "@LociQ",
          "type": 2,
          "biz_id": "1543896304"
        },
        {
          "raw_text": " ",
          "type": 1,
          "biz_id": ""
        }
      ]
    },
    "pics": [
      {
        "img_src": "http://i0.hdslb.com/bfs/new_dyn/34caf7e35036aebf164060e59b15d8f8558830935.jpg",
        "img_width": 1080,
        "img_height": 1142,
        "img_size": 156.404296875
      }
    ],
    "scene": 2,
    "attach_card": {
      "common_card": {
        "type": 14,
        "biz_id": 1347836,
        "reserve_source": 0,
        "reserve_lottery": 0
      }
    },
    "upload_id": "558830935_1672401667_2438",
    "meta": {
      "app_meta": {
        "from": "create.dynamic.web",
        "mobi_app": "web"
      }
    },
    "topic": {
      "id": 654258,
      "name": "软件测试怎么测试",
      "from_source": "dyn.web.search",
      "from_topic_id": 0
    }
  }
}
```

response
```json
{
  "code": 0,
  "message": "0",
  "ttl": 1,
  "data": {
    "dyn_id": 765835008873070600,
    "dyn_id_str": "765835008873070616",
    "dyn_type": 2,
    "dyn_rid": 226125755
  }
}
```

**Comment by z0z0r4** [comment]
> 我刚刚尝试发的一个 body
> 
> ```json
> {
>   "dyn_req": {
>     "content": {
>       "contents": [
>         {
>           "raw_text": "测试，B站api",
>           "type": 1,
>           "biz_id": ""
>         },
>         {
>           "raw_text": "[兔年]",
>           "type": 9,
>           "biz_id": ""
>         },
>         {
>           "raw_text": "[2023]",
>           "type": 9,
>           "biz_id": ""
>         },
>         {
>           "raw_text": "\n我发起了一个投票",
>           "type": 1,
>           "biz_id": ""
>         },
>         {
>           "raw_text": "测试接口",
>           "type": 4,
>           "biz_id": "5322590"
>         },
>         {
>           "raw_text": "@LociQ",
>           "type": 2,
>           "biz_id": "1543896304"
>         },
>         {
>           "raw_text": " ",
>           "type": 1,
>           "biz_id": ""
>         }
>       ]
>     },
>     "pics": [
>       {
>         "img_src": "http://i0.hdslb.com/bfs/new_dyn/34caf7e35036aebf164060e59b15d8f8558830935.jpg",
>         "img_width": 1080,
>         "img_height": 1142,
>         "img_size": 156.404296875
>       }
>     ],
>     "scene": 2,
>     "attach_card": {
>       "common_card": {
>         "type": 14,
>         "biz_id": 1347836,
>         "reserve_source": 0,
>         "reserve_lottery": 0
>       }
>     },
>     "upload_id": "558830935_1672401667_2438",
>     "meta": {
>       "app_meta": {
>         "from": "create.dynamic.web",
>         "mobi_app": "web"
>       }
>     },
>     "topic": {
>       "id": 654258,
>       "name": "软件测试怎么测试",
>       "from_source": "dyn.web.search",
>       "from_topic_id": 0
>     }
>   }
> }
> ```
> 
> response
> 
> ```json
> {
>   "code": 0,
>   "message": "0",
>   "ttl": 1,
>   "data": {
>     "dyn_id": 765835008873070600,
>     "dyn_id_str": "765835008873070616",
>     "dyn_type": 2,
>     "dyn_rid": 226125755
>   }
> }
> ```

https://www.bilibili.com/opus/765835008873070616

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/blob/dev/bilibili_api/dynamic.py#L181

**Comment by z0z0r4** [comment]
是我乐观了，得重构，笑死

**Comment by z0z0r4** [comment]
![image](https://user-images.githubusercontent.com/78744121/220942363-c1f1c8a3-411c-4fa9-aaaf-8b7d82773c26.png)

**Comment by z0z0r4** [comment]
> 直播预约 https://api.bilibili.com/x/activity/up/reserve/create
> 
> ```powershell
> Invoke-WebRequest -UseBasicParsing -Uri "https://api.bilibili.com/x/activity/up/reserve/create" `
> -Method "POST" `
> -ContentType "application/x-www-form-urlencoded" `
> -Body "type=2&title=%E7%9B%B4%E6%92%AD%E5%86%99%E6%8E%A5%E5%8F%A3&live_plan_start_time=1677240000&stime=&from=1&csrf="
> ```

@Nemo2011 给个建议？直播预约接口我塞哪个文件里

**Comment by Nemo2011** [comment]
就live就可以了

**Comment by z0z0r4** [comment]
答辩定时动态谁爱用谁用，反正我不写
![@KQRN S@BLXS49{T$S%{ %5](https://user-images.githubusercontent.com/78744121/221075622-b9483eb3-300e-40a9-a128-16de1e38d2f1.png)

**Comment by Nemo2011** [comment]
_parse_at 不能用吗？

**Comment by Nemo2011** [comment]
刚刚看了一些代码，觉得这里可以改一下：
1. `emote.json` 过于大了吧，`emoji.get_emoji_list` 可以用啊
2. 教你一个从字符串中分离 at 和各种的表情包的方法（我就是这么做的）(或者在 BuildDynamic 中加上传入字符串解析的函数）
   - 1. 写一个 `_parse_emojis`，返回的值和 `_parst_at` 类似，要求需要有表情包的位置及长度
   - 2. 将所有的表情包和所有的 at 整理为列表，需要加上位置、长度的数据，根据每一个表情包/at 的位置进行排序，将先出现的表情包/at 放在前面
   - 3. 写一个递归函数，支持接入一个字符串列表及未处理的表情包/at 列表，每一次函数提取字符串列表的最后一项，然后把它分割为三份：表情包/at 前面纯文本，表情包/at 文本，表情包/at 后面纯文本，然后加入字符串列表，删除处理过的那个表情包 /at，然后递归调用，直到所有表情包/at 都处理过了为止。

**Comment by z0z0r4** [comment]
> 刚刚看了一些代码，觉得这里可以改一下：
> 
> 1. `emote.json` 过于大了吧，`emoji.get_emoji_list` 可以用啊
> 2. 教你一个从字符串中分离 at 和各种的表情包的方法（我就是这么做的）(或者在 BuildDynamic 中加上传入字符串解析的函数）
>    
>    * 1. 写一个 `_parse_emojis`，返回的值和 `_parst_at` 类似，要求需要有表情包的位置及长度
>    * 2. 将所有的表情包和所有的 at 整理为列表，需要加上位置、长度的数据，根据每一个表情包/at 的位置进行排序，将先出现的表情包/at 放在前面
>    * 3. 写一个递归函数，支持接入一个字符串列表及未处理的表情包/at 列表，每一次函数提取字符串列表的最后一项，然后把它分割为三份：表情包/at 前面纯文本，表情包/at 文本，表情包/at 后面纯文本，然后加入字符串列表，删除处理过的那个表情包 /at，然后递归调用，直到所有表情包/at 都处理过了为止。
>    * 4. 记得调整 python 的递归最大层数，否则有几率会爆（python 递归最大层数为 1000, 虽然 B 站动态只支持 1000 字，不可能出现 1000 个 at/表情包，但是万一用户设置了一个更小的值呢？）

我只是觉得既然是个单独的 content，没必要塞在纯文本里面像CQ码一样来解析...？
这个解析，大概和定时动态一个后端逻辑...？感觉从哪种意义来说都很麻烦
> 答辩定时动态谁爱用谁用，反正我不写
![@KQRN S@BLXS49{T$S%{ %5](https://user-images.githubusercontent.com/78744121/221075622-b9483eb3-300e-40a9-a128-16de1e38d2f1.png)

**Comment by Nemo2011** [comment]
反正定时动态我已经写好了~~照着以前的来抄就没问题了啊~~，从文本里面提取 at 和表情包也在写了（都说了以前写过放在本地）

**Comment by z0z0r4** [comment]
> 反正定时动态我已经写好了~照着以前的来抄就没问题了啊~，从文本里面提取 at 和表情包也在写了（都说了以前写过放在本地）

定时太答辩了，遍历文本，我干不出这么恶心的事.jpg
那你来，即时动态能用函数添加表情还是就用它吧？qeq

**Comment by z0z0r4** [comment]
emmm，问点问题 @Nemo2011 
https://github.com/Nemo2011/bilibili-api/blob/6fe7279ca625f2ee0f999164c297bf78c2448a27/bilibili_api/dynamic.py#L220 为什么不是 `self.pics`，又不是只有一张图

**Comment by Nemo2011** [comment]
?这不是你写的部分吗

**Comment by z0z0r4** [comment]
> ?这不是你写的部分吗

https://github.com/Nemo2011/bilibili-api/commit/e302fc01828b486124bb2261a121f50383d35348#r102028814 再看看...

**Comment by z0z0r4** [comment]
顺便问问，能不能开放讨论模块...总觉得有些东西不算issue
