### ISSUE TITLE
【求助】有关于判断done_geetest()

### ISSUE THREAD

**Issue by yhzcake** [Nemo2011/bilibili-api#207]
**Python 版本：** 3.10.7

**模块版本：** 15.0.0

**运行环境：** Windows
---

我是一个初学者,正在尝试写一个我自己的bilibili相关的想法来锻炼自己的能力
我参考本库的文档设计了一个窗口,其他一切正常,但我不知道如何在主函数中判断done_geetest()来关闭极验的窗口随后获取验证码.

我一开始想到的就是使用while true来循环判断并根据if来break,但很显然这会导致线程阻塞并使窗口崩溃
随后我想到使用async进行异步处理,但相关的教程过于繁琐导致我找不到实际需要的部分
我也进行了一些尝试,但实际上还是阻塞了
如果有大佬愿意帮助解决不胜感激

**Comment by Drelf2018** [comment]
方便展示一下你的代码吗？因为登录这边我也没了解过，但是看你的意思应该是需要一个定时任务框架 `apscheduler` 每隔几秒调用一次函数 `done_geetest()`

**Comment by Drelf2018** [comment]
如果是的话我这里贴一份参考代码

有关 `apscheduler` 的使用可以参考 [Python apscheduler安装和基本使用](https://www.coonote.com/python-note/python-apscheduler-install.html)

```python
import time

from apscheduler.schedulers.background import BackgroundScheduler

from bilibili_api.login_func import done_geetest

# 这是一个后台的定时任务框架
scheduler = BackgroundScheduler(timezone="Asia/Shanghai")

# 每三秒在后台执行一次 check() 函数 不会因为 time.sleep(1) 阻塞
@scheduler.scheduled_job("interval", seconds=3)
def check():
    if done_geetest():
        print("完成验证")
    else:
        print("未完成验证")

# 启动框架
scheduler.start()

# 模拟主函数阻塞
while True:
    time.sleep(1)
```

**Comment by yhzcake** [comment]
> 

谢谢,不过我在文档有关登录功能的那篇里找到了qt自带的timerevent,可能可以实现我的需求.
不过schedulerye应该也可以,或者用在别的地方也可以
