### ISSUE TITLE
【提问】有关于login_with_password

### ISSUE THREAD

**Issue by yhzcake** [Nemo2011/bilibili-api#209]
**Python 版本：** 3.10.7

**模块版本：** 15.0.0

**运行环境：** Windows
---

![image](https://user-images.githubusercontent.com/80627671/220561780-7ef50a76-41af-4713-84e2-7418c29d2840.png)

如图,在我使用login_with_password时,会报错'验证码错误',一开始我以为是有关极验的问题,我在代码中添加了有关极验验证的部分,但仍旧会崩溃,不知道是什么问题,所以来这里问问

**Comment by Nemo2011** [comment]
看来是登录接口出了问题
