### ISSUE TITLE
【漏洞】python 3.9 api版本15.1.0 ，上传视频 一直显示分块上传失败

### ISSUE THREAD

**Issue by xzh12** [Nemo2011/bilibili-api#210]
报错信息：
{'name': 'PREUPLOAD', 'data': {<bilibili_api.video_uploader.VideoUploaderPage object at 0x7ff990aa06a0>: <bilibili_api.video_uploader.VideoUploaderPage object at 0x7ff990aa06a0>}}
api["url"] https://member.bilibili.com/preupload
preupload {'OK': 1, 'auth': 'ak=1494471752&cdn=%2F%2Fupos-cs-upcdnbda2.bilivideo.com&os=upos&sign=91dd76d164f79f3650eb5c9ee329ebe0&timestamp=1677056263.595&uid=51129781&uip=101.230.199.161&uport=3159&use_dqp=0', 'biz_id': 1020196268, 'chunk_retry': 10, 'chunk_retry_delay': 3, 'chunk_size': 10485760, 'endpoint': '//upos-cs-upcdnbda2.bilivideo.com', 'endpoints': ['//upos-cs-upcdnbda2.bilivideo.com', '//upos-cs-upcdnqn.bilivideo.com'], 'expose_params': None, 'put_query': 'os=upos&profile=ugcfx%2Fbup', 'threads': 3, 'timeout': 1200, 'uip': '101.230.199.161', 'upos_uri': 'upos://ugcfx2lf/n230222a21awtyg10pba8w2asd5g7w8o.mp4'}
{'name': 'PRE_PAGE', 'data': {'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x7ff990aa06a0>}}
{'name': 'PRE_CHUNK', 'data': {'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x7ff990aa06a0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 34}}
{'name': 'PRE_CHUNK', 'data': {'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x7ff990aa06a0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 34}}
{'name': 'PRE_CHUNK', 'data': {'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x7ff990aa06a0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 34}}
{'name': 'CHUNK_FAILED', 'data': {'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x7ff990aa06a0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 34, 'info': ''}}
{'name': 'CHUNK_FAILED', 'data': {'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x7ff990aa06a0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 34, 'info': ''}}
{'name': 'CHUNK_FAILED', 'data': {'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x7ff990aa06a0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 34, 'info': ''}}
在此处写正文

**Comment by Nemo2011** [comment]
1. 打开本地的模块的文件夹 (windows 通常为 python安装路径/lib/site-packages/bilibili-api）
2. 找到 video_uploader 模块中的这一行：

https://github.com/Nemo2011/bilibili-api/blob/main/bilibili_api/video_uploader.py#L639 

在这一行后面加上：

```python
raise e
```

3. 重新试着上传，发一下重试之后的日志。

**Comment by xzh12** [comment]
{'name': 'PREUPLOAD', 'data': {<bilibili_api.video_uploader.VideoUploaderPage object at 0x7f92aeaa1cd0>: <bilibili_api.video_uploader.VideoUploaderPage object at 0x7f92aeaa1cd0>}}
api["url"] https://member.bilibili.com/preupload
preupload {'OK': 1, 'auth': 'ak=1494471752&cdn=%2F%2Fupos-cs-upcdnbda2.bilivideo.com&os=upos&sign=b22ce94deae388718fdf908f025e423d&timestamp=1677114208.812&uid=51129781&uip=101.230.199.161&uport=63622&use_dqp=0', 'biz_id': 1021212373, 'chunk_retry': 10, 'chunk_retry_delay': 3, 'chunk_size': 10485760, 'endpoint': '//upos-cs-upcdnbda2.bilivideo.com', 'endpoints': ['//upos-cs-upcdnbda2.bilivideo.com', '//upos-cs-upcdnqn.bilivideo.com'], 'expose_params': None, 'put_query': 'os=upos&profile=ugcfx%2Fbup', 'threads': 3, 'timeout': 1200, 'uip': '101.230.199.161', 'upos_uri': 'upos://ugcfx2lf/n230223a22e60szdt71dab1nytp5cwqz.mp4'}
{'name': 'PRE_PAGE', 'data': {'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x7f92aeaa1cd0>}}
{'name': 'PRE_CHUNK', 'data': {'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x7f92aeaa1cd0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 1}}
{'name': 'FAILED', 'data': {'err': WriteTimeout('')}}

**Comment by xzh12** [comment]
session = httpx.AsyncClient(timeout=httpx.Timeout(settings.timeout, write=None))

**Comment by SYSHelloWorld** [comment]
报错信息：
[-] 上传中
{'name': 'PREUPLOAD', 'data': ({<bilibili_api.video_uploader.VideoUploaderPage object at 0x000002BE8C0A6CA0>: <bilibili_api.video_uploader.VideoUploader
Page object at 0x000002BE8C0A6CA0>},)}
{'name': 'PRE_PAGE', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x000002BE8C0A6CA0>},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x000002BE8C0A6CA0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 21},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x000002BE8C0A6CA0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 21},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x000002BE8C0A6CA0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 21},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x000002BE8C0A6CA0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 21, 'info': ''},)}
{'name': 'FAILED', 'data': ({'err': ReadTimeout('')},)}
[!] 上传失败 原因：
我也报相同的错误，我用的是最新的dev分支，也像xzh12改了这个参数，但还是报了这个错误
环境：windows
