### ISSUE TITLE
【提问】video_uploader超出当前可用分p视频数上限

### ISSUE THREAD

**Issue by rua3391** [Nemo2011/bilibili-api#22]
**Python 版本：** 3.10.3

**模块版本：** 9.1.0

**运行环境：** Windows / Linux

---

使用VideoUploader传入了多个VideoUploaderPage对象时在提交视频时失败，提示超出当前可用分p视频数上限，请问分p这一块是有什么限制吗

``` python
pages = []
for filename in os.listdir(dirname):
    filepath = os.path.join(dirname, filename)
    page = video_uploader.VideoUploaderPage(filepath, meta['title'], meta['desc'])
    pages.append(page)
uploader = video_uploader.VideoUploader(pages=pages, meta=meta, credential=myCredential)
await uploader.start()
```

**Comment by Nemo2011** [comment]
现在的 API 暂时只能上传单 P。
原因 ->：https://github.com/MoyuScript/bilibili-api/issues/243

> >  > 完了，这个接口废了
>
> > 开发者还会考虑继续做视频投稿方面的功能么？
>
>Web 端的投稿接口倒是可以，问题是 Web 端不能投多 P 视频，目前好像只有 PC 投稿工具支持。如果实在不行，我就做会 Web 端的算了。
>b 站似乎是要取消多 p，从流量的角度来讲，多 p 视频确实不适合。目前有部分 up 主内测视频合集的形式，估计是想用合集来替代多 p。

关键当时官方投稿工具都用不了（什
如果以后发现了上传多 P 的 API, 我会第一时间更新的。

**Comment by rua3391** [comment]
好了解了，感谢

**Comment by rua3391** [comment]
> 

rust的代码看的比较少，怎么实现的upload得研究研究，目前我直接调用他的工具上传了，也能解决问题

**Comment by Nemo2011** [comment]
```
dependencies = [
 "anyhow",
 "biliup",
 "bytes",
 "futures",
 "reqwest",
 "serde",
 "serde_json",
 "serde_yaml",
 "tauri",
 "tauri-build",
 "thiserror",
 "tokio",
 "tracing",
 "tracing-appender",
 "tracing-subscriber",
]
```
可以在 `main.rs` 中扒出对 `biliup` 的应用，但是我就死活找不到哪里有什么 `biliup.rs` 或是 `biliup` 的文件夹（就是叫 `biliup` 的模块），怀疑是第三方库，结果翻了 `Cargo.lock`，还真是第三方库！

**Comment by Nemo2011** [comment]
https://github.com/ForgQi/biliup-rs
