### ISSUE TITLE
[BUG] [需求] 内置弹幕发送者反查

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#223]
https://github.com/z0z0r4/CRC32Cracker/blob/master/main.py

征求下意见

**Comment by Nemo2011** [comment]
不是有了吗

**Comment by Drelf2018** [comment]
https://github.com/Nemo2011/bilibili-api/blob/main/bilibili_api/utils/Danmaku.py#L107

**Comment by z0z0r4** [comment]
> https://github.com/Nemo2011/bilibili-api/blob/main/bilibili_api/utils/Danmaku.py#L107

xd 这是不是搞错了点什么，`zlib.crc32` 怎么可能用来根据 hash 反查出 uid，这个不是生成 hash 的函数吗？？？

我的 uid 558830935，crc32 为 a3efe724
![image](https://user-images.githubusercontent.com/78744121/221383935-49fb2384-39b7-4ee2-8732-a647fc6a4d4e.png)

**Comment by Nemo2011** [comment]
还有一件事，目前此算法对9位以上uid已经失效

**Comment by z0z0r4** [comment]
> 还有一件事，目前此算法对9位以上uid已经失效

此算法指的是我发的那个还是 `zlib.crc32`

很显然超长 uid 没法快速反查，但 https://github.com/Nemo2011/bilibili-api/blob/main/bilibili_api/utils/Danmaku.py#L107 
这算什么鬼...这个有问题吧，拿 hash 再 crc32 一次之后的值作为 uid？？

**Comment by Nemo2011** [comment]
是指你发的算法

**Comment by z0z0r4** [comment]
> 是指你发的算法

那是肯定的吧，不过没方法，没人会去做这么长的彩虹表
https://github.com/Nemo2011/bilibili-api/blob/96f9b37908b8ec275456591239953487991b45d9/bilibili_api/utils/Danmaku.py#L107-L115

这段都不知道谁的逆天理解...写出来的玩意，我待会PR一份

**Comment by Nemo2011** [comment]
把原来的重新改了过来。
