### ISSUE TITLE
关于 credential 凭证问题 及 Cookies 刷新

### ISSUE THREAD

**Issue by AkiNya2021** [Nemo2011/bilibili-api#227]
**Python 版本：** 3.10

**模块版本：** 15.1.0

**运行环境：** Windows 

---

按照[获取 Credential 类所需信息](https://nemo2011.github.io/bilibili-api/#/get-credential)的方式进行登录，会有登录失效的可能吗？（即这几个参数会不会变化？变化频率如何？）

**Comment by AkiNya2021** [comment]
> 

我会尝试记录一下，结果到时候反馈到这来，多谢解答

**Comment by Drelf2018** [comment]
在获取cookies的浏览器不退出登录的情况下，我的能用相当久(> 4 months)

**Comment by z0z0r4** [comment]
建议转入 discussion

**Comment by z0z0r4** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/a46f140fde73530868ce9db5f613deed8d5c645e/docs/login/cookie_refresh.md

有希望了.jpg

**Comment by z0z0r4** [comment]
> https://github.com/SocialSisterYi/bilibili-API-collect/blob/a46f140fde73530868ce9db5f613deed8d5c645e/docs/login/cookie_refresh.md
> 
> 有希望了.jpg

封装中，还差二维码登录等等时不知道去哪里搞 `ac_time_value`

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/pull/321 Cookies 刷新，待 dev 测试（我测的没事，等个谁试试看

**Comment by z0z0r4** [comment]
又是循环嵌套...
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/89e1aeb7-30b8-4d1e-99a9-8763cf2a1c1f)

**Comment by Drelf2018** [comment]
Credential 是个基础类，就相当于一个用来存放数据的类，不要给他加功能了。可以把对 Credential 操作的功能专门做一个文件放在 Credential 父级目录，在父级就可以同时引用 request 和 Credential

**Comment by Drelf2018** [comment]
这也是为什么之前删掉 Credential 里 check_valid() 的原因，如果你愿意可以把你这个刷新cookies跟 check_valid 写一个文件放在 bilibili_api 目录下

**Comment by z0z0r4** [comment]
> Credential 是个基础类，就相当于一个用来存放数据的类，不要给他加功能了。可以把对 Credential 操作的功能专门做一个文件放在 Credential 父级目录，在父级就可以同时引用 request 和 Credential

开个 `bilibili/credential.py`？懂了

**Comment by z0z0r4** [comment]
fixed https://github.com/Nemo2011/bilibili-api/pull/328

> > Credential 是个基础类，就相当于一个用来存放数据的类，不要给他加功能了。可以把对 Credential 操作的功能专门做一个文件放在 Credential 父级目录，在父级就可以同时引用 request 和 Credential
> 
> 开个 `bilibili/credential.py` 导入 `Credential`，然后在里面写操作？我试试看

**Comment by jhzgjhzg** [comment]
使用三种方式登录都会缺失buvid3，这是什么情况？版本为15.5.1

**Comment by z0z0r4** [comment]
> 使用三种方式登录都会缺失buvid3，这是什么情况？版本为15.5.1

请使用 `15.5.1b0` 版本

`pip install bilibili-api-python==15.5.1b0`

**Comment by jhzgjhzg** [comment]
> > 使用三种方式登录都会缺失buvid3，这是什么情况？版本为15.5.1
> 
> 请使用 `15.5.1b0` 版本
> 
> `pip install bilibili-api-python==15.5.1b0`

更新15.5.1b0版本后，只有二维码登录正常，密码和验证码还是缺失buvid3，看了一下源码，为什么这两种登录方式不加上buvid3嘞

**Comment by z0z0r4** [comment]
> > > 使用三种方式登录都会缺失buvid3，这是什么情况？版本为15.5.1
> > 
> > 
> > 请使用 `15.5.1b0` 版本
> > `pip install bilibili-api-python==15.5.1b0`
> 
> 更新15.5.1b0版本后，只有二维码登录正常，密码和验证码还是缺失buvid3，看了一下源码，为什么这两种登录方式不加上buvid3嘞

本身登录操作就不返回 `buvid3`，如果你需要可以自己调函数拿，或者提 PR 吧...

二维码调了的话，都不记得是谁最近才顺便加上去的了...

**Comment by jhzgjhzg** [comment]
> > > > 使用三种方式登录都会缺失buvid3，这是什么情况？版本为15.5.1
> > > 
> > > 
> > > 请使用 `15.5.1b0` 版本
> > > `pip install bilibili-api-python==15.5.1b0`
> > 
> > 
> > 更新15.5.1b0版本后，只有二维码登录正常，密码和验证码还是缺失buvid3，看了一下源码，为什么这两种登录方式不加上buvid3嘞
> 
> 本身登录操作就不返回 `buvid3`，如果你需要可以自己调函数拿，或者提 PR 吧...
> 
> 二维码调了的话，都不记得是谁最近才顺便加上去的了...

OK

**Comment by z0z0r4** [comment]
有 refresh 无所谓了

**Comment by Ikaros-521** [comment]
```
window.localStorage.ac_time_value
undefined
```
是不是有所改动了呢

**Comment by z0z0r4** [comment]
> ```
> window.localStorage.ac_time_value
> undefined
> ```
> 
> 是不是有所改动了呢

姑且没有

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/57d46e33-5b37-4a34-936f-d211b1d6c348)

**Comment by Ikaros-521** [comment]
> > ```
> > window.localStorage.ac_time_value
> > undefined
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 是不是有所改动了呢
> 
> 姑且没有
> 
> ![image](https://user-images.githubusercontent.com/78744121/265211473-57d46e33-5b37-4a34-936f-d211b1d6c348.png)

![image](https://github.com/Nemo2011/bilibili-api/assets/40910637/a91b90f1-85c3-4a1d-956b-368a3ec423a1)
难绷

**Comment by Ikaros-521** [comment]
还必须在首页。。。难绷

**Comment by Ikaros-521** [comment]
> 还必须在首页。。。难绷

好吧，也不是，这个参数不是稳定被设置的。。。

**Comment by Ikaros-521** [comment]
退出重新登录后有了。呃
![TUD~V_ `BTEOO`G_5PFVQSK](https://github.com/Nemo2011/bilibili-api/assets/40910637/136c577d-dd4e-4f8b-b23a-43b209ccfb1d)

**Comment by z0z0r4** [comment]
我没话说

**Comment by Ikaros-521** [comment]
![@V_~4GX7OYGLBQ`AL03%XNH](https://github.com/Nemo2011/bilibili-api/assets/40910637/4e8abe52-5ee8-40b8-a3c6-95b99c46dc24)
