### ISSUE TITLE
【提问】爬取弹幕时添加时间爬历史弹幕的时候出现问题

### ISSUE THREAD

**Issue by JiaLeDe** [Nemo2011/bilibili-api#228]
出现问题，时间类型按文档要求填写的，不知道为什么会报错
![image](https://user-images.githubusercontent.com/63954316/222079949-970e5ad4-af09-4288-b356-51df8f721c9d.png)

**Comment by Nemo2011** [comment]
不是传参的问题，历史弹幕需要登录，`Video` 类初始化需要传入 `Credential` 类并携带 `SESSDATA`

**Comment by Nemo2011** [comment]
这就是为什么 `CredentialNoSessdataException`

**Comment by Drelf2018** [comment]
![222079949-970e5ad4-af09-4288-b356-51df8f721c9d](https://user-images.githubusercontent.com/41439182/222092714-6fc25e16-f71c-4696-ab6d-a570ff16b6f6.png)

**Comment by Nemo2011** [comment]
你可以参考一下视频点赞的示例，然后就知道如何传入 `Credential` 了

**Comment by z0z0r4** [comment]
缺少 Credential 已解决
