### ISSUE TITLE
【需求】最近手机版的哔哩哔哩出现了自动截长图的功能

### ISSUE THREAD

**Issue by NONAME-2121237** [Nemo2011/bilibili-api#237]
请问这个功能是api还是本地生成的
想要api

**Comment by z0z0r4** [comment]
截图肯定是本地的吧，哪有API的...你指的是什么的截图，大概哪的功能，不清楚，指明下？

**Comment by NONAME-2121237** [comment]
![F128DDB52B6BD4D2846968721EAF67F8](https://user-images.githubusercontent.com/104999550/226206726-9fdefded-2ffa-4b22-b6ea-27745be4c304.jpg)
这个功能，我觉得很好用，想来做bilibili的手机推送

**Comment by z0z0r4** [comment]
这个是前端的吧...
