### ISSUE TITLE
【漏洞】import错误和CLOSE_WAIT问题

### ISSUE THREAD

**Issue by Apple-QAQ** [Nemo2011/bilibili-api#24]
**Python 版本：** 3.9 / **NodeJS 版本：** 无

**模块版本：** 11.5.1 (python/JS&TS)

**运行环境：** Debian 11 x86_64     Kernel: 5.10.0-14-amd64

**模块路径：** ./.local/lib/python3.9/site-packages

**解释器(Python)：** python

**报错信息：**

``` Python3
Exception in thread Thread-9:
Traceback (most recent call last):
File "/home/appleUqaq/haku-qqbot/plugins/commands/bilibili.py", line 1, in <module>
    import bilibili_api
  File "/home/appleUqaq/.local/lib/python3.9/site-packages/bilibili_api/__init__.py", line 17, in <module>
    nest_asyncio.apply()
  File "/home/appleUqaq/.local/lib/python3.9/site-packages/nest_asyncio.py", line 16, in apply
    loop = loop or asyncio.get_event_loop()
  File "/home/appleUqaq/.local/lib/python3.9/site-packages/nest_asyncio.py", line 45, in _get_event_loop
    loop = events.get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-9'.
```

**报错代码：**

``` Python3
import bilibili_api
```

---

还有一个问题，就是如果执行多次用 `lsof | grep CLOSE_WAIT` 查找则会出现CLOSE_WAIT，会导致 `OSError: Too many open files` ，因为不会异步，所以用的都是bilibili_api.sync()
![image](https://user-images.githubusercontent.com/88485487/180458030-4944377a-9af6-42d5-8da1-99bac8e6ecec.png)

**Comment by Nemo2011** [comment]
Hello, 我怀疑出问题的是 nest_asyncio（看报错堆栈）要不试一试 11.6.0，我把 nest_asyncio 删了，要不看一下最新版有没有解决。

**Comment by Apple-QAQ** [comment]
> 可能出问题的是 nest_asyncio（看报错堆栈）要不试一试 11.6.0，我把 nest_asyncio 删了，看一下最新版有没有解决。

好的谢谢

**Comment by Apple-QAQ** [comment]
> 可能出问题的是 nest_asyncio（看报错堆栈）要不试一试 11.6.0，我把 nest_asyncio 删了，看一下最新版有没有解决。

import 错误已解决，CLOSE_WAIT问题仍在

![image](https://user-images.githubusercontent.com/88485487/180610527-75792a9b-ba36-430f-a7ad-ca03a78070ad.png)

---

相关用到bilibili_api的代码: 

``` Python3
import bilibili_api.utils.sync
import bilibili_api.live


class GetLive:
    def __init__(self, room_id: int):

        self.info = bilibili_api.sync(bilibili_api.live.LiveRoom(room_id).get_room_info())

    def useful_get_info(self):
        """
        获取一些常用的
        """
        get_live_info = self.info
        if get_live_info['room_info']['live_status'] == 0:
            status = "未在直播"
        else:
            status = "正在直播"
        return status

      ...
...


print(Getlive(114514).useful_get_info())
```
或者说，这有可能不是bug，但是也请教一下如何解决此问题，万分感谢

**Comment by Nemo2011** [comment]
能否说明一下机器人是怎么做到“不会关闭”的，麻烦把代码贴一下。

**Comment by Apple-QAQ** [comment]
> 能否说明一下机器人是怎么做到“不会关闭”的，麻烦把代码贴一下。

类似于:
``` Python3
import bilibili_api.utils.sync
import bilibili_api.live
import time


class GetLive:
    def __init__(self, room_id: int):

        self.info = bilibili_api.sync(bilibili_api.live.LiveRoom(room_id).get_room_info())

    def useful_get_info(self):
        """
        获取一些常用的
        """
        get_live_info = self.info
        if get_live_info['room_info']['live_status'] == 0:
            status = "未在直播"
        else:
            status = "正在直播"
        return status

    ...  # 若干代码
...  # 若干代码


get = GetLive(114514)
while True:
    tmp = ''
    ret = get.useful_get_info()
    if ret != tmp:
        tmp = ret
        print(ret)
    time.sleep(300)
```
因为人不在家，所以写了个类似的

**Comment by Nemo2011** [comment]
我好像知道原因了。你的 GetLive 类在 __init__ 请求完之后，代码就切到了 while True 死循环，人家请求的的连接还来不及关掉，然后就 close_wait 了（亲测 web 请求+while True=CLOSE_WAIT）。CLOSE_WAIT 不会影响代码运行的，to many open files 的罪魁祸首应该不是 CLOSE_WAIT，而是 while True。以上说法只是猜测。总之整体影响不大，而且代码运行时也没有出问题。

**Comment by Apple-QAQ** [comment]
> 我好像知道原因了。你的 GetLive 类在 __init__ 请求完之后，代码就切到了 while True 死循环，连接还来不及关掉就到了死循环(你要相信 asyncio)，然后就 close_wait 了（亲测 web 请求+while True=CLOSE_WAIT）。CLOSE_WAIT 不会影响代码运行的，to many open files 的罪魁祸首应该不是 CLOSE_WAIT，而是 while True 死循环永远不会停下来。以上说法只是猜测。总之 CLOSE_WAIT 问题整体影响不大，而且代码运行时也没有出问题。

好的谢谢
