### ISSUE TITLE
【需求】个人开直播，自动回复直播间弹幕

### ISSUE THREAD

**Issue by ZJJHYM** [Nemo2011/bilibili-api#240]
你好，有没有回复直播间弹幕的接口，回复内容我可以自己搞，接口有吗，感谢楼主！

**Comment by Drelf2018** [comment]
```python
from bilibili_api import Credential, Danmaku, sync
from bilibili_api.live import LiveDanmaku, LiveRoom

# 自己直播间号
ROOMID = 123
# 凭证 根据回复弹幕的账号填写
credential = Credential(
    sessdata="",
    bili_jct=""
)
# 监听直播间弹幕
monitor = LiveDanmaku(ROOMID, credential=credential)
# 用来发送弹幕
sender = LiveRoom(ROOMID, credential=credential)
# 自己的UID 可以手动填写也可以根据直播间号获取
UID = sync(sender.get_room_info())["room_info"]["uid"]


@monitor.on("DANMU_MSG")
async def recv(event):
    # 发送者UID
    uid = event["data"]["info"][2][0]
    # 排除自己发送的弹幕
    if uid == UID:
        return
    # 弹幕文本
    msg = event["data"]["info"][1]
    if msg == "你好":
        # 发送弹幕
        await sender.send_danmaku(Danmaku("你好！"))


# 启动监听
sync(monitor.connect())
```

**Comment by iceshoesss** [comment]
> 

请问我参考这段代码，把最后同步改成

> asyncio.run(monitor.connect())
可以正常使用，但是会提示bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：10031，信息：您发送弹幕的频率过快。
如何避免这个报错？

**Comment by iceshoesss** [comment]
> ```python
> from bilibili_api import Credential, Danmaku, sync
> from bilibili_api.live import LiveDanmaku, LiveRoom
> 
> # 自己直播间号
> ROOMID = 123
> # 凭证 根据回复弹幕的账号填写
> credential = Credential(
>     sessdata="",
>     bili_jct=""
> )
> # 监听直播间弹幕
> monitor = LiveDanmaku(ROOMID, credential=credential)
> # 用来发送弹幕
> sender = LiveRoom(ROOMID, credential=credential)
> # 自己的UID 可以手动填写也可以根据直播间号获取
> UID = sync(sender.get_room_info())["room_info"]["uid"]
> 
> 
> @monitor.on("DANMU_MSG")
> async def recv(event):
>     # 发送者UID
>     uid = event["data"]["info"][2][0]
>     # 排除自己发送的弹幕
>     if uid == UID:
>         return
>     # 弹幕文本
>     msg = event["data"]["info"][1]
>     if msg == "你好":
>         # 发送弹幕
>         await sender.send_danmaku(Danmaku("你好！"))
> 
> 
> # 启动监听
> sync(monitor.connect())
> ```

请问我参考这段代码，最后同步改成

> asyncio.run(monitor.connect())

可以正常使用，但是会出现

> bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：10031，信息：您发送弹幕的频率过快。

请问如何避免这样的错误？

**Comment by z0z0r4** [comment]
似乎是 monitor 的轮询没等够，待检查

**Comment by z0z0r4** [comment]
`bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：10031，信息：您发送弹幕的频率过快。`

这真的只是发送频率太快了吧？你发送弹幕了吗，不是意外触发吧？正常的，没辙

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/111314f9-a911-4a63-9051-be0dc3a6aa59)

**Comment by wartheking** [comment]
sessdata和bili_jct我都是拿chrome最新的，为啥自动发送弹幕会返回这个
{'code': -111, 'message': 'csrf 校验失败', 'ttl': 1}

**Comment by z0z0r4** [comment]
> sessdata和bili_jct我都是拿chrome最新的，为啥自动发送弹幕会返回这个 {'code': -111, 'message': 'csrf 校验失败', 'ttl': 1}

你确定吗...给下示例代码？

**Comment by wartheking** [comment]
# 自己直播间号
ROOMID = 
# 凭证 根据回复弹幕的账号填写
credential = Credential(
    sessdata="",
    bili_jct="",
    buvid3=""
)

# 监听直播间弹幕
monitor = LiveDanmaku(ROOMID, credential=credential)
# 用来发送弹幕
sender = LiveRoom(ROOMID, credential=credential)
# 自己的UID 可以手动填写也可以根据直播间号获取
UID = sync(sender.get_room_info())["room_info"]["uid"]

print(UID)

@monitor.on('DANMU_MSG')
async def on_danmaku(event):
    # 收到弹幕
    #jsonData = json.loads(event)
    #print(event["data"])
    #print(event["data"]["info"][0][15]["extra"])
    
    msg = event["data"]["info"][1]
    print("------------------------")
    userName = event["data"]["info"][2][1]
    uid = event["data"]["info"][2][0]

    print("UID:" + str(UID))
    print("uid:" + str(uid))
     
    match = re.match(r"第(\d+)集", msg)
    if match:
        episode_number = int(match.group(1))
        
        if 1 <= episode_number <= 200:
            # 调用对应的函数
            await sender.send_danmaku(Danmaku("{0}成功切换至{1}!".format(userName,msg)))
                

@monitor.on('SEND_GIFT')
async def on_gift(event):
    # 收到礼物
    print(event)


# 启动直播间连接
sync(monitor.connect())

**Comment by z0z0r4** [comment]
给下对应的roomid?

**Comment by wartheking** [comment]
> 给下对应的roomid?方便测试

搞明白了，send_danmaku不能放异步，回调，线程里面，否则验证不过，放主线程没问题

**Comment by Drelf2018** [comment]
> > 给下对应的roomid?方便测试
> 
> 搞明白了，send_danmaku不能放异步，回调，线程里面，否则验证不过，放主线程没问题

该漏洞解释和修复见 #355

**Comment by simonheard** [comment]
大佬，想请教一下监听不到弹幕是什么原因呀？
![image](https://github.com/Nemo2011/bilibili-api/assets/90641289/a11b45c1-c3e2-42b0-a93b-cf940b57fedc)

**Comment by like2dog** [comment]
大佬 大佬 sync(room.connect())  链接时一直 返回-352是什么情况呀，我检查了cookie是没问题的，可以正常发弹幕。
