### ISSUE TITLE
【提问】关于comment模块无法爬取所有评论

### ISSUE THREAD

**Issue by andoninari** [Nemo2011/bilibili-api#241]
**Python 版本：** 3.8

**模块版本：** 15.3.1

**运行环境：** Windows 

---
依照文档里的范例直接爬取，试过不同视频都只显示总评论在200多条左右，实际评论都超过这个数量。
而且爬取下来的也只有部分评论，请问是接口那边更新了导致失效吗
![image](https://user-images.githubusercontent.com/114718547/226254278-007b4b02-19a0-4b1b-aee2-2f8e95e66a85.png)
![image](https://user-images.githubusercontent.com/114718547/226254346-b90ea319-5dd8-4f31-ae43-0d39f692a828.png)
![image](https://user-images.githubusercontent.com/114718547/226539613-8980845f-c704-4b03-97aa-16b91b5307c2.png)
代码和示例里的一致 只加了个写入文本

**Comment by Drelf2018** [comment]
调用 ```get_comments()``` 函数时添加了参数 ```credential``` 吗

**Comment by andoninari** [comment]
> 

没有 我只按照了文档示例的 提供了视频地址 和 comment.CommentResourceType.VIDEO, page 这两个参数

**Comment by Drelf2018** [comment]
你加上凭证试试呢

**Comment by andoninari** [comment]
> 你加上凭证试试呢

解决了 非常感谢
