### ISSUE TITLE
【提问】使用后用过的cookie全部失效

### ISSUE THREAD

**Issue by brestain** [Nemo2011/bilibili-api#244]
**Python 版本：3.9.10

**模块版本：latest

**运行环境：** Windows

---

昨晚测试了点赞视频,点赞评论,获取硬币数量几个功能后,今天发现cookie全部失效了.

**Comment by z0z0r4** [comment]
正常...

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/issues/146#issue-1550763921

**Comment by brestain** [comment]
不不不,我用的是无痕模式下的cookie,不会很快更新,之前一直用requests库调用api正常使用很久的.今天全部失效,手机端和网页端的登录也给顶下去了

**Comment by z0z0r4** [comment]
> 不不不,我用的是无痕模式下的cookie,不会很快更新,之前一直用requests库调用api正常使用很久的.今天全部失效,手机端和网页端的登录也给顶下去了

显然和本库无关啦...还是说 httpx 请求和 requests 被B站认出来了 :（
