### ISSUE TITLE
【提问】获取收藏夹列表接口内的type，不明白为什么判断出错

### ISSUE THREAD

**Issue by night-zhang** [Nemo2011/bilibili-api#245]
**Python 版本：** 3.8.10

**模块版本：** 直接在项目主支尝试(最新commit到：183a01ea)

**运行环境：** Windows

---
测试脚本如下，执行get_content_video方法时，直接报`AssertionError: 此函数仅在收藏夹为视频收藏家时可用`的错，前两个函数分别能正确得到`<FavoriteListType.VIDEO: 'video'>`和`True`。
不太清楚为什么会这样，尝试把`bilibili_api/favorite_list.py`的106行改成`assert self.__type.value != FavoriteListType.VIDEO, "此函数仅在收藏夹为视频收藏家时可用"`又可以正常执行。
`is_video_favorite_list`都可以正常执行，这里不行，是py版本问题？还是异步会不一样？

```python
import asyncio
import pprint
from bilibili_api import favorite_list
from account_info import credential, uid


async def main() -> None:
    video_favorite_list = await favorite_list.get_video_favorite_list(uid=uid, credential=credential)

    favorite_obj = favorite_list.FavoriteList(media_id=video_favorite_list['list'][0]["id"],
                                              credential=credential)

    resp = favorite_obj.get_favorite_list_type()
    pprint.pprint(resp)
    resp = favorite_obj.is_video_favorite_list()
    pprint.pprint(resp)
    resp = await favorite_obj.get_content_video()
    pprint.pprint(resp)


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())


```

**Comment by z0z0r4** [comment]
发下你的favorite_list id？

**Comment by z0z0r4** [comment]
无法处理...

**Comment by lihaoyun6** [comment]
> 无法处理...

正常现象, 可能是这一段的贡献者写累了不小心大脑串线了. 断言的逻辑是成功放行, 失败报错
所以`favorite_list.py`中的这一行
`assert self.__type != FavoriteListType.VIDEO, "此函数仅在收藏夹为视频收藏家时可用"`
应该改为这样就对了
`assert self.__type == FavoriteListType.VIDEO, "此函数仅在收藏夹为视频收藏夹时可用"`

按照原来代码的逻辑, 只有在self的类型不是FavoriteListType.VIDEO的情况下才会放行, 一单相等反而会报错

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/commit/6f705c4398ff9e90d1579c3159a31365f8915add

已修复，感谢排查 @lihaoyun6
