### ISSUE TITLE
【提问】下载模块后显示imported module bilibili_api' 中找不到引用 'video' 

### ISSUE THREAD

**Issue by zhaozhao678** [Nemo2011/bilibili-api#247]
**Python 版本：3。9

**模块版本：15.3.1

**运行环境：Windows 

![image](https://user-images.githubusercontent.com/103492415/228263018-1ff074a4-38f9-4514-b58e-fc3481f3309a.png)
![image](https://user-images.githubusercontent.com/103492415/228263154-fc5c6e16-3400-4087-841c-be9ca86ed1d1.png)

不知道是为什么，是从之前更新来的，把之前的包卸载之后重新下载的15.3.1版本

**Comment by Drelf2018** [comment]
我有个猜测是不是你文件名是 `video.py`

**Comment by zhaozhao678** [comment]
是3.9的，我看了15.3.1是支持3.9版本的，不明白是怎么回事？
![image](https://user-images.githubusercontent.com/103492415/228406681-4cdf9fe8-ba55-4e81-a2af-0d8b35243777.png)

**Comment by Nemo2011** [comment]
在REPL里面尝试引入
