### ISSUE TITLE
【提问】无法下载历史弹幕

### ISSUE THREAD

**Issue by debuggerzh** [Nemo2011/bilibili-api#248]
**Python 版本：** 3.10

**模块版本：** 15.3.1

**运行环境：** Windows

---
如题，下载历史弹幕的代码报错提示Credential 类未提供 sessdata
```python
import datetime

from bilibili_api import ass, sync, video
from bilibili_api import Credential

cred = Credential(sessdata="我的sessdata",
                  ……)

dt = datetime.date(2022, 5, 5)

sync(ass.make_ass_file_danmakus_protobuf(video.Video("BV1AV411x7Gs"), 0,
                                         dt.strftime("%Y-%m-%d"), credential=cred,
                                         date=dt))
```

![image](https://user-images.githubusercontent.com/51440761/228293269-ea296a6d-230c-4643-a1db-a3258df89b32.png)

**Comment by Drelf2018** [comment]
`video.Video("BV1AV411x7Gs", credential=cred)`

**Comment by Drelf2018** [comment]
https://github.com/Nemo2011/bilibili-api/blob/main/bilibili_api/ass.py#L141-L143

@Nemo2011 这函数既然已经要求了传入 `credential` 并且判断过了，是不是在后续处理的时候给没有 `credential` 的 `obj` 添加上这个 `credential` ？

不过感觉也不太好，是否传入 `credential` 也应该由使用者自行决定。
