### ISSUE TITLE
能用 requests去擷取Credential 類所需全部訊息嗎?

### ISSUE THREAD

**Issue by TommcyOWO** [Nemo2011/bilibili-api#253]
**Python 版本：** 3.8.9

**模块版本：** 最新

**运行环境：** Windows
---

我想利用此api 寫一個下載器，盡量簡潔。
但我一直無法擷取Credential 類所需的全部cookie
只有BUVID3 和b_nut
如果想下載影片，有沒有更好的解決方式?

**Comment by Nemo2011** [comment]
可以写登录窗口，用登录接口可以获取所有需要的 cookies

**Comment by TommcyOWO** [comment]
> 可以写登录窗口，用登录接口可以获取所有需要的 cookies

ok感謝
