### ISSUE TITLE
【提问】文章的 get_all 似乎有问题？

### ISSUE THREAD

**Issue by dongruixiao** [Nemo2011/bilibili-api#255]
**Python 版本：** 3.x.y

**模块版本：** x.y.z

**运行环境：** Windows / Linux / MacOS

---

<img width="959" alt="image" src="https://user-images.githubusercontent.com/16684015/230406871-853652c0-2ae9-4531-8f46-16ed615bb059.png">

**Comment by dongruixiao** [comment]
加了 headers 就好了

**Comment by z0z0r4** [comment]
等 main 分支更新 https://github.com/Nemo2011/bilibili-api/pull/252#commits-pushed-01f03ee

**Comment by z0z0r4** [comment]
已合并
