### ISSUE TITLE
【提问】{这里填写标题}

### ISSUE THREAD

**Issue by nevertoday** [Nemo2011/bilibili-api#256]
**Python 版本：** 3.9

**模块版本：** x.y.z

**运行环境：macos

---
执行处理到4083条，就会提示错误，反复测试多次了，好奇怪
 File "/opt/homebrew/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 186, in connect_tcp
    addr_obj = ip_address(remote_host)

**Comment by z0z0r4** [comment]
请给出复现代码。。

**Comment by z0z0r4** [comment]
@Nemo2011 话说 Github 有办法给仓库部分权限的吗？
比如我有空可以帮你关些逆天 issue 之类的，实在是看了无语，有时比较闲
