### ISSUE TITLE
【412】报错412，bilibili_api.exceptions.NetworkException: 网络错误。状态码：412

### ISSUE THREAD

**Issue by qinxukun21** [Nemo2011/bilibili-api#257]
**Python 版本：** 3.9

**模块版本：** 4.1.0

**运行环境：** Windows

---

爬取时报错
Traceback (most recent call last):
  File "E:\PyCharmWorkplace\bilibili_web\main.py", line 37, in <module>
    for each_comment in comment_generator:
  File "E:\Anaconda\lib\site-packages\bilibili_api\common.py", line 165, in get_comments
    resp = get_comments_raw(oid=oid, pn=page, order=order, verify=verify, type_=type_)
  File "E:\Anaconda\lib\site-packages\bilibili_api\common.py", line 147, in get_comments_raw
    resp = utils.get(api["url"], params=params, cookies=verify.get_cookies())
  File "E:\Anaconda\lib\site-packages\bilibili_api\utils.py", line 424, in get
    resp = request("GET", url=url, params=params, cookies=cookies, headers=headers, data_type=data_type, **kwargs)
  File "E:\Anaconda\lib\site-packages\bilibili_api\utils.py", line 410, in request
    raise exceptions.NetworkException(req.status_code)
bilibili_api.exceptions.NetworkException: 网络错误。状态码：412

Process finished with exit code 1

**Comment by qinxukun21** [comment]
from bilibili_api import video, user
import pymysql

# 连接数据库
conn = pymysql.connect(host='127.0.0.1'
                       , user='root'
                       , passwd='123456'
                       , port=3306
                       , db='bilibili_comment'
                       , charset='utf8mb4'
                       )
cur = conn.cursor()  # 生成游标对象

# 零刻的uid
target_uid = '477318199'
video_generator = list(user.get_videos_g(uid=target_uid))

index = 0
for each_video in video_generator:
    index += 1
    print("Collecting video {}".format(index))
    video_id = each_video["bvid"]
    video_title = each_video["title"]
    user_id = each_video["mid"]
    video_description = each_video["description"]
    video_length = each_video["length"]
    play_num = each_video["play"]
    comment_num = each_video["comment"]

    sql = "REPLACE INTO video VALUES ('{}','{}','{}','{}','{}','{}','{}')"
    sql = sql.format(video_id, video_title, user_id, video_description, video_length, play_num, comment_num)
    cur.execute(sql)  # 执行插入的sql语句
    conn.commit()  # 提交到数据库执行

    # 爬取当前视频下的评论 注意root和parent的区别
    comment_generator = video.get_comments_g(bvid=video_id)
    for each_comment in comment_generator:
        comment_id = each_comment["rpid"]
        root_id = each_comment["root"]
        parent_id = each_comment["parent"]
        comment_user_id = each_comment["mid"]
        comment_content = each_comment["content"]["message"]
        comment_video_id = video_id
        like_num = each_comment["like"]
        subcomment_num = each_comment["rcount"]
        print("Collecting comment {}".format(comment_id))
        sql = "REPLACE INTO comment VALUES ('{}','{}','{}','{}','{}','{}','{}','{}')"
        sql = sql.format(comment_id, root_id, parent_id, comment_user_id, comment_content, comment_video_id, like_num,
                         subcomment_num)
        cur.execute(sql)  # 执行插入的sql语句
        conn.commit()  # 提交到数据库执行

        if subcomment_num != 0:
            sub_comment_generator = video.get_sub_comments_g(root=comment_id, bvid=video_id)
            for each_sub_comment in sub_comment_generator:
                sub_comment_id = each_sub_comment["rpid"]
                sub_root_id = each_sub_comment["root"]
                sub_parent_id = each_sub_comment["parent"]
                sub_comment_user_id = each_sub_comment["mid"]
                sub_comment_content = each_sub_comment["content"]["message"]
                sub_comment_video_id = video_id
                sub_like_num = each_sub_comment["like"]
                sub_subcomment_num = each_sub_comment["rcount"]
                print("Collecting comment {}".format(sub_comment_id))
                sql = "REPLACE INTO comment VALUES ('{}','{}','{}','{}','{}','{}','{}','{}')"
                sql = sql.format(sub_comment_id, sub_root_id, sub_parent_id, sub_comment_user_id, sub_comment_content,
                                 sub_comment_video_id,
                                 sub_like_num, sub_subcomment_num)
                cur.execute(sql)  # 执行插入的sql语句
                conn.commit()  # 提交到数据库执行

conn.close()  # 关闭数据库连接

**Comment by qinxukun21** [comment]
更改为异步操作仍有问题~
import aiomysql
from bilibili_api import video, user
import asyncio


async def collect_comments(video_id, conn):
    comment_generator = video.get_comments_g(bvid=video_id)
    async with conn.cursor() as cur:
        for each_comment in comment_generator:
            comment_id = each_comment["rpid"]
            root_id = each_comment["root"]
            parent_id = each_comment["parent"]
            comment_user_id = each_comment["mid"]
            comment_content = each_comment["content"]["message"]
            comment_video_id = video_id
            like_num = each_comment["like"]
            subcomment_num = each_comment["rcount"]
            print("Collecting comment {}".format(comment_id))
            sql = "REPLACE INTO comment VALUES (%s, %s, %s, %s, %s, %s, %s, %s)"
            await cur.execute(sql, (comment_id, root_id, parent_id, comment_user_id, comment_content,
                                     comment_video_id, like_num, subcomment_num))
            if subcomment_num != 0:
                sub_comment_generator = video.get_sub_comments_g(root=comment_id, bvid=video_id)
                for each_sub_comment in sub_comment_generator:
                    sub_comment_id = each_sub_comment["rpid"]
                    sub_root_id = each_sub_comment["root"]
                    sub_parent_id = each_sub_comment["parent"]
                    sub_comment_user_id = each_sub_comment["mid"]
                    sub_comment_content = each_sub_comment["content"]["message"]
                    sub_comment_video_id = video_id
                    sub_like_num = each_sub_comment["like"]
                    sub_subcomment_num = each_sub_comment["rcount"]
                    print("Collecting comment {}".format(sub_comment_id))
                    sql = "REPLACE INTO comment VALUES (%s, %s, %s, %s, %s, %s, %s, %s)"
                    await cur.execute(sql, (sub_comment_id, sub_root_id, sub_parent_id, sub_comment_user_id,
                                             sub_comment_content, sub_comment_video_id, sub_like_num,
                                             sub_subcomment_num))
    await conn.commit()


async def collect_videos(target_uid, conn):
    video_generator = list(user.get_videos_g(uid=target_uid))
    index = 0
    async with conn.cursor() as cur:
        for each_video in video_generator:
            index += 1
            print("Collecting video {}".format(index))
            video_id = each_video["bvid"]
            video_title = each_video["title"]
            user_id = each_video["mid"]
            video_description = each_video["description"]
            video_length = each_video["length"]
            play_num = each_video["play"]
            comment_num = each_video["comment"]
            sql = "REPLACE INTO video VALUES (%s, %s, %s, %s, %s, %s, %s)"
            await cur.execute(sql, (video_id, video_title, user_id, video_description, video_length, play_num,
                                     comment_num))
            await collect_comments(video_id, conn)
    await conn.commit()


async def main():
    conn = await aiomysql.connect(host='127.0.0.1', port=3306, user='root', password='123456',
                                   db='bilibili_comment', charset='utf8mb4', autocommit=True)
    target_uid = '477318199'
    await collect_videos(target_uid, conn)
    conn.close()

if __name__ == '__main__':
    asyncio.run(main())

**Comment by z0z0r4** [comment]
能打个断点看看是哪个视频拿不到评论吗...

另外强烈建议使用代码块发example

**Comment by qinxukun21** [comment]
bvid BV1WS4y1J7A4
感谢您的解答，我现在怀疑是因为评论太长了，导致爬取到后边的评论的时候header中的时间验证过期了（我理解的每个generator都有一个确定的时间戳）。我不太清楚我这样的想法对不对。

原代码：
```
from bilibili_api import video, user
import pymysql

# 连接数据库
conn = pymysql.connect(host='127.0.0.1'
                       , user='root'
                       , passwd='123456'
                       , port=3306
                       , db='bilibili_comment'
                       , charset='utf8mb4'
                       )
cur = conn.cursor()  # 生成游标对象


# 零刻的uid
target_uid = '477318199'
video_generator = user.get_videos_g(uid=target_uid)

video_id_list = []
for each_video in video_generator:
    video_id = each_video["bvid"]
    video_title = each_video["title"]
    user_id = each_video["mid"]
    video_description = each_video["description"]
    video_length = each_video["length"]
    play_num = each_video["play"]
    comment_num = each_video["comment"]
    print("Collecting video {}".format(video_id))

    sql = "REPLACE INTO video VALUES ('{}','{}','{}','{}','{}','{}','{}')"
    sql = sql.format(video_id, video_title, user_id, video_description, video_length, play_num, comment_num)
    cur.execute(sql)  # 执行插入的sql语句
    conn.commit()  # 提交到数据库执行

    video_id_list.append(video_id)

sub_comment_dic_list = []

for video_id in video_id_list:
    # 爬取当前视频下的评论 注意root和parent的区别
    comment_generator = video.get_comments_g(bvid=video_id)
    for each_comment in comment_generator:
        comment_id = each_comment["rpid"]
        root_id = each_comment["root"]
        parent_id = each_comment["parent"]
        comment_user_id = each_comment["mid"]
        comment_content = each_comment["content"]["message"]
        comment_video_id = video_id
        like_num = each_comment["like"]
        subcomment_num = each_comment["rcount"]
        print("Collecting comment {} for video {}".format(comment_id, video_id))

        sql = "REPLACE INTO comment VALUES ('{}','{}','{}','{}','{}','{}','{}','{}')"
        sql = sql.format(comment_id, root_id, parent_id, comment_user_id, comment_content, comment_video_id, like_num,
                         subcomment_num)
        cur.execute(sql)  # 执行插入的sql语句
        conn.commit()  # 提交到数据库执行
        if subcomment_num != 0:
            sub_comment_dic_list.append({"comment_id":comment_id, "video_id":video_id})

for sub_comment_dic in sub_comment_dic_list:
    sub_comment_generator = video.get_sub_comments_g(root=sub_comment_dic["comment_id"], bvid=sub_comment_dic["video_id"])
    for each_sub_comment in sub_comment_generator:
        sub_comment_id = each_sub_comment["rpid"]
        sub_root_id = each_sub_comment["root"]
        sub_parent_id = each_sub_comment["parent"]
        sub_comment_user_id = each_sub_comment["mid"]
        sub_comment_content = each_sub_comment["content"]["message"]
        sub_comment_video_id = sub_comment_dic["video_id"]
        sub_like_num = each_sub_comment["like"]
        sub_subcomment_num = each_sub_comment["rcount"]
        print("Collecting sub comment {} for video {} under root comment {}".format(sub_comment_id, sub_comment_dic["video_id"], sub_root_id))

        sql = "REPLACE INTO comment VALUES ('{}','{}','{}','{}','{}','{}','{}','{}')"
        sql = sql.format(sub_comment_id, sub_root_id, sub_parent_id, sub_comment_user_id, sub_comment_content,
                         sub_comment_video_id,
                         sub_like_num, sub_subcomment_num)
        cur.execute(sql)  # 执行插入的sql语句
        conn.commit()  # 提交到数据库执行

conn.close()  # 关闭数据库连接

```

**Comment by z0z0r4** [comment]
请问使用的版本是...？完全没找到 ` video.get_comments_g(bvid=video_id)` 这个函数...

也许你的版本已经过时了？`pip install bilibili-api-python --upgrade`

**Comment by z0z0r4** [comment]
![image](https://user-images.githubusercontent.com/78744121/230752932-cb718be2-d58a-41ac-be9a-b2cfeb537b85.png)

```python
from bilibili_api import video, comment
await comment.get_comments(video.Video("BV1WS4y1J7A4").get_aid(), type_=comment.CommentResourceType.VIDEO)
```

**Comment by qinxukun21** [comment]
ahah 我刚注意到。。好滴 感谢。。我还说我的video为啥不是一个类。。

**Comment by z0z0r4** [comment]
可以 close 了
