### ISSUE TITLE
【提问】请问只能获取粉丝列表前五页吗

### ISSUE THREAD

**Issue by WShihan** [Nemo2011/bilibili-api#258]
**Python 版本：** 3.10.0

**模块版本：**  15.3.1

**运行环境：** MacOS

---

请问目前只能获取粉丝列表前五页，是官方接口的限制的吗？

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/52617949/230774663-5f25f68f-afaa-4b3a-a8cc-e5b89424c7b3.png">

**Comment by Drelf2018** [comment]
这是B站的限制

**Comment by WShihan** [comment]
请问有没有方法能突破限制呢

**Comment by Drelf2018** [comment]
不在本库使用范围内

**Comment by z0z0r4** [comment]
> 请问有没有方法能突破限制呢

没有
