### ISSUE TITLE
【需求】请问可以加上分区和栏目的API吗

### ISSUE THREAD

**Issue by SCUTJcfeng** [Nemo2011/bilibili-api#26]
类似于下面这种，没找到相应的API
- 分区列表 get_tid_list
- 栏目列表 get_cid_list_by_tid

**Comment by Nemo2011** [comment]
get_tid_list 对应 bilibili_api.channel.get_channel_list,
get_cid_list_by_tid（是指一个分区的所有子分区吗） 对应 bilibili_api.channel.get_channel_info_by_tid(tid) 的结果的 sub 键值对应的列表。

**Comment by SCUTJcfeng** [comment]
噢噢，我看到了，原来直接写在json里了，好的
