### ISSUE TITLE
【提问】1200是什么错误

### ISSUE THREAD

**Issue by SCUTJcfeng** [Nemo2011/bilibili-api#27]
接口是 `user.get_videos`，`msg`为空，可能是偶发的，这个错误码遇到过吗？

**Comment by Nemo2011** [comment]
麻烦可以给一下您的用户的 uid 吗（就是您要查看哪一个用户的视频）。

**Comment by SCUTJcfeng** [comment]
偶然出现的，我批量跑的，那个id再跑一遍又没报错了

**Comment by Nemo2011** [comment]
https://zhidao.baidu.com/question/881498264978604612.html

这个可能就是唯一记载 1200 错误码的地方了，只能说，这个错误码不常见。可能是你在批量跑时系统繁忙吧。这种情况就先加上 try except 吧。
