### ISSUE TITLE
【提问】在json中定义了接口,但是在api层没有暴露

### ISSUE THREAD

**Issue by HeavenElegy** [Nemo2011/bilibili-api#272]
**Python 版本：** 3.9

**模块版本：** 15.4.1

**运行环境：** Windows

---
具体接口如下图
![image](https://user-images.githubusercontent.com/19890506/235571795-31a72292-9c8a-44b8-8dea-399388b2e1c2.png)
我简单的全局搜了下,似乎没有发现引用

**Comment by z0z0r4** [comment]
虽然不知道为什么没实装，但似乎这个接口有问题

`https://api.bilibili.com/x/v3/fav/folder/collected/list?up_mid=178429408&pn=1&ps=10`

返回

```JSON
{
    "code": 0,
    "message": "0",
    "ttl": 1,
    "data": {
        "count": 1,
        "list": [
            {
                "id": 1383946363,
                "fid": 13839463,
                "mid": 646313163,
                "attr": 22,
                "title": "杂谈",
                "cover": "http://i1.hdslb.com/bfs/archive/07ded5421d7a4ab3c78e2d17a4d22cbae7411bdc.jpg",
                "upper": {
                    "mid": 646313163,
                    "name": "datsasts",
                    "face": ""
                },
                "cover_type": 2,
                "intro": "",
                "ctime": 1634966932,
                "mtime": 1634966932,
                "state": 0,
                "fav_state": 0,
                "media_count": 44,
                "view_count": 0,
                "vt": 0,
                "play_switch": 0,
                "type": 11,
                "link": "",
                "bvid": ""
            }
        ],
        "has_more": false
    }
}
```

按照 comment 里面是获取自己的，然而其他指定账户的也可以，且数据也不全，如上返回值只有一个收藏夹被获取...

此接口有待考究？有什么看法吗，大雾

**Comment by HeavenElegy** [comment]
> 虽然不知道为什么没实装，但似乎这个接口有问题
> 
> `https://api.bilibili.com/x/v3/fav/folder/collected/list?up_mid=178429408&pn=1&ps=10`
> 
> 返回
> 
> ```json
> {
>     "code": 0,
>     "message": "0",
>     "ttl": 1,
>     "data": {
>         "count": 1,
>         "list": [
>             {
>                 "id": 1383946363,
>                 "fid": 13839463,
>                 "mid": 646313163,
>                 "attr": 22,
>                 "title": "杂谈",
>                 "cover": "http://i1.hdslb.com/bfs/archive/07ded5421d7a4ab3c78e2d17a4d22cbae7411bdc.jpg",
>                 "upper": {
>                     "mid": 646313163,
>                     "name": "datsasts",
>                     "face": ""
>                 },
>                 "cover_type": 2,
>                 "intro": "",
>                 "ctime": 1634966932,
>                 "mtime": 1634966932,
>                 "state": 0,
>                 "fav_state": 0,
>                 "media_count": 44,
>                 "view_count": 0,
>                 "vt": 0,
>                 "play_switch": 0,
>                 "type": 11,
>                 "link": "",
>                 "bvid": ""
>             }
>         ],
>         "has_more": false
>     }
> }
> ```
> 
> 按照 comment 里面是获取自己的，然而其他指定账户的也可以，且数据也不全，如上返回值只有一个收藏夹被获取...
> 
> 此接口有待考究？有什么看法吗，大雾

可以试下[https://api.bilibili.com/x/v3/fav/folder/collected/list?pn=1&ps=20&up_mid=178429408&platform=web&jsonp=jsonp](url)
添加platform参数后,就可以正常返回了(大概

**Comment by z0z0r4** [comment]
> > 虽然不知道为什么没实装，但似乎这个接口有问题
> > `https://api.bilibili.com/x/v3/fav/folder/collected/list?up_mid=178429408&pn=1&ps=10`
> > 返回
> > ```json
> > {
> >     "code": 0,
> >     "message": "0",
> >     "ttl": 1,
> >     "data": {
> >         "count": 1,
> >         "list": [
> >             {
> >                 "id": 1383946363,
> >                 "fid": 13839463,
> >                 "mid": 646313163,
> >                 "attr": 22,
> >                 "title": "杂谈",
> >                 "cover": "http://i1.hdslb.com/bfs/archive/07ded5421d7a4ab3c78e2d17a4d22cbae7411bdc.jpg",
> >                 "upper": {
> >                     "mid": 646313163,
> >                     "name": "datsasts",
> >                     "face": ""
> >                 },
> >                 "cover_type": 2,
> >                 "intro": "",
> >                 "ctime": 1634966932,
> >                 "mtime": 1634966932,
> >                 "state": 0,
> >                 "fav_state": 0,
> >                 "media_count": 44,
> >                 "view_count": 0,
> >                 "vt": 0,
> >                 "play_switch": 0,
> >                 "type": 11,
> >                 "link": "",
> >                 "bvid": ""
> >             }
> >         ],
> >         "has_more": false
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 按照 comment 里面是获取自己的，然而其他指定账户的也可以，且数据也不全，如上返回值只有一个收藏夹被获取...
> > 此接口有待考究？有什么看法吗，大雾
> 
> 可以试下`https://api.bilibili.com/x/v3/fav/folder/collected/list?pn=1&ps=20&up_mid=178429408&platform=web&jsonp=jsonp` 添加platform参数后,就可以正常返回了(大概

我明天去看看，处理下，或者能否提个PR？

**Comment by HeavenElegy** [comment]
提pr?
我可没写过开源啊 | ω・´)

**Comment by Drelf2018** [comment]
> 提pr? 我可没写过开源啊 | ω・´)

可以试试哦 [pr指南](https://github.com/nemo2011/bilibili-api/blob/main/.github/CONTRIBUTING.md)

**Comment by z0z0r4** [comment]
> 提pr?
> 我可没写过开源啊 | ω・´)

具体的话，写个函数封装，加上test和docs

也可以参考  https://github.com/Nemo2011/bilibili-api/commit/d48037810f992b1bc7ec782460429945836f0e65 的流程

**Comment by HeavenElegy** [comment]
我看下
