### ISSUE TITLE
【文档】 这里的三种参数都是英文pubdate吗

### ISSUE THREAD

**Issue by debuggerzh** [Nemo2011/bilibili-api#274]
如题
https://github.com/Nemo2011/bilibili-api/blob/5481b2c57ac07c4c36a1242278a1335bf3642d68/bilibili_api/data/api/user.json#L111

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/commit/bf8ab074fba1f549ec12f82d7474fcfb64d6dd57

已经改了
~~可惜是main~~
