### ISSUE TITLE
【提问】{怎么获取艾特自己的消息}

### ISSUE THREAD

**Issue by HzxLsy** [Nemo2011/bilibili-api#276]
如题 找不到接口

**Comment by HzxLsy** [comment]
好像没有收录
地址在这:https://api.bilibili.com/x/msgfeed/at?build=0&mobi_app=web

**Comment by HzxLsy** [comment]
上面的问题已经解决了 现在的新问题是没有监测艾特自己事件的装饰器 这个应该怎么弄啊

**Comment by Drelf2018** [comment]
> 上面的问题已经解决了 现在的新问题是没有监测艾特自己事件的装饰器 这个应该怎么弄啊

轮询不就可以了吗，最简单的一个死循环，每获取一次事件 sleep 几秒

**Comment by Drelf2018** [comment]
@z0z0r4 这个也可以关了

**Comment by Sherlockouo** [comment]
> 上面的问题已经解决了 现在的新问题是没有监测艾特自己事件的装饰器 这个应该怎么弄啊

请问怎么解决的呢？
