### ISSUE TITLE
【异常】3.1.3版本获取一个用户的所有公开视频

### ISSUE THREAD

**Issue by nicliuqi** [Nemo2011/bilibili-api#277]
**Python 版本：** 3.9.9

**模块版本：** 3.1.3

**运行环境：**  Linux

---

user.get_videos_g(uid=uid)这个方法之前返回的是用户所有的视频列表，啥时候被改成返回一个生成器了，且该生成器迭代完只有30个视频

**Comment by Drelf2018** [comment]
版本 `3.1.3` 认真的吗
现在最新版本已经是 `15.4.1` 了，尝试更新库

```cmd
pip uninstall bilibili-api
pip install bilibili-api-python
```

**Comment by z0z0r4** [comment]
这很抽象，逆天版本

**Comment by nicliuqi** [comment]
> 版本 `3.1.3` 认真的吗 现在最新版本已经是 `15.4.1` 了，尝试更新库
> 
> ```batchfile
> pip uninstall bilibili-api
> pip install bilibili-api-python
> ```

虽然但是，突然发现功能不可用了有点疑惑

**Comment by nicliuqi** [comment]
> 这很抽象，逆天版本

版本迭代太快了  如果现版本无法使用会考虑升级版本的

**Comment by z0z0r4** [comment]
> > 这很抽象，逆天版本
> 
> 版本迭代太快了 如果现版本无法使用会考虑升级版本的

强烈建议升级，一般用不了，接口变动
