### ISSUE TITLE
[提问] 为什么 action 发布不出去...

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#287]
见 https://github.com/Nemo2011/bilibili-api/actions/runs/4967667715/jobs/8889831370#step:5:57

明明已经改了 https://github.com/Nemo2011/bilibili-api/blob/main/setup.py#L11

离谱，没发布过包，明明我在本地 `python setup.py sdist bdist_wheel` 出来的都是 v15.4.2

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/7f1273f7-c075-4951-bd6e-fa93dff7d56b)

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/actions/runs/4967706580/jobs/8889859326

**Comment by Drelf2018** [comment]
https://pypi.org/project/bilibili-api-python/15.4.2/

这不是更新好了吗

**Comment by z0z0r4** [comment]
> https://pypi.org/project/bilibili-api-python/15.4.2/
> 
> 这不是更新好了吗

昨晚脑子烧糊了...三阳开泰中 =. =
