### ISSUE TITLE
【提问】```user.get_user_info()```、```user.get_videos()```和```user.get_dynamics()```接口无法获取到有效信息，但是没有错误信息被抛出

### ISSUE THREAD

**Issue by WindowsSov8forUs** [Nemo2011/bilibili-api#289]
**Python 版本：** 3.11.2

**模块版本：** 15.4.2

**运行环境：** Windows

---

在bot内通过```user.get_user_info()```、```user.get_videos()```和```user.get_dynamics()```接口获取信息时经常没有获取到有效内容，但是也没有任何错误信息接收，单独运行类似代码时却能够正常获取信息

**部分代码**

该代码运行于一个**异步函数**中
```CREDENTIAL```是一个事先定义了的静态```Credential```对象，在我看来并不是问题的重点
```sub_list```是一个记录了指定用户的```uid```、```name```、```bvid```和```dynamic_id```的字典列表，用于记录获取到的信息并统合进一个json文件中
```
new_sub_list = []
    for sub_info in sub_list: #遍历群组关注列表
        uid = sub_info['uid']
        user = User(uid, CREDENTIAL) #创建用户对象
        #获取用户昵称
        try:
            user_info = await user.get_user_info()
            name = user_info['name']
        except Exception as exception:
            logger.info(f'本次用户信息获取失败，错误信息：{exception} 目标uid：{uid}')
            logger.error(exception)
            name = sub_info['name']
        #获取最新视频bvid
        try:
            videos = await user.get_videos()
            vlist = videos['list']['vlist']
            if len(vlist) != 0:
                bvid = vlist[0]['bvid']
            else: #如果没有视频（为什么？）
                bvid = None
        except Exception as exception:
            logger.info(f'本次视频获取失败，错误信息：{exception} 目标uid：{uid}')
            logger.error(exception)
            bvid = sub_info['bvid']
        #获取最新动态dynamic_id
        try:
            dynamics = await user.get_dynamics()
            if dynamics.get('cards'):
                dynamic_id = dynamics['cards'][0]['desc']['dynamic_id']
            else: #如果没有动态（为什么？）
                dynamic_id = None
        except Exception as exception:
            logger.info(f'本次动态获取失败，错误信息：{exception} 目标uid：{uid}')
            logger.error(exception)
            dynamic_id = sub_info['dynamicId']
        #记录关注信息
        new_sub_list.append({'uid': uid, 'name': name, 'bvid': bvid, 'dynamicId': dynamic_id})
        #判断并输出更新信息
        if bvid != None and (sub_info.get('bvid') == None or sub_info['bvid'] != bvid): #如果旧列表无bvid或与新bvid不同
            logger.info(f'[{group_id}]更新了UP主{name}的视频：{bvid}')
            if sub_info.get('bvid') == None: #如果旧列表无bvid
                await videoPost(bvid, group_id, 'new')
            else:
                bvid_list = []
                end_reach = False
                for video in vlist:
                    if video['bvid'] == sub_info['bvid']: #如果遍历到了之前更新的BV号
                        end_reach = True
                    if not end_reach:
                        bvid_list.append(video['bvid']) #记录这个BV号
                if end_reach: #如果是正常遍历到上次的记录而中断
                    for bvid_now in reversed(bvid_list): #逆向遍历记录到的BV号
                        await videoPost(bvid_now, group_id, 'new')
                else: #如果是因到达第一页限制而中断（证明之前记录的BV号有问题）
                    await videoPost(bvid, group_id, 'new')
        if dynamic_id != None and (sub_info.get('dynamicId') == None or sub_info['dynamicId'] != dynamic_id): #如果旧列表无dynamicId或与新id不同
            logger.info(f'[{group_id}]更新了UP主{name}的动态：{dynamic_id}')
            # TODO: 绘制并通过API发送动态图片
            pass
        
    return group_id, new_sub_list
```

**运行结果**

（运行结果被记录在logger中）
```
[2023-05-17 12:32:24,653] INFO in bilibili: [572486880]更新了UP主酸酸子Histidine的视频：BV1qo4y1t743
[2023-05-17 12:32:29,825] INFO in bot_main: 消息发送成功，返回码：200
[2023-05-17 12:32:29,827] INFO in bilibili: 本次动态获取失败，错误信息： 目标uid：11350969
[2023-05-17 12:32:29,827] ERROR in bilibili: 
[2023-05-17 12:32:29,827] INFO in bilibili: [161155357]更新了UP主WindowsSov8的视频：BV1uo4y1t7DQ
[2023-05-17 12:32:29,827] INFO in bilibili: 本次用户信息获取失败，错误信息： 目标uid：25199467
[2023-05-17 12:32:29,827] ERROR in bilibili: 
[2023-05-17 12:32:29,827] INFO in bilibili: 本次动态获取失败，错误信息： 目标uid：522443873
[2023-05-17 12:32:29,827] ERROR in bilibili: 
[2023-05-17 12:32:29,827] INFO in bilibili: 本次动态获取失败，错误信息： 目标uid：11350969
[2023-05-17 12:32:29,827] ERROR in bilibili: 
[2023-05-17 12:32:38,522] INFO in bot_main: 消息发送成功，返回码：200
[2023-05-17 12:32:38,523] INFO in bilibili: 本次视频获取失败，错误信息： 目标uid：25199467
[2023-05-17 12:32:38,523] ERROR in bilibili: 
[2023-05-17 12:32:38,526] INFO in bilibili: 本次用户信息获取失败，错误信息： 目标uid：494479664
[2023-05-17 12:32:38,526] ERROR in bilibili: 
[2023-05-17 12:32:38,526] INFO in bilibili: 本次用户信息获取失败，错误信息： 目标uid：11350969
[2023-05-17 12:32:38,526] ERROR in bilibili: 
```

从logger记录的输出信息来看，失败概率不低

**单独运行时的代码**

```
# -*- coding: utf-8 -*-
#!/usr/bin/python3
import os
import json
import asyncio
from bilibili_api import Credential, HEADERS
from bilibili_api.user import name2uid, User
from bilibili_api.video import Video, VideoDownloadURLDataDetecter

#获取当前文件所在的目录
current_dir = os.path.dirname(__file__)
CURRENT_DIR = current_dir[:-1]
#切换到当前文件的目录
os.chdir(current_dir)

#获取所需的Credential
CREDENTIAL = Credential(sessdata='', bili_jct='', buvid3='', dedeuserid='')

uid = input()
user = User(uid, CREDENTIAL)
user_info = asyncio.run(user.get_user_info())
name = user_info['name']
print(name)
videos = asyncio.run(user.get_videos())
dynamics = asyncio.run(user.get_dynamics())
print(videos['list']['vlist'][0]['bvid'])
print(dynamics['cards'][0]['desc']['dynamic_id'])
```

这段代码独立进行运行的时候是能够正常获取并输出信息的，且几乎没有出错过

**Comment by WindowsSov8forUs** [comment]
> 参考 #262 确认下运行代码的环境 是不是服务器没有更新库呢，这个问题在 [v15.4.1](https://github.com/Nemo2011/bilibili-api/releases/tag/15.4.1) 解决了

确信是更新了的，终端运行``pip3 show bilibili-api-python```显示的版本号是 v15.4.2

**Comment by z0z0r4** [comment]
> 参考 #262 确认下运行代码的环境 是不是服务器没有更新库呢，这个问题在 [v15.4.1](https://github.com/Nemo2011/bilibili-api/releases/tag/15.4.1) 解决了

有的接口没测试...我没环境，你测试过了吗？action炸了

**Comment by Drelf2018** [comment]
> > 参考 #262 确认下运行代码的环境 是不是服务器没有更新库呢，这个问题在 [v15.4.1](https://github.com/Nemo2011/bilibili-api/releases/tag/15.4.1) 解决了
> 
> 有的接口没测试...我没环境，你测试过了吗？action炸了

我本地测的都正常

**Comment by Drelf2018** [comment]
https://github.com/Nemo2011/bilibili-api/blob/efe0d04070448e313aa34cd384ba465b7c54f390/bilibili_api/utils/network_httpx.py#L147-L152

L152 报错的，我试找下 json 报错的原因，实在不行这里加 try except 得了

**Comment by z0z0r4** [comment]
我周日才有环境测试

**Comment by z0z0r4** [comment]
@WindowsSov8forUs 请问可以提供下具体的报错信息吗？而不仅仅是 
`[2023-05-17 12:32:29,827] ERROR in bilibili: `

从这里面看不出原因...

既然根据 @Drelf2018 所言是概率性报错，很可能是只是触发频率风控？
目测示例代码里的轮询完全不存在请求间的等待，被限制是很正常的

https://github.com/Nemo2011/bilibili-api#faq

> Q: 为什么会提示 412 Precondition Failed ？
> A: 你的请求速度太快了。造成请求速度过快的原因可能是你写了高并发的代码。
> 这种情况下，你的 IP 会暂时被封禁而无法使用，你可以设置代理绕过。

但为啥是 JSON 解析报错...勉强到家，正在测试中~

> https://github.com/Nemo2011/bilibili-api/blob/efe0d04070448e313aa34cd384ba465b7c54f390/bilibili_api/utils/network_httpx.py#L147-L152
> 
> L152 报错的，我试找下 json 报错的原因，实在不行这里加 try except 得了

**Comment by z0z0r4** [comment]
`user.User().get_user_info()` 多次轮询后出现 `-403 访问权限不足`
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/20b2f64e-e562-48e8-994c-aac7ef791d32)

**Comment by WindowsSov8forUs** [comment]
> @WindowsSov8forUs 请问可以提供下具体的报错信息吗？而不仅仅是 `[2023-05-17 12:32:29,827] ERROR in bilibili: `
> 
> 从这里面看不出原因...
> 
> 既然根据 @Drelf2018 所言是概率性报错，很可能是只是触发频率风控？ 目测示例代码里的轮询完全不存在请求间的等待，被限制是很正常的
> 
> https://github.com/Nemo2011/bilibili-api#faq
> 
> > Q: 为什么会提示 412 Precondition Failed ？
> > A: 你的请求速度太快了。造成请求速度过快的原因可能是你写了高并发的代码。
> > 这种情况下，你的 IP 会暂时被封禁而无法使用，你可以设置代理绕过。
> 
> 但为啥是 JSON 解析报错...勉强到家，正在测试中~
> 
> > https://github.com/Nemo2011/bilibili-api/blob/efe0d04070448e313aa34cd384ba465b7c54f390/bilibili_api/utils/network_httpx.py#L147-L152
> > 
> > L152 报错的，我试找下 json 报错的原因，实在不行这里加 try except 得了

我应当是在提问时说过的，没有**任何报错信息**收到
既没有**JSON解析错误**，也没有**接口返回错误代码**，更没有其他报错消息
除非存在这段代码无法输出的报错
```
        try:
            user_info = await user.get_user_info()
            name = user_info['name']
        except Exception as exception:
            logger.info(f'本次用户信息获取失败，错误信息：{exception} 目标uid：{uid}')
            logger.error(exception)
            name = sub_info['name']
```
其他三段也是类似的结构，都没有返回任何报错信息，只有**单纯的获取失败**
（或者可能是我的logger本身出现了问题，但是那样的话我就更不知道了）
我也想提供报错信息，但是我没法写出不存在的东西出来……总不能编一个吧

**Comment by Drelf2018** [comment]
没有报错可能是因为你用了异步任务框架之类的，会自动捕获报错，除非你自己try

**Comment by WindowsSov8forUs** [comment]
> 没有报错可能是因为你用了异步任务框架之类的，会自动捕获报错，除非你自己try

我一直都有在try的啊，你看我给出的代码，如果这都捕获不到的话那确实是超出我当前的代码水平了

**Comment by z0z0r4** [comment]
emmm，我都是在本项目 dev 下测试的，debug 捕捉不到...不清楚，错怪了!

本话题还是转往新 issue 处理比较好，因为涉及的接口不止上述这些，看起来加了很多鉴权

不需要特别高的速率话，可以 sleep 一会再请求

虽然我 2s 间隔都能 `-403`，估计无法满足你的需要了，建议等等看看这边扒拉

比如 https://api.bilibili.com/x/space/wbi/article?mid=558830935&pn=1 这些现在都这样了...

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/issues/290

**Comment by z0z0r4** [comment]
fixed
