### ISSUE TITLE
【需求】近期投稿API

### ISSUE THREAD

**Issue by SCUTJcfeng** [Nemo2011/bilibili-api#29]
某个栏目近期投稿API，有吗？

https://www.bilibili.com/v/knowledge/business
从网页抓到的例子是
https://s.search.bilibili.com/cate/search?main_ver=v3&search_type=video&view_type=hot_rank&copy_right=-1&new_web_tag=1&order=click&cate_id=207&page=1&pagesize=30&time_from=20220501&time_to=20220730

这里只能拿到过去大概3个月的数据，有没有办法可以拿到更久的？

**Comment by Nemo2011** [comment]
测过，获取时间最长三个月。

**Comment by SCUTJcfeng** [comment]
嗯嗯 暂时只能这样
