### ISSUE TITLE
【建议】爬取视频弹幕时对cookies应该不设置要求

### ISSUE THREAD

**Issue by jhzgjhzg** [Nemo2011/bilibili-api#298]
看了一下代码，发现爬取视频弹幕需要提供cookies，但是大部分视频不需要cookies即可获取弹幕，是否可以修改为若不提供credential也可以爬取弹幕。

**Comment by Drelf2018** [comment]
具体是哪个类/函数？

**Comment by jhzgjhzg** [comment]
> 具体是哪个类/函数？

Video 类里的get_danmakus以及相关函数，代码里所有和获取弹幕相关的操作都需要cookies，在Video中如果没有传入credential会报错

**Comment by jhzgjhzg** [comment]
> 我试了下不用 `Credential` 也能获取到弹幕啊
> 
> ```python
> from bilibili_api import sync, video
> 
> 
> async def main():
>     for dm in await video.Video(bvid="BV1CT41147Uz").get_danmakus():
>         print(dm)
> 
> 
> sync(main())
> 
> # 1684749995, 21.57, 可爱
> # 1684750004, 9.46, ？？？
> # 1684750030, 16.764, 可爱可爱！
> # 1684750038, 26.533, 可爱捏
> # 1684750040, 12.005, 好好好
> # ...
> ```

感谢，我找到问题了，我在继承的时候漏写了点东西。
