### ISSUE TITLE
b站某个视频评论区所有评论id主页的视频

### ISSUE THREAD

**Issue by pengchengKong** [Nemo2011/bilibili-api#304]
你好，我想获取b站某个视频评论区所有评论id主页的视频，然后递归不断获取这些视频评论id的视频，为了限制数量级，可以设置迭代次数，或者对视频的播放量有要求，比如播放量小于1000就不查找该视频的信息。最后返回所有视频的up主id和评论人的id
请问可以实现这个功能吗。

**Comment by Drelf2018** [comment]
这个你不是自己都有思路了吗，一步一步写呗

**Comment by Drelf2018** [comment]
你要是不知道具体用哪个函数可以再问

**Comment by z0z0r4** [comment]
这里只有基本封装，具体实现自己写
