### ISSUE TITLE
函数使用

### ISSUE THREAD

**Issue by pengchengKong** [Nemo2011/bilibili-api#305]
![image](https://github.com/Nemo2011/bilibili-api/assets/122085240/01d72496-a6b3-46e8-b516-3d6389878992)
我想获取某个人主页的所有视频信息，我翻了文档，应该是用这个函数，async def get_videos() ，(https://nemo2011.github.io/bilibili-api/#/modules/user?id=async-def-get_videos)，但是我不知道具体该怎么用，请问有详细的示例介绍吗，谢谢兄弟！

**Comment by z0z0r4** [comment]
```python
import asyncio
from bilibili_api import user

uid = 558830935

async def main():
    print(await user.User(uid=uid).get_videos())

if __name__ == "__main__":
     asyncio.run(main())

**Comment by pengchengKong** [comment]
谢谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月27日(周六) 下午4:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Nemo2011/bilibili-api] 函数使用 (Issue #305)




 import asyncio from bilibili_api import user uid = 558830935 async def main():     print(await user.User(uid=uid).get_videos()) if __name__ == "__main__":      asyncio.run(main())

**Comment by z0z0r4** [comment]
get_videos 可能在多次请求下会报错，下一个 release 会修复

**Comment by pengchengKong** [comment]
好滴，大佬好强🫡



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月27日(周六) 下午5:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Nemo2011/bilibili-api] 函数使用 (Issue #305)




 
get_videos 可能在多次请求下会报错，下一个 release 会修复

**Comment by pengchengKong** [comment]
孔鹏程
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nemo2011/bilibili-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月27日(星期六) 下午5:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nemo2011/bilibili-api] 函数使用 (Issue #305)





 
get_videos 可能在多次请求下会报错，下一个 release 会修复
