### ISSUE TITLE
[建议] 统一使用 `httpx` 而不是兼用 `aiohttp`

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#306]
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/387176a4-0eab-4607-af7b-c9f11499961e)

v10 就写着迁移了，但一些用到 ws 的地方还是 `httpx` 

也许 `httpx` 也支持？对 ws 协议不了解，挖个坑

**Comment by Drelf2018** [comment]
没找到 httpx 怎么连 ws 的，[CSDN](https://blog.csdn.net/haloged/article/details/130452294) 找到一个说可以的我试了是报错的。

**Comment by z0z0r4** [comment]
> 没找到 httpx 怎么连 ws 的，[CSDN](https://blog.csdn.net/haloged/article/details/130452294) 找到一个说可以的我试了是报错的。

难办，只能放弃嘛…
主要是 import 一大堆库说实话好耗时，明显感觉导入很慢

**Comment by z0z0r4** [comment]
give up.jpg
