### ISSUE TITLE
这个包可以在脚手架里用吗，我在vue-cli开发模式下启动直接提示跨域

### ISSUE THREAD

**Issue by Tomato-orz** [Nemo2011/bilibili-api#31]
**js：** vue-cli 3** 

**模块版本：*文档上的第一个例子*

**运行环境：*vscode* 

---

在此处写正文

**Comment by Nemo2011** [comment]
试一下设置 `Access-Control-Allow-Origin` 头。

**Comment by Nemo2011** [comment]
要不把 api 请求代码先放在后端，跨域问题暂时还没有解决方法。
