### ISSUE TITLE
动态显示不全

### ISSUE THREAD

**Issue by pengchengKong** [Nemo2011/bilibili-api#312]
**Python 版本：** 3.10.9

**模块版本：** x.y.z

**运行环境：** Windows

---
您好，就是这段代码，运行后显示的动态不全，只能显示到5月23日的，我想要获得全部动态，然后找出里面投稿视频的aid，麻烦大佬
from bilibili_api import user, sync

u = user.User(1655988782)

print(sync(u.get_dynamics()))

**Comment by z0z0r4** [comment]
tmd你是不会在旧issue接着发回复吗

**Comment by z0z0r4** [comment]
别再灌水了，这不是贴吧

**Comment by pengchengKong** [comment]
不好意思大佬，我刚刚qq加你了
