### ISSUE TITLE
【提问】抓取弹幕提示：bilibili_api.exceptions.ResponseException.ResponseException: 解析响应数据错误

### ISSUE THREAD

**Issue by hfjiao** [Nemo2011/bilibili-api#314]
**Python 版本：** 3.10.9

**模块版本：** github同步代码

**运行环境：** Linux / MacOS

---
之前用本项目抓取b站弹幕十分正常，2023/5/29突然开始提示ResponseException 异常。运行环境没有变化

**Comment by Drelf2018** [comment]
可以给具体代码吗

**Comment by AzureIvory** [comment]
`from bilibili_api import sync, Credential, video

v_self = video.Video(aid=2)

q=sync(v_self.get_danmakus(page_index=0))

print(q)
`
我也是出现这种情况，我以为是我自己的代码有问题，于是就随便写了一个测试发现还是会返回bilibili_api.exceptions.ResponseException.ResponseException: 解析响应数据错误
![image](https://github.com/Nemo2011/bilibili-api/assets/39545867/71db9a00-dc8e-4653-9e43-2a5fcd552005)

**Comment by jhzgjhzg** [comment]
我今天也是遇到这个错误，然后我自己写了一下爬取弹幕，没问题，看起来应该是新版本proto解析的问题（15.4.3没有这个错误）

**Comment by Drelf2018** [comment]
可以先把 L796-L797 注释掉，可以正常获取弹幕。我也不懂这块，还是得等懂得来。

https://github.com/Nemo2011/bilibili-api/blob/67ab806abb00864b333047f30ed74a4f407b9185/bilibili_api/video.py#L790-L797

**Comment by jhzgjhzg** [comment]
> 奇怪了，15.4.4也没有更新这块相关的代码呀，怎么就报错呢了

回退到15.4.3也报错，但是直接用bilibili-api-collect的proto解析爬弹幕是没有报错的，原理我也不懂。。。

**Comment by hfjiao** [comment]
> 可以先把 L796-L797 注释掉，可以正常获取弹幕。我也不懂这块，还是得等懂得来。
> 
> https://github.com/Nemo2011/bilibili-api/blob/67ab806abb00864b333047f30ed74a4f407b9185/bilibili_api/video.py#L790-L797

刚看到，这么操作确实可行。多谢～

**Comment by z0z0r4** [comment]
感觉待细究
