### ISSUE TITLE
关于文档的建议

### ISSUE THREAD

**Issue by zerowuxian** [Nemo2011/bilibili-api#319]
文档中对每个函数的return都是”对应api的调用结果“，无法立即判断函数的return包含什么内容。如果能确切的写出每个函数的return，解释调用api返回的dict，会对二次开发人员有很好的帮助。

**Comment by z0z0r4** [comment]
解释接口返回值可以说是巨大的工程量，同时 [BAC](https://github.com/SocialSisterYi/bilibili-API-collect) 已经收录了绝大多数接口，在给函数注释加上接口一一对应的 URL 之前，似乎可以直接在仓库内勉强搜索下看返回值的含义
