### ISSUE TITLE
[漏洞] 异步函数中无法再使用 sync()

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#322]
在异步函数中调用 send_sms 发现的...

```python
import asyncio

async def main():
    sync(get_nav())

if __name__ == "__main__":
    asyncio.run(main())
```

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/ca8ad835-7040-42f4-bc5a-fdc8eba51139)

**Comment by Drelf2018** [comment]
可以学习下事件循环相关知识
