### ISSUE TITLE
【提问】异步小白提问：LiveDanmaku如何运行disconnect

### ISSUE THREAD

**Issue by jhzgjhzg** [Nemo2011/bilibili-api#324]
**Python 版本：** 3.9.16

**模块版本：** 15.4.4

**运行环境：** MacOS

---
LiveDanmaku在运行connect以后会进入无限循环，那要如何执行disconnect呢

**Comment by z0z0r4** [comment]
好问题，你可能需要多线程（？

不了解，@Drelf2018  ;]

**Comment by jhzgjhzg** [comment]
> 好问题，你可能需要多线程（？
> 
> 不了解，@Drelf2018 ;]

还有就是问一句，为什么“DANMU_MSG”返回的数据是一个很奇怪的东西，info关键字里是列表而不是字典

**Comment by z0z0r4** [comment]
> > 好问题，你可能需要多线程（？
> > 不了解，@Drelf2018 ;]
> 
> 还有就是问一句，为什么“DANMU_MSG”返回的数据是一个很奇怪的东西，info关键字里是列表而不是字典

不是我写的不了解，但似乎是返回的原数据，大概没做啥处理（？
https://github.com/Nemo2011/bilibili-api/blob/7fa46a5f8bf51d9d5cd21c71bff2ca37c56d508c/bilibili_api/live.py#L992C49-L1043

**Comment by Drelf2018** [comment]
以下是一份示例代码，你需要在异步函数中使用 `await room.disconnect()` 关闭连接。

```python
from bilibili_api import live, sync


room = live.LiveDanmaku(...)

@room.on("DANMU_MSG")
async def danmu(evt: dict):
    msg: str = evt["data"]["info"][1]
    if msg == "close":
        await room.disconnect()

sync(room.connect())
```

例如上面的代码是在接收到弹幕内容为 `close` 时断开连接。

如果你想通过别的方式断开连接，请说明你的需求，我才能更好的解答。

**Comment by Drelf2018** [comment]
> > 好问题，你可能需要多线程（？
> > 不了解，@Drelf2018 ;]
> 
> 还有就是问一句，为什么“DANMU_MSG”返回的数据是一个很奇怪的东西，info关键字里是列表而不是字典

这个你就要问b站了，可以推测的原因是节省带宽，你想想每一条弹幕都要发给多少人啊，每个字段加关键字太浪费了。

**Comment by jhzgjhzg** [comment]
> 以下是一份示例代码，你需要在异步函数中使用 `await room.disconnect()` 关闭连接。
> 
> ```python
> from bilibili_api import live, sync
> 
> 
> room = live.LiveDanmaku(...)
> 
> @room.on("DANMU_MSG")
> async def danmu(evt: dict):
>     msg: str = evt["data"]["info"][1]
>     if msg == "close":
>         await room.disconnect()
> 
> sync(room.connect())
> ```
> 
> 例如上面的代码是在接收到弹幕内容为 `close` 时断开连接。
> 
> 如果你想通过别的方式断开连接，请说明你的需求，我才能更好的解答。

可以在监控到主播结束推流的时候断开连接吗

**Comment by z0z0r4** [comment]
> 或者简单的说，如何监控直播未开始

没有接口显示直播状态吗…我记得 user.get_info 似乎有

**Comment by jhzgjhzg** [comment]
> > 或者简单的说，如何监控直播未开始
> 
> 轮询下？没有接口显示直播状态吗…我记得 user.get_info 似乎有

除了轮询，在直播间中能做到吗

**Comment by Drelf2018** [comment]
你是想要主播开播就开始监听，下播就关闭监听吗？没必要其实，一直监听就行了。

**Comment by z0z0r4** [comment]
姑且文档还是有东西的

https://github.com/Nemo2011/bilibili-api/blob/7fa46a5f8bf51d9d5cd21c71bff2ca37c56d508c/docs/modules/live.md?plain=1#L330-L351

**Comment by jhzgjhzg** [comment]
> 姑且文档还是有东西的
> 
> https://github.com/Nemo2011/bilibili-api/blob/7fa46a5f8bf51d9d5cd21c71bff2ca37c56d508c/docs/modules/live.md?plain=1#L330-L351

哈哈，我还以为直播准备中意思是推流准备
