### ISSUE TITLE
[建议] 注释换行

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#329]
话说这些注释是不是应该换行的，vscode根本成一坨了
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/d3c828e1-e671-4861-a87a-cf0c2f97faec)

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/c95fb142-91f7-4379-862a-da1690e0afa7)

**Comment by z0z0r4** [comment]
> 注释而已，随便改

量巨tm大

然后我也不知道哪里找vscode咋预览注释的，有的没换行自己会换上一两行，大雾

**Comment by jhzgjhzg** [comment]
这个应该是vsc的问题，我在pycharm上看时有换行的
