### ISSUE TITLE
【提问】无法评论动态?

### ISSUE THREAD

**Issue by wcw1qqw** [Nemo2011/bilibili-api#33]
**Python 版本：** 3.8.0** 

**模块版本：** PYTHON

**运行环境：** Windows

---

```
a = requests.post('https://api.bilibili.com/x/v2/reply/add',headers = headers,cookies = cookies,data = {"oid": 689276739895951381,"type":17,"message": "Hi","plat": 1,"root":"","parent":"","csrf" : cookies['bili_jct'],"csrf_token":cookies['bili_jct']})
print(a.text)
```

`{"code":-404,"message":"啥都木有","ttl":1,"data":null}`

求教 感谢大佬

**Comment by Nemo2011** [comment]
```
a = requests.post('https://api.bilibili.com/x/v2/reply/add',headers = headers,cookies = cookies,data = {"oid": 689276739895951381,"type":17,"message": "Hi","plat": 1,"csrf" : cookies['bili_jct'],"csrf_token":cookies['bili_jct']})
print(a.text)
```
试一下

**Comment by wcw1qqw** [comment]
> ```
> a = requests.post('https://api.bilibili.com/x/v2/reply/add',headers = headers,cookies = cookies,data = {"oid": 689276739895951381,"type":17,"message": "Hi","plat": 1,"csrf" : cookies['bili_jct'],"csrf_token":cookies['bili_jct']})
> print(a.text)
> ```
> 
> 试一下

貌似还是不行...
