### ISSUE TITLE
【需求】假如获取评论回复和互动的功能

### ISSUE THREAD

**Issue by Liusy12810** [Nemo2011/bilibili-api#334]
简单看了一下这个api，发现了一个小问题：
没法获取自己收到的回复和更新回复列表
希望能够加入这一功能
信息！
（谢谢你，笔芯，python大佬，666）

**Comment by Drelf2018** [comment]
在 `bilibili_api.session` 里有这个功能

```python
from bilibili_api import Credential, session, sync

credential=Credential(sessdata=..., bili_jct=...)


async def main():
    data = await session.get_replies(credential=credential)
    for item in data["items"]:
        print(item["user"]["nickname"], item["item"]["source_content"])


sync(main())
```

**Comment by z0z0r4** [comment]
> 在 `bilibili_api.session` 里有这个功能
> 
> ```python
> from bilibili_api import Credential, session, sync
> 
> credential=Credential(sessdata=..., bili_jct=...)
> 
> 
> async def main():
>     data = await session.get_replies(credential=credential)
>     for item in data["items"]:
>         print(item["user"]["nickname"], item["item"]["source_content"])
> 
> 
> sync(main())
> ```

感觉你每次写demo可以塞进example =-=

实在懒开个 discussion 集中下也行

**Comment by Liusy12810** [comment]
好的，谢谢！

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年6月11日 22:27
收件人: ***@***.***>
抄送: Three ***@***.***>; ***@***.***>
主题: Re: [Nemo2011/bilibili-api] 【需求】假如获取评论回复和互动的功能 (Issue #334)


在 bilibili_api.session 里有这个功能

from bilibili_api import Credential, session, sync



credential=Credential(sessdata=..., bili_jct=...)





async def main():

    data = await session.get_replies(credential=credential)

    for item in data["items"]:

        print(item["user"]["nickname"], item["item"]["source_content"])





sync(main())

感觉你每次写demo可以塞进example =-=

实在懒开个 discussion 集中下也行

―
