### ISSUE TITLE
【漏洞】移除 credential.py 中对 Crypto 的依赖

### ISSUE THREAD

**Issue by Drelf2018** [Nemo2011/bilibili-api#335]
这个库我甚至没有，整个包直接运行不了了，然后也没写 requirements.txt

https://github.com/Nemo2011/bilibili-api/blob/7fa46a5f8bf51d9d5cd21c71bff2ca37c56d508c/CHANGELOGS/v12.md?plain=1#L70

**Comment by z0z0r4** [comment]
emmm，同意
