### ISSUE TITLE
【需求】直接获取用户充电列表

### ISSUE THREAD

**Issue by jhzgjhzg** [Nemo2011/bilibili-api#339]
在User类里添加一个获取用户充电列表的函数，API为https://api.bilibili.com/x/ugcpay-rank/elec/month/up

**Comment by z0z0r4** [comment]
这周末

**Comment by z0z0r4** [comment]
> 在User类里添加一个获取用户充电列表的函数，API为https://api.bilibili.com/x/ugcpay-rank/elec/month/up

此接口除了 `up_mid` 外还有什么参数吗？只能获取十五个充电用户？

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/commit/689c7a7c039c5bb2475d99c4a9f17c5fa9eca804 finished
