### ISSUE TITLE
【漏洞】user.get_user_info() 返回403访问权限不足

### ISSUE THREAD

**Issue by LXRee** [Nemo2011/bilibili-api#340]
**Python 版本：** 3.x.y

**模块版本：** x.y.z 

**运行环境：** Windows

**模块路径：** `bilibili_api.user.User.get_user_info(`

**解释器：** cpython / pypi / jython

**报错信息：**

```
![image](https://github.com/Nemo2011/bilibili-api/assets/51704570/e8d02e23-3690-4989-9ab5-9ea00fcf2a8d)

```

**报错代码：**

```
u = user.User(mid,credential = credential)
json_data  = await u.get_user_info()
```

---

我怀疑应该是请求个人信息的接口的参数需求变严格了，因为我一层层看了作者的代码，和以前我自己请求的一样，只有mid参数，但是现在发现必须把所有参数都加上才能请求，而且每个人的w_rid这个参数对应的值还都不一样，所以这个接口作者可能需要更新下了

**Comment by Drelf2018** [comment]
是不是没更新库？
```python
pip install bilibili-api-python --upgrade
```
