### ISSUE TITLE
【漏洞】Video.get_tags返回值类型错误

### ISSUE THREAD

**Issue by jhzgjhzg** [Nemo2011/bilibili-api#341]
**Python 版本：** 3.9.16

**模块版本：** 15.4.4 

**运行环境：** MacOS

**模块路径：** `bilibili_api.Video.py`

**解释器：** cpython / pypi / jython

**报错信息：** 

```
无
```

**报错代码：**

```
无
```

---
Video.get_tags的返回值类型应该是list[dict]， 不是dict，小问题，只是看着难受

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/commit/090c725996e011439b432ab777f6f8aec0cd1ce3 finished
