### ISSUE TITLE
【提问】{能否提供一个下载字幕的demo示例代码呢}

### ISSUE THREAD

**Issue by wwdok** [Nemo2011/bilibili-api#344]
**Python 版本：** 3.8.10

**模块版本：** 15.4.4

**运行环境：** Windows

---

这是我想用来下载字幕的脚本：
```
import asyncio
from bilibili_api import video
import requests, json
import pprint
pp = pprint.PrettyPrinter(indent=4)

he = {
    "Host": 'api.bilibili.com',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0',
    'Accept': '*/*',
    'Accept-Language': 'zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2',
    'Accept-Encoding': 'gzip,deflate',
    'Connection': 'keep-alive',
    }

def getVideoList(bv):
    '''
    传入BV号，返回该BV号的视频列表
    '''
    url = 'https://api.bilibili.com/x/player/pagelist?bvid=%s' % bv 
    response  = requests.get(url,headers=he)        
    videoList = json.loads(response.text)['data']     
    print ('请求URL:', url)
    print ('视频目录获取成功！共%sP。\n'%len(videoList)) 
    return videoList

async def main():
    # 实例化 Video 类
    bvid = "BV1pK4y1u79P" 
    v = video.Video(bvid=bvid)
    # 获取信息
    # info = await v.get_info()
    # 打印信息
    # pp.pprint(info)

    videoList = getVideoList(bvid)
    for i in videoList:
        cid = i['cid']
        print(f"==>> cid: {cid}")
        caption = await v.get_subtitle(cid)
        print(f"==>> caption: {caption}")

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```
但读取到的字幕是空的，但这个视频明明是有字幕的

**Comment by jhzgjhzg** [comment]
下载字幕需要cookies，也就是Credential，应该是必须提供的，至少我试验的时候是这样的，你也可以多试几个视频看看

**Comment by z0z0r4** [comment]
你指的是 `中文（自动生成）`吧，这个不在当前的接口范围内，当前能get到的只有`中文（简体中文）`这样非 ai 生成的字幕...
等我抓抓看 ai 字幕的接口

**Comment by wwdok** [comment]
嗯嗯，确实用了Credential就返回不为空了，如果本代码仓库能提供个自动获取cookie的函数来初始化Credential类实例就好了。
```
from bilibili_api import video, Credential
    # 实例化 Credential 类，获取方法见：https://nemo2011.github.io/bilibili-api/#/get-credential
    SESSDATA = "ea144c7b%2C170067530**************"
    BILI_JCT = "d7d22b537c11432***************************"
    BUVID3 = "9FB1787A-F1E8-23B3-91B3-8********************************"
    DEDEUSERID = "101********"
    credential = Credential(sessdata=SESSDATA, bili_jct=BILI_JCT, buvid3=BUVID3, dedeuserid=DEDEUSERID)
    # 实例化 Video 类
    bvid = "BV1pK4y1u79P"
    v = video.Video(bvid=bvid, credential=credential)
```

**Comment by z0z0r4** [comment]
> 嗯嗯，确实用了Credential就返回不为空了，如果本代码仓库能提供个自动获取cookie的函数来初始化Credential类实例就好了。
> 
> ```
> from bilibili_api import video, Credential
>     # 实例化 Credential 类，获取方法见：https://nemo2011.github.io/bilibili-api/#/get-credential
>     SESSDATA = "ea144c7b%2C170067530**************"
>     BILI_JCT = "d7d22b537c11432***************************"
>     BUVID3 = "9FB1787A-F1E8-23B3-91B3-8********************************"
>     DEDEUSERID = "101********"
>     credential = Credential(sessdata=SESSDATA, bili_jct=BILI_JCT, buvid3=BUVID3, dedeuserid=DEDEUSERID)
>     # 实例化 Video 类
>     bvid = "BV1pK4y1u79P"
>     v = video.Video(bvid=bvid, credential=credential)
> ```

你指的是从浏览器？不太可能，不过有扫码登录等等

**Comment by wwdok** [comment]
@z0z0r4 我想了一下，咱们这个python api要自动获取cookie好像有点难，不像浏览器插件那样容易获取cookie，我浅尝了一下https://github.com/borisbabic/browser_cookie3, 不过依然没有获取完整的cookie

**Comment by z0z0r4** [comment]
> @z0z0r4 我想了一下，咱们这个python api要自动获取cookie好像有点难，不像浏览器插件那样容易获取cookie，我浅尝了一下https://github.com/borisbabic/browser_cookie3, 不过依然没有获取完整的cookie

cookie 自己手动获取...实在不行就在跑脚本前扫码登录下 `from bilibili_api import login` 获取登录凭据

**Comment by wwdok** [comment]
@z0z0r4 嗯，我看了一下，这个可以作为备选方案
