### ISSUE TITLE
【提问】{目前我们有api能直接下载视频的音频吗}

### ISSUE THREAD

**Issue by wwdok** [Nemo2011/bilibili-api#349]
我看有个api是
```
        auid = ""
        a = audio.Audio(auid = auid, credential=credential)
        audio_url = await a.get_download_url()
```
但它要传入一个auid，我不知道怎么获取，感觉是从一个音频url里解析出来的，但如果我的url是一个视频呢，我们能直接下载这个视频的音频吗，还是说需要先下载视频再从视频里提取出音频 ？

**Comment by jhzgjhzg** [comment]
有一个想法，就是下载视频，然后调用ffmpeg分离音频

**Comment by z0z0r4** [comment]
audio 类是处理B站音频区的，不是视频的音频

先创建 video 实例，调用 `video.Video(bvid=bvid).get_download_url()`获取视频的下载信息，里面一般是音视频分离的，可以单独下载音频 
如果需要解析调用 `video.VideoDownloadURLDataDetecter` https://github.com/Nemo2011/bilibili-api/blob/df95d37987787f9aacd0643ee4645b763508043d/bilibili_api/video.py#L2020

**Comment by z0z0r4** [comment]
参考 https://nemo2011.github.io/bilibili-api/#/examples/video?id=%e7%a4%ba%e4%be%8b%ef%bc%9a%e4%b8%8b%e8%bd%bd%e8%a7%86%e9%a2%91 里面下载的 `audio_temp.m4s` 为你要的音频，不混流就行了

**Comment by wwdok** [comment]
好的，多谢！
