### ISSUE TITLE
【漏洞】Credential.refresh

### ISSUE THREAD

**Issue by jhzgjhzg** [Nemo2011/bilibili-api#351]
**Python 版本：** 3.9.16

**模块版本：** 15.5.0 

**运行环境：** MacOS

**模块路径：** `bilibili_api.Credential.py`

**解释器：** cpython / pypi / jython

**报错信息：**

```
AttributeError: 'coroutine' object has no attribute 'sessdata'
sys:1: RuntimeWarning: coroutine 'refresh_cookies' was never awaited
```

**报错代码：**

```
    def refresh(self) -> None:
        """
        刷新 cookies
        """
        new_cred: Credential = refresh_cookies(self)
        self.sessdata = new_cred.sessdata
        self.bili_jct = new_cred.bili_jct
        self.dedeuserid = new_cred.dedeuserid
        self.ac_time_value = new_cred.ac_time_value
```

---

refresh里用到了refresh_cookies函数，这个函数是异步的，然而在refresh里没有await，这会导致new_cred为None

**Comment by Drelf2018** [comment]
有为本项目 pull request 的想法吗？

可以参考 [CONTRIBUTING](https://github.com/nemo2011/bilibili-api/blob/main/.github/CONTRIBUTING.md) 学习怎么修改并提交代码解决问题呢！

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/commit/8cd72c7ca9256ede8e850450e22819ecb212b107

**Comment by Drelf2018** [comment]
> [8cd72c7](https://github.com/Nemo2011/bilibili-api/commit/8cd72c7ca9256ede8e850450e22819ecb212b107)

https://github.com/Nemo2011/bilibili-api/blob/8cd72c7ca9256ede8e850450e22819ecb212b107/bilibili_api/credential.py#L45-L49

只加 await 不加 async 是吧

**Comment by jhzgjhzg** [comment]
> 有为本项目 pull request 的想法吗？
> 
> 可以参考 [CONTRIBUTING](https://github.com/nemo2011/bilibili-api/blob/main/.github/CONTRIBUTING.md) 学习怎么修改并提交代码解决问题呢！

主要是懒（

**Comment by z0z0r4** [comment]
web dev没话说，你修吧（
