### ISSUE TITLE
请问怎么获取一个up主的所有视频id

### ISSUE THREAD

**Issue by thesby** [Nemo2011/bilibili-api#354]
**Python 版本：** 3.7.10

**运行环境：** Windows

---
我想根据up主 id 获取其所有视频的 id，请问怎么操作

**Comment by Drelf2018** [comment]
https://nemo2011.github.io/bilibili-api/#/modules/user?id=async-def-get_videos

**Comment by z0z0r4** [comment]
感觉这里就该接个 GPT 喂个文档进去自动🤮
