### ISSUE TITLE
【漏洞】直播间发送弹幕检验失败的错误

### ISSUE THREAD

**Issue by Drelf2018** [Nemo2011/bilibili-api#355]
在 https://github.com/Nemo2011/bilibili-api/issues/240#issuecomment-1600570164 提到：

> sessdata和bili_jct我都是拿chrome最新的，为啥自动发送弹幕会返回这个 {'code': -111, 'message': 'csrf 校验失败', 'ttl': 1}

经测试，这个问题确实存在。

### 错误分析

破案了，原本版本 76a9821f772bbb5e7af0d4b505ed0bee3870f812 中的代码：

https://github.com/Nemo2011/bilibili-api/blob/76a9821f772bbb5e7af0d4b505ed0bee3870f812/bilibili_api/utils/network_httpx.py#L121-L126

在版本 7de8a87ca4e9c071d11644f0078075ad8afa8bd7 被替换成了：

https://github.com/Nemo2011/bilibili-api/blob/7de8a87ca4e9c071d11644f0078075ad8afa8bd7/bilibili_api/utils/network_httpx.py#L124-L130

看上去没问题，因为 `HEADERS` 的定义与原来的相同

https://github.com/Nemo2011/bilibili-api/blob/7de8a87ca4e9c071d11644f0078075ad8afa8bd7/bilibili_api/utils/network_httpx.py#L29-L31

实际上 python 的字典是引用赋值的，这样会导致该 `HEADERS` 复用，也就是说后续代码：

https://github.com/Nemo2011/bilibili-api/blob/7de8a87ca4e9c071d11644f0078075ad8afa8bd7/bilibili_api/utils/network_httpx.py#L170-L171

对这个 `config["headers"]` 的修改，会修改“常量” `HEADERS` 。

### 尝试修复

对于下面的测试代码：

```python
from bilibili_api import Credential, live, sync, Danmaku
import time

credential=Credential(sessdata="", bili_jct="")

# 自己直播间号
ROOMID = 14703541

# 监听直播间弹幕
monitor = live.LiveDanmaku(ROOMID, credential=credential)
# 用来发送弹幕
sender = live.LiveRoom(ROOMID, credential=credential)

# 自己的UID 可以手动填写也可以根据直播间号获取
UID = sync(sender.get_room_info())["room_info"]["uid"]

sync(sender.send_danmaku(Danmaku("第一次调用")))

@monitor.on('DANMU_MSG')
async def on_danmaku(event):
    msg = event["data"]["info"][1]
    print(msg)
    time.sleep(2)
    await sender.send_danmaku(Danmaku("之后调用"))


# 启动直播间连接
sync(monitor.connect())
```

我们预想的结果是：运行脚本后立即发送弹幕”第一次调用“，之后在直播间收到这条弹幕后的两秒回复”之后调用“。

实际上仅有”第一次调用“弹幕发送成功，这并不是send_danmaku不能放异步的原因。

通过打印这两次请求的 `config` 可以发现，第二次请求的 `headers` 多了个 `'Content-Type': 'application/json'`

![屏幕截图 2023-06-23 015911](https://github.com/Nemo2011/bilibili-api/assets/41439182/8465f6d2-5e2e-45d4-8f21-8adf6e832e63)

这就是验证失败的罪魁祸首，通过修改代码：

https://github.com/Nemo2011/bilibili-api/blob/76a9821f772bbb5e7af0d4b505ed0bee3870f812/bilibili_api/utils/network_httpx.py#L177-L178

```python
if True:  # try:
    if url == "https://api.live.bilibili.com/msg/send":
        if "Content-Type" in config["headers"]:
            config["headers"].pop("Content-Type")
    resp = await session.request(**config)
```

之后就可以正常发出上述两条弹幕了。

### 根本原因

在发出第一条弹幕后，`monitor` 同时监听到这条弹幕，并对他进行了处理：

https://github.com/Nemo2011/bilibili-api/blob/76a9821f772bbb5e7af0d4b505ed0bee3870f812/bilibili_api/live.py#L1072-L1079

这里请求时使用了 `json_body=True` ，也就造成了前文提到的对 `HEADERS` 的修改。
因此在发送第二条弹幕的时候就使用了错误的请求头。

### 解决方案

```diff
# 现有常量为啥不用...
- headers = HEADERS
+ headers = HEADERS.copy()
```

每次使用时复制一份，修改时就不会影响 `HEADERS`

### 总结

代码能跑就别乱改🤣

**Comment by Drelf2018** [comment]
值得一提的是，这个漏洞不止影响发送弹幕这一个接口，应尽快上线修复方案。

**Comment by z0z0r4** [comment]
难蚌，我去全局搜下调用了 `HEADERS` 的代码

**Comment by z0z0r4** [comment]
> 值得一提的是，这个漏洞不止影响发送弹幕这一个接口，应尽快上线修复方案。

还有哪些...？没找到

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/commit/3dd4c6de5538a1c2c15e0a9c610f79d7ccffc16b

**Comment by Drelf2018** [comment]
> > 值得一提的是，这个漏洞不止影响发送弹幕这一个接口，应尽快上线修复方案。
> 
> 还有哪些...？没找到

我的意思是，当你运行脚本时，只要用了一次会修改headers的函数，之后再用别的函数都会受到影响。

**Comment by z0z0r4** [comment]
那没事了
