### ISSUE TITLE
【提问】获取b站字幕信息

### ISSUE THREAD

**Issue by zhao-cs-debug** [Nemo2011/bilibili-api#357]
有些视频获取不到字幕信息，我分析可能是部分视频没有配置字幕。看能否获取AI字幕。

**Comment by z0z0r4** [comment]
请等待release更新

**Comment by zhao-cs-debug** [comment]
传入过程中报错了。
----> 9 credential = Credential(sessdata=SESSDATA, 
     10                         bili_jct=Bili_jct, 
     11                         buvid3=Buvid3, 
     12                         dedeuserid=Dedeuserid, 
     13                         ac_time_value=Ac_time_value)

TypeError: Credential.__init__() got an unexpected keyword argument 'dedeuserid'

**Comment by z0z0r4** [comment]
```
Credential(dedeuserid=1)
<bilibili_api.utils.Credential.Credential object at 0x00B74A90>
```

好像其实没啥问题？

**Comment by zhao-cs-debug** [comment]
Dedeuserid不用传参是吗？可是对于获取b站字幕信息，我还没有头绪。
我是从langchain过来的，源代码是这样。
import openai
import os
openai.api_key = "OPENAI_KEY"
from langchain.document_loaders import BiliBiliLoader
import nest_asyncio
nest_asyncio.apply()

loader = BiliBiliLoader(
    ["https://www.bilibili.com/video/BV1mh4y1X75Y/?spm_id_from=333.337.search-card.all.click"]
)
loader.load()

报了这个错误：UserWarning: 
                No subtitles found for video: https://www.bilibili.com/video/BV1mh4y1X75Y/?spm_id_from=333.337.search-card.all.click.
                Return Empty transcript.
获取不到弹幕信息

**Comment by z0z0r4** [comment]
Dedeuserid 不传也可以

**Comment by z0z0r4** [comment]
> Dedeuserid不用传参是吗？可是对于获取b站字幕信息，我还没有头绪。 我是从langchain过来的，源代码是这样。 import openai import os openai.api_key = "OPENAI_KEY" from langchain.document_loaders import BiliBiliLoader import nest_asyncio nest_asyncio.apply()
> loader = BiliBiliLoader( ["https://www.bilibili.com/video/BV1mh4y1X75Y/?spm_id_from=333.337.search-card.all.click"] ) loader.load()
> 
> 报了这个错误：UserWarning: No subtitles found for video: https://www.bilibili.com/video/BV1mh4y1X75Y/?spm_id_from=333.337.search-card.all.click. Return Empty transcript. 获取不到弹幕信息

没啥帮助，看不出问题，只要正确传入 sessdata 和 bili_jct 应该就能拿字幕

**Comment by zhao-cs-debug** [comment]
或许需要您测试看看。传入该视频链接或其他更多视频链接后，看能否获取字幕，如果能获取成功，可能是我的问题。

**Comment by z0z0r4** [comment]
获取弹幕的接口我试过是没问题的...必须要登录，以及你更新了吗？我记得前阵子修了ai字幕的

**Comment by z0z0r4** [comment]
以及你用的哪个函数？

**Comment by zhao-cs-debug** [comment]
langchain库里调用方法是这样的。用的from bilibili_api import sync, video

import json
import re
import warnings
from typing import List, Tuple

import requests

from langchain.docstore.document import Document
from langchain.document_loaders.base import BaseLoader


class BiliBiliLoader(BaseLoader):
    """Loader that loads bilibili transcripts."""

    def __init__(self, video_urls: List[str]):
        """Initialize with bilibili url."""
        self.video_urls = video_urls

    def load(self) -> List[Document]:
        """Load from bilibili url."""
        results = []
        for url in self.video_urls:
            transcript, video_info = self._get_bilibili_subs_and_info(url)
            doc = Document(page_content=transcript, metadata=video_info)
            results.append(doc)

        return results

    def _get_bilibili_subs_and_info(self, url: str) -> Tuple[str, dict]:
        try:
            from bilibili_api import sync, video
        except ImportError:
            raise ValueError(
                "requests package not found, please install it with "
                "`pip install bilibili-api-python`"
            )

        bvid = re.search(r"BV\w+", url)
        if bvid is not None:
            v = video.Video(bvid=bvid.group())
        else:
            aid = re.search(r"av[0-9]+", url)
            if aid is not None:
                try:
                    v = video.Video(aid=int(aid.group()[2:]))
                except AttributeError:
                    raise ValueError(f"{url} is not bilibili url.")
            else:
                raise ValueError(f"{url} is not bilibili url.")

        video_info = sync(v.get_info())
        print(video_info)
        video_info.update({"url": url})
        print(video_info)
        # Get subtitle url
        subtitle = video_info.pop("subtitle")
        print(subtitle)
        sub_list = subtitle["list"]
        print(sub_list)
        if sub_list:
            sub_url = sub_list[0]["subtitle_url"]
            result = requests.get(sub_url)
            raw_sub_titles = json.loads(result.content)["body"]
            raw_transcript = " ".join([c["content"] for c in raw_sub_titles])

            raw_transcript_with_meta_info = (
                f"Video Title: {video_info['title']},"
                f"description: {video_info['desc']}\n\n"
                f"Transcript: {raw_transcript}"
            )
            return raw_transcript_with_meta_info, video_info
        else:
            raw_transcript = ""
            warnings.warn(
                f"""
                No subtitles found for video: {url}.
                Return Empty transcript.
                """
            )
            return raw_transcript, video_info

**Comment by z0z0r4** [comment]
用 `video.Video().get_subtitle()` 而不是 `video.Video().get_info()`，难怪炸

**Comment by zhao-cs-debug** [comment]
这就奇怪了。我把函数单独拿出来运行，显示AttributeError: 'Video' object has no attribute 'get_subtitle'。我看Video里有这个函数的，不知道是哪里出错了。
示例代码是这样的

import re
from bilibili_api import sync, video
url="https://www.bilibili.com/video/BV1mh4y1X75Y/?spm_id_from=333.337.search-card.all.click"
bvid = re.search(r"BV\w+", url)
print(bvid.group())
v = video.Video(bvid=bvid.group())
video_info = sync(v.get_subtitle())
print(video_info)

AttributeError: 'Video' object has no attribute 'get_subtitle'

**Comment by Drelf2018** [comment]
> 传入过程中报错了。 ----> 9 credential = Credential(sessdata=SESSDATA, 10 bili_jct=Bili_jct, 11 buvid3=Buvid3, 12 dedeuserid=Dedeuserid, 13 ac_time_value=Ac_time_value)
> 
> TypeError: Credential.**init**() got an unexpected keyword argument 'dedeuserid'

检查库版本是否最新，这个参数是五个月前加入的，合理怀疑库版本不是最新导致的

```python
pip install bilibili-api-python --upgrade
```
