### ISSUE TITLE
【建议】似乎有一些地方疏忽了

### ISSUE THREAD

**Issue by umbrella-leaf** [Nemo2011/bilibili-api#358]
## bilibili_api/credential.py下Credential类的check_refresh和refresh方法好像忘了设为异步
![image](https://github.com/Nemo2011/bilibili-api/assets/113193998/d78c8a03-9187-4b5e-bbe9-a75a8abdc96f)
![image](https://github.com/Nemo2011/bilibili-api/assets/113193998/fe4c5281-e569-443c-ac60-9aa091b63431)

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/issues/351
