### ISSUE TITLE
PyInstaller 打包问题

### ISSUE THREAD

**Issue by cancundeyingzi** [Nemo2011/bilibili-api#36]
![image](https://user-images.githubusercontent.com/73635883/184184853-a9d0ecfb-d797-4b15-b3e1-8209f99b7e6c.png)
如图,我用的是api示例直接复制粘贴,,在pyc里直接运行是正常的

**Comment by cancundeyingzi** [comment]
![image](https://user-images.githubusercontent.com/73635883/184186781-d6c0e905-fd6b-4646-98ef-2533a12af44a.png)
这是我自己的程序,错误差不多,都是打包成exe后用不了

**Comment by Nemo2011** [comment]
应该是 Pyinstaller 打包的时候没有把 data/api 打进去(放在 json 文件里面了）。

**Comment by Nemo2011** [comment]
需要单独拎出来写一个 hook

**Comment by Nemo2011** [comment]
已经修复了。请下载 dev 分支自行安装（`python setup.py install`）。

**Comment by cancundeyingzi** [comment]
> python setup.py install

已经下载了,但是再次打包发现还是老问题

**Comment by Nemo2011** [comment]
sorry, 刚刚发消息的时候 `git push` 失败了，麻烦再试一下。

如果还出错，就直接把 pyinstaller 的 log 发一下。

我的系统是 macos，目前打包直播第一个示例通过了。

**Comment by cancundeyingzi** [comment]
> sorry, 刚刚发消息的时候 `git push` 失败了，麻烦再试一下。
> 
> 如果还出错，就直接把 pyinstaller 的 log 发一下。
> 
> 我的系统是 macos，目前打包直播第一个示例通过了。

软件包版本已经变成11.11...但依旧还是那个错误,下面是截图中的输出内容,如果有必要,可以使用远程控制(todesk等)
![image](https://user-images.githubusercontent.com/73635883/184311946-9cc35be7-20a1-4209-8e7c-9c1726de6afd.png)

`Running auto-py-to-exe v2.17.0
Building directory: C:\Users\ASUS\AppData\Local\Temp\tmpjxo0_74h
Provided command: pyinstaller --noconfirm --onefile --console  "D:/py/pythonProject/测试.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onefile --console D:/py/pythonProject/测试.py --distpath C:\Users\ASUS\AppData\Local\Temp\tmpjxo0_74h\application --workpath C:\Users\ASUS\AppData\Local\Temp\tmpjxo0_74h\build --specpath C:\Users\ASUS\AppData\Local\Temp\tmpjxo0_74h

9939 INFO: PyInstaller: 5.1
9947 INFO: Python: 3.10.1
9979 INFO: Platform: Windows-10-10.0.22622-SP0
9984 INFO: wrote C:\Users\ASUS\AppData\Local\Temp\tmpjxo0_74h\测试.spec
10001 INFO: UPX is not available.
10014 INFO: Extending PYTHONPATH with paths
['D:\\py\\pythonProject']
11167 INFO: checking Analysis
11185 INFO: Building Analysis because Analysis-00.toc is non existent
11187 INFO: Initializing module dependency graph...
11208 INFO: Caching module graph hooks...
11231 INFO: Analyzing base_library.zip ...
16813 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
16816 INFO: distutils: retargeting to non-venv dir 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib'
18275 INFO: Caching module dependency graph...
18528 INFO: running Analysis Analysis-00.toc
18548 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\ASUS\AppData\Local\Programs\Python\Python310\python.exe
18918 INFO: Analyzing D:\py\pythonProject\测试.py
21587 INFO: Processing module hooks...
21590 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
21595 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
21611 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
21626 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
21781 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
21798 INFO: Loading module hook 'hook-lib2to3.py' from 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
22051 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
22056 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
22067 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
22082 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
22086 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
22090 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
22229 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
22535 INFO: checking Tree
22554 INFO: Building Tree because Tree-00.toc is non existent
22570 INFO: Building Tree Tree-00.toc
22730 INFO: checking Tree
22743 INFO: Building Tree because Tree-01.toc is non existent
22746 INFO: Building Tree Tree-01.toc
22929 INFO: checking Tree
22934 INFO: Building Tree because Tree-02.toc is non existent
22936 INFO: Building Tree Tree-02.toc
22974 INFO: Looking for ctypes DLLs
22995 INFO: Analyzing run-time hooks ...
23013 INFO: Including run-time hook 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
23019 INFO: Including run-time hook 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_subprocess.py'
23030 INFO: Including run-time hook 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
23050 INFO: Including run-time hook 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
23067 INFO: Looking for dynamic libraries
24983 INFO: Looking for eggs
24986 INFO: Using Python library C:\Users\ASUS\AppData\Local\Programs\Python\Python310\python310.dll
24998 INFO: Found binding redirects: 
[]
25023 INFO: Warnings written to C:\Users\ASUS\AppData\Local\Temp\tmpjxo0_74h\build\测试\warn-测试.txt
25076 INFO: Graph cross-reference written to C:\Users\ASUS\AppData\Local\Temp\tmpjxo0_74h\build\测试\xref-测试.html
25107 INFO: checking PYZ
25125 INFO: Building PYZ because PYZ-00.toc is non existent
25128 INFO: Building PYZ (ZlibArchive) C:\Users\ASUS\AppData\Local\Temp\tmpjxo0_74h\build\测试\PYZ-00.pyz
25952 INFO: Building PYZ (ZlibArchive) C:\Users\ASUS\AppData\Local\Temp\tmpjxo0_74h\build\测试\PYZ-00.pyz completed successfully.
25979 INFO: checking PKG
25983 INFO: Building PKG because PKG-00.toc is non existent
25998 INFO: Building PKG (CArchive) 测试.pkg
27724 INFO: Building PKG (CArchive) 测试.pkg completed successfully.
27732 INFO: Bootloader C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
27747 INFO: checking EXE
27751 INFO: Building EXE because EXE-00.toc is non existent
27756 INFO: Building EXE from EXE-00.toc
27760 INFO: Copying bootloader EXE to C:\Users\ASUS\AppData\Local\Temp\tmpjxo0_74h\application\测试.exe.notanexecutable
27775 INFO: Copying icon to EXE
27779 INFO: Copying icons from ['C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\bootloader\\images\\icon-console.ico']
27783 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
27794 INFO: Writing RT_ICON 1 resource with 3752 bytes
27797 INFO: Writing RT_ICON 2 resource with 2216 bytes
27811 INFO: Writing RT_ICON 3 resource with 1384 bytes
27813 INFO: Writing RT_ICON 4 resource with 37019 bytes
27826 INFO: Writing RT_ICON 5 resource with 9640 bytes
27842 INFO: Writing RT_ICON 6 resource with 4264 bytes
27844 INFO: Writing RT_ICON 7 resource with 1128 bytes
27865 INFO: Copying 0 resources to EXE
27872 INFO: Embedding manifest in EXE
27888 INFO: Updating manifest in C:\Users\ASUS\AppData\Local\Temp\tmpjxo0_74h\application\测试.exe.notanexecutable
27903 INFO: Updating resource type 24 name 1 language 0
27914 INFO: Appending PKG archive to EXE
29756 INFO: Building EXE from EXE-00.toc completed successfully.

Moving project to: D:\py\output
Complete.`

**Comment by Nemo2011** [comment]
`pyinstaller -F "your-file.py"`

再试一下

**Comment by Nemo2011** [comment]
实在不行的话，在 `python 目录/lib/site-packages/PyInstaller/hooks` 下新建 `hook-bilibili_api` 文件，内容：
```
from PyInstaller.utils.hooks import collect_data_files

datas = collect_data_files("bilibili_api")
```

然后再尝试打包。

**Comment by cancundeyingzi** [comment]
> 实在不行的话，在 `python 目录/lib/site-packages/PyInstaller/hooks` 下新建 `hook-bilibili_api` 文件，内容：
> 
> ```
> from PyInstaller.utils.hooks import collect_data_files
> 
> datas = collect_data_files("bilibili_api")
> ```
> 
> 然后再尝试打包。

感谢,我在C:\Users\ASUS\AppData\Local\Programs\Python\Python310\Lib\site-packages\PyInstaller\hooks位置创建了hook-bilibili_api.py,并粘贴上上面的代码,再打包,已经不会有类似的错误了,剩下的错误好像是我微软语音模块有问题(靠,为什么直接运行pyc都没问题,一打包全报错)

**Comment by Nemo2011** [comment]
解决了就好。
