### ISSUE TITLE
【提问】Picture.from_content(image, 'jpg').upload_file(cred)接口返回错误代码：4125014

### ISSUE THREAD

**Issue by BesiegedCity** [Nemo2011/bilibili-api#362]
**Python 版本：** 3.9.16

**模块版本：** 15.5.1

**运行环境：** Linux

---

向b站上传jpg图片时报错，前几天似乎还是正常的。更新了cred信息也没有效果。
调用：
img = await Picture.from_content(image, 'jpg').upload_file(cred)
其中image为bytes，cred中四项属性已经是最新了

错误栈：

bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：4125014，信息：4125014

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/bilibili_api/utils/network_httpx.py", line 445, in wrapper
>     return await func(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/bilibili_api/utils/network_httpx.py", line 510, in request
>     if api.method != "GET" and not api.no_csrf:
> AttributeError: 'str' object has no attribute 'method'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/local/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
>     exitcode = _main(fd, parent_sentinel)
>   File "/usr/local/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
>     return self._bootstrap(parent_sentinel)
>   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/lib/python3.9/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
>     target(sockets=sockets)
>   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
>     return asyncio.run(self.serve(sockets=sockets))
>   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
> > File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
>     retval = await job.func(*job.args, **job.kwargs)
>   File "/bot/src/plugins/hxzxhelper/__init__.py", line 165, in send2bili
>     pictures.append(await Picture.from_content(image, 'jpg').upload_file(cred))
>   File "/usr/local/lib/python3.9/site-packages/bilibili_api/utils/picture.py", line 158, in upload_file
>     res = await upload_image(self, credential)
>   File "/usr/local/lib/python3.9/site-packages/bilibili_api/dynamic.py", line 202, in upload_image
>     return_info = await request(
>   File "/usr/local/lib/python3.9/site-packages/bilibili_api/utils/network_httpx.py", line 471, in inner
>     return await func(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/bilibili_api/utils/network_httpx.py", line 447, in wrapper
>     return await request_old(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/bilibili_api/utils/network_httpx.py", line 399, in request_old
>     raise ResponseCodeException(code, msg, resp_data)
> bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：4125014，信息：4125014。
> {'code': 4125014, 'message': '4125014', 'ttl': 1, 'data': {'image_url': '', 'image_width': 0, 'image_height': 0}}

请问有没有调试建议，感谢

**Comment by Drelf2018** [comment]
我这边测试是正常的，我再试试

**Comment by BesiegedCity** [comment]
我检查了下，应该是上传了一个1*1的图片导致的，过滤掉这种图片就正常了，无需其他修改。

感谢回复！
