### ISSUE TITLE
【提问】私信图片加载失败

### ISSUE THREAD

**Issue by MEYUYU** [Nemo2011/bilibili-api#365]
**Python 版本：** 3.8.3

**模块版本：** 15.4.1

**运行环境：** Windows

---

参考示例代码的私信回复图片，可以正常发送和显示，但是过了一段时间以后会无法加载
![Screenshot_20230626-205646928](https://github.com/Nemo2011/bilibili-api/assets/3656262/87b0e3c1-449d-43ff-bf83-46caf13af94b)
![Screenshot_20230626-205650402](https://github.com/Nemo2011/bilibili-api/assets/3656262/174fdeeb-29a6-4856-9362-11e48d9a5743)

**Comment by Drelf2018** [comment]
难道图片上传接口改了？可是我本地测都是正常的。感觉和 #362 是一个问题
