### ISSUE TITLE
【提问】get_dahanghai 获取的大航海列表，是从第四位开始的。

### ISSUE THREAD

**Issue by newlong2008** [Nemo2011/bilibili-api#368]
**Python 版本：** 3.10

**模块版本：** 15.1

**运行环境：** Windows 

---
` from bilibili_api.live import LiveRoom
room = LiveRoom(room_id)
data_list = await room.get_dahanghai（)
`

请问，我用以上方式获取的大航海列表，为什么是从第四位开始的，前3个人没有。获取的信息中，rank 1，2，3也是没有的。

**Comment by Drelf2018** [comment]
好像有个top3啥的字段，你看看，这个是b站设置的

**Comment by newlong2008** [comment]
看到了，感谢，是我疏忽了，每一页的最后果然有个top3
