### ISSUE TITLE
【建议】更换 user.get_followings 的 api 接口

### ISSUE THREAD

**Issue by unprintable123** [Nemo2011/bilibili-api#374]
将获取关注列表的接口改为API["info"]["followings"] (api.bilibili.com/x/relation/followings)
原来的app.biliapi.net/x/v2/relation/followings就算登录了也只能查看前5页。
这个api也是支持order_type的，可以把user.json也顺便更新一下。

**Comment by z0z0r4** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/436f26f15bab7855184e40b21c54ab0e41fb6133/docs/user/relation.md#%E6%9F%A5%E8%AF%A2%E7%94%A8%E6%88%B7%E5%85%B3%E6%B3%A8%E6%98%8E%E7%BB%86

**Comment by z0z0r4** [comment]
我周日回家换

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/pull/381
