### ISSUE TITLE
【需求】视频数据新接口？

### ISSUE THREAD

**Issue by Yoak3n** [Nemo2011/bilibili-api#377]
关于这段时间哔哩哔哩观看数(vv)改观看时长(vt)，在原来的视频数据接口`https://api.bilibili.com/x/web-interface/archive/stat`中有`vt`字段但值为`null`
![image](https://github.com/Nemo2011/bilibili-api/assets/120039624/863ca800-a221-45bb-b266-89f2cb9fee6f)
在某个群中无意中看到群友分享的一个接口：`https://api.bilibili.com/archive_stat/stat`
![image](https://github.com/Nemo2011/bilibili-api/assets/120039624/049fe814-8821-4ba2-820b-c0dc13e36c80)
能够获得`vv`和`vt`
**请求参数貌似暂时只能是`aid`**，

**Comment by Yoak3n** [comment]
> 感觉你可以再等等看看B站，是不是接口还没写完？

确实像是一个测试中的版本，还有点好奇群友是怎么知道的hhhh

**Comment by z0z0r4** [comment]
> > 感觉你可以再等等看看B站，是不是接口还没写完？
> 
> 确实像是一个测试中的版本，还有点好奇群友是怎么知道的hhhh

https://github.com/SocialSisterYi/bilibili-API-collect/blob/21c7f54e0519b10a8e00edb88d11caa470683571/docs/video/status_number.md?plain=1#L4

**Comment by Yoak3n** [comment]
也就是说这个接口其实一直都有，只不过最近更新了
https://github.com/SocialSisterYi/bilibili-API-collect/issues/734

**Comment by z0z0r4** [comment]
是这么回事，看看情况先

**Comment by z0z0r4** [comment]
没了，不用等了
      
> > 这个接口应该是被删除了 🤔
> 
> 指的是 https://api.bilibili.com/archive_stat/stat?aid=170001 吗？

这个接口现在 HTTP 403 了

_Originally posted by @SocialSisterYi in https://github.com/SocialSisterYi/bilibili-API-collect/issues/734#issuecomment-1627447622_
