### ISSUE TITLE
【提问】嗯。退出时报错。这是为什么啊

### ISSUE THREAD

**Issue by LondonClass** [Nemo2011/bilibili-api#38]
<img width="875" alt="屏幕截图 2022-08-12 182822" src="https://user-images.githubusercontent.com/43668206/184336545-b61689b8-0fd2-40be-8795-840e902f2524.png">

**Comment by LondonClass** [comment]
<img width="1027" alt="屏幕截图 2022-08-12 234852" src="https://user-images.githubusercontent.com/43668206/184394037-019253f3-7f9f-4add-b41e-728f153b91e7.png">

示例代码会报错耶。希望大佬能看一下

**Comment by Nemo2011** [comment]
??? 模块版本？

**Comment by LondonClass** [comment]
> ??? 模块版本？

9.1.0

**Comment by Nemo2011** [comment]
试着用 `python 你的文件名.py` 运行。

**Comment by Nemo2011** [comment]
最好重装一下模块。

**Comment by LondonClass** [comment]
谢谢大佬。重装解决了。就是退出时还是会报错

**Comment by LondonClass** [comment]
> 最好重装一下模块。

谢谢大佬。重装解决了。就是退出时还是会报错

**Comment by cancundeyingzi** [comment]
这是啥vs版本,,我感觉vs好难用

**Comment by Nemo2011** [comment]
退出报错是用 `python 你的文件名.py` 运行的吗？

**Comment by LondonClass** [comment]
> 退出报错是用 `python 你的文件名.py` 运行的吗？

是的

**Comment by LondonClass** [comment]
> 这是啥vs版本,,我感觉vs好难用

vs2022
