### ISSUE TITLE
【提问】函数名称拼字有误

### ISSUE THREAD

**Issue by kevin0216** [Nemo2011/bilibili-api#380]
**Python 版本：** 3.11.4

**模块版本：** 15.5.1

**运行环境：** Ubuntu 20.04

---

在 credential class 中的 check_refresh() 函数拼字有误 (credential.py line 36)
被拼写为 chcek_refresh()
![image](https://github.com/Nemo2011/bilibili-api/assets/52964758/c9d1864c-e7a8-4d51-ba85-a6ba0b9a0bcd)

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/commit/3a3b291ddf7d7bb99e927a2c1f11d3d46b073cd6
