### ISSUE TITLE
【提问】想问一下文档是用的什么模版嘞

### ISSUE THREAD

**Issue by jhzgjhzg** [Nemo2011/bilibili-api#382]
如题，求文档的模版

**Comment by z0z0r4** [comment]
> 没有模板，就按照已有的改改就行

问的应该是哪个框架构建的

**Comment by jhzgjhzg** [comment]
> > 没有模板，就按照已有的改改就行
> 
> 问的应该是哪个框架构建的

确实，想把文档整个重写一下，总觉得现在的文档除了看有什么函数以外就没啥作用了

**Comment by z0z0r4** [comment]
> > > 没有模板，就按照已有的改改就行
> > 
> > 
> > 问的应该是哪个框架构建的
> 
> 确实，想把文档整个重写一下，总觉得现在的文档除了看有什么函数以外就没啥作用了

我觉得你没必要用现有的模板，也挺丑的其实（）

**Comment by z0z0r4** [comment]
如果是重写文档，参考下这个 https://github.com/Nemo2011/bilibili-api/issues/293 ？

建议在下面交流下有啥想法

**Comment by zerowuxian** [comment]
> 如果是重写文档，参考下这个 #293 ？
> 
> 建议在下面交流下有啥想法

我在考虑给每个函数加返回值示例（但是好像工作量有点太大了

**Comment by z0z0r4** [comment]
> > 如果是重写文档，参考下这个 #293 ？
> > 
> > 建议在下面交流下有啥想法
> 
> 我在考虑给每个函数加返回值示例（但是好像工作量有点太大了

也就比把库重写一遍耗时略小…
