### ISSUE TITLE
v15.5.1b0 Beta 测试中

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#387]
## **没问题的用户不应该试用此版本**

主要修复了直播间的问题，如果有问题请先试试看更新到此版本

`pip install bilibili-api-python==15.5.1b0` 

> **Warning** 
> **`pip install bilibili-api-python --upgrade` 是无效的，对应的版本会是 `15.5.1`** 

此处用于汇总下仍未修复的漏洞，在下方反馈

**Comment by yainse** [comment]
在直播间使用弹幕的功能，似乎不能获取到所有的弹幕。

**Comment by yainse** [comment]
Name: bilibili-api-python
Version: 15.5.1

在获取弹幕的时候会出现漏弹幕，但是在5分钟后，弹幕就不会再出现遗漏了。
症状与
https://github.com/Nemo2011/bilibili-api/issues/372#issuecomment-1625630331
一致。

**Comment by z0z0r4** [comment]
> Name: bilibili-api-python Version: 15.5.1
> 
> 在获取弹幕的时候会出现漏弹幕，但是在5分钟后，弹幕就不会再出现遗漏了。 症状与 [#372 (comment)](https://github.com/Nemo2011/bilibili-api/issues/372#issuecomment-1625630331) 一致。

> Version: 15.5.1

你真的更新了吗？这不应该是 `v15.5.1b0`？

`pip install bilibili-api-python==15.5.1b0`

**Comment by Drelf2018** [comment]
@Erekilu @yainse 更新库版本至 `v15.5.1b0` 再尝试运行代码，检查是否仍然出现漏弹幕情况。本人目前测试中未出现该情况。

**Comment by MisakaAI** [comment]
都快俩周了，`15.5.2` 还没有发布……是还有什么问题吗？
`v15.5.1b0` 毕竟不是正式版呀QAQ

**Comment by z0z0r4** [comment]
> 都快俩周了，`15.5.2` 还没有发布……是还有什么问题吗？
> `v15.5.1b0` 毕竟不是正式版呀QAQ

没，在发了在发了

**Comment by z0z0r4** [comment]
发了
