### ISSUE TITLE
抓取弹幕提示：bilibili_api.exceptions.ResponseException.ResponseException: 解析响应数据错误

### ISSUE THREAD

**Issue by chensiyi0904** [Nemo2011/bilibili-api#393]
**Python 版本：3.9.7

**模块版本：15.4.3

**运行环境： Windows 

仍显示无法获取响应数据，按照之前issue修改方法无效

**Comment by chensiyi0904** [comment]
![image](https://github.com/Nemo2011/bilibili-api/assets/78398899/40f683bc-e2aa-4680-882e-c690e21ce355)
这是文档所给demo代码，刚刚进行了upgrade后仍无法使用

**Comment by chensiyi0904** [comment]
> 
测试视频为：
v = video.Video(bvid='BV1hu4y1d7uz') 
v = video.Video(bvid='BV1Ps4y1q7K2')
在更新版本后，部分视频可以抓取弹幕，但数量（900）远少于填充数量（3000），且最终均以三条未知时间和0.0弹幕内容结束。
以及部分视频会在video.py.L686报错。

**Comment by chensiyi0904** [comment]
> 更新版本

您好，所遇到的部分问题发布在上面

**Comment by Drelf2018** [comment]
你没登录

```python
credential = Credential(
    sessdata="",
    bili_jct=""
)
v = video.Video(bvid="BV1AV411x7Gs", credential=credential)
```

**Comment by chensiyi0904** [comment]
> 你没登录
> 
> ```python
> credential = Credential(
>     sessdata="",
>     bili_jct=""
> )
> v = video.Video(bvid="BV1AV411x7Gs", credential=credential)
> ```

在此感谢您的解答，之前半年多爬取弹幕时并未注意登陆问题。
在登陆后，测试了十几个视频已经可以正常爬取到弹幕，但其中一个测试视频BV1hu4y1d7uz，仍然在L686处报错bilibili_api.exceptions.ResponseException.ResponseException: 解析响应数据错误。

**Comment by z0z0r4** [comment]
response 又中断了吧…

感觉得考虑下给弹幕单独加个 @retry？

**Comment by jhzgjhzg** [comment]
弹幕是这样的，对于弹幕量过大的视频，爬到一半可能就寄了，所以你可以自己写个装饰器，（然而不管多大的评论，都不会有这样的问题）

**Comment by z0z0r4** [comment]
> 弹幕是这样的，对于弹幕量过大的视频，爬到一半可能就寄了，所以你可以自己写个装饰器，（然而不管多大的评论，都不会有这样的问题）

@retry 是已有的
