### ISSUE TITLE
【提问】如何获取字幕

### ISSUE THREAD

**Issue by liyf1** [Nemo2011/bilibili-api#394]
**Python 版本：** 3.8

**模块版本：** 15.5.1

**运行环境：** MacOS

我在用langchain获取字幕时一直获取不到，求解是什么原因
loader = BiliBiliLoader(["https://www.bilibili.com/video/BV1hp4y1b7xq?t=35.8"])
报错
No subtitles found for video: https://www.bilibili.com/video/BV1hp4y1b7xq?t=35.8.
                Return Empty transcript.

**Comment by z0z0r4** [comment]
参考 ass 模块
https://nemo2011.github.io/bilibili-api/#/modules/ass?id=async-def-make_ass_file_subtitle
