### ISSUE TITLE
【提问】是否有获取直播当前观看人数的接口（或者是那个高能用户榜单）

### ISSUE THREAD

**Issue by jhzgjhzg** [Nemo2011/bilibili-api#395]
**Python 版本：** 3.9.16

**模块版本：** 15.5.1

**运行环境：** MacOS

---

如题，顺便问一句，直播间人气更新里面人气是什么

**Comment by nailvcoronation** [comment]
直播的websocket里ONLINE_COUNT这个cmd是高能人数

**Comment by jhzgjhzg** [comment]
> 

文档里没有这个cmd啊，而且监控了一下这个没有数据回传

**Comment by nailvcoronation** [comment]
斯米马赛，记错cmd了，是`ONLINE_RANK_COUNT`。
```
{
      "cmd": "ONLINE_RANK_COUNT",
      "data": {
        "count": 5189
      },
      "is_report": false,
      "msg_id": "601986417301504",
      "send_time": 1689702077970
}
```
参见https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/live/message_stream.md

**Comment by jhzgjhzg** [comment]
> 斯米马赛，记错cmd了，是`ONLINE_RANK_COUNT`。
> 
> ```
> {
>     "cmd": "ONLINE_RANK_COUNT",
>     "data": {
>       "count": 5189
>     },
>     "is_report": false,
>     "msg_id": "601986417301504",
>     "send_time": 1689702077970
> }
> ```
> 
> 参见https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/live/message_stream.md

万分感谢
