### ISSUE TITLE
【提问】API调用时间限制

### ISSUE THREAD

**Issue by 30000lightyears** [Nemo2011/bilibili-api#397]
**Python 版本：** 3.11.4

**模块版本：** 15.5.1

**运行环境：** Windows

---

API是否有调用时间限制，如1秒请求1次是否会触发网站机制？

**Comment by z0z0r4** [comment]
> **Python 版本：** 3.11.4
> 
> **模块版本：** 15.5.1
> 
> **运行环境：** Windows
> 
> ---
> 
> API是否有调用时间限制，如1秒请求1次是否会触发网站机制？
> 

具体情况自己试试看…没有明确的阈值

**Comment by Drelf2018** [comment]
那肯定是有限制的，我的建议是2-3秒一次。我之前3秒一次都被ban过。不过等个几小时半天就恢复了。
