### ISSUE TITLE
【提问】连接直播间出现弹幕获取不到的问题

### ISSUE THREAD

**Issue by iAilu** [Nemo2011/bilibili-api#399]
**Python 版本：** 3.9

**模块版本：** 15.5.1

**运行环境：** Windows

---

如题，连接直播间后能获取到的弹幕相当少，好半天才能拿到一条。用之前老版本的bilibili-api时，弹幕获取正常，前几天突然就不能正常获取弹幕了，更新了新的bilibili-api-python以后还是有一样的问题。
有大佬遇到相似的问题吗？

**Comment by z0z0r4** [comment]
用 15.5.1b0 试试看

**Comment by iAilu** [comment]
可以了 15.5.1b0没有这个问题

**Comment by Starlwr** [comment]
> 用 15.5.1b0 试试看

能否问一下是哪个commit修复了这个问题，试着翻了一下没有找到

**Comment by Drelf2018** [comment]
https://github.com/Nemo2011/bilibili-api/commit/79c424ea9a3b5ca8f6351fd707e8803d3e2030d4

**Comment by Starlwr** [comment]
奇怪，我现在已经有这段逻辑了，但是我在连接数很多的时候会丢事件，我这大概有四百多个ws连接，从前几天开始有部分直播间丢弹幕之类的数据，还有些开播下播事件也会漏，还没找到是哪里的原因

**Comment by Drelf2018** [comment]
> 奇怪，我现在已经有这段逻辑了，但是我在连接数很多的时候会丢事件，我这大概有四百多个ws连接，从前几天开始有部分直播间丢弹幕之类的数据，还有些开播下播事件也会漏，还没找到是哪里的原因

尝试 https://github.com/Nemo2011/bilibili-api/pull/373 提到的方法 2 呢

原解决方案 https://github.com/simon300000/bilibili-live-ws/issues/397#issuecomment-1617901764

**Comment by Starlwr** [comment]
两个方法试过了都不太行，UID字段用自己的和用主播的都试过了，然后换了一个账号的cookie也是不行，真奇怪，看起来最近也没有其他人提类似的issue
