### ISSUE TITLE
Api 相关 BUG

### ISSUE THREAD

**Issue by Drelf2018** [Nemo2011/bilibili-api#405]
test action 一堆报错的啊

**Comment by z0z0r4** [comment]
~~action 就没看过，压根没登录~~ 我看看，草

**Comment by Drelf2018** [comment]
出错测试项目解决方案：
- tests.test_interactive_video.test_a_InteractiveVideo_get_graph_version
> https://github.com/Nemo2011/bilibili-api/blob/bf6ea9de34ddcc2060446bdc4badc9835139d7a8/bilibili_api/interactive_video.py#L528-L531
> 这里的 api 其实是 url
> 可以通过在 .json 中写新的接口解决
- tests.test_interactive_video.test_b_InteractiveVideo_get_edge_info
- tests.test_interactive_video.test_c_get_all_nodes
- tests.test_live.test_i_get_self_info
- tests.test_live.test_t_get_self_live_info
- tests.test_live.test_v_get_self_bag
- tests.test_live.test_zb_get_area_info
- tests.test_dynamic.test_b_get_schedules_list
- tests.test_favorite_list.test_get_favorite_collected_1
- tests.test_favorite_list.test_get_favorite_collected_2
- tests.test_video_tag.test_d_subscribe_tag
- tests.test_video_tag.test_e_unsubscribe_tag
- tests.test_vote.test_b_create_vote
- tests.test_vote.test_c_update_vote
- tests.test_rank.test_k_get_live_sailing_rank
- tests.test_rank.test_p_subscribe_music_rank

**Comment by z0z0r4** [comment]
```
  'NoneType' object has no attribute 'copy'
  Traceback (most recent call last):
    File "/home/runner/work/bilibili-api/bilibili-api/tests/main.py", line 72, in test
      res = await func()
    File "/home/runner/work/bilibili-api/bilibili-api/tests/test_live.py", line 124, in test_t_get_self_live_info
      return await live.get_self_live_info(get_credential())
    File "/home/runner/work/bilibili-api/bilibili-api/bilibili_api/live.py", line 1159, in get_self_live_info
      return await Api(**api, credential=credential).result
    File "<string>", line 16, in __init__
    File "/home/runner/work/bilibili-api/bilibili-api/bilibili_api/utils/network_httpx.py", line 130, in __post_init__
      self.original_params = self.params.copy()
  AttributeError: 'NoneType' object has no attribute 'copy'
```

这货不是字典emm

**Comment by Drelf2018** [comment]
不知道 没设备实测

**Comment by z0z0r4** [comment]
这一时半会搞不定，先把 update 全部换成赋值用着吧... json 里面的键都进去了，单 `self.params = {k: "" for k in self.params.keys()}` 没用

**Comment by z0z0r4** [comment]
- tests.test_rank.test_k_get_live_sailing_rank code: -1
- tests.test_rank.test_p_subscribe_music_rank 重试上限
我估计也是，不测了，合并先

**Comment by z0z0r4** [comment]
根本不能不测...屎糊的 fix
https://github.com/Nemo2011/bilibili-api/pull/407

**Comment by z0z0r4** [comment]
example Model

![f9cb7e8118b8939d6b1ddd86620de446](https://github.com/Nemo2011/bilibili-api/assets/78744121/32b341c6-34a3-448c-9c9d-1d0be848d910)

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/actions/runs/5656226601 Pass 我再发个，乐死了
