### ISSUE TITLE
[提问] 获取用户动态列表api可能过旧

### ISSUE THREAD

**Issue by blyc** [Nemo2011/bilibili-api#420]
**Python 版本：** 3.9.16

**模块版本：** 15.5.3

**运行环境：** Windows

---

_语言组织能力较差，望海涵_

使用 user.User(uid=1875094289, credential=XXX).get_dynamics(827362760244330537) 时发现缺少一条充电动态数据，
而后通过查阅源码的api json拼接了api地址并使用 **已给该UP充电** 的 Cookie 调用 api，确认了该api似乎因为版本过旧不含有充电动态数据

以下两次api调用皆已确保含有正确且相同的Cookie

旧api地址：
https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/space_history?host_uid=1875094289&offset_dynamic_id=827362760244330537
Response：
![图片](https://github.com/Nemo2011/bilibili-api/assets/34291620/f05200a0-97e3-42c5-bf14-18638594200a)

新api地址：
https://api.bilibili.com/x/polymer/web-dynamic/v1/feed/space?offset=827362760244330537&host_mid=1875094289&timezone_offset=-480&features=itemOpusStyle
Response：
![图片](https://github.com/Nemo2011/bilibili-api/assets/34291620/3fb088ba-41aa-424a-83fe-120c5e4ad22e)

_其它对照项：
    不传正确Cookie调用新api：_
![图片](https://github.com/Nemo2011/bilibili-api/assets/34291620/99751290-34b6-424f-9e02-a4fae906d644)

以上，可见新api会在 **使用了正确的Cookie**[即给该up充电]后，返回动态列表加入可见的充电动态 _[id:827025884499148801]_

所以想请问库什么时候会更新为新的动态列表api？

**Comment by z0z0r4** [comment]
此接口位于网页版哪个界面被调用？有新参数，我得抓下

**Comment by z0z0r4** [comment]
只找到一个 `feature`

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/75d74efd-eb77-4b25-bb5c-57f7cc787a51)

**Comment by z0z0r4** [comment]
`need_top` 失效...

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/pull/432

**Comment by blyc** [comment]
> #432

首先感谢大佬的更新，以及很抱歉没能及时响应您的回复和测试该更新

然后是对该更新测试后发现的问题

1. 新接口参数中的offset默认值应为`空字符串`而不是`0`
测试使用本库调用api以及直接请求拼接的url发现传入0的响应是错误代码`4101129`
2. 看到新的release版本您标注了该更新的传参是一项破坏性更新
先是关于need_top置顶：据我个人观察，新接口返回的动态列表中，若不传offset且有置顶动态，则置顶动态在第一位；若传入offset，不管offset的值大于还是小于置顶动态id，置顶动态都不会出现在列表 _(除非新接口真的有个类似参数还能被猜到参数名才能解决问题了)_
然后是关于破坏性更新，个人感受最大的破坏性更新是response的变动，不管是前文提到的置顶动态还是整个response结构对使用更新前接口的其它项目可能都是极大的破坏性更新，同时biliapi文档的获取动态的示例也将收到影响，所以是否要考虑保留旧的接口而将新接口另写为一个新的函数？

**Comment by z0z0r4** [comment]
> > #432
> 
> 首先感谢大佬的更新，以及很抱歉没能及时响应您的回复和测试该更新
> 
> 然后是对该更新测试后发现的问题
> 
> 1. 新接口参数中的offset默认值应为`空字符串`而不是`0`
>    测试使用本库调用api以及直接请求拼接的url发现传入0的响应是错误代码`4101129`
> 2. 看到新的release版本您标注了该更新的传参是一项破坏性更新
>    先是关于need_top置顶：据我个人观察，新接口返回的动态列表中，若不传offset且有置顶动态，则置顶动态在第一位；若传入offset，不管offset的值大于还是小于置顶动态id，置顶动态都不会出现在列表 _(除非新接口真的有个类似参数还能被猜到参数名才能解决问题了)_
>    然后是关于破坏性更新，个人感受最大的破坏性更新是response的变动，不管是前文提到的置顶动态还是整个response结构的变化，对使用更新前接口的其它项目可能都会造成较大影响，同时biliapi文档的获取动态的示例也将受到影响，所以是否要考虑保留旧的接口而将新接口另写为一个新的函数？

第一点建议新开 issue 了，草，我这没测到

关于第二点 need_top 是直接不支持指定是否置顶动态，有什么问题？并没这么多要考虑的

**Comment by blyc** [comment]
> > > #432
> > 
> > 
> > 首先感谢大佬的更新，以及很抱歉没能及时响应您的回复和测试该更新
> > 然后是对该更新测试后发现的问题
> > 
> > 1. 新接口参数中的offset默认值应为`空字符串`而不是`0`
> >    测试使用本库调用api以及直接请求拼接的url发现传入0的响应是错误代码`4101129`
> > 2. 看到新的release版本您标注了该更新的传参是一项破坏性更新
> >    先是关于need_top置顶：据我个人观察，新接口返回的动态列表中，若不传offset且有置顶动态，则置顶动态在第一位；若传入offset，不管offset的值大于还是小于置顶动态id，置顶动态都不会出现在列表 _(除非新接口真的有个类似参数还能被猜到参数名才能解决问题了)_
> >    然后是关于破坏性更新，个人感受最大的破坏性更新是response的变动，不管是前文提到的置顶动态还是整个response结构的变化，对使用更新前接口的其它项目可能都会造成较大影响，同时biliapi文档的获取动态的示例也将受到影响，所以是否要考虑保留旧的接口而将新接口另写为一个新的函数？
> 
> 第一点建议新开 issue 了，草，我这没测到
> 
> 关于第二点 need_top 是直接不支持指定是否置顶动态，有什么问题？并没这么多要考虑的

好的，第一点我再去开个 issue 

第二点对我本人项目倒是没什么问题，只是担心 其他人项目以及 [文档示例](https://nemo2011.github.io/bilibili-api/#/examples/user?id=%e7%a4%ba%e4%be%8b%ef%bc%9a%e8%8e%b7%e5%8f%96%e7%94%a8%e6%88%b7%e6%89%80%e6%9c%89%e5%8a%a8%e6%80%81) 受到的影响，所以在此更具体的说明新接口相对旧接口的变化，来方便你来判断下是 同时保留新旧两种接口 还是 按现在的 release 完全用新接口替换旧接口

**Comment by z0z0r4** [comment]
一般是保留接口
emm，有说法吗？我看看示例值差别有多大
@Nemo2011 @Drelf2018

**Comment by blyc** [comment]
> 一般是保留接口 emm，有说法吗？我看看示例值差别有多大 @Nemo2011 @Drelf2018

旧：https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/space_history?host_uid=97164600&offset_dynamic_id=0&need_top=0
新：https://api.bilibili.com/x/polymer/web-dynamic/v1/feed/space?offset=&host_mid=97164600&timezone_offset=-480&features=itemOpusStyle
以及新接口应该是加了referer限制，直接点击这里链接跳转会请求失败

**Comment by blyc** [comment]
> > 一般是保留接口 emm，有说法吗？我看看示例值差别有多大 @Nemo2011 @Drelf2018
> 
> 旧：https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/space_history?host_uid=97164600&offset_dynamic_id=0&need_top=0 ![图片](https://user-images.githubusercontent.com/34291620/261193880-b77b003d-ae30-49df-bf3b-bc73a75e0f65.png) 新：https://api.bilibili.com/x/polymer/web-dynamic/v1/feed/space?offset=&host_mid=97164600&timezone_offset=-480&features=itemOpusStyle ![图片](https://user-images.githubusercontent.com/34291620/261193842-6288399d-f7b3-4f58-a7ce-b5e1ff652169.png)
> 
> 简单看下来几乎没用共通点，算是完全重构了
> 
> 以及新接口应该是加了referer限制，直接点击这里链接跳转会请求失败，所以地址栏手动回车一下

刚发另一个issues才发现的问题，新接口似乎必须有cookie才能调用，光这一点就和旧接口差别巨大了

**Comment by z0z0r4** [comment]
那，开新的，寄，revert
