### ISSUE TITLE
无法获取高画质视频下载信息

### ISSUE THREAD

**Issue by Naxrin** [Nemo2011/bilibili-api#422]
如题
还想问下投稿编辑和添加分P的功能目前有吗（一年没关注了）

**Comment by z0z0r4** [comment]
能

**Comment by z0z0r4** [comment]
~~问问，你们为什么会有操作投稿视频这样的需求...自动录播？~~

**Comment by Naxrin** [comment]
> 能

所以应该怎么改参数呢 用模板下来的是480P想不到改哪里参数了

改已有稿件是因为自己手上有个合集要持续性更新而且挺麻烦的_（:3」∠）_

**Comment by z0z0r4** [comment]
> > 能
> 
> 所以应该怎么改参数呢 用模板下来的是480P想不到改哪里参数了
> 
> 改已有稿件是因为自己手上有个合集要持续性更新而且挺麻烦的_（:3」∠）_

只要传入 credential 默认返回的下载信息里面就有了，只不过是音视频分离的自己合并，啥参数都不用

**Comment by Naxrin** [comment]
> > > 能
> > 
> > 
> > 所以应该怎么改参数呢 用模板下来的是480P想不到改哪里参数了
> > 改已有稿件是因为自己手上有个合集要持续性更新而且挺麻烦的_（:3」∠）_
> 
> 只要传入 credential 默认返回的下载信息里面就有了，只不过是音视频分离的自己合并，啥参数都不用

是要动下面这行吗？
video_url = url["dash"]["video"][0]['baseUrl']
我credential传进去后，获得的url是这样（附的文件），desc有1080p60（该有的都有），下载链接却没有高画质的
quality vip是带了自己账号credential的，quality是没带账号credential=None的。
[quality vip.txt](https://github.com/Nemo2011/bilibili-api/files/12328767/quality.vip.txt)
[quality.txt](https://github.com/Nemo2011/bilibili-api/files/12328768/quality.txt)

**Comment by Naxrin** [comment]
> > > 能
> > 
> > 
> > 所以应该怎么改参数呢 用模板下来的是480P想不到改哪里参数了
> > 改已有稿件是因为自己手上有个合集要持续性更新而且挺麻烦的_（:3」∠）_
> 
> 只要传入 credential 默认返回的下载信息里面就有了，只不过是音视频分离的自己合并，啥参数都不用

完整代码是这样，不知道有没有过期
async def download(bvid, page, filename, credential=None):
    # 实例化 Video 类
    v = video.Video(bvid, credential)
    # 获取视频下载链接
    url = await v.get_download_url(page-1)
    json.dump(url, open('quality vip.json','w'), ensure_ascii=False, indent=4)
    # 视频轨链接
    video_url = url["dash"]["video"][0]['baseUrl']
    # 音频轨链接
    audio_url = url["dash"]["audio"][0]['baseUrl']
    async with httpx.AsyncClient(headers=HEADERS) as sess:

        #下载视频流
        resp = await sess.get(video_url)
        length = resp.headers.get('content-length')
        with open('video_temp.m4s', 'wb') as f:
            process = 0
            for chunk in resp.iter_bytes(1024):
                if not chunk:
                    break

                process += len(chunk)
                f.write(chunk)

        # 下载音频流
        resp = await sess.get(audio_url)
        length = resp.headers.get('content-length')
        with open('audio_temp.m4s', 'wb') as f:
            process = 0
            for chunk in resp.iter_bytes(1024):
                if not chunk:
                    break

                process += len(chunk)
                f.write(chunk)

        # 混流
        
        print(os.getcwd())
        os.system(f'{FFMPEG_PATH} -i video_temp.m4s -i audio_temp.m4s -vcodec copy -acodec copy {filename}')

        # 删除临时文件
        os.remove("video_temp.m4s")
        os.remove("audio_temp.m4s")
        print(f'\033[32m{filename}已下载\33[0m')

**Comment by z0z0r4** [comment]
直接 [0] 不太行吧，你怎么确认第一个是 1080P60

这边新增有一个解析器，可以参考下
https://github.com/Nemo2011/bilibili-api/blob/d184c038bf5a3a15871ffaa651e065ac3d3c2455/bilibili_api/video.py#L1990-L2339

**Comment by z0z0r4** [comment]
或者参考下 https://nemo2011.github.io/bilibili-api/#/examples/video?id=%e7%a4%ba%e4%be%8b%ef%bc%9a%e4%b8%8b%e8%bd%bd%e8%a7%86%e9%a2%91

**Comment by z0z0r4** [comment]
另外请使用代码块上传代码...

**Comment by Naxrin** [comment]
试了一下下面那个文档，也不行。登录下载仍然是480p
感觉是get_download_url的问题？因为附文档的url就是这个函数得到的，而且确实是没有高于480p的画质选项。就算我不用会员号下载也该有720p才对啊？
`async def download_url(url: str, out: str, info: str):
    # 下载函数
    async with httpx.AsyncClient(headers=HEADERS) as sess:
        resp = await sess.get(url)
        length = resp.headers.get('content-length')
        with open(out, 'wb') as f:
            process = 0
            for chunk in resp.iter_bytes(1024):
                if not chunk:
                    break

                process += len(chunk)
                print(f'下载 {info} {process} / {length}')
                f.write(chunk)
                
#下载单个视频：part分P标号；filename文件名；credential账号凭证
async def download(bvid, page, filename, credential=None):
    
    # 实例化 Video 类
    v = video.Video(bvid, credential)
    
    # 获取视频下载链接
    url = await v.get_download_url(page-1)
    json.dump(url, open('quality vip.json','w'), ensure_ascii=False, indent=4)
    
    # 视频轨链接
    detecter = video.VideoDownloadURLDataDetecter(data=url)
    streams = detecter.detect_best_streams()
    
    if detecter.check_flv_stream() == True:
            # FLV 流下载
            await download_url(streams[0].url, "flv_temp.flv", "FLV 音视频流")
            # 转换文件格式
            os.system(f'{FFMPEG_PATH} -i flv_temp.flv video.mp4')
            # 删除临时文件
            os.remove("flv_temp.flv")
    else:
        # MP4 流下载
        await download_url(streams[0].url, "video_temp.m4s", "视频流")
        await download_url(streams[1].url, "audio_temp.m4s", "音频流")
        # 混流
        os.system(f'{FFMPEG_PATH} -i video_temp.m4s -i audio_temp.m4s -vcodec copy -acodec copy video.mp4')
            
        # 删除临时文件
        os.remove("video_temp.m4s")
        os.remove("audio_temp.m4s")
            
        print(f'\033[32m{filename}已下载\33[0m')

if __name__ == '__main__':
    credential = Login(0)
    asyncio.get_event_loop().run_until_complete(download('BV1ax4y1M7NU', 1, 'third.mp4', credential))
`
[quality test.txt](https://github.com/Nemo2011/bilibili-api/files/12329088/quality.test.txt)

**Comment by z0z0r4** [comment]
请使用代码块上传代码，否则不会帮你 debug 的...

**Comment by z0z0r4** [comment]
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/828ccadc-d11e-476d-9208-b6517226f5b3)

图中的 `'id': 120` 就是你要的 4K 画质的下载信息，原因自己分析

有可能是 credential 失效，请确认

`support_format` 不能作为成功获取高画质视频的依据
