### ISSUE TITLE
[提问] 未知接口返回-401 anti-crawler

### ISSUE THREAD

**Issue by LittIeRed** [Nemo2011/bilibili-api#424]
**Python 版本：3.9.2

**模块版本：** 15.5.3

**运行环境：** Linux

![image](https://github.com/Nemo2011/bilibili-api/assets/42204608/b5b90ec4-c870-4068-a856-3ea2216bc3e6)
在真寻bot的B站订阅模块使用bilibli-api-python，原本用的bilireq不会返回-401，bilireq能自动获取bilibili网站首页cookie再调用api就可以正常访问，想请教下大佬bilibli-api-python这块应该怎么处理呀

**Comment by z0z0r4** [comment]
好家伙B站这么狠直接 `anti-crawler` 了吗...

**Comment by z0z0r4** [comment]
这个得库修，等更新吧（

**Comment by z0z0r4** [comment]
> **Python 版本：3.9.2 **Python版本：3.9.2
> 
> **模块版本：** 15.5.3
> 
> **运行环境：** Linux
> 
> ![image](https://user-images.githubusercontent.com/42204608/260319812-b5b90ec4-c870-4068-a856-3ea2216bc3e6.png) 在真寻bot的B站订阅模块使用bilibli-api-python，原本用的bilireq不会返回-401，bilireq能自动获取bilibili网站首页cookie再调用api就可以正常访问，想请教下大佬bilibli-api-python这块应该怎么处理呀

能看一下是哪个函数调用报错的吗？调试下？

**Comment by LittIeRed** [comment]
我刚刚又去试了一下，又不报错了，复现不出来了，代码里主要用了这几个函数：用户相关的get_user_info、get_dynamics、get_videos，直播相关的get_room_info，番剧相关的bangumi.get_meta，昨天的报错是在爬取用户动态时报的错，只用到了用户相关的那几个函数

**Comment by z0z0r4** [comment]
那先摆着吧...草

**Comment by z0z0r4** [comment]
> 我刚刚又去试了一下，又不报错了，复现不出来了，代码里主要用了这几个函数：用户相关的get_user_info、get_dynamics、get_videos，直播相关的get_room_info，番剧相关的bangumi.get_meta，昨天的报错是在爬取用户动态时报的错，只用到了用户相关的那几个函数

关于获取 `user` 获取视频及其动态都是正常的，未能复现，请提供具体的debug信息以便定位问题所在

你看看那几个id，对应的是啥，用户、番剧、动态，我必须知道哪一步出错了...

**Comment by z0z0r4** [comment]
另外看似你没有传入登录凭据，应该是这个原因...`'mid': 0`

**Comment by z0z0r4** [comment]
以及 action 凭据已过期，无法作为测试依据... @Nemo2011

**Comment by z0z0r4** [comment]
转到 https://github.com/Nemo2011/bilibili-api/issues/435 讨论
