### ISSUE TITLE
[提问] 直播模块无法获取实时弹幕了，目前是间隔一段时间才获取一批（不是逐个是一批）

### ISSUE THREAD

**Issue by CodFish124** [Nemo2011/bilibili-api#425]
**Python 版本：** 3.10.11

**模块版本：** 15.5.3

**运行环境：** Windows & Linux

**正文如题，运行代码照搬文档实例

from bilibili_api import live, sync

room = live.LiveDanmaku(xxxxxxxxxxxx)

@room.on('DANMU_MSG')
async def on_danmaku(event):
    # 收到弹幕
    print(event)

@room.on('SEND_GIFT')
async def on_gift(event):
    # 收到礼物
    print(event)

sync(room.connect())

**Comment by z0z0r4** [comment]
直播全是问题，就算你这么说...你看看issue全是直播

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/pull/430 这里可能修了，我发个release

**Comment by CodFish124** [comment]
> Collaborator

感谢，辛苦啦，目前试着正常了

**Comment by CodFish124** [comment]
解决方案：
https://github.com/Nemo2011/bilibili-api/issues/419#issuecomment-1674558385

**Comment by z0z0r4** [comment]
ok，我处理完最后一点才能发release（
