### ISSUE TITLE
[RuntimeError: This event loop is already running] {使用第一个实例代码出错}

### ISSUE THREAD

**Issue by ifhjl** [Nemo2011/bilibili-api#428]
**Python 版本：** 3.10.11

**模块版本：** 15.5.3

**运行环境：** Windows

---

在使用代码：
`import asyncio
from bilibili_api import video

async def main() -> None:
    # 实例化 Video 类
    v = video.Video(bvid="BV1uv411q7Mv")
    # 获取信息
    info = await v.get_info()
    # 打印信息
    print(info)

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())`

即实例1中的代码时出现问题，无法修改：

RuntimeError                              Traceback (most recent call last)
[c:\Users\](file:///C:/Users/)黄健朗\Desktop\2023暑假搞的小玩意\爬虫优化\demo.ipynb 单元格 1 in 1
     [10](vscode-notebook-cell:/c%3A/Users/%E9%BB%84%E5%81%A5%E6%9C%97/Desktop/2023%E6%9A%91%E5%81%87%E6%90%9E%E7%9A%84%E5%B0%8F%E7%8E%A9%E6%84%8F/%E7%88%AC%E8%99%AB%E4%BC%98%E5%8C%96/demo.ipynb#W5sZmlsZQ%3D%3D?line=9)     print(info)
     [12](vscode-notebook-cell:/c%3A/Users/%E9%BB%84%E5%81%A5%E6%9C%97/Desktop/2023%E6%9A%91%E5%81%87%E6%90%9E%E7%9A%84%E5%B0%8F%E7%8E%A9%E6%84%8F/%E7%88%AC%E8%99%AB%E4%BC%98%E5%8C%96/demo.ipynb#W5sZmlsZQ%3D%3D?line=11) if __name__ == '__main__':
---> [13](vscode-notebook-cell:/c%3A/Users/%E9%BB%84%E5%81%A5%E6%9C%97/Desktop/2023%E6%9A%91%E5%81%87%E6%90%9E%E7%9A%84%E5%B0%8F%E7%8E%A9%E6%84%8F/%E7%88%AC%E8%99%AB%E4%BC%98%E5%8C%96/demo.ipynb#W5sZmlsZQ%3D%3D?line=12)     asyncio.get_event_loop().run_until_complete(main())

File [C:\Program](file:///C:/Program) Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py:625, in BaseEventLoop.run_until_complete(self, future)
    614 """Run until the Future is done.
    615 
    616 If the argument is a coroutine, it is wrapped in a Task.
   (...)
    622 Return the Future's result, or raise its exception.
    623 """
    624 self._check_closed()
--> 625 self._check_running()
    627 new_task = not futures.isfuture(future)
    628 future = tasks.ensure_future(future, loop=self)

File [C:\Program](file:///C:/Program) Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py:584, in BaseEventLoop._check_running(self)
    582 def _check_running(self):
    583     if self.is_running():
--> 584         raise RuntimeError('This event loop is already running')
    585     if events._get_running_loop() is not None:
    586         raise RuntimeError(
    587             'Cannot run the event loop while another loop is running')

RuntimeError: This event loop is already running
`RuntimeError                              Traceback (most recent call last)
[c:\Users\](file:///C:/Users/)\demo.ipynb 单元格 1 in 1
     [10](vscode-notebook-cell:/c%3A/Users/%E9%BB%84%E5%81%A5%E6%9C%97/Desktop/2023%E6%9A%91%E5%81%87%E6%90%9E%E7%9A%84%E5%B0%8F%E7%8E%A9%E6%84%8F/%E7%88%AC%E8%99%AB%E4%BC%98%E5%8C%96/demo.ipynb#W5sZmlsZQ%3D%3D?line=9)     print(info)
     [12](vscode-notebook-cell:/c%3A/Users/%E9%BB%84%E5%81%A5%E6%9C%97/Desktop/2023%E6%9A%91%E5%81%87%E6%90%9E%E7%9A%84%E5%B0%8F%E7%8E%A9%E6%84%8F/%E7%88%AC%E8%99%AB%E4%BC%98%E5%8C%96/demo.ipynb#W5sZmlsZQ%3D%3D?line=11) if __name__ == '__main__':
---> [13](vscode-notebook-cell:/c%3A/Users/%E9%BB%84%E5%81%A5%E6%9C%97/Desktop/2023%E6%9A%91%E5%81%87%E6%90%9E%E7%9A%84%E5%B0%8F%E7%8E%A9%E6%84%8F/%E7%88%AC%E8%99%AB%E4%BC%98%E5%8C%96/demo.ipynb#W5sZmlsZQ%3D%3D?line=12)     asyncio.get_event_loop().run_until_complete(main())

File [C:\Program](file:///C:/Program) Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py:625, in BaseEventLoop.run_until_complete(self, future)
    614 """Run until the Future is done.
    615 
    616 If the argument is a coroutine, it is wrapped in a Task.
   (...)
    622 Return the Future's result, or raise its exception.
    623 """
    624 self._check_closed()
--> 625 self._check_running()
    627 new_task = not futures.isfuture(future)
    628 future = tasks.ensure_future(future, loop=self)

File [C:\Program](file:///C:/Program) Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py:584, in BaseEventLoop._check_running(self)
    582 def _check_running(self):
    583     if self.is_running():
--> 584         raise RuntimeError('This event loop is already running')
    585     if events._get_running_loop() is not None:
    586         raise RuntimeError(
    587             'Cannot run the event loop while another loop is running')

RuntimeError: This event loop is already running`

如何解决？？？

**Comment by Drelf2018** [comment]
你的编辑器是什么，用的 `ipython` 之类的吗

**Comment by Drelf2018** [comment]
怎么说呢，你知道异步事件循环也就是 `asyncio` 和 `eventloop` 方面知识吗？如果你知道那我直接说 `Jupyter notebook` 运行就是依靠异步，也就是说他自己给自己开了一个事件循环，再把你的代码放进去跑。但是事件循环内不能再开启新的事件循环，所以就报错了。

相关网页：[使用 Jupyter Notebook 时“无法从正在运行的事件循环中调用 asyncio.run()”](https://segmentfault.com/q/1010000042819896)

**Comment by Drelf2018** [comment]
因此我不推荐使用 `Jupyter notebook` 作为编辑器。

**Comment by ifhjl** [comment]
使用python直接操作可以解决问题，已解决
