### ISSUE TITLE
【提问】直播间礼物统计方法

### ISSUE THREAD

**Issue by cancundeyingzi** [Nemo2011/bilibili-api#43]
请问我想要输出"谢谢熱血赠送的2个辣条、1个PK票",该如何操作?
@room.on('COMBO_SEND')经常触发不动
@room.on('SEND_GIFT')不支持数量统计
`

    from bilibili_api import live, sync
    room = live.LiveDanmaku(2xxxx)
    @room.on('SEND_GIFT')
    async def on_gift1(event):
        礼物名=event['data']['data']['giftName']
        送礼人=event['data']['data']['uname']
        礼物数 = event['data']['data']['num']
        print(送礼人+礼物名+str(礼物数))
    sync(room.connect())

`
具体要求:
1收到礼物后观察n秒,假如n秒内没有收到同一用户的礼物,就print()
2如果在观察的时候再次收到该用户礼物,则重置观察时间(再观察n秒),循环直到执行1
3不同用户的礼物互不干扰,每位用户的观察时间独立
4同一用户多个礼物可以合并一起输出
思考:
1while循环:浪费资源,堵住线程
2新建线程:目标3可能会有问题
3批量创建线程,一位用户一个线程去观察:不会......没找到代码实现方法
全局变量
主线程                                                             子线程
发现礼物创建子线程----------------------------计时n秒
发现礼物,礼物数+x,重启子线程----------------计时n秒
发现礼物,礼物数+x,重启子线程----------------计时n秒
n秒了还没礼物----------------------------------print,结束子线程

**Comment by cancundeyingzi** [comment]
虽然严格说不算是这个模块的问题,但是还是想稍微问下

**Comment by Drelf2018** [comment]
尽管这是个业务代码，不该在这里提问，但我还是稍微写了下
我的运行环境是 Python 3.10 经测试正常运行
```python
import time
from typing import Dict, TypedDict

from apscheduler.schedulers.asyncio import AsyncIOScheduler
from bilibili_api import live, sync


class Gift(TypedDict):
    '''用户赠送礼物列表
    username: 用户名
    last_gift_time: 最后一次赠送礼物时时间戳
    gift_list: 赠送的礼物字典，格式 礼物名: 数量'''
    username: str
    last_gift_time: int
    gift_list: Dict[str, int]

user_list: Dict[int, Gift] = dict()
room = live.LiveDanmaku(21452505)
sched = AsyncIOScheduler(timezone="Asia/Shanghai")  # 定时任务框架

@room.on('SEND_GIFT')
async def on_gift(event):
    '记录礼物'
    info = event['data']['data']
    uid = info['uid']
    user = user_list.get(uid)
    if user:
        # 如果用户列表中有该用户 则更新他的礼物字典以及礼物时间戳
        num = user['gift_list'].get(info['giftName'], 0)
        user['gift_list'][info['giftName']] = num + info['num']
        user['last_gift_time'] = int(time.time())
    else:
        # 不存在则以现在时间及礼物新建 Gift 对象
        user_list[uid] = Gift(
            username=info['uname'],
            last_gift_time=int(time.time()),
            gift_list={info['giftName']: info['num']}
        )
        # 开启一个监控
        sched.add_job(check, 'interval', seconds=1, args=[uid], id=str(uid))

async def check(uid: int):
    '判断是否超过阈值并输出'
    user = user_list.get(uid)
    if user:
        tt = time.time()
        if tt - user.get('last_gift_time', 0) > 5:  # 此处的 5 即需求中的 n 表示秒数
            sched.remove_job(str(uid))  # 移除该监控任务
            print(user_list.pop(uid))  # 将该用户从列表中弹出并打印

if __name__ == '__main__':
    sched.start()  # 启动定时任务
    sync(room.connect())  # 连接直播间
```

**Comment by cancundeyingzi** [comment]
> 尽管这是个业务代码，不该在这里提问，但我还是稍微写了下 我的运行环境是 Python 3.10 经测试正常运行
> 
> ```python
> import time
> from typing import Dict, TypedDict
> 
> from apscheduler.schedulers.asyncio import AsyncIOScheduler
> from bilibili_api import live, sync
> 
> 
> class Gift(TypedDict):
>     '''用户赠送礼物列表
>     username: 用户名
>     last_gift_time: 最后一次赠送礼物时时间戳
>     gift_list: 赠送的礼物字典，格式 礼物名: 数量'''
>     username: str
>     last_gift_time: int
>     gift_list: Dict[str, int]
> 
> user_list: Dict[int, Gift] = dict()
> room = live.LiveDanmaku(21452505)
> sched = AsyncIOScheduler(timezone="Asia/Shanghai")  # 定时任务框架
> 
> @room.on('SEND_GIFT')
> async def on_gift(event):
>     '记录礼物'
>     info = event['data']['data']
>     uid = info['uid']
>     user = user_list.get(uid)
>     if user:
>         # 如果用户列表中有该用户 则更新他的礼物字典以及礼物时间戳
>         num = user['gift_list'].get(info['giftName'], 0)
>         user['gift_list'][info['giftName']] = num + info['num']
>         user['last_gift_time'] = int(time.time())
>     else:
>         # 不存在则以现在时间及礼物新建 Gift 对象
>         user_list[uid] = Gift(
>             username=info['uname'],
>             last_gift_time=int(time.time()),
>             gift_list={info['giftName']: info['num']}
>         )
>         # 开启一个监控
>         sched.add_job(check, 'interval', seconds=1, args=[uid], id=str(uid))
> 
> async def check(uid: int):
>     '判断是否超过阈值并输出'
>     user = user_list.get(uid)
>     if user:
>         if int(time.time()) - user.get('last_gift_time', 0) > 5:  # 此处的 5 即需求中的 n 表示秒数
>             sched.remove_job(str(uid))  # 移除该监控任务
>             print(user_list.pop(uid))  # 将该用户从列表中弹出并打印
> 
> if __name__ == '__main__':
>     sched.start()  # 启动定时任务
>     sync(room.connect())  # 连接直播间
> ```

卧槽,感谢大佬!本来我是想借这里的格式去闲鱼等地方找人问的(毕竟别的地方搞不了这种格式,发出去太乱).没想到居然被回复了!非常感谢!!

**Comment by cancundeyingzi** [comment]
卧槽,这个直播间是你自己的直播间?
https://space.bilibili.com/434334701/

**Comment by Drelf2018** [comment]
> 卧槽,这个直播间是你自己的直播间? https://space.bilibili.com/434334701/

b站关注 [@七海Nana7mi](https://space.bilibili.com/434334701/) 谢谢喵！

**Comment by cancundeyingzi** [comment]
> > 卧槽,这个直播间是你自己的直播间? https://space.bilibili.com/434334701/
> 
> b站关注 [@七海Nana7mi](https://space.bilibili.com/434334701/) 谢谢喵！

?真是本人?????我要给你打137的sc(不是)

**Comment by cancundeyingzi** [comment]
> b站[@七海Nana7mi](https://space.bilibili.com/434334701/)

那我在感谢名单就用这个名字了
话说这代码我有几个不明白的地方

1      第19行sched = AsyncIOScheduler(timezone="Asia/Shanghai")  # 定时任务框架
        按照我的理解是用上海时区,但是这模块为啥要用到时区呢?

2      帮我看看我的代码理解对不对
        info提取获取到的内容,方便下一步.
        uid用户uid.
        user看看列表里有没有这个用户的uid,方便下面if操作
        else创建
        username=info['uname']对应'username': 'xxxxx'
        last_gift_time=int(time.time()),对应'last_gift_time': 1661323025,
        gift_list={info['giftName']: info['num']}对应'gift_list': {'giftName': num}
        如果已有
        num = user['gift_list'].get(info['giftName'], 0)在列表中寻找info里giftName的数量列表里有5辣条,info里又来了辣条,num=5
        user['gift_list'][info['giftName']] = num + info['num']加上该礼物的数量
        user['last_gift_time'] = int(time.time())更新时间
        那如果是新礼物呢?num=0然后[info['giftName']] 直接创建另一个礼物列表么?
        我说怎么找不到判断礼物是否相同的if.

3      他是如何'判断是否超过阈值并输出'的呢?
        check函数运行一次只能判断一次啊,也没有循环.怎么做到5秒钟一过立即print的呢?
        这个sched.add_job是起啥作用?


谢谢大佬!

**Comment by Drelf2018** [comment]
> 这模块为啥要用到时区呢?

可以不用，但是在某些特殊环境（比如我的服务器）中会报一个 `Warning`

> 那如果是新礼物呢?num=0然后[info['giftName']] 直接创建另一个礼物列表么?

是的 `user['gift_list'][info['giftName']] = num + info['num']` 
不仅可以可以更新值，也可以在项不存在时新建项（此处为礼物）

> 他是如何'判断是否超过阈值并输出的呢?

`sched.add_job(check, 'interval', seconds=1, args=[uid], id=str(uid))`

其中 `sched` 是前文提到的 `AsyncIOScheduler()`

它的使用方法可参考 [Python apscheduler安装和基本使用](https://www.coonote.com/python-note/python-apscheduler-install.html)

简单来说就是 `interval` 表示间隔调度任务 其后的 `seconds=1` 表示每间隔 1 秒就执行一次任务

在本代码中用处就是每秒判断一次距离上次送礼有没有超过 5 秒

**Comment by cancundeyingzi** [comment]
> 简单来说就是 `interval` 表示间隔调度任务 其后的 `seconds=1` 表示每间隔 1 秒就执行一次任务
> 
> 在本代码中用处就是每秒判断一次距离上次送礼有没有超过 5 秒

也就是说这个类似于while
time.sleep,但是不会堵塞?
呃.....或者说定时器?

**Comment by cancundeyingzi** [comment]
> ```python
>  print(user_list.pop(uid))  # 将该用户从列表中弹出并打印
> ```

另外我发现一个问题,
 print(user_list.pop(uid))  # 将该用户从列表中弹出并打印
这个写两行就报错,这是啥情况啊
![image](https://user-images.githubusercontent.com/73635883/186391378-c23cacf4-f50d-4884-993f-afdd20c14a67.png)

**Comment by Drelf2018** [comment]
[Python 字典 pop() 方法](https://www.runoob.com/python/python-att-dictionary-pop.html)

> 如果 key 不存在且默认值 default 没有指定 - 触发 KeyError 异常

哥们，这是基础知识啊。为什么写两行就报错是因为这个元素已经被删除了，再 pop 那就报错了。

你可以用一个变量接收 pop 出的元素

```python
whatever = user_list.pop(uid)
out = '谢谢' + whatever['username'] + '赠送的' + '、'.join([str(v) + '个' + k for k, v in whatever['gift_list'].items()])
print(out)
```

**Comment by cancundeyingzi** [comment]
> ```python
> whatever = user_list.pop(uid)
> out = '谢谢' + whatever['username'] + '赠送的' + '、'.join([str(v) + '个' + k for k, v in whatever['gift_list'].items()])
> print(out)
> ```

试过,实测还是报错,所以我才另创函数

**Comment by cancundeyingzi** [comment]
我目前是改成这样了,我最开始也是你这思路,搞一个`xxx=user_list.pop(uid)`
但是还是一堆红,不知道什么情况
```
@room.on('SEND_GIFT')
async def 收到礼物(event):
    '记录礼物'
    info = event['data']['data']#提取获取到的内容,方便下一步.
    uid = info['uid']
    user = user_list.get(uid)#看看列表里有没有这个用户的uid,方便下面if操作
    if user:
        # 如果用户列表中有该用户 则更新他的礼物字典以及礼物时间戳
        num = user['gift_list'].get(info['giftName'], 0)#在列表中寻找info里giftName的数量...列表里有5辣条,info里又来了辣条,num=5
        user['gift_list'][info['giftName']] = num + info['num']#加上该礼物的数量.不仅可以可以更新值，也可以在项不存在时新建项（此处为礼物）
        user['last_gift_time'] = int(time.time())#更新时间
    else:
        # 不存在则以现在时间及礼物新建 Gift 对象
        user_list[uid] = Gift(
            username=info['uname'],
            last_gift_time=int(time.time()),
            gift_list={info['giftName']: info['num']}
        )
        # 开启一个监控
        sched.add_job(监控作业, 'interval', seconds=1, args=[uid], id=str(uid))#args是传进去的参数,id是任务名称
        #其中 sched 是前文提到的 AsyncIOScheduler()它的使用方法可参考 Python apscheduler安装和基本使用简单来说就是 interval 表示间隔调度任务
        # 其后的 seconds=1 表示每间隔 1 秒就执行一次任务在本代码中用处就是每秒判断一次距离上次送礼有没有超过 5 秒
async def 监控作业(uid: int):
    '判断是否超过阈值并输出'
    user = user_list.get(uid)
    if user:
        if int(time.time()) - user.get('last_gift_time', 0) > 5:  # 此处的 5 即需求中的 n 表示秒数
            sched.remove_job(str(uid))  # 移除该监控任务
            礼物输出(user_list.pop(uid))  # 将该用户从列表中弹出并打印
def 礼物输出(礼物数据):
    礼物数量 = str({v: k for k, v in 礼物数据['gift_list'].items()})#反转键值对{'PK票': 2, '辣条': 30}变{2: 'PK票', 30: '辣条'}
    礼物数量 = 礼物数量.replace(': ', '个')
    礼物数量 = 礼物数量.replace('{', '')
    礼物数量 = 礼物数量.replace('}', '')
    out=礼物开头+'('+礼物数据['username']+')送的'+礼物数量+礼物结尾
    thistime = datetime.datetime.now()
    print('\033[1;'+礼物前景+';'+礼物背景+'m'+str(thistime)[0:19] + out)
    语音控制(out)
```
