### ISSUE TITLE
[漏洞] 剧集炸了

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#433]
https://github.com/Nemo2011/bilibili-api/actions/runs/5873861814/job/15927725649#step:5:50

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/67880b9a-9722-4e45-83b0-e84938e61511)

```
        <script id="__NEXT_DATA__" type="application/json">
            {"data": null}
        </script>
```

这么个玩意，我很好奇怎么写正则，麻了

**Comment by z0z0r4** [comment]
出货
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/47afe5b4-8ad8-46dc-ba03-e9fcda48dd0a)

**Comment by z0z0r4** [comment]
判断不是ip问题，香港没事
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/d6c2d140-5481-4d13-be87-601caa7b57ae)

**Comment by z0z0r4** [comment]
没修好...现在很抽象
window.__INITIAL_STATE__ 和 __NEXT_DATA__ 随机出现...未能理解原因所在

**Comment by z0z0r4** [comment]
有建议吗？window.INITIAL_STATE 和 NEXT_DATA 的返回值不同，虽然不暴露，是多次请求取指定一种还是根据获取到的种类分别解析
@Nemo2011 @Drelf2018 
返回值都不会暴露在外，没啥区别

**Comment by Drelf2018** [comment]
返回值不同吗，我粗略看了下好像就是多嵌套了几层 props 啥的，没仔细对比

**Comment by z0z0r4** [comment]
返回值不同，而且正则匹配的也不同...现在随机出新旧版本网页，我也没发现哪个cookie控制...

> 返回值不同吗，我粗略看了下好像就是多嵌套了几层 props 啥的，没仔细对比

**Comment by z0z0r4** [comment]
明天没说法的话我就混合处理了，不打算重新请求拖慢速度（

现在我跑的test就差这个问题

**Comment by z0z0r4** [comment]
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/3d5ffc55-0466-461d-ba7d-2aaf9c6a6ce2)

**Comment by z0z0r4** [comment]
v45.5.4

**Comment by Nemo2011** [comment]
2023.8.31 又炸了

**Comment by z0z0r4** [comment]
> 2023.8.31 又炸了

新旧网页里面的 HTML 数据乱存，已经不敢碰了

next_data / init_state

epid / id

乱的一坨

**Comment by Nemo2011** [comment]
貌似刷不出来INITIAL_STATE了，然后卡住了

**Comment by Nemo2011** [comment]
处理好了
