### ISSUE TITLE
[漏洞] 风控策略收紧

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#435]
https://github.com/Nemo2011/bilibili-api/actions/runs/5874194394/job/15928723251#step:5:834

```
{'code': -401, 'message': '非法访问', 'ttl': 1, 'data': {'ga_data': {'decisions': ['verify_captcha_level2'], 'risk_level': 1, 'grisk_id': '55aa98739b8235bf64ad75d38164dc40', 'decision_ctx': {'buvid': '931081E9D-AE3E-9F5F-9109F-6E1521591018836102infoc', 'decision_type': '4', 'ip': '4.154.90.97', 'mid': '0', 'origin_scene': 'anti_crawler', 'scene': 'anti_crawler', 'ua': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.37', 'v_checkIds': '931081E9D-AE3E-9F5F-9109F-6E1521591018836102infoc', 'v_seconds': '120', 'v_times': '100', 'v_voucher': 'voucher_2c8c3a77-c37a-44f8-8eb5-8e1858e2e5b6'}}}}
```

原因未知，待抓包分析

**Comment by z0z0r4** [comment]
主要影响范围是 `user`

**Comment by z0z0r4** [comment]
目测 `wbi` 类接口反复不带鉴权就能稳定触发此报错

以及 action 凭据已过期，无法作为测试依据... @Nemo2011 

盲猜 WBI 还是算错了...但没有证据，v15.5.4 发不了力

**Comment by z0z0r4** [comment]
在触发 -401 后B站要求人机验证，原因未知...根据是 ip 还是 wbi 鉴权变了引入新参数均未知

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/398fb211-2438-4812-8080-96bf32d0a99c)

**Comment by z0z0r4** [comment]
我心态爆炸了...难道是误报...？

分析了半天它又能跑了，同样没登录，今日活见鬼

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/a1ce2ccc-6b87-4006-9075-7e1e3949dec6)

**Comment by z0z0r4** [comment]
```
{'code': -401, 'message': '非法访问', 'ttl': 1, 'data': {'ga_data': {'decisions': ['verify_captcha_level2'], 'risk_level': 1, 'grisk_id': '28749db067b6b4e3555c2fbc3a64e741', 'decision_ctx': {'buvid': '4BBAA786-E238-3199-F1A5-97150BA859D674037infoc', 'decision_type': '4', 'ip': '', 'mid': '0', 'origin_scene': 'anti_crawler', 'scene': 'anti_crawler', 'ua': 'python-requests/2.31.0', 'v_checkIds': '4BBAA786-E238-3199-F1A5-97150BA859D674037infoc', 'v_seconds': '120', 'v_times': '100', 'v_voucher': 'voucher_c09e27de-5ab1-4ce8-a972-ce7bb1007eb4'}}}}
```

UA 不对为 `verify_captcha_level2` `'risk_level': 1`

**Comment by z0z0r4** [comment]
```{'code': -401, 'message': '非法访问', 'ttl': 1, 'data': {'ga_data': {'decisions': ['verify_captcha_level3'], 'risk_level': 1, 'grisk_id': '69a5bd3d8993ec8d55b3060a1964e743', 'decision_ctx': {'buvid': '068C1858-82ED-1D81-258E-22ECE89B5D9359063infoc', 'decision_type': '4', 'ip': '38.207.148.56', 'mid': '0', 'origin_scene': 'anti_crawler', 'scene': 'anti_crawler', 'ua': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.37', 'v_voucher': 'voucher_fd9f26f1-e1c9-4800-b44a-fce83dc25809'}}}}```

**Comment by iconFehu** [comment]
QwQ所以现在的版本接口可以获取到嘛

**Comment by z0z0r4** [comment]
> QwQ所以现在的版本接口可以获取到嘛

能

**Comment by iconFehu** [comment]
请问是直接拉取dev版本代码测试嘛

**Comment by z0z0r4** [comment]
直接更新 v15.5.5

**Comment by blyc** [comment]
现在最新修复应该还在dev分支没发release，v15.5.5应该是未修复版本吧？

**Comment by z0z0r4** [comment]
sorry 我记混了，是这样的

**Comment by z0z0r4** [comment]
我会在月底前发，看看有没有别的报错一块...

**Comment by SimonFungC** [comment]
> 我会在月底开学前发，看看有没有别的报错一块...
明天开学了，还没发吗

**Comment by SimonFungC** [comment]
明天开学了，还没发吗

**Comment by z0z0r4** [comment]
> 明天开学了，还没发吗

人在广东，台风福利到 9.4 下午

没台风昨晚就发了...今天都入狱了

**Comment by z0z0r4** [comment]
我靠refer错了
