### ISSUE TITLE
[漏洞] 获取用户动态列表报错

### ISSUE THREAD

**Issue by blyc** [Nemo2011/bilibili-api#438]
**Python 版本：** 3.9.16

**模块版本：** 15.5.4

**运行环境：** Windows

**模块路径：** `bilibili_api.user`

**解释器：** cpython / pypi / jython

**报错信息：**

```
接口返回错误代码：4101129，信息：加载错误，请稍后再试。
{'code': 4101129, 'message': '加载错误，请稍后再试', 'ttl': 1}
```

**报错代码：**

```
from bilibili_api import user, sync, Credential

credential = Credential(
    sessdata="XXX",
    bili_jct="XXX",
    buvid3="XXX",
    dedeuserid="XXX"
)
u = user.User(uid=97164600, credential=credential)
sync(u.get_dynamics())

```

---

#432 

更新的接口参数中的offset默认值应为`空字符串`而不是`0`
测试使用现阶段调用该api响应是错误代码`4101129`

**Comment by blyc** [comment]
又测试发现新的api不登录响应错误代码`-352`

```
Traceback (most recent call last):
  File "C:\Users\XXX\Documents\PycharmProjects\XXX\test.py", line 4, in <module>
    sync(u.get_dynamics())
  File "D:\miniconda3\envs\XXX\lib\site-packages\bilibili_api\utils\sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
  File "D:\miniconda3\envs\XXX\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\miniconda3\envs\XXX\lib\site-packages\bilibili_api\user.py", line 499, in get_dynamics
    data = await Api(**api, credential=self.credential).update_params(**params).result
  File "D:\miniconda3\envs\XXX\lib\site-packages\bilibili_api\utils\network_httpx.py", line 159, in result
    self.__result = await self.request()
  File "D:\miniconda3\envs\XXX\lib\site-packages\bilibili_api\utils\network_httpx.py", line 61, in inner
    return await func(*args, **kwargs)
  File "D:\miniconda3\envs\XXX\lib\site-packages\bilibili_api\utils\network_httpx.py", line 310, in request
    raise ResponseCodeException(code, msg, resp_data)
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：-352，信息：-352。
{'code': -352, 'message': '-352', 'ttl': 1}

进程已结束,退出代码1

```

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/pull/439

**Comment by blyc** [comment]
```
import time

from bilibili_api import user, sync, Credential

credential = Credential(
    sessdata="XXX",
    bili_jct="XXX",
    buvid3="XXX",
    dedeuserid="XXX"
)
u = user.User(uid=2, credential=credential)
offset = ''
while True:
    print(f'fetch, offset->{offset}')
    try:
        res = sync(u.get_dynamics_new(offset))
    except BaseException as ex:
        print(ex)
        break
    else:
        for item in res['items']:
            print({
                'dynamic_id': int(item['id_str']),
                'timestamp': item['modules']['module_author']['pub_ts'],
            })
        if not res['has_more']:
            break
        offset = res['offset']
    time.sleep(5)
print("end")

```

个人测试ok，不过`get_dynamics_new`的doc中的`next_offset`应该要改为`offset`了
![图片](https://github.com/Nemo2011/bilibili-api/assets/34291620/f7dbd911-a088-440d-9b11-12ae1efe5b74)
![$Z 9 W(Q@XR%1O7GSUKR8Y](https://github.com/Nemo2011/bilibili-api/assets/34291620/dae85a1c-6f54-4844-aea0-fa5c3905e44c)

**Comment by z0z0r4** [comment]
> ```
> import time
> 
> from bilibili_api import user, sync, Credential
> 
> credential = Credential(
>     sessdata="XXX",
>     bili_jct="XXX",
>     buvid3="XXX",
>     dedeuserid="XXX"
> )
> u = user.User(uid=2, credential=credential)
> offset = ''
> while True:
>     print(f'fetch, offset->{offset}')
>     try:
>         res = sync(u.get_dynamics_new(offset))
>     except BaseException as ex:
>         print(ex)
>         break
>     else:
>         for item in res['items']:
>             print({
>                 'dynamic_id': int(item['id_str']),
>                 'timestamp': item['modules']['module_author']['pub_ts'],
>             })
>         if not res['has_more']:
>             break
>         offset = res['offset']
>     time.sleep(5)
> print("end")
> 
> ```
> 
> 个人测试ok，不过`get_dynamics_new`的doc中的`next_offset`应该要改为`offset`了
> ![图片](https://github.com/Nemo2011/bilibili-api/assets/34291620/f7dbd911-a088-440d-9b11-12ae1efe5b74)
> ![$Z 9 W(Q@XR%1O7GSUKR8Y](https://github.com/Nemo2011/bilibili-api/assets/34291620/dae85a1c-6f54-4844-aea0-fa5c3905e44c)
> 

好的

~~有点忙，改啥都没过脑子抱歉了~~
