### ISSUE TITLE
【提问】关于添加创作激励稿件收入接口

### ISSUE THREAD

**Issue by JellyBeanXiewh** [Nemo2011/bilibili-api#44]
**Python 版本：** 3.9

**模块版本：** 12.1.0

**运行环境：** Windows

---

假设我想添加一个接口用于获取创作激励的稿件收入信息，我应当将其加入User类吗？还是应该将创作中心相关接口单独作为一个模块？

**Comment by Nemo2011** [comment]
可以加入 `user.py` 模块, 但是不要加入 `User` 类。
