### ISSUE TITLE
[提问] {关于使用弹幕获取模块无法得到全部弹幕}

### ISSUE THREAD

**Issue by ifhjl** [Nemo2011/bilibili-api#440]
**Python 版本：** 3.10.11

**模块版本：** 15.5.3

**运行环境：** Windows 

---

近日在按照文档使用获取弹幕的函数时，虽然确实可以获取到弹幕，当时仅仅是其中的十分之一，甚至更少，下面是两个例子以及代码。

`  sync(ass.make_ass_file_danmakus_protobuf(video.Video("BV1yt4y1Q7SS"), 0, "out.ass"))`

原视频是《敢杀我的马》，这玩意弹幕不可能少吧，但是当我打开ass文件时发现如下内容：

![image](https://github.com/Nemo2011/bilibili-api/assets/111429201/a1bb75f7-89d6-47fb-a8e9-dfb57ba31f4d)

也就是只有900多个弹幕，请问是需要额外设置参数还是什么原因弹幕缺失呢？

**Comment by Drelf2018** [comment]
#248

**Comment by ifhjl** [comment]
> #248

修改代码后报错:'bilibili_api.exceptions.ResponseException.ResponseException: 返回数据类型错误：'
代码如下：
cred = Credential(sessdata=SESSDATA, bili_jct=BILI_JCT)

dt = datetime.date(2022, 5, 5)

sync(ass.make_ass_file_danmakus_protobuf(video.Video("BV1yt4y1Q7SS",credential= cred), 0,
                                         out="out.ass", credential=cred,
                                         date=dt))

请大佬指点，感激不尽

**Comment by Drelf2018** [comment]
你的凭据 `cred` 过期了，重新在浏览器里找一下

**Comment by Drelf2018** [comment]
https://nemo2011.github.io/bilibili-api/#/modules/ass

**Comment by ifhjl** [comment]
我看过那个文档了，但是里面写的“获取时间”的意思无法理解，请问是获取这个时间的弹幕还是获取这个时间之前的弹幕，还是获取这个时间之后的弹幕呢？

**Comment by z0z0r4** [comment]
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/27538ece-4ae8-4d33-b560-94b615941e7f)

你可以dui对照着 web 的看看

**Comment by z0z0r4** [comment]
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/c9c5ebde-d238-489a-a321-d43d7cebc975)

**Comment by ifhjl** [comment]
感谢！
