### ISSUE TITLE
[漏洞][需求] session.get_replies

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#442]
https://github.com/Nemo2011/bilibili-api/blob/bb9c7eb13f01340e5299c5445e396af0ebf41019/bilibili_api/session.py#L160-L171C58

参数全不见了，这接口是有游标的 https://message.bilibili.com/#/reply

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/fa74c3f0-9052-4584-a8e0-38d873972df9)
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/a8a6568e-abd9-4618-af7a-029d56fe5be0)

**Comment by z0z0r4** [comment]
at https://api.bilibili.com/x/msgfeed/at 没人@我，我没数据

**Comment by z0z0r4** [comment]
like https://api.bilibili.com/x/msgfeed/like 同理

**Comment by z0z0r4** [comment]
系统通知 https://message.bilibili.com/x/sys-msg/query_notify_list

**Comment by Drelf2018** [comment]
reply 的 id 参数是什么，不加不也能获取到数据吗？

**Comment by z0z0r4** [comment]
> reply 的 id 参数是什么，不加不也能获取到数据吗？

不传你分页没了

**Comment by z0z0r4** [comment]
> reply 的 id 参数是什么，不加不也能获取到数据吗？

reply参数不是有截图吗...cursor里面那俩id和reply_time

**Comment by Drelf2018** [comment]
那你都知道直接改了提交呗，还专门开个 issue 干嘛。

**Comment by z0z0r4** [comment]
> 那你都知道直接改了提交呗，还专门开个 issue 干嘛。

备忘...因为我在急着赶个别的东西

**Comment by z0z0r4** [comment]
> [api.bilibili.com/x/msgfeed/at](https://api.bilibili.com/x/msgfeed/at)

emmm，你有号吗...我没法测试 @ 的那个接口

**Comment by z0z0r4** [comment]
没人@我，触发不了分页
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/e804d052-755a-4ed7-9d90-98df8235ea98)

**Comment by z0z0r4** [comment]
> 系统通知 [message.bilibili.com/x/sys-msg/query_notify_list](https://message.bilibili.com/x/sys-msg/query_notify_list)系统通知 message.bilibili.com/x/sys-msg/query_notify_list

太杂不做
