### ISSUE TITLE
[需求] 视频分享接口

### ISSUE THREAD

**Issue by blyc** [Nemo2011/bilibili-api#446]
翻看了video模块和issues，似乎都没提到视频分享这个接口，不知是否会考虑实现？
[BAC链接](https://socialsisteryi.github.io/bilibili-API-collect/docs/video/action.html#%E5%88%86%E4%BA%AB%E8%A7%86%E9%A2%91-web%E7%AB%AF)

**Comment by z0z0r4** [comment]
可以有，但是很想知道是用在哪个页面的…也想不出用途，看返回示例就一个计数，能做啥？

**Comment by z0z0r4** [comment]
![Screenshot_20230821_173658.jpg](https://github.com/Nemo2011/bilibili-api/assets/78744121/ed50ef68-8e13-40d1-9add-907bbacf4159)

没能理解意义…哪里有统计总分享还是？

**Comment by blyc** [comment]
> ![Screenshot_20230821_173658.jpg](https://user-images.githubusercontent.com/78744121/261983349-ed50ef68-8e13-40d1-9add-907bbacf4159.jpg)
> 
> 没能理解意义…哪里有统计总分享还是？

就单纯是对视频的一个操作，对应 点赞/投币/三连 这样的三个操作接口
![图片](https://github.com/Nemo2011/bilibili-api/assets/34291620/ebd7ca5c-13c2-40b5-8abb-d68e6fa6a381)

**Comment by blyc** [comment]
至于说 分享 的数据获取，是在视频信息接口就有的
![图片](https://github.com/Nemo2011/bilibili-api/assets/34291620/c15d49c9-b299-476e-a590-8b213ee6b56d)
![图片](https://github.com/Nemo2011/bilibili-api/assets/34291620/3f8c29b4-2748-42df-beb5-877a32565e8b)

**Comment by z0z0r4** [comment]
> 至于说 分享 的数据获取，是在视频信息接口就有的
> ![图片](https://github.com/Nemo2011/bilibili-api/assets/34291620/c15d49c9-b299-476e-a590-8b213ee6b56d)
> ![图片](https://github.com/Nemo2011/bilibili-api/assets/34291620/3f8c29b4-2748-42df-beb5-877a32565e8b)
> 

行，明白了…我以为视频里面那个跟着三连的分享接口，会更区分用户来源和去向的…没怀疑它

**Comment by blyc** [comment]
> #448

个人测试没有问题，感谢
