### ISSUE TITLE
[提问] {请问有没有可以获取up主某个视频列表的所有av号的接口呢？}

### ISSUE THREAD

**Issue by ifhjl** [Nemo2011/bilibili-api#449]
如题

**Comment by ifhjl** [comment]
比如说这个up主的这个列表中的av号，如何获取呢？
![image](https://github.com/Nemo2011/bilibili-api/assets/111429201/8660a8b9-b023-4478-bcc6-2ecea42f580d)

**Comment by ifhjl** [comment]
okok，感谢大佬

**Comment by z0z0r4** [comment]
> `user`模块下`get_channel_list()`获取到用户的合集列表（_即视频列表列表，~奇怪的名字~_）， 从返回数据的`seasons_list`或`series_list`中项目的meta拿到对应的`seasons_id`或`series_id`,即视频列表id（下图一）， 根据id类型的不同调用`user`模块对应的接口`get_channel_videos_season()`或`get_channel_videos_series()`，返回值是视频列表（下图二）
> 
> ![图一](https://user-images.githubusercontent.com/34291620/262197233-7f4fff1d-ba10-463c-a33a-9e84e7ce7e40.png)
> 
> ![图二](https://user-images.githubusercontent.com/34291620/262197924-e7aa61ba-b767-49c4-bb5d-c6675dd2d1be.png)

qeq 马上开学断网断电坐牢，急需大佬这样的人才来解决这种 issue

**Comment by blyc** [comment]
> > `user`模块下`get_channel_list()`获取到用户的合集列表（_即视频列表列表，~奇怪的名字~_）， 从返回数据的`seasons_list`或`series_list`中项目的meta拿到对应的`seasons_id`或`series_id`,即视频列表id（下图一）， 根据id类型的不同调用`user`模块对应的接口`get_channel_videos_season()`或`get_channel_videos_series()`，返回值是视频列表（下图二）
> > ![图一](https://user-images.githubusercontent.com/34291620/262197233-7f4fff1d-ba10-463c-a33a-9e84e7ce7e40.png)
> > ![图二](https://user-images.githubusercontent.com/34291620/262197924-e7aa61ba-b767-49c4-bb5d-c6675dd2d1be.png)
> 
> qeq 马上开学断网断电坐牢，急需大佬这样的人才来解决这种 issue

大佬真谈不上，毕竟没学python，所以之前才只提issue不pr；
不过watch项目了，能力范围内的我倒确实可以解决下

**Comment by z0z0r4** [comment]
> > > `user`模块下`get_channel_list()`获取到用户的合集列表（_即视频列表列表，~奇怪的名字~_）， 从返回数据的`seasons_list`或`series_list`中项目的meta拿到对应的`seasons_id`或`series_id`,即视频列表id（下图一）， 根据id类型的不同调用`user`模块对应的接口`get_channel_videos_season()`或`get_channel_videos_series()`，返回值是视频列表（下图二）
> > > ![图一](https://user-images.githubusercontent.com/34291620/262197233-7f4fff1d-ba10-463c-a33a-9e84e7ce7e40.png)
> > > ![图二](https://user-images.githubusercontent.com/34291620/262197924-e7aa61ba-b767-49c4-bb5d-c6675dd2d1be.png)
> > 
> > qeq 马上开学断网断电坐牢，急需大佬这样的人才来解决这种 issue
> 
> 大佬真谈不上，毕竟没学python，所以之前才只提issue不pr；
> 不过watch项目了，能力范围内的我倒确实可以解决下

thx
