### ISSUE TITLE
【漏洞】{音频区文件获取报错}

### ISSUE THREAD

**Issue by MareDevi** [Nemo2011/bilibili-api#45]
**Python 版本：3.10.6** / **NodeJS 版本：16**

**模块版本：** python(python/JS&TS)

**运行环境：** Linux

**模块路径：** `bilibili_api.audio, sync, get_session

**解释器(Python)：** cpython

**报错信息：**

```
AttributeError: 'bytes' object has no attribute 'read'```

**报错代码：**

```
这里填写报错代码
```

---

chunk = await resp.content.read(1024)

**Comment by Nemo2011** [comment]
这里的 RESP 不是 `aiohttp.ClientSession.request` 的 response, 是 `httpx.AsyncClient.request`  的 response, 直接用 resp.iter_bytes 就行了。

**Comment by Nemo2011** [comment]
是用的示例代码吗？

``` python
from bilibili_api import audio, sync, get_session
import os

AUDIO_LIST_ID = 10624

async def main():
    # 获取歌单歌曲列表
    al = audio.AudioList(AUDIO_LIST_ID)
    audios = []
    p = 1

    while True:
        l = await al.get_song_list(p)
        audios.extend(l['data'])
        if l['pageCount'] >= p:
            break

        p += 1

    sess = get_session()

    # 创建歌单文件夹
    if not os.path.exists(str(AUDIO_LIST_ID)):
        os.mkdir(str(AUDIO_LIST_ID))

    for au in audios:
        # 下载歌曲
        file = f"{AUDIO_LIST_ID}/{au['id']} - {au['title']}.m4a"
        a = audio.Audio(au['id'])
        url = await a.get_download_url()
        url = url['cdns'][0]
        print(f"下载 {au['title']}")
        resp = await sess.get(url, headers={
            "User-Agent": "Mozilla/5.0",
            "Referer": "https://www.bilibili.com/"
        })
        with open(file, 'wb') as f:
            for chunk in resp.iter_bytes(1024):
                if not chunk:
                    break

                f.write(chunk)


sync(main())
```

**Comment by MareDevi** [comment]
> 是用的示例代码吗？
> 
> ```python
> from bilibili_api import audio, sync, get_session
> import os
> 
> AUDIO_LIST_ID = 10624
> 
> async def main():
>     # 获取歌单歌曲列表
>     al = audio.AudioList(AUDIO_LIST_ID)
>     audios = []
>     p = 1
> 
>     while True:
>         l = await al.get_song_list(p)
>         audios.extend(l['data'])
>         if l['pageCount'] >= p:
>             break
> 
>         p += 1
> 
>     sess = get_session()
> 
>     # 创建歌单文件夹
>     if not os.path.exists(str(AUDIO_LIST_ID)):
>         os.mkdir(str(AUDIO_LIST_ID))
> 
>     for au in audios:
>         # 下载歌曲
>         file = f"{AUDIO_LIST_ID}/{au['id']} - {au['title']}.m4a"
>         a = audio.Audio(au['id'])
>         url = await a.get_download_url()
>         url = url['cdns'][0]
>         print(f"下载 {au['title']}")
>         resp = await sess.get(url, headers={
>             "User-Agent": "Mozilla/5.0",
>             "Referer": "https://www.bilibili.com/"
>         })
>         with open(file, 'wb') as f:
>             for chunk in resp.iter_bytes(1024):
>                 if not chunk:
>                     break
> 
>                 f.write(chunk)
> 
> 
> sync(main())
> ```

好的，成功了，谢谢大佬
