### ISSUE TITLE
[需求] 当前接口回复私信信息过长

### ISSUE THREAD

**Issue by luofengda** [Nemo2011/bilibili-api#452]
**Python 版本：** 3.x.y

**模块版本：** x.y.z

**运行环境：** Windows / Linux / MacOS

---

同样的私信内容，
使用该库会提示：内容过长
使用web端回复，显示正常

**Comment by luofengda** [comment]
内容超过500个字

**Comment by Drelf2018** [comment]
给管人发小作文呢这么多字？

**Comment by luofengda** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by luofengda** [comment]
已用web接口了。只是给提出来而已。改不改都没事

**Comment by z0z0r4** [comment]
> 已用web接口了。只是给提出来而已。改不改都没事

能顺手发下接口的url吗

**Comment by z0z0r4** [comment]
方便的画我去改下

**Comment by luofengda** [comment]
https://api.vc.bilibili.com/web_im/v1/web_im/send_msg

**Comment by z0z0r4** [comment]
神奇了...现在用的不就是这个吗...

我明天测试下到底调用当前接口会不会500字限制，有截图报错吗？

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/ef97c694-b941-4c37-938a-00b579637714)


> [api.vc.bilibili.com/web_im/v1/web_im/send_msgapi.vc.bilibili.com/web_im/v1/web_im/send_msg](https://api.vc.bilibili.com/web_im/v1/web_im/send_msg)

**Comment by Drelf2018** [comment]
> 内容超过500个字

![image](https://github.com/Nemo2011/bilibili-api/assets/41439182/c99df43d-e7c1-4073-b33d-69113d403b2e)

我倒是想知道web怎么发出去超过500个字的

**Comment by z0z0r4** [comment]
> > 内容超过500个字
> 
> ![image](https://user-images.githubusercontent.com/41439182/263349094-c99df43d-e7c1-4073-b33d-69113d403b2e.png)
> 
> 我倒是想知道web怎么发出去超过500个字的

加几个字看看重放？逆天 ~~我去，编辑到你的了~~

**Comment by z0z0r4** [comment]
我宣布这个issue的前提就是个伪命题，并没有接口能发送500字以上

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/babdfc59-c30c-46fe-9278-b85e30401313)
