### ISSUE TITLE
feat: watchroom.watchroom

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#454]
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/125030b3-bcd1-4451-b87d-ccae8702fcdb)
有人来 dev 分支测试下 watchroom 能不能用吗...限制比较多有点慌...时不时炸

_Originally posted by @z0z0r4 in https://github.com/Nemo2011/bilibili-api/issues/453#issuecomment-1696689382_

**Comment by z0z0r4** [comment]
action 出错测试项目：
- tests.test_album.test_c_get_homepage_albums
- tests.test_album.test_d_get_recommend_uppers
- tests.test_video.test_d_Video_get_stat
- tests.test_channel.test_h_get_channel_videos_by_order
- tests.test_root_functions.test_a_parse_link

**Comment by z0z0r4** [comment]
get_stat 是B站在做播放时长吧...

403 api.bilibili.com/archive_stat/stat

**Comment by Drelf2018** [comment]
https://github.com/Nemo2011/bilibili-api/blob/2a519f8b1264d887846054a55097bbbc57321e53/bilibili_api/watchroom.py#L220

这句可以

```python
{"content": '{"text":"%s"}' % msg}
```

**Comment by z0z0r4** [comment]
> https://github.com/Nemo2011/bilibili-api/blob/2a519f8b1264d887846054a55097bbbc57321e53/bilibili_api/watchroom.py#L220
> 
> 这句可以
> 
> ```python
> {"content": '{"text":"%s"}' % msg}
> ```

有道理，我 printf 不行直接急了

**Comment by z0z0r4** [comment]
how...

https://github.com/Nemo2011/bilibili-api/actions/runs/5982732067/job/16232136629#step:5:787 

ss 界面里的NEXT_DATA没返回对应epid，我要炸了，不会得 bs4 吧

**Comment by z0z0r4** [comment]
正则吧... (<link rel="canonical" href="//www.bilibili.com/bangumi/play/ep678061"/>)

**Comment by z0z0r4** [comment]
又tm改键了，B站的后端都缺少点啥吧...
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/92fd26fa-bf3d-48a3-bda6-0c1cf39e99e5)
