### ISSUE TITLE
[公告] `h.bilibili.com` 内接口已下线

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#458]
https://h.bilibili.com/ 直接进去看吧，没了已经

@Nemo2011 @Drelf2018 有先例吗...这种下线的接口怎么处理，删还是注释掉？总不能留着等测试 failed 吧

我提议是留下接口 JSON 信息但删除 py 源码

**Comment by Drelf2018** [comment]
你要删的话主版本号要加一，可以缓缓，多攒点破坏修改一次发

**Comment by z0z0r4** [comment]
已经多了个 watchroom 了挺多的，姑且感觉有必要 v16

接口炸了就算不破坏性更新 album 也用不了吧...感觉这规则不太适用于接口抓包之类的库

**Comment by Drelf2018** [comment]
破坏更新是指原来的代码用不了了，如果之前有的代码里有相关函数，函数被删掉了如果不更新大版本，更新之后运行就会报错找不到函数

**Comment by z0z0r4** [comment]
> 破坏更新是指原来的代码用不了了，如果之前有的代码里有相关函数，函数被删掉了如果不更新大版本，更新之后运行就会报错找不到函数

我打算更新大版本，搞定那几个action 报错之后，没空等了

**Comment by Drelf2018** [comment]
这个接口删掉了吗，删了我就关了啊
