### ISSUE TITLE
【漏洞】python 3.9 api版本12.1.0 ，上传视频报错，一直显示分块上传失败

### ISSUE THREAD

**Issue by guyu818** [Nemo2011/bilibili-api#46]
Python 版本：3.9
模块版本：bilibili-api-python 12.1.0
报错信息：
{'name': 'PRE_CHUNK', 'data': {'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x117db95b0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 1}}
{'name': 'CHUNK_FAILED', 'data': {'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x117db95b0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 1, 'info': '分块上传失败'}}

**报错代码：**

    credential = video_uploader.Credential(sessdata=SESSDATA, bili_jct=BILI_JCT, buvid3=BUVID3)

    # 具体请查阅相关文档
    meta = {
           "copyright": 2,
           "source": v_url,
           "cover": v_cover,
           "desc": v_desc,
           "desc_format_id": 0,
           "dynamic": "自动化上传测试",
           "interactive": 0,
           "open_elec": 1,
           "no_reprint": 1,
           "subtitles": {
               "lan": "",
               "open": 1
           },
           "tag": ','.join(v_tag),
           "tid": 171,
           "title": v_title,
           "up_close_danmaku": False,
           "up_close_reply": False
        }
    page = video_uploader.VideoUploaderPage(path=video_path, title=v_title, description=v_desc)
    uploader = video_uploader.VideoUploader([page], meta, credential, v_cover)

在此处写正文

**Comment by Naxrin** [comment]
> 
[新建 文本文档 (3).txt](https://github.com/Nemo2011/bilibili-api/files/9558406/3.txt)您好，我想请教一下，我也遇到了一样的问题，代码抄的示例且根据新api做了适配，credential确认没问题，可以点赞评论发动态，视频也不是很大只有80M，但跑了5分钟一个分片都上不去，我应该怎么做呢？会不会是被服务器那边阻止了？
