### ISSUE TITLE
[提问] 直播弹幕事件：直播间人气更新接口可能需要更换

### ISSUE THREAD

**Issue by jhzgjhzg** [Nemo2011/bilibili-api#481]
**Python 版本：** 3.9.16

**模块版本：** 15.5.5

**运行环境：** MacOS

---

多次测试中，此事件返回数据类似
```
{'data': 1,
 'room_display_id': 25512443,
 'room_real_id': 25512443,
 'type': 'VIEW'}
```
其中data关键字恒为1

**Comment by z0z0r4** [comment]
给下函数名称？（这算是接口弃用了…？

**Comment by jhzgjhzg** [comment]
> 给下函数名称？（这算是接口弃用了…？

[class LiveDanmaku](https://nemo2011.github.io/bilibili-api/#/modules/live?id=class-livedanmaku)里的事件，我是从昨天开始发现返回的数据不对，更早就不知道了

**Comment by z0z0r4** [comment]
我测试下，虽然事实上除了没登录以外我猜不到别的原因

**Comment by jhzgjhzg** [comment]
> 我测试下，虽然事实上除了没登录以外我猜不到别的原因
> 
> 显然返回的就是这个数据，如果确实一直为 1 那也没啥可做的

我换了几个直播间，登录没登录都测过了，应该是接口下线了

**Comment by z0z0r4** [comment]
不了解直播，我的评价是 @Drelf2018

**Comment by z0z0r4** [comment]
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/28235dc3-04b5-464e-a62d-696f1dccfd37)

**Comment by z0z0r4** [comment]
![ebcbb483779e73bf17ad9f7965bc551f](https://github.com/Nemo2011/bilibili-api/assets/78744121/538fe42f-1965-4a24-a51f-7e5469059f06)

问问，B 站直播间热度在哪里...哪个位置写着热度... 我找都找不到

**Comment by Drelf2018** [comment]
不报错没必要删

**Comment by z0z0r4** [comment]
话说是不是有很多 CMD 压根没列出来

**Comment by jhzgjhzg** [comment]
> ![ebcbb483779e73bf17ad9f7965bc551f](https://user-images.githubusercontent.com/78744121/265205718-538fe42f-1965-4a24-a51f-7e5469059f06.png)
> 
> 问问，B 站直播间热度在哪里...哪个位置写着热度... 我找都找不到

emm...我猜是这个？
<img width="289" alt="截屏2023-09-02 20 58 18" src="https://github.com/Nemo2011/bilibili-api/assets/101122762/6b3908a2-9975-4c07-ab31-2b360ac6b42c">

**Comment by z0z0r4** [comment]
> > ![ebcbb483779e73bf17ad9f7965bc551f](https://user-images.githubusercontent.com/78744121/265205718-538fe42f-1965-4a24-a51f-7e5469059f06.png)
> > 问问，B 站直播间热度在哪里...哪个位置写着热度... 我找都找不到
> 
> emm...我猜是这个？ <img alt="截屏2023-09-02 20 58 18" width="289" src="https://user-images.githubusercontent.com/101122762/265205921-6b3908a2-9975-4c07-ab31-2b360ac6b42c.png">

你也不知道...？那这个issue可以关了，这个榜单我记得在 `rank` 里面
