### ISSUE TITLE
[???]

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#483]
wc 16.0.0 什么时候发的，这不科学我四小时前在打 csgo ，怎么是我的署名，有 2fa

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/9f489353-8795-472b-a69f-e3636d6fc601)

**Comment by z0z0r4** [comment]
给盗号了？我只打了 draft release

**Comment by Nemo2011** [comment]
我发的啊

**Comment by Nemo2011** [comment]
？？？

**Comment by Drelf2018** [comment]
@Nemo2011 可以给我协助者吗，我改代码会方便点

**Comment by Nemo2011** [comment]
难道`v16`还有其他要更新的吗？我看`changelog`、`BILIBILI_API_VERSION`、`setup.py`都写好了

**Comment by z0z0r4** [comment]
> 难道`v16`还有其他要更新的吗？我看`changelog`、`BILIBILI_API_VERSION`、`setup.py`都写好了

eeeeeee，是你发的？我以为号被盗了

姑且有个必须传 uid 的 cookie 很无语…不过算了吧
