### ISSUE TITLE
[建议] 可以在 PyPI 开一个 bilibili-api-dev 的仓库

### ISSUE THREAD

**Issue by Drelf2018** [Nemo2011/bilibili-api#484]
`main` 分支每次 release 会自动发布到 `bilibili-api-python`，同样让 `dev` 分支也能发布一个。

每次在 `dev` 解决完漏洞还没提交到 `main` 的时候，就可以用 `dev` 发一个 `beta` 的 `release` 。

这个 `release` 就可以提供给用户测试修改后的代码能否解决问题。

也可以给那些喜欢尝鲜版的用户用。

```python
pip install bilibili-api-dev
```

实现方法我研究过了，只要改这一行：

https://github.com/Nemo2011/bilibili-api/blob/7d2a52c5c6ebdd707e35d5e2a831aa5147bbdc5f/setup.py#L10

```python
 name="bilibili-api-dev", 
```

然后发 `release` 的时候选择 `dev` 分支就行。

![image](https://github.com/Nemo2011/bilibili-api/assets/41439182/a36ccbdf-a42a-403b-b3a5-90c4095dde0e)

**Comment by Drelf2018** [comment]
我在自己的仓库已经实现了 1697e118cdbd0676c3631b1302bf1e5a2e199c8a 也就是说现在 `bilibili-api-dev` 是基于我的 fork 仓库的 `dev` 分支发布的，可以通过 pr 转到本仓库。

**Comment by z0z0r4** [comment]
支持，这库需要 nightly

**Comment by Nemo2011** [comment]
建议pre-release的版本号具体到提交，否则一个版本几十个commits也命名不过来

**Comment by Drelf2018** [comment]
意思是类似 `16.0.1-beta.0-1697e11` 这样吗？

**Comment by Nemo2011** [comment]
是的

**Comment by Nemo2011** [comment]
就是不知道pypi的自动排序会不会出问题

**Comment by Drelf2018** [comment]
恐怕不行，我看pypi的版本号就是 `x.y.z(a|b|rc)w` 我昨天发的 `v16.0.1-beta.1` 他都自动化成了 `16.0.1b1`

**Comment by z0z0r4** [comment]
不能新开pypi项目吗？

**Comment by z0z0r4** [comment]
建议把 `bilibili-api-dev` 公告出来

**Comment by Drelf2018** [comment]
我又想了想，感觉这个 `dev` 库没必要啊，测试版直接发 `python` 库不就好了

**Comment by z0z0r4** [comment]
> 我又想了想，感觉这个 `dev` 库没必要啊，测试版直接发 `python` 库不就好了

很不稳定吧这样

**Comment by z0z0r4** [comment]
是不是可以关了...
