### ISSUE TITLE
[漏洞] user.get_user_info 接口返回错误代码：-401，信息：非法访问。

### ISSUE THREAD

**Issue by SimonFungC** [Nemo2011/bilibili-api#488]
**Python 版本：** 3.11.4

**模块版本：** 16.0.0 

**运行环境：**  MacOS

**模块路径：** `bilibili_api.xxxx`

**解释器：** cpython / pypi / jython

**报错信息：**

```
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：-401，信息：非法访问。
{'code': -401, 'message': '非法访问', 'ttl': 1, 'data': {'ga_data': {'decisions': ['verify_captcha_level2'], 'risk_level': 1, 'grisk_id': '6db0660df4fac6827404e32c1864f584', 'decision_ctx': {'buvid': '91E9D-AE3E-9F5F-9109F-6E1521591018836102infoc', 'decision_type': '4', 'ip': '219.136.74.50', 'mid': '0', 'origin_scene': 'anti_crawler', 'scene': 'crawler_main_space_wbi_acc_info', 'ua': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.37', 'v_voucher': 'voucher_e96123da-5a72-4fcd-87ce-23d2e37bedcf'}}}}
```

**报错代码：**

```
 user_info = await u.get_user_info()

```

---

<img width="1625" alt="image" src="https://github.com/Nemo2011/bilibili-api/assets/3145760/a1bade9a-d088-4a63-a4ca-f4178ed2c26c">

**Comment by Drelf2018** [comment]
代码给全，`u` 是怎么定义的？

**Comment by SimonFungC** [comment]
> 

`# https://github.com/Nemo2011/bilibili-api

import asyncio

from bilibili_api import user
from bilibili_api import video as video_m, exceptions

import time
import os
import csv


class BilibiliSpider:

    def __init__(self, options=None):
        # 是否保存csv文件
        self.is_save_csv = False

    def get_info(self, uid):
        return asyncio.run(self.get_info_asyncio(uid))

    async def get_info_asyncio(self, uid):
        info_dict = {}
        # uid转换int
        u = user.User(int(uid), None)

        # 获取用户信息
        user_info = await u.get_user_info()
        info_dict["uid"] = str(uid)
        info_dict["用户名"] = user_info["name"]
        info_dict["性别"] = user_info["sex"]
        info_dict["头像地址"] = user_info["face"]
        info_dict["签名"] = user_info["sign"]
        info_dict["等级"] = user_info["level"]
        info_dict["生日"] = user_info["birthday"]
        info_dict["认证信息"] = user_info["official"]["title"]

        # 获取粉丝数和关注数
        relation_info = await u.get_relation_info()
        info_dict["粉丝数"] = relation_info["follower"]
        info_dict["关注数"] = relation_info["following"]
        # print(relation_info)

        return info_dict

    def get_works(self, uid, pages=1):
        return asyncio.run(self.get_works_asyncio(uid))

    async def get_works_asyncio(self, uid):

        u = user.User(int(uid), None)

        # 获取视频列表
        video_list = []

        sizes = 10
        video_list_res = (await u.get_videos(0, 1, sizes, ''))['list']['vlist']

        for item in video_list_res:
            video = video_m.Video(aid=item['aid'])

            # 创建视频对象
            video_dict = {}

            # 视频基础信息
            video_dict['id'] = item['aid']
            video_dict['标题'] = item['title']
            video_dict['描述'] = item['description']
            video_dict['作者'] = item['author']
            video_dict['作品地址'] = 'https://www.bilibili.com/video/' + video.get_bvid()
            video_dict['视频长度'] = item['length']
            create_time = item['created']
            video_dict['上传时间'] = time.strftime("%Y-%m-%d %H:%M", time.localtime(create_time))
            video_dict['上传时间戳'] = create_time

            # 视频统计
            video_stat = await video.get_stat()
            # print(video_stat)
            video_dict['观看次数'] = video_stat['view']
            video_dict['弹幕次数'] = video_stat['danmaku']
            video_dict['点赞次数'] = video_stat['like']
            video_dict['投币次数'] = video_stat['coin']
            video_dict['收藏次数'] = video_stat['favorite']
            video_dict['转发次数'] = video_stat['share']
            #
            # 视频标签
            video_tags_res = await video.get_tags()
            video_tags = []
            for item in video_tags_res:
                video_tags.append(item['tag_name'])
            video_dict['标签'] = ', '.join(str(item) for item in video_tags)

            video_list.append(video_dict)

        return video_list

    # 将视频列表写入到csv
    def write_csv(self, full_path, reviews):
        title = reviews[0].keys()
        path, file_name = os.path.split(full_path)

        if os.path.exists(full_path):
            with open(full_path, 'a+', newline='', encoding='utf-8-sig') as f:
                writer = csv.DictWriter(f, title)
                writer.writerows(reviews)
        else:
            try:
                os.mkdir(path)
            except Exception:
                print('路径已存在，或未获得建立路径的权限。请检查路径是否存在，或手动建立路径。')
            with open(full_path, 'a+', newline='', encoding='utf-8-sig') as f:
                writer = csv.DictWriter(f, title)
                writer.writeheader()
                writer.writerows(reviews)

    def spider(self, uid):
        self.get_works(uid)


if __name__ == '__main__':

    bilibili_spider = BilibiliSpider()
    print(bilibili_spider.get_info(774729))
`

我的代码，  u = user.User(int(774729), None)
user_info = await u.get_user_info()

**Comment by SimonFungC** [comment]
`

import asyncio

from bilibili_api import user
from bilibili_api import video as video_m, exceptions

import time
import os
import csv


class BilibiliSpider:

    def __init__(self, options=None):
        # 是否保存csv文件
        self.is_save_csv = False

    def get_info(self, uid):
        return asyncio.run(self.get_info_asyncio(uid))

    async def get_info_asyncio(self, uid):
        info_dict = {}
        # uid转换int
        u = user.User(int(uid), None)

        # 获取用户信息
        user_info = await u.get_user_info()
        info_dict["uid"] = str(uid)
        info_dict["用户名"] = user_info["name"]
        info_dict["性别"] = user_info["sex"]
        info_dict["头像地址"] = user_info["face"]
        info_dict["签名"] = user_info["sign"]
        info_dict["等级"] = user_info["level"]
        info_dict["生日"] = user_info["birthday"]
        info_dict["认证信息"] = user_info["official"]["title"]

        # 获取粉丝数和关注数
        relation_info = await u.get_relation_info()
        info_dict["粉丝数"] = relation_info["follower"]
        info_dict["关注数"] = relation_info["following"]
        # print(relation_info)

        return info_dict

    def get_works(self, uid, pages=1):
        return asyncio.run(self.get_works_asyncio(uid))

    async def get_works_asyncio(self, uid):

        u = user.User(int(uid), None)

        # 获取视频列表
        video_list = []

        sizes = 10
        video_list_res = (await u.get_videos(0, 1, sizes, ''))['list']['vlist']

        for item in video_list_res:
            video = video_m.Video(aid=item['aid'])

            # 创建视频对象
            video_dict = {}

            # 视频基础信息
            video_dict['id'] = item['aid']
            video_dict['标题'] = item['title']
            video_dict['描述'] = item['description']
            video_dict['作者'] = item['author']
            video_dict['作品地址'] = 'https://www.bilibili.com/video/' + video.get_bvid()
            video_dict['视频长度'] = item['length']
            create_time = item['created']
            video_dict['上传时间'] = time.strftime("%Y-%m-%d %H:%M", time.localtime(create_time))
            video_dict['上传时间戳'] = create_time

            # 视频统计
            video_stat = await video.get_stat()
            # print(video_stat)
            video_dict['观看次数'] = video_stat['view']
            video_dict['弹幕次数'] = video_stat['danmaku']
            video_dict['点赞次数'] = video_stat['like']
            video_dict['投币次数'] = video_stat['coin']
            video_dict['收藏次数'] = video_stat['favorite']
            video_dict['转发次数'] = video_stat['share']
            #
            # 视频标签
            video_tags_res = await video.get_tags()
            video_tags = []
            for item in video_tags_res:
                video_tags.append(item['tag_name'])
            video_dict['标签'] = ', '.join(str(item) for item in video_tags)

            video_list.append(video_dict)

        return video_list

    # 将视频列表写入到csv
    def write_csv(self, full_path, reviews):
        title = reviews[0].keys()
        path, file_name = os.path.split(full_path)

        if os.path.exists(full_path):
            with open(full_path, 'a+', newline='', encoding='utf-8-sig') as f:
                writer = csv.DictWriter(f, title)
                writer.writerows(reviews)
        else:
            try:
                os.mkdir(path)
            except Exception:
                print('路径已存在，或未获得建立路径的权限。请检查路径是否存在，或手动建立路径。')
            with open(full_path, 'a+', newline='', encoding='utf-8-sig') as f:
                writer = csv.DictWriter(f, title)
                writer.writeheader()
                writer.writerows(reviews)

    def spider(self, uid):
        self.get_works(uid)


if __name__ == '__main__':

    bilibili_spider = BilibiliSpider()
    print(bilibili_spider.get_info(774729))

`

u = user.User(int(uid), None)
user_info = await u.get_user_info()
这是我的代码。

**Comment by Drelf2018** [comment]
我本地可以正常运行，你是不是开了梯子？

**Comment by SimonFungC** [comment]
是我本机anaconda锁了项目的版本。 在服务器上upgreade试了可以
