### ISSUE TITLE
[漏洞] dynamic模块url固定无法改参

### ISSUE THREAD

**Issue by blyc** [Nemo2011/bilibili-api#490]
**Python 版本：** 3.9

**模块版本：** 16.0.0

**运行环境：** Windows

**模块路径：** `bilibili_api.dynamic`

**解释器：** cpython / pypi / jython

1.`api/dynamic.json`中`info.dynamic_page_info`的url固定，导致传参无效
![image](https://github.com/Nemo2011/bilibili-api/assets/34291620/1acdcf41-0a33-4e4c-ad68-ca4fd680005f)

2.希望`dynamic.get_dynamic_page_info`和`dynamic.get_info`两个方法开放`features`的传参，目前默认固定为`itemOpusStyle`且不支持传入修改
希望能接受入参，今晚发现两个url的`features`参数传入`itemOpusStyle`或`空字符串`返回格式不同（上午格式还是正常）
参考：(json太长用链接和对比截图代替)
https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?id=837877699193077780&timezone_offset=-480&features=itemOpusStyle
![image](https://github.com/Nemo2011/bilibili-api/assets/34291620/5c5f4801-7166-44dd-8f86-090d704d9b64)
https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?id=837877699193077780&timezone_offset=-480&features=
![image](https://github.com/Nemo2011/bilibili-api/assets/34291620/d1a37ff1-36a6-4122-b901-5f7cacc26955)

**Comment by Drelf2018** [comment]
为啥这个接口会带着参数啊，我去查下 git blame

**Comment by Drelf2018** [comment]
你看下这个提交，要是没别的问题我就合并了

**Comment by blyc** [comment]
测试ok，已解决
