### ISSUE TITLE
[建议] 用户自定义 HTTP 客户端

### ISSUE THREAD

**Issue by Nemo2011** [Nemo2011/bilibili-api#496]
10.2.0 的时候模块是将 `aiohttp.ClientSession` 全部换成了 `httpx.AsyncClient`，但是使用 `aiohttp` 的 `async` 库也不在少数，所以如果模块要与其他使用 `aiohttp` 的库进行交接则会出现 `httpx` 与 `aiohttp` 不兼容的问题。因此这里的想法是让用户选择使用 `aiohttp` 或者是 `httpx` (当然 `websocket` 只能用 `aiohttp`），这样子就能解决兼容上的问题，也有让用户具体情况具体选择的机会。

**Comment by z0z0r4** [comment]
改 `Api` 倒是方便，有的直接拿 `session` 的麻烦

**Comment by Nemo2011** [comment]
总的来说，还是拼测试覆盖率，否则会及其不稳定。

**Comment by z0z0r4** [comment]
> 总的来说，还是拼测试覆盖率，否则会及其不稳定。

爬虫也没法咋提高了吧emm

**Comment by Drelf2018** [comment]
我会了，可以用 `abc.ABCMate` 定义一个抽象的会话类，然后分别用不同的请求模块去实现这个类

**Comment by z0z0r4** [comment]
默认 httpx 吧，我看看咋做 Api 的切换

**Comment by z0z0r4** [comment]
aiohttp 没法在 `ClientSession` 设置代理，麻了，明天再继续

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/8538b28d-ea1e-4124-8671-8e6312b02031)

**Comment by z0z0r4** [comment]
添加 `raw` 参数，返回原始数据...免得特殊 `OK` 状态码这种情况

`OK` 部分我打算在函数里面处理吧，不留在 Api...我明天找找哪个接口加上的

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/8462fdfd-4514-44cc-85e8-4a0703a2fee8)

**Comment by z0z0r4** [comment]
看似已经完成了

**Comment by z0z0r4** [comment]
爆了，原谅我恕不负责

**Comment by z0z0r4** [comment]
看似已经被修了
