### ISSUE TITLE
[提问] room 16.1 版本 未传入凭据

### ISSUE THREAD

**Issue by topcmm** [Nemo2011/bilibili-api#500]
bilibili_api.exceptions.CredentialNoSessdataException.CredentialNoSessdataException: Credential 类未提供 sessdata 或者为空。

**Comment by Drelf2018** [comment]
那你提供一下不就行了吗

**Comment by Nemo2011** [comment]
- 1. 找到定义 `room` 变量的地方。
- 2. 在 `LiveDanmaku` 类初始化的参数中添加 `credential` 项目，传入 `Credential` 类，查询文档了解获取 `Credential` 类参数的步骤。
- 3. 再次 `room.connect`
