### ISSUE TITLE
[提问] 关于直播分区查询

### ISSUE THREAD

**Issue by nankaine** [Nemo2011/bilibili-api#501]
Python 版本：Python 3.9.16

模块版本：bilibili-api-python 16.1.0

运行环境：linux

---

正常请求：
```python
from bilibili_api import live_area

print(live_area.get_area_info_by_name("弹幕互动玩法")[1]) # 不显示主分区信息
```

返回值
```
{'id': '460', 'parent_id': '6', 'old_area_id': '1', 'name': '弹幕互动玩法', 'act_id': '0', 'pk_status': '1', 'hot_status': 0, 'lock_status': '0', 'pic': 'https://i0.hdslb.com/bfs/im/321fe8138b85f38a19f9c18d7be2c7383ee8f8cb.png', 'complex_area_name': '', 'parent_name': '单机游戏', 'area_type': 0}
```
非正常请求
```python
from bilibili_api import live_area

print(live_area.get_area_info_by_name("白夜极光")[1]) # 不显示主分区信息
```

返回值：
None

但是直播分区存在白夜极光分区

使用`def get_area_list()`打印所有的分区，也不存在白夜极光分区。

最后，感谢各位维护API

**Comment by Nemo2011** [comment]
更新数据了，现在应该找得到了

**Comment by blyc** [comment]
看了下这个模块，好奇什么多数接口都是读取静态json而不是接口了？
https://[api.live.bilibili.com/room/v1/Area/getList](https://api.live.bilibili.com/room/v1/Area/getList)

**Comment by z0z0r4** [comment]
> 看了下这个模块，好奇什么多数接口都是读取静态json而不是接口了？ https://[api.live.bilibili.com/room/v1/Area/getList](https://api.live.bilibili.com/room/v1/Area/getList)

仅限部分是读取已有数据，比如分区信息

**Comment by z0z0r4** [comment]
不是实时的，有发现更新就加进去
