### ISSUE TITLE
[漏洞] 上传视频出错

### ISSUE THREAD

**Issue by HowHsu** [Nemo2011/bilibili-api#504]
**Python 版本：** 3.11.5

**模块版本：** 16.1.0

**运行环境：** MacOS

**模块路径：** `bilibili_api.xxxx`

**解释器：** cpython / pypi / jython

**报错信息：**

<img width="1785" alt="image" src="https://github.com/Nemo2011/bilibili-api/assets/38499194/4b8d2f22-dddc-4f0b-a361-51e5fd4841a7">

**报错代码：**

```
这里填写报错代码
```

---

<img width="984" alt="image" src="https://github.com/Nemo2011/bilibili-api/assets/38499194/cef095f5-0ba7-4bd8-a0d0-a908e5329711">

**Comment by z0z0r4** [comment]
dev 分支好了，可以试试看，我不确定没测试

**Comment by z0z0r4** [comment]
没改好甚至炸了，不能理解

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/ce3fe08f-4c19-4055-ad20-a35225f01c96)

**Comment by z0z0r4** [comment]
现在 Web 端用的是 v3 的接口

```python
import requests
params = {
    't': '1694932881344',
    'csrf': '',
}

json_data = {
    'cover': 'https://archive.biliimg.com/bfs/archive/c499c29a371eb3c0ecfac044712e9c8c8dcc9e8b.jpg',
    'title': '2023-09-17 14-27-24',
    'copyright': 1,
    'tid': 231,
    'tag': '编程开发',
    'desc_format_id': 9999,
    'desc': '',
    'recreate': -1,
    'dynamic': '',
    'interactive': 0,
    'videos': [
        {
            'filename': 'n230917qn3qcmhf30gfaz5wm6rua20j0',
            'title': '2023-09-17 14-27-24',
            'desc': '',
            'cid': 1270113250,
        },
    ],
    'act_reserve_create': 0,
    'no_disturbance': 0,
    'no_reprint': 1,
    'subtitle': {
        'open': 0,
        'lan': '',
    },
    'dolby': 0,
    'lossless_music': 0,
    'web_os': 1,
    'csrf': '',
}

response = requests.post(
    'https://member.bilibili.com/x/vu/web/add/v3',
    params=params,
    cookies=cookies,
    headers=headers,
    json=json_data,
)

**Comment by z0z0r4** [comment]
![qq_pic_merged_1694933790182](https://github.com/Nemo2011/bilibili-api/assets/78744121/6e0a6b0c-cc06-4eed-8f30-838e2001845b)

v3

**Comment by z0z0r4** [comment]
需要测试 https://github.com/Nemo2011/bilibili-api/pull/507

原因大概是 `json_body`

[yes-github/bilibili-api@`main...yes-github-patch-1`#diff-d945671176](https://github.com/yes-github/bilibili-api/compare/main...yes-github-patch-1#diff-d94567117639dea8ca3c4e667129f4894b0630f12fa3f9bb509b6d17845c6978)

**Comment by HowHsu** [comment]
我之前测试了yes-github的fix是ok的

**Comment by z0z0r4** [comment]
> 我之前测试了yes-github的fix是ok的

现在 dev 分支的可以跑了，确实是

**Comment by yjss1225** [comment]
<img width="921" alt="error" src="https://github.com/Nemo2011/bilibili-api/assets/140266191/c48bc344-d803-4b74-a423-8f5b67359216">
您好，我用此模块也报了’not a str‘的错，看到你们通过改源码才解决的是吗？但是我改video_uploader的源码，却报了图片上的错误，请问该怎么解决呢？

**Comment by HowHsu** [comment]
> <img alt="error" width="921" src="https://user-images.githubusercontent.com/140266191/270296545-c48bc344-d803-4b74-a423-8f5b67359216.png"> 您好，我用此模块也报了’not a str‘的错，看到你们通过改源码才解决的是吗？但是我改video_uploader的源码，却报了图片上的错误，请问该怎么解决呢？

用dev分支试试

**Comment by z0z0r4** [comment]
@Drelf2018 发个release吧

**Comment by Drelf2018** [comment]
你发一样的，target选dev就行

**Comment by yjss1225** [comment]
你好，请问dev的分支是？

> > <img alt="error" width="921" src="https://user-images.githubusercontent.com/140266191/270296545-c48bc344-d803-4b74-a423-8f5b67359216.png"> 您好，我用此模块也报了’not a str‘的错，看到你们通过改源码才解决的是吗？但是我改video_uploader的源码，却报了图片上的错误，请问该怎么解决呢？
> 
> 用dev分支试试

**Comment by z0z0r4** [comment]
> 你好，请问dev的分支是？
> 
> > > <img alt="error" width="921" src="https://user-images.githubusercontent.com/140266191/270296545-c48bc344-d803-4b74-a423-8f5b67359216.png"> 您好，我用此模块也报了’not a str‘的错，看到你们通过改源码才解决的是吗？但是我改video_uploader的源码，却报了图片上的错误，请问该怎么解决呢？
> > 
> > 
> > 用dev分支试试

https://github.com/Nemo2011/bilibili-api/tree/dev

**Comment by yjss1225** [comment]
> > 你好，请问dev的分支是？
> > > > <img alt="error" width="921" src="https://user-images.githubusercontent.com/140266191/270296545-c48bc344-d803-4b74-a423-8f5b67359216.png"> 您好，我用此模块也报了’not a str‘的错，看到你们通过改源码才解决的是吗？但是我改video_uploader的源码，却报了图片上的错误，请问该怎么解决呢？
> > > 
> > > 
> > > 用dev分支试试
> 
> https://github.com/Nemo2011/bilibili-api/tree/dev

不好意思，替换了类库之后也报错了，请问这是？？

**Comment by z0z0r4** [comment]
> > > 你好，请问dev的分支是？
> > > > > <img alt="error" width="921" src="https://user-images.githubusercontent.com/140266191/270296545-c48bc344-d803-4b74-a423-8f5b67359216.png"> 您好，我用此模块也报了’not a str‘的错，看到你们通过改源码才解决的是吗？但是我改video_uploader的源码，却报了图片上的错误，请问该怎么解决呢？
> > > > 
> > > > 
> > > > 用dev分支试试
> > 
> > 
> > https://github.com/Nemo2011/bilibili-api/tree/dev
> 
> 不好意思，替换了类库之后也报错了，请问这是？？


给出报错

~~虽然我认为你这是没切换到dev~~

**Comment by yjss1225** [comment]
啥叫切换到dev？我现在把原本的bilibili-api替换成dev.zip里的bilibili-api.py了，就很奇怪

**Comment by z0z0r4** [comment]
完全看不懂...算了我今晚发release

**Comment by yjss1225** [comment]
你好，我换成最新的release，但报错内容还是跟旧版执行的报错内容一样是什么问题呢？
![image](https://github.com/Nemo2011/bilibili-api/assets/140266191/8993b216-7522-41e8-95a0-88ebce9aa964)

**Comment by z0z0r4** [comment]
> 你好，我换成最新的release，但报错内容还是跟旧版执行的报错内容一样是什么问题呢？ ![image](https://user-images.githubusercontent.com/140266191/273355525-8993b216-7522-41e8-95a0-88ebce9aa964.png)

你这有提供凭据吗？给下代码，怎么会炸在这一步的...

**Comment by yjss1225** [comment]
凭据我刚刚又搜了，重新填了：一下是代码和报错，麻烦帮我看看是啥问题，谢谢
python代码：
from bilibili_api import sync, video_uploader, Credential
async def main():
    credential = Credential(sessdata=""
                            , bili_jct=""
                            , buvid3="")
    # 具体请查阅相关文档
    meta = {
        "act_reserve_create": 0,
        "copyright": 1,
        "source": "",
        "desc": "",
        "desc_format_id": 0,
        "dynamic": "",
        "interactive": 0,
        "no_reprint": 1,
        "open_elec": 0,
        "origin_state": 0,
        "subtitles": {
            "lan": "",
            "open": 0
        },
        "tag": "搞笑,综合",
        "tid": '',
        "title": "title",
        "up_close_danmaku": False,
        "up_close_reply": False,
        "up_selection_reply": False,
        "dtime": 0
    }
    page = video_uploader.VideoUploaderPage(path='./tewt.mp4', title='title', description='title')
    uploader = video_uploader.VideoUploader([page], meta, credential, cover='./cover.png')

    @uploader.on("__ALL__")
    async def ev(data):
        print(data)

    await uploader.start()

sync(main())
报错：
C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\python.exe C:/Users/LENOVO/PycharmProjects/pythonProject2/bilibilii/blbl3.py
{'name': 'PREUPLOAD', 'data': ({<bilibili_api.video_uploader.VideoUploaderPage object at 0x000002460EE4AC40>: <bilibili_api.video_uploader.VideoUploaderPage object at 0x000002460EE4AC40>},)}
{'name': 'PRE_PAGE', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x000002460EE4AC40>},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x000002460EE4AC40>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 1},)}
{'name': 'AFTER_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x000002460EE4AC40>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 1},)}
{'name': 'PRE_PAGE_SUBMIT', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x000002460EE4AC40>},)}
{'name': 'AFTER_PAGE_SUBMIT', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x000002460EE4AC40>},)}
{'name': 'AFTER_PAGE', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x000002460EE4AC40>},)}
{'name': 'PRE_COVER', 'data': (None,)}
{'name': 'AFTER_COVER', 'data': ({'url': 'https://archive.biliimg.com/bfs/archive/63ac25349ff2f609bf3cf6d0f9a026d60602f9e0.png'},)}
{'name': 'PRE_SUBMIT', 'data': ({'act_reserve_create': 0, 'copyright': 1, 'source': '', 'desc': '', 'desc_format_id': 0, 'dynamic': '', 'interactive': 0, 'no_reprint': 1, 'open_elec': 0, 'origin_state': 0, 'subtitles': {'lan': '', 'open': 0}, 'tag': '搞笑,综合', 'tid': '', 'title': 'title', 'up_close_danmaku': False, 'up_close_reply': False, 'up_selection_reply': False, 'dtime': 0, 'cover': 'https://archive.biliimg.com/bfs/archive/63ac25349ff2f609bf3cf6d0f9a026d60602f9e0.png', 'videos': [{'title': 'title', 'desc': 'title', 'filename': 'n231007a21idr682zau5mt1mbeop2l5t', 'cid': 1291854705}]},)}
{'name': 'SUBMIT_FAILED', 'data': ({'err': ResponseCodeException('参数错误')},)}
{'name': 'FAILED', 'data': ({'err': ResponseCodeException('参数错误')},)}
Traceback (most recent call last):
  File "C:\Users\LENOVO\PycharmProjects\pythonProject2\bilibilii\blbl3.py", line 39, in <module>
    sync(main())
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\bilibili_api\utils\sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\LENOVO\PycharmProjects\pythonProject2\bilibilii\blbl3.py", line 37, in main
    await uploader.start()
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\bilibili_api\video_uploader.py", line 446, in start
    raise e
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\bilibili_api\video_uploader.py", line 438, in start
    result = await task
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\bilibili_api\video_uploader.py", line 421, in _main
    result = await self._submit(videos, cover_url)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\bilibili_api\video_uploader.py", line 749, in _submit
    raise err
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\bilibili_api\video_uploader.py", line 736, in _submit
    await Api(
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\bilibili_api\utils\network.py", line 170, in result
    self.__result = await self.request()
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\bilibili_api\utils\network.py", line 70, in inner
    return await func(*args, **kwargs)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\bilibili_api\utils\network.py", line 331, in request
    raise ResponseCodeException(code, msg, resp_data)
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：21001，信息：参数错误。
{'code': 21001, 'message': '参数错误', 'ttl': 1}

进程已结束,退出代码1

**Comment by z0z0r4** [comment]
meta 的问题吧

**Comment by z0z0r4** [comment]
> 现在 Web 端用的是 v3 的接口
> 
> ```python
> import requests
> params = {
>     't': '1694932881344',
>     'csrf': '',
> }
> 
> json_data = {
>     'cover': 'https://archive.biliimg.com/bfs/archive/c499c29a371eb3c0ecfac044712e9c8c8dcc9e8b.jpg',
>     'title': '2023-09-17 14-27-24',
>     'copyright': 1,
>     'tid': 231,
>     'tag': '编程开发',
>     'desc_format_id': 9999,
>     'desc': '',
>     'recreate': -1,
>     'dynamic': '',
>     'interactive': 0,
>     'videos': [
>         {
>             'filename': 'n230917qn3qcmhf30gfaz5wm6rua20j0',
>             'title': '2023-09-17 14-27-24',
>             'desc': '',
>             'cid': 1270113250,
>         },
>     ],
>     'act_reserve_create': 0,
>     'no_disturbance': 0,
>     'no_reprint': 1,
>     'subtitle': {
>         'open': 0,
>         'lan': '',
>     },
>     'dolby': 0,
>     'lossless_music': 0,
>     'web_os': 1,
>     'csrf': '',
> }
> 
> response = requests.post(
>     'https://member.bilibili.com/x/vu/web/add/v3',
>     params=params,
>     cookies=cookies,
>     headers=headers,
>     json=json_data,
> )
> ```

建议参考下这个设置meta，比如tid啥的...

~~没做检查我也看不出哪的问题，下周再整~~

**Comment by yjss1225** [comment]
好了，能上传了，我的tid没填数据，tid是啥id，谢谢解答。

**Comment by yjss1225** [comment]
我想问一下，如果一次性上传10个视频，会被检测出来和封杀之类的吗？之前有遇到这种情况吗

**Comment by z0z0r4** [comment]
> 好了，能上传了，我的tid没填数据，tid是啥id，谢谢解答。

分区id

**Comment by z0z0r4** [comment]
> 我想问一下，如果一次性上传10个视频，会被检测出来和封杀之类的吗？之前有遇到这种情况吗

有可能

**Comment by yjss1225** [comment]
C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\python.exe C:/Users/LENOVO/PycharmProjects/pythonProject2/bilibilii/bl4.py
C:\Users\LENOVO\Desktop\blbl\教练带你见世面，你给教练那冠军？？.mp4
Traceback (most recent call last):
  File "C:\Users\LENOVO\PycharmProjects\pythonProject2\bilibilii\bl4.py", line 66, in <module>
    sync(main())
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\bilibili_api\utils\sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\LENOVO\PycharmProjects\pythonProject2\bilibilii\bl4.py", line 61, in main
    await uploader.start()
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\bilibili_api\video_uploader.py", line 446, in start
    raise e
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\bilibili_api\video_uploader.py", line 438, in start
    result = await task
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\bilibili_api\video_uploader.py", line 421, in _main
    result = await self._submit(videos, cover_url)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\bilibili_api\video_uploader.py", line 749, in _submit
    raise err
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\bilibili_api\video_uploader.py", line 736, in _submit
    await Api(
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\bilibili_api\utils\network.py", line 170, in result
    self.__result = await self.request()
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\bilibili_api\utils\network.py", line 70, in inner
    return await func(*args, **kwargs)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python39\lib\site-packages\bilibili_api\utils\network.py", line 331, in request
    raise ResponseCodeException(code, msg, resp_data)
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：601，信息：请输入验证码信息。
{'code': 601, 'message': '请输入验证码信息', 'ttl': 1, 'data': {'v_voucher': 'voucher_f7d607a3-4ffb-433e-9cd9-7643aa279fb8'}}

进程已结束,退出代码1

我此前上传了挺多视频的，现在报要验证码，是不是被反爬了？

**Comment by z0z0r4** [comment]
y，去网页端过下验证码就行了

**Comment by smilemilk1992** [comment]
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：601，信息：请输入验证码信息。 这种大家如何解决的 ，楼上说去网页过一次验证码 我明天收到验证码提示啊

**Comment by z0z0r4** [comment]
> bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：601，信息：请输入验证码信息。 这种大家如何解决的 ，楼上说去网页过一次验证码 我明天收到验证码提示啊

> 我明天收到验证码提示啊

你在说什么...

601 全部去网页端做验证码
