### ISSUE TITLE
[提问] Credential刷新问题

### ISSUE THREAD

**Issue by jhzgjhzg** [Nemo2011/bilibili-api#505]
**Python 版本：** 3.9.16

**模块版本：** 16.1.0

**运行环境：** MacOS

---

Credential刷新是需要在参数有效的情况下才可以进行的吗，如果是这样，那这个刷新是不是有点多余了？

我很久前登录的账号，今天使用的时候突然报错：
`bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：-101，信息：账号未登录。
{'code': -101, 'message': '账号未登录', 'ttl': 1, 'data': None}`
检查发现是Credential的参数过期了，然而这个错是`credential.check_refresh()`报的，这意味着无法进行刷新？还是我理解有问题

**Comment by z0z0r4** [comment]
`check_refresh` 是是否需要刷新，而不是凭据是否过期

**Comment by z0z0r4** [comment]
凭据是否过期看

https://github.com/Nemo2011/bilibili-api/blob/223e42a578b5fcfd2091968a30691af6ce6d05e5/bilibili_api/credential.py#L57-L67

**Comment by jhzgjhzg** [comment]
过期的cookies不可刷新吗，那什么情况下cookies需要刷新

**Comment by z0z0r4** [comment]
> 过期的cookies不可刷新吗，那什么情况下cookies需要刷新

当 `check_refresh` 为 `True` 的时候需要刷新，再不刷新就没法刷新直接过期了

**Comment by jhzgjhzg** [comment]
> > 过期的cookies不可刷新吗，那什么情况下cookies需要刷新
> 
> 当 `check_refresh` 为 `True` 的时候需要刷新，再不刷新就没法刷新直接过期了
> 
> 没法 `check_refresh` 的已经寄了

寄了以后就只能重新登陆吗

**Comment by z0z0r4** [comment]
> > > 过期的cookies不可刷新吗，那什么情况下cookies需要刷新
> > 
> > 
> > 当 `check_refresh` 为 `True` 的时候需要刷新，再不刷新就没法刷新直接过期了
> > 没法 `check_refresh` 的已经寄了
> 
> 寄了以后就只能重新登陆吗

是
