### ISSUE TITLE
[需求] 私信相关

### ISSUE THREAD

**Issue by jhzgjhzg** [Nemo2011/bilibili-api#508]
啊b改版了私信，up主未回复或关注你前，只能发送一条私信，是否有可能绕过此限制

**Comment by Drelf2018** [comment]
未听说过

**Comment by jhzgjhzg** [comment]
> 未听说过

9.10，刚改版，使用当前接口强行发私信会报错：
`bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：21047，信息：你最多发送1条消息，对方回复或者关注你后可以继续发消息~。
{'code': 21047, 'message': '你最多发送1条消息，对方回复或者关注你后可以继续发消息~', 'ttl': 1, 'data': None}`

**Comment by Drelf2018** [comment]
我的意思是未听说过可以绕过

**Comment by jhzgjhzg** [comment]
> 我的意思是未听说过可以绕过

BV16j411y7JK，这里提供了绕过限制的软件，暂不清楚实现方式

**Comment by z0z0r4** [comment]
> > 我的意思是未听说过可以绕过
> 
> BV16j411y7JK，这里提供了绕过限制的软件，暂不清楚实现方式

这软件没开源，kkn

https:/

**Comment by Drelf2018** [comment]
我已经逆向过了，用的 `3.11` 不能完全解出源码，但是我看了下用的接口就是发私信的那个，不知道怎么做到所谓的破解的

**Comment by blyc** [comment]
无法完全逆向的话，能否直接抓包研究参数呢？
不过我试了fiddler配置自签名解析https，但似乎因为python的requsets校验ssl不允许自签名证书使得请求失败无法抓包，不知道有没有办法绕过？
```
ERROR:root:发生了异常: HTTPSConnectionPool(host='api.bilibili.com', port=443): Max retries exceeded with url: /x/emote/user/panel/web?business=reply (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
```

**Comment by jhzgjhzg** [comment]
> 周末再说吧
> 
> 话说有人试过吗...确定绕过限制了？我听着还是荒谬

用这个软件，在自己的私信里看，确实没有红色感叹号，但是不清楚对方能否看到

**Comment by z0z0r4** [comment]
> > 周末再说吧
> > 话说有人试过吗...确定绕过限制了？我听着还是荒谬
> 
> 用这个软件，在自己的私信里看，确实没有红色感叹号，但是不清楚对方能否看到

难品，要不直接扔B站白帽那边去得了...攒几个薅个娃娃

**Comment by shenjackyuanjie** [comment]
这玩意是 pyinstaller 整的？ 还是 nuitka
如果是nuitka 那就别想了
pyinstaller 也许可以（

**Comment by shenjackyuanjie** [comment]
> 我已经逆向过了，用的 `3.11` 不能完全解出源码，但是我看了下用的接口就是发私信的那个，不知道怎么做到所谓的破解的

欸，所以是怎么逆向的？（

**Comment by plusls** [comment]
> > 周末再说吧
> > 话说有人试过吗...确定绕过限制了？我听着还是荒谬
> 
> 用这个软件，在自己的私信里看，确实没有红色感叹号，但是不清楚对方能否看到

可以把py的版本发上来看看

**Comment by z0z0r4** [comment]
https://tieba.baidu.com/p/8611430719

**Comment by z0z0r4** [comment]
弱智B站 等寄
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/00effc76-2954-45e3-94a0-9d1748207540)

**Comment by blyc** [comment]
> 弱智B站 等寄 ![image](https://user-images.githubusercontent.com/78744121/275194861-00effc76-2954-45e3-94a0-9d1748207540.png)

草 笑死 这也怪不得阿b一副要死的样子了

**Comment by z0z0r4** [comment]
难品，随便来个谁去恶意利用下吧我没话说了...
