### ISSUE TITLE
[建议] 可以提供网络请求的方式访问接口

### ISSUE THREAD

**Issue by nooblong** [Nemo2011/bilibili-api#512]
接口这么完善但是只能用py调用太可惜了，我根据我的需求加了个sanic server，可以通过http调用，https://github.com/nooblong/bilibili-api
，不知道作者是否有这方面的想法。

**Comment by Drelf2018** [comment]
https://github.com/Nemo2011/bilibili-api/issues/184

我已经写过了😂

https://github.com/Nemo2011/bilibili-api/tree/main/bilibili_api/tools/parser

**Comment by nooblong** [comment]
有人在视频评论底下@我的时候，自动去下载视频然后上传到网易云播客里面，类似b站的一堆ai解析视频机器人一样。但是好像没找到别人的代码，就自己写个，但是好像也用不到。

为什么是七海nanami！！！为什么不是梓宝！！！

**Comment by Drelf2018** [comment]
> 有人在视频评论底下@我的时候，自动去下载视频然后上传到网易云播客里面，类似b站的一堆ai解析视频机器人一样。但是好像没找到别人的代码，就自己写个，但是好像也用不到。
> 
> 为什么是七海nanami！！！为什么不是梓宝！！！

这种操作直接写代码里更好吧，做成接口会有很多隐患的

**Comment by Drelf2018** [comment]
除了这个还有啥新功能吗，如果有的话可以加进我写的那个解析器里

**Comment by nooblong** [comment]
除了获取评论和发评论以外其他都是java写的，而且不太会py，两边都启动然后在localhost互相调没有隐患吧

**Comment by Drelf2018** [comment]
> 除了获取评论和发评论以外其他都是java写的，而且不太会py，两边都启动然后在localhost互相调没有隐患吧

我以为你是要做成外网接口，内网那大可以随便调用

**Comment by nooblong** [comment]
> 除了这个还有啥新功能吗，如果有的话可以加进我写的那个解析器里

目标肯定是能把所有接口都能用起来呗

**Comment by Drelf2018** [comment]
> 目标肯定是能把所有接口都能用起来呗

比如说哪些接口？

**Comment by nooblong** [comment]
那应该是够了吧，剩下些涉及文件上传下载的？我现在也用不上。没发现其他的了。

**Comment by z0z0r4** [comment]
我总觉得这应该单独挖个库出来的说？

> #184
> 
> 我已经写过了😂
> 
> https://github.com/Nemo2011/bilibili-api/tree/main/bilibili_api/tools/parser
