### ISSUE TITLE
上传视频出现601 请输入验证码 错误

### ISSUE THREAD

**Issue by HowHsu** [Nemo2011/bilibili-api#513]
**Python 版本：** 3.x.y

**模块版本：** x.y.z 

**运行环境：** Windows / Linux / MacOS

**模块路径：** `bilibili_api.xxxx`

**解释器：** cpython / pypi / jython

**报错信息：**

```
这里填写报错信息
```

**报错代码：**

```
这里填写报错代码
```

---

在此处写正文

**Comment by z0z0r4** [comment]
报错呢我傻了

**Comment by HowHsu** [comment]
<img width="1751" alt="image" src="https://github.com/Nemo2011/bilibili-api/assets/38499194/2ea2f2ed-c6dd-4b13-bff3-a358ae3feea1">
没啥特别的信息，就是601

**Comment by HowHsu** [comment]
应该是风控，但是我距离上次上传挺久了，很奇怪

**Comment by HowHsu** [comment]
上传的代码是根据repo中的example写的，没改动什么。

**Comment by z0z0r4** [comment]
那你修，我摆烂了

**Comment by z0z0r4** [comment]
那你修，我摆烂了

**Comment by z0z0r4** [comment]
dev 吗

**Comment by HowHsu** [comment]
dev 分支 507b7ad fix: video_uploader submit api v3

**Comment by z0z0r4** [comment]
周末待测，搞不好是换v3了的原因，但我也找不到v1来调试

**Comment by HowHsu** [comment]
我切到main分支试了下，返回“21001 参数错误”

**Comment by Nemo2011** [comment]
还是那个验证码是 recaptcha

**Comment by z0z0r4** [comment]
> 很可能也要 geetest 了

网页端主动要求上传视频要验证？不是风控？

**Comment by HowHsu** [comment]
> 还是那个验证码是 recaptcha

我用网页端手工上传时候遇到的是图形点击对应字符的验证码

**Comment by HowHsu** [comment]
https://github.com/Nemo2011/bilibili-api/blob/main/docs/examples/video_uploader.md
我的调用代码是copy的这个example的形式，这个需要针对v3改动吗？
另外，我发现main分支很多commits没有通过CI啊。。

**Comment by z0z0r4** [comment]
> > 还是那个验证码是 recaptcha
> 
> 我用网页端手工上传时候遇到的是图形点击对应字符的验证码

看看咋自动化极验吧

**Comment by HowHsu** [comment]
> > > 还是那个验证码是 recaptcha
> > 
> > 
> > 我用网页端手工上传时候遇到的是图形点击对应字符的验证码
> 
> 看看咋自动化极验吧

大佬们冲，web这块我是纯小白

**Comment by z0z0r4** [comment]
> > > > 还是那个验证码是 recaptcha
> > > 
> > > 
> > > 我用网页端手工上传时候遇到的是图形点击对应字符的验证码
> > 
> > 
> > 看看咋自动化极验吧
> 
> 大佬们冲，web这块我是纯小白

这得 ocr...

**Comment by z0z0r4** [comment]
> > 还是那个验证码是 recaptcha
> 
> 我用网页端手工上传时候遇到的是图形点击对应字符的验证码

我姑且是压根没看到哪里有验证码，怎么触发的...

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/4b2a66d8-89b5-406e-a0e7-a58b5dace1ad)

顶多只看到删除有验证码

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/9798e8b8-7ce9-4228-870a-682eef0cd091)

**Comment by z0z0r4** [comment]
这就没法调试了欸...

看到个 https://www.bilibili.com/blackboard/activity-Ju4AWRzssB.html

**Comment by HowHsu** [comment]
> 这就没法调试了欸...
> 
> 看到个 https://www.bilibili.com/blackboard/activity-Ju4AWRzssB.html

No, that's not my case

**Comment by HowHsu** [comment]
我刚刚用api提交了下可以了，冷却了大概三天左右。个人感觉是某段时间提交过快导致风控了。复现的话不加sleep不停提交应该就能复现。

**Comment by z0z0r4** [comment]
...如果是被风控了的话那我没话说，最近的风控比较多，得上网页过人机解封

**Comment by nicliuqi** [comment]
为啥昨天还能上传，突然就一直报错了
version: 16.1.1

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/bilibili_api/utils/sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/bilibili_api/video_uploader.py", line 446, in start
    raise e
  File "/usr/local/lib/python3.9/site-packages/bilibili_api/video_uploader.py", line 438, in start
    result = await task
  File "/usr/local/lib/python3.9/site-packages/bilibili_api/video_uploader.py", line 421, in _main
    result = await self._submit(videos, cover_url)
  File "/usr/local/lib/python3.9/site-packages/bilibili_api/video_uploader.py", line 749, in _submit
    raise err
  File "/usr/local/lib/python3.9/site-packages/bilibili_api/video_uploader.py", line 736, in _submit
    await Api(
  File "/usr/local/lib/python3.9/site-packages/bilibili_api/utils/network.py", line 170, in result
    self.__result = await self.request()
  File "/usr/local/lib/python3.9/site-packages/bilibili_api/utils/network.py", line 70, in inner
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/bilibili_api/utils/network.py", line 331, in request
    raise ResponseCodeException(code, msg, resp_data)
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：601，信息：请输入验证码信息。
{'code': 601, 'message': '请输入验证码信息', 'ttl': 1, 'data': {'v_voucher': 'voucher_def0db31-4388-4505-b0f7-892876439802'}}

**Comment by nicliuqi** [comment]
经界面投稿测试确认，目前手动投稿也需要进行图片点击验证，请问这是因为频繁测试导致的吗，还是说所有账号现在上传都需要额外验证了？

**Comment by HowHsu** [comment]
估计是频繁投稿，我之前也是这个问题

**Comment by nicliuqi** [comment]
搞得不敢测试了 QAQ

> 估计是频繁投稿，我之前也是这个问题

**Comment by z0z0r4** [comment]
> 估计是频繁投稿，我之前也是这个问题

是这个原因

**Comment by liaozd** [comment]
你们有多频繁？一天几次？
