### ISSUE TITLE
按照视频下载的api示例进行下载，打开后无画面

### ISSUE THREAD

**Issue by Mr-IT007** [Nemo2011/bilibili-api#515]
**Python 版本：** 3.8

**模块版本：** bilibili-api-python 16.1.0

**运行环境：** Windows

bvid: BV14u411w7eS

![bd1](https://github.com/Nemo2011/bilibili-api/assets/39551480/85be48e7-685e-4311-9529-1af86ccc5827)

![bd2](https://github.com/Nemo2011/bilibili-api/assets/39551480/f7cb6786-ced7-4bc4-8e0d-5f335a730691)

**Comment by z0z0r4** [comment]
ffmpeg 命令提供下thx

**Comment by Mr-IT007** [comment]
> ffmpeg 命令提供下thx

就是api示例里的命令：

os.system(f'{FFMPEG_PATH} -i video_temp.m4s -i audio_temp.m4s -vcodec copy -acodec copy video.mp4')

**Comment by jhzgjhzg** [comment]
> > ffmpeg 命令提供下thx
> 
> 就是api示例里的命令：
> 
> ```python
> os.system(f'{FFMPEG_PATH} -i video_temp.m4s -i audio_temp.m4s -vcodec copy -acodec copy video.mp4')
> ```

应该是你播放器的问题，我可以打开

**Comment by z0z0r4** [comment]
> > > ffmpeg 命令提供下thx
> > 
> > 
> > 就是api示例里的命令：
> > ```python
> > os.system(f'{FFMPEG_PATH} -i video_temp.m4s -i audio_temp.m4s -vcodec copy -acodec copy video.mp4')
> > ```
> 
> 应该是你播放器的问题，我可以打开

支持
