### ISSUE TITLE
[需求] 增加验证码识别

### ISSUE THREAD

**Issue by HowHsu** [Nemo2011/bilibili-api#516]
使用该库提交视频发现每隔20分钟提交1个视频，提交10个左右就出现了验证码，如果可以解决验证码的问题，上传功能的实用性会大大提高。

**Comment by z0z0r4** [comment]
不用说这个也是个很难的功能，先得找个能稳定触发风控但也只是获取信息的接口

**Comment by z0z0r4** [comment]
ddddocr 倒是可用直接拿来用，但我没了解极验拿到坐标之后咋加密的...

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/1e8abcd5-585b-43aa-8e5f-6d2c685bc1ae)

**Comment by HowHsu** [comment]
FYI：https://zhuanlan.zhihu.com/p/336590706

**Comment by HowHsu** [comment]
> 但在这之前爬虫封装库有必要提供验证码功能吗？

我认为克服verification获取网页信息应该是《爬虫》的题中应有之义

**Comment by z0z0r4** [comment]
> FYI：https://zhuanlan.zhihu.com/p/336590706

屁用没有，得谁去把 `w` 参数给逆向出来，翻js

**Comment by HowHsu** [comment]
> > FYI：https://zhuanlan.zhihu.com/p/336590706
> 
> 屁用没有，得谁去把 `w` 参数给逆向出来，翻js

难度确实高

**Comment by HowHsu** [comment]
经测试，一天内提交8个视频会出现验证码。快来前端大佬解决下，小弟不胜感激。

**Comment by z0z0r4** [comment]
> 经测试，一天内提交8个视频会出现验证码。快来前端大佬解决下，小弟不胜感激。

把 js 那段扔给 gpt 读吧

**Comment by z0z0r4** [comment]
算了这不现实...没找到现成的三代点选，放弃
