### ISSUE TITLE
[漏洞] pyinstaller打包问题

### ISSUE THREAD

**Issue by JiaLeDe** [Nemo2011/bilibili-api#522]
打包后运行时报错
No such file or directory: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI316082\\bilibili_api\\data/countries_codes.json'

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/issues/39

**Comment by z0z0r4** [comment]
打包命令发下？按道理会带上 `data` 文件夹的

**Comment by JiaLeDe** [comment]
> 打包命令发下？按道理会带上 `data` 文件夹的
> 
> 这不是 bug

pyinstaller -F xxx.py

**Comment by JiaLeDe** [comment]
我的pip list只有biliapi和pyimstaller，其他的都没有了

**Comment by z0z0r4** [comment]
> 我的pip list只有biliapi和pyimstaller，其他的都没有了

看看版本，你安装的最好是 `bilibili-api-python` 而不是 `bilibili-api`

**Comment by z0z0r4** [comment]
pyinstaller 直接打包没问题的

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/de7cb739-eb6c-4a52-b341-964d50f9021b)

**Comment by JiaLeDe** [comment]
> pyinstaller 直接打包没问题的
> 
> ![image](https://user-images.githubusercontent.com/78744121/272499493-de7cb739-eb6c-4a52-b341-964d50f9021b.png)

我是用的bilibi-api-python，给你看下我的pip list，我用到的关键函数有有live_area和live，其他的没报错，这两个方法会报错

aiohttp                   3.8.4
aiosignal                 1.3.1
altgraph                  0.17.3
anyio                     3.6.2
APScheduler               3.10.1
async-timeout             4.0.2
attrs                     23.1.0
qrcode                    7.4.2
requests                  2.30.0
rsa                       4.9
setuptools                67.7.2
six                       1.16.0
sniffio                   1.3.0
soupsieve                 2.4.1
tqdm                      4.65.0
typing_extensions         4.5.0
tzdata                    2023.3
tzlocal                   4.3
urllib3                   1.25.1
wheel                     0.40.0
yarl                      1.9.2

**Comment by M4cr0-storm** [comment]
> > 我的pip list只有biliapi和pyimstaller，其他的都没有了
> 
> 看看版本，你安装的最好是 `bilibili-api-python` 而不是 `bilibili-api`

遇到了同样的问题，安装的是bilibili-api-python
![图片](https://github.com/user-attachments/assets/1acbde86-4914-4ddc-841d-ac3137ab22f4)
![图片](https://github.com/user-attachments/assets/0fa2df94-91c3-4b5b-8607-a8fb80dc758c)
![图片](https://github.com/user-attachments/assets/4e779d2f-1d9f-4c8e-ad48-f63bbe688c3c)

**Comment by z0z0r4** [comment]
显然你调用的是 `bilibili-api`
![{36890B7C-DF3C-4B1B-9B8E-8A43DC343373}](https://github.com/user-attachments/assets/babca990-4b19-4fae-a839-0370cb0f8cfe)

**Comment by tp1415926535** [comment]
> 显然你调用的是 `bilibili-api` 

我也遇到了，在我加上`login_func` 的引用之后。以前没引用登录功能的时候打包正常的。
``` python
from bilibili_api import live, sync, Credential, Danmaku, user ,login_func

login_func.get_qrcode()
```

那怎么确保调用 `bilibili-api-python` 呢，我已经尝试
``` command
> pip uninstall bilibili-api
WARNING: Skipping bilibili-api as it is not installed.

> pip show bilibili-api-python
Name: bilibili-api-python
Version: 16.3.0
Summary: The fork of module bilibili-api. 哔哩哔哩的各种 API 调用便捷整合（视频、动态、直播等），另外附加一些常用的功能 。
Home-page: None
Author: None
Author-email: Nemo2011 <yimoxia@outlook.com>
License: GPL-3.0-or-later
Location: d:\python39\lib\site-packages
Requires: lxml, httpx, tqdm, colorama, brotli, yarl, pyyaml, aiohttp, APScheduler, pycryptodomex, pillow, beautifulsoup4, qrcode, rsa, qrcode-terminal
Required-by:
```

**Comment by M4cr0-storm** [comment]
> 显然你调用的是 `bilibili-api` ![{36890B7C-DF3C-4B1B-9B8E-8A43DC343373}](https://private-user-images.githubusercontent.com/78744121/378127314-babca990-4b19-4fae-a839-0370cb0f8cfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NzcxNTMsIm5iZiI6MTcyOTU3Njg1MywicGF0aCI6Ii83ODc0NDEyMS8zNzgxMjczMTQtYmFiY2E5OTAtNGIxOS00ZmFlLWE4MzktMDM3MGNiMGY4Y2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA2MDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5OTViNTkwNGYxY2FmNDI4ZTc1ZDY3NzFhNDg0ZDk2OTUyNWU1MzZiY2YxMmJmNjhiN2U3ZmNkZGNjYzY5ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FLhUu5hgPufVDn5lTGgw2ELV9-k6WVUgJtYjuV5gVL0)

我安装的是bilibili-api-python 调用的是bilibili_api
```
from bilibili_api import login, user, sync,live
from bilibili_api import Credential
```
