### ISSUE TITLE
[需求] 获取视频tag是否可以匿名获取

### ISSUE THREAD

**Issue by Marrylatiao** [Nemo2011/bilibili-api#523]
目前获取视频标签是需要传Credential对象，大佬是否可以考虑匿名获取

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/blob/5ad63105643a6cc5124ff2ffebf5598d22e50952/bilibili_api/data/api/video.json#L45

这里要求verify，原因未知，我测试了下是不需要登录的

https://[api.bilibili.com/x/web-interface/view/detail/tag?bvid=BV1wu411u7WK](https://api.bilibili.com/x/web-interface/view/detail/tag?bvid=BV1wu411u7WK)

**Comment by z0z0r4** [comment]
改了 https://github.com/Nemo2011/bilibili-api/commit/3482971e5b582a1ed28140dc2beb8013d6cd85c4

等更新吧
