### ISSUE TITLE
[提问]是否有办法判断用户是否是自己的粉丝

### ISSUE THREAD

**Issue by LondonClass** [Nemo2011/bilibili-api#528]
即使对方隐藏了关注列表，这个应该也是能看到的

**Comment by z0z0r4** [comment]
你可以通过 https://nemo2011.github.io/bilibili-api/#/modules/user?id=async-def-get_followers 遍历自己的粉丝列表看看是不是关注了自己

这个应该也是能够看到的指的是哪里？指出下具体页面我方便找

**Comment by z0z0r4** [comment]
或者通过 https://[api.bilibili.com/x/space/wbi/acc/relation?mid=558830935](https://api.bilibili.com/x/space/wbi/acc/relation?mid=558830935) 查看互相的关系，顺便还有包括分组

如果 `be_related` 全是 0 那就说明不是你的粉丝

```JSON
{
  "code": 0,
  "message": "0",
  "ttl": 1,
  "data": {
    "relation": {
      "mid": 129323413,
      "attribute": 6,
      "mtime": 1697279495,
      "tag": [
        -10,
        132523584
      ],
      "special": 1
    },
    "be_relation": {
      "mid": 558830935,
      "attribute": 6,
      "mtime": 1643215147,
      "tag": null,
      "special": 0
    }
  }
}
```
这个接口好像待加入

**Comment by LondonClass** [comment]
> 你可以通过 https://nemo2011.github.io/bilibili-api/#/modules/user?id=async-def-get_followers 遍历自己的粉丝列表看看是不是关注了自己
> 
> 这个应该也是能够看到的指的是哪里？指出下具体页面我方便找

点开其他人的个人空间，不同的关系下，右上角的按钮会不同

**Comment by z0z0r4** [comment]
> > 你可以通过 [nemo2011.github.io/bilibili-api/#/modules/user?id=async-def-get_followers](https://nemo2011.github.io/bilibili-api/#/modules/user?id=async-def-get_followers) 遍历自己的粉丝列表看看是不是关注了自己
> > 这个应该也是能够看到的指的是哪里？指出下具体页面我方便找
> 
> 点开其他人的个人空间，不同的关系下，右上角的按钮会不同

这个仅限于你在关注了对方之后才会显示互相关注吧？

**Comment by LondonClass** [comment]
> 你可以通过 https://nemo2011.github.io/bilibili-api/#/modules/user?id=async-def-get_followers 遍历自己的粉丝列表看看是不是关注了自己
> 
> 这个应该也是能够看到的指的是哪里？指出下具体页面我方便找

在这个上面这个粉红色按钮
<img width="257" alt="屏幕截图 2023-10-14 215413" src="https://github.com/Nemo2011/bilibili-api/assets/43668206/1da90df3-7739-4094-afd3-afaaf4adbdbd">
<img width="235" alt="屏幕截图 2023-10-14 215441" src="https://github.com/Nemo2011/bilibili-api/assets/43668206/08058e3d-c2c8-4e9e-8b37-bf9e36f865da">

**Comment by z0z0r4** [comment]
那没事了，应该就是这个接口，我现在写

> 或者通过 https://[api.bilibili.com/x/space/wbi/acc/relation?mid=558830935](https://api.bilibili.com/x/space/wbi/acc/relation?mid=558830935) 查看互相的关系，顺便还有包括分组
> 
> 如果 `be_related` 全是 0 那就说明不是你的粉丝
> 
> ```json
> {
>   "code": 0,
>   "message": "0",
>   "ttl": 1,
>   "data": {
>     "relation": {
>       "mid": 129323413,
>       "attribute": 6,
>       "mtime": 1697279495,
>       "tag": [
>         -10,
>         132523584
>       ],
>       "special": 1
>     },
>     "be_relation": {
>       "mid": 558830935,
>       "attribute": 6,
>       "mtime": 1643215147,
>       "tag": null,
>       "special": 0
>     }
>   }
> }
> ```
> 
> 这个接口好像待加入

**Comment by z0z0r4** [comment]
搞定了，用 dev 分支的话直接 `await user.User(uid=558830935, credential=c).get_relation(523952593)`
https://github.com/Nemo2011/bilibili-api/pull/531
