### ISSUE TITLE
[漏洞] 获取动态评论列表第二页及之后时获取到空数据

### ISSUE THREAD

**Issue by Gedoy9793** [Nemo2011/bilibili-api#529]
**Python 版本：** 3.9.10

**模块版本：** 16.1.0

**运行环境：** Windows / Linux / MacOS

**模块路径：** `bilibili_api.comment`

**解释器：** cpython

**报错信息：**

没有报错，但返回内容：
```json
{
	"page": {
		"num": 0,
		"size": 0,
		"count": 0,
		"acount": 0
	},
	"config": {
		"showtopic": 0,
		"show_up_flag": false,
		"read_only": false
	},
	"replies": null,
	"upper": {
		"mid": 0,
		"top": null,
		"vote": null
	},
	"top": null,
	"vote": 0,
	"blacklist": 0,
	"assist": 0,
	"mode": 0,
	"support_mode": null,
	"control": {
		"input_disable": false,
		"root_input_text": "",
		"child_input_text": "",
		"giveup_input_text": "",
		"screenshot_icon_state": 0,
		"upload_picture_icon_state": 0,
		"answer_guide_text": "",
		"answer_guide_icon_url": "",
		"answer_guide_ios_url": "",
		"answer_guide_android_url": "",
		"bg_text": "",
		"empty_page": null,
		"show_type": 0,
		"show_text": "",
		"web_selection": false,
		"disable_jump_emote": false,
		"enable_charged": false,
		"enable_cm_biz_helper": false
	},
	"folder": {
		"has_folded": false,
		"is_folded": false,
		"rule": ""
	}
}
```

**报错代码：**

没有错误代码

---

使用comment.get_comments时，选择获取第二页或者之后的页面，返回结果如上，实际动态有第二页评论，DYNAMIC和DYNAMIC_DRAW都存在这个问题

**Comment by z0z0r4** [comment]
提供下动态的id或者链接？

**Comment by Gedoy9793** [comment]
> 提供下动态的id或者链接？

没事了，带上登录态之后就可以了(

不过如果可以的话，希望还是能在文档里加上要求登录态的说明，这B站也不说是因为没有登录

**Comment by z0z0r4** [comment]
是没登录一律不行？动态评论区现在没登录不能看了吗emm

**Comment by Gedoy9793** [comment]
> 是没登录一律不行？动态评论区现在没登录不能看了吗emm

啊，我这边不登录的话第一页是正常的，后面会返回空

**Comment by z0z0r4** [comment]
我这边看好像确实有问题，晚点看看

**Comment by z0z0r4** [comment]
```python
await comment.get_comments_lazy(oid=852334198324723713, type_=comment.CommentResourceType.DYNAMIC, credential=c)```

`{'code': -403, 'message': '访问权限不足', 'ttl': 1}`

接口炸了...

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/f3030d74-6722-408e-9219-1cd2bcce5b17)

**Comment by z0z0r4** [comment]
我怀疑是 `wbi` 炸了...看不懂思密达

**Comment by z0z0r4** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/issues/843#issue-1943262427

**Comment by GaoAO1e** [comment]
> > 提供下动态的id或者链接？
> 
> 没事了，带上登录态之后就可以了(
> 
> 不过如果可以的话，希望还是能在文档里加上要求登录态的说明，这B站也不说是因为没有登录

所以是带上登录态后就解决问题了吗？如果是，那怎么加

**Comment by blyc** [comment]
> > > 提供下动态的id或者链接？
> > 
> > 
> > 没事了，带上登录态之后就可以了(
> > 不过如果可以的话，希望还是能在文档里加上要求登录态的说明，这B站也不说是因为没有登录
> 
> 所以是带上登录态后就解决问题了吗？如果是，那怎么加

参见：
 - 手动传参构建：https://nemo2011.github.io/bilibili-api/#/get-credential
 - 通过登录获取：https://nemo2011.github.io/bilibili-api/#/examples/login

API使用如：https://github.com/Nemo2011/bilibili-api/blob/main/bilibili_api/comment.py#L380C15-L380C15
![图片](https://github.com/Nemo2011/bilibili-api/assets/34291620/1bda188a-dcab-46dd-b313-8777120d56e7)
直接调用时候传入`credential`即可,即`bilibili_api.comment.get_comments(oid,type_,page_index,credential=XXXXXX)`
