### ISSUE TITLE
[漏洞] 16.1.1离线安装失败, 缺少github.txt

### ISSUE THREAD

**Issue by KaiSanPao** [Nemo2011/bilibili-api#541]
版本: 16.1.1
下载源码后离线安装使用setup.py失败, 这新的setup.py增加使用了github.txt, 但是项目现在并没有这个文件...

**Comment by Drelf2018** [comment]
啊这个是发 `release` 的时候 `action` 自动生成的，你可以把 `setup.py` 里的读取这个文件的代码删了，然后自己填一个版本号。

**Comment by Drelf2018** [comment]
没考虑过有下载源码安装的情况，毕竟本库在 pypi 发布了

**Comment by KaiSanPao** [comment]
最近在试用python3.12, 不能pip直接安装这个库, 得修改下requirements.txt和setup.py, 然后才能安装

**Comment by Drelf2018** [comment]
其实做这个修改的初衷是懒得每次发新版本都手动改版本号（容易忘），没想到还有别的影响。我现在在考虑是否需要改回原来手动填版本号的形式了🧐

**Comment by Nemo2011** [comment]
如果有文件覆盖，否则提供一个默认设置，我觉得这样子会好一点

**Comment by z0z0r4** [comment]
> 最近在试用python3.12, 不能pip直接安装这个库, 得修改下requirements.txt和setup.py, 然后才能安装

说来可以把3.12支持考虑下了？

https://github.com/Nemo2011/bilibili-api/blob/f67717998728461cda79b7b15469eab136216bbc/setup.py#L34-L41

**Comment by KaiSanPao** [comment]
> > 最近在试用python3.12, 不能pip直接安装这个库, 得修改下requirements.txt和setup.py, 然后才能安装
> 
> 说来可以把3.12支持考虑下了？
> 
> https://github.com/Nemo2011/bilibili-api/blob/f67717998728461cda79b7b15469eab136216bbc/setup.py#L34-L41

我大体用下来倒是没啥问题, 不过感觉还是再等等, 支持python3.12的aiohttp3.9还在测试:
https://github.com/aio-libs/aiohttp/issues/7675

**Comment by Drelf2018** [comment]
> 如果有文件则覆盖原有设置，然后提供一个默认设置，（如默认 main，文件中如果有 dev 则切 dev）我觉得这样子会好一点

这样如何？

```diff
- with open("github.txt", "r", encoding="utf-8") as f:
-     cfg = f.read().split("|")
+ cfg = ["v17.0.0", "main"]
+ if os.path.exists("github.txt"):
+     with open("github.txt", "r", encoding="utf-8") as f:
+         cfg = f.read().split("|")
```

**Comment by z0z0r4** [comment]
不如不读取release，反正每次都得改

或者在action打包的时候自动写一份 `cfg` 进去然后 push 再打包，也省得发新版本得手动写版本号

**Comment by Drelf2018** [comment]
https://github.com/Nemo2011/bilibili-api/blob/main/.github/workflows/python-publish.yml#L24-L25

`github.txt` 就是 `action` 自动导出的

**Comment by z0z0r4** [comment]
我指的是直接替换里面的版本而不是存到 `github.txt` 再读取

**Comment by Drelf2018** [comment]
打包的时候用的代码是你提交 release 的时候打 tag 的那一刻的版本，在这之后的修改不会被打包，怎么实现push后再打包？

**Comment by z0z0r4** [comment]
你指的是 release 里面的那份？那没办法吧...我指的是仓库里那份

**Comment by z0z0r4** [comment]
> > 如果有文件则覆盖原有设置，然后提供一个默认设置，（如默认 main，文件中如果有 dev 则切 dev）我觉得这样子会好一点
> 
> 这样如何？
> 
> ```diff
> - with open("github.txt", "r", encoding="utf-8") as f:
> -     cfg = f.read().split("|")
> + cfg = ["v17.0.0", "main"]
> + if os.path.exists("github.txt"):
> +     with open("github.txt", "r", encoding="utf-8") as f:
> +         cfg = f.read().split("|")
> ```

close
