### ISSUE TITLE
[提问] 使用bangumi.set_follow()取消番剧订阅报错

### ISSUE THREAD

**Issue by CalhounChen** [Nemo2011/bilibili-api#544]
**Python 版本：** 3.11.5

**模块版本：** 16.1.1

**运行环境：** Windows 11 22635.2483

**模块路径：** `bilibili_api.bangumi`

**解释器：** cpython

**报错信息：**

```
try to cancel bangumi 辉夜大小姐想让我告白～天才们的恋爱头脑战～
Traceback (most recent call last):
  File "D:\DevHome\PythonProjects\playground\src\bili.py", line 90, in <module>
    info = ASYNC_RUN(cancel_bgm(c))
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DevHome\PythonProjects\playground\src\utils.py", line 72, in ASYNC_RUN
    return asyncio.get_event_loop().run_until_complete(ff)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\11376\.pyenv\pyenv-win\versions\3.11.5\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\DevHome\PythonProjects\playground\src\bili.py", line 72, in cancel_bgm
    res = await bangumi.set_follow(bangumi=b, status=False, credential=cred)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DevHome\PythonProjects\playground\.venv\Lib\site-packages\bilibili_api\bangumi.py", line 1254, in set_follow
    return await Api(**api, credential=credential).update_data(**data).result
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DevHome\PythonProjects\playground\.venv\Lib\site-packages\bilibili_api\utils\network.py", line 170, in result
    self.__result = await self.request()
                    ^^^^^^^^^^^^^^^^^^^^
  File "D:\DevHome\PythonProjects\playground\.venv\Lib\site-packages\bilibili_api\utils\network.py", line 70, in inner
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DevHome\PythonProjects\playground\.venv\Lib\site-packages\bilibili_api\utils\network.py", line 331, in request
    raise ResponseCodeException(code, msg, resp_data)
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：-401，信息：未授权。
{'code': -401, 'message': '未授权'}
```

**报错代码：**

```
async def cancel_bgm(cred: Credential):
    b = Bangumi(5267730, credential=cred)
    assert_that(b.get_season_id()).is_equal_to(26274)
    info = await b.get_overview()
    print("try to cancel bangumi {}".format(info["title"]))
    resp = await bangumi.set_follow(bangumi=b, status=False, credential=cred)
    return resp
```

使用```bangumi.set_follow()```取消番剧订阅无效并报错-401未授权。
使用```bangumi.update_follow_status()```更新追番状态也同样报错-401未授权。
我不太清楚这是bug还是我使用不当，所以选择了提问模板。

**Comment by z0z0r4** [comment]
你确定登录没过期吗

**Comment by CalhounChen** [comment]
> 你确定登录没过期吗
我使用```bilibili_api.credential.Credential.check_valid()```来检查凭据的有效性，返回值为True。这应该算没过期吧？

**Comment by z0z0r4** [comment]
这就很抽象了，我这是 `-400` 大雾

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/9fcd63fc-54db-4009-952c-e58fa5434678)

**Comment by z0z0r4** [comment]
emm，我实在复现不出 `-401` 的情况

有传 `bili_jct` 吗（但这情况也是 `-111`...

**Comment by z0z0r4** [comment]
你姑且可以试试看 dev 分支里面的那个 commit 有没有效果

https://github.com/Nemo2011/bilibili-api/pull/547

**Comment by CalhounChen** [comment]
> emm，我实在复现不出 `-401` 的情况
> 
> 有传 `bili_jct` 吗（但这情况也是 `-111`...

我是从已登录账号的浏览器内获取的```sessdata```、```bili_jct```、```buvid3```、```dedeuserid```、```ac_time_value```然后传入```bangumi.credential.Credential()```实例化出一个```cred```来使用的。

**Comment by CalhounChen** [comment]
> 你姑且可以试试看 dev 分支里面的那个 commit 有没有效果
> 
> #547

好的，我试试。

**Comment by CalhounChen** [comment]
> 你姑且可以试试看 dev 分支里面的那个 commit 有没有效果
> 
> #547

参考https://github.com/Nemo2011/bilibili-api/issues/541#issuecomment-1764751656 进行离线安装后再次尝试上述代码，仍然报错```{'code': -401, 'message': '未授权'}```
![image](https://github.com/Nemo2011/bilibili-api/assets/41644510/17ab0204-8e1c-4108-89c1-d42574e05a63)

**Comment by z0z0r4** [comment]
完全不理解3..

**Comment by CalhounChen** [comment]
> 完全不理解3..

可能是登录方式的问题？我更换登录方式为```login.login_with_password()```后，并且使用dev分支，取消订阅的操作成功了。
然后登录方式不变，安装回16.1.1版，此时报错```{'code': -400, 'message': '请求错误'}```，与你先前实验的结果一致了。

**Comment by z0z0r4** [comment]
你原来用的啥登录方式

**Comment by CalhounChen** [comment]
> 你原来用的啥登录方式

我原来用的是```login.login_with_qrcode()```，登录后把获取的cred的```sessdata```、```bili_jct```等写入到一个本地的.env文件里以免重复扫码。(说是 _从浏览器获取_，其实不算)

**Comment by z0z0r4** [comment]
我觉得这应该不是原因，但你那边能解决就这样吧
