### ISSUE TITLE
[漏洞] Dynamic 接口 -352

### ISSUE THREAD

**Issue by LXRee** [Nemo2011/bilibili-api#561]
**Python 版本：** 3.9.7

**模块版本：** 15.5.0

**运行环境：** Windows

**模块路径：** `bilibili_api.dynamic`

**解释器：** cpython / pypi / jython

**报错信息：**

```
File "D:\software\anaconda\lib\site-packages\bilibili_api\utils\network_httpx.py", line 471, in inner
    return await func(*args, **kwargs)
  File "D:\software\anaconda\lib\site-packages\bilibili_api\utils\network_httpx.py", line 447, in wrapper
    return await request_old(*args, **kwargs)
  File "D:\software\anaconda\lib\site-packages\bilibili_api\utils\network_httpx.py", line 399, in request_old
    raise ResponseCodeException(code, msg, resp_data)
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：-352，信息：-352。
{'code': -352, 'message': '-352', 'ttl': 1}

```

**报错代码：python3.0版本**

```
my_dynamic = dynamic.Dynamic(840145150107713544)
    print('dy_id: ', my_dynamic.get_dynamic_id())
    dynamic_data = []
    dy_info = await my_dynamic.get_info()
dynamic.get_info函数报错，显示网络连接错误
```

---

1.有时候可以跑通，但是有时候又不可以跑通，感觉应该是b站的反爬机制变严格了

**Comment by z0z0r4** [comment]
-352 是什么状态...

**Comment by LXRee** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我已收到你发送的管理学作业。

**Comment by LXRee** [comment]
我给你发一张报错的图片，具体见附件，上面显示的是-352，是这样的，就是感觉应该是b站和动态有关的这个接口变严格了，所以看到的就是这样




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nemo2011/bilibili-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月9日(星期四) 晚上10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nemo2011/bilibili-api] [漏洞] Dynamic 接口 -532 (Issue #561)





 
-352 是什么状态...

**Comment by z0z0r4** [comment]
没看到有附件…

**Comment by LXRee** [comment]
我给你发一张报错的图片，具体见附件，上面显示的是-352，是这样的，就是感觉应该是b站和动态有关的这个接口变严格了，所以看到的就是这样（你没有看到一张图片吗，就是有一张单独的图片，上面显示的就是微信图片.png,我这次把它添加到正文了，你再看看)






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Nemo2011/bilibili-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月9日(星期四) 晚上10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nemo2011/bilibili-api] [漏洞] Dynamic 接口 -532 (Issue #561)





 
-352 是什么状态...

**Comment by blyc** [comment]
你要不试试用网页来回复吧（

**Comment by z0z0r4** [comment]
我觉得你不用发也行了...@blyc 有空看下吗？我在学校...周日抽空赶音频上传没空处理这个qeq

**Comment by blyc** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/issues/686
这里有讨论相关问题

还是风控返回的code，虽然里边提到了一些解决方案，但我试了不登录用B站网页都能在刷新几次后触发，追求稳定还是用登录账号的cookie吧
![图片](https://github.com/Nemo2011/bilibili-api/assets/34291620/a6a93d3d-cde5-49b2-8c2e-928ec838f62f)

**Comment by z0z0r4** [comment]
> [SocialSisterYi/bilibili-API-collect#686社交姐姐易/bilibili-API-collect#686](https://github.com/SocialSisterYi/bilibili-API-collect/issues/686) 这里有讨论相关问题
> 
> 还是风控返回的code，虽然里边提到了一些解决方案，但我试了不登录用B站网页都能在刷新几次后触发，追求稳定还是用登录账号的cookie吧 ![图片](https://user-images.githubusercontent.com/34291620/282646695-a6a93d3d-cde5-49b2-8c2e-928ec838f62f.png)

登录后能触发吗？

**Comment by blyc** [comment]
> > [SocialSisterYi/bilibili-API-collect#686社交姐姐易/bilibili-API-collect#686](https://github.com/SocialSisterYi/bilibili-API-collect/issues/686) 这里有讨论相关问题
> > 还是风控返回的code，虽然里边提到了一些解决方案，但我试了不登录用B站网页都能在刷新几次后触发，追求稳定还是用登录账号的cookie吧 ![图片](https://user-images.githubusercontent.com/34291620/282646695-a6a93d3d-cde5-49b2-8c2e-928ec838f62f.png)
> 
> 登录后能触发吗？

![图片](https://github.com/Nemo2011/bilibili-api/assets/34291620/ea34f786-afe5-498e-966a-a847e84cad7e)
登录账号短时间重发了24次左右这个请求(1-2s一次)，可惜没来得及触发`-532`先触发了`-412`，~测试需谨慎啊~

**Comment by z0z0r4** [comment]
我只能说等我来测试估计就寒假了.jpg

**Comment by blyc** [comment]
登录和不登录各以 10s一次 轮询5分钟以上 均未触发`-532`和`-412`
正在测试5s一次

**Comment by z0z0r4** [comment]
看不太懂，如果只是限制于频率触发 -532 的话， raise response code 给-532和-412加个登录提示应该会好点

假定这个反爬不是少参数的情况下，我没法确认...你这边不应该拿浏览器 devtools 来测试，建议直接走代码测才有效果

**Comment by blyc** [comment]
> 看不太懂，如果只是限制于频率触发 -532 的话， raise response code 给-532和-412加个登录提示应该会好点
> 
> 假定这个反爬不是少参数的情况下，我没法确认...你这边不应该拿浏览器 devtools 来测试，建议直接走代码测才有效果

直接用的库测试的

~~~
from apscheduler.schedulers.blocking import BlockingScheduler
from bilibili_api import Credential, sync, dynamic
from loguru import logger


def login_main():
    credential = Credential(
        sessdata='***',
        bili_jct='***',
        buvid3='***',
        dedeuserid='***'
    )
    # logger.info("已登录用户：" + sync(user.get_self_info(credential))['name'], "!")
    test(credential)


def test(credential):
    try:
        my_dynamic = dynamic.Dynamic(840145150107713544)
        resp = sync(my_dynamic.get_info())
        print(resp)
    except Exception as e:
        logger.error(f"任务异常 - {repr(e)}")


if __name__ == '__main__':
    # settings.request_log = True
    # login_main()
    scheduler = BlockingScheduler()
    scheduler.add_job(login_main, 'cron', second='*/5')
    scheduler.start()

~~~

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/issues/576

姑且算是啥也干不了，先 close 了
