### ISSUE TITLE
[需求] 获取用户的全部视频的 medialist

### ISSUE THREAD

**Issue by z0z0r4** [Nemo2011/bilibili-api#562]
https://api.bilibili.com/x/v1/medialist/info?type=1&biz_id=178827471&tid=0

可以把 UP 的视频当成 medialist 处理...虽然没啥用

**Comment by TZFC** [comment]
正好我需要这个功能，准备着手做

**Comment by TZFC** [comment]
另：这个接口有v2：
https://api.bilibili.com/x/v2/medialist/resource/list?mobi_app=web&type=1&biz_id=1733415840&oid=&otype=2&ps=20&direction=false&desc=false&sort_field=1&tid=0&with_current=false
将用v2实现

**Comment by TZFC** [comment]
已提交PR #599

**Comment by TZFC** [comment]
使用示例：
从uid=1733415840的用户上传的所有视频中，获取相对于aid=488433591的视频播放量更低的3个视频
https://colab.research.google.com/drive/1ScCIm6ZZh9PoedUzF7uqRG70HakEFNiN?usp=sharing
