### ISSUE TITLE
连接直播姬开播的直播间弹幕LIVE事件触发两次

### ISSUE THREAD

**Issue by TZFC** [Nemo2011/bilibili-api#563]
**Python 版本：** 3.11.6

**模块版本：** 16.1.1

**运行环境：** Linux
 

---

如此连接：
```python
from bilibili_api import Credential, Danmaku, sync
from bilibili_api.live import LiveDanmaku, LiveRoom
import asyncio

credential = Credential( ... )
ROOMS = [0001, 0002, 0003]
all_rooms = [LiveDanmaku(room_id = room_id, credential=credential) for room_id in ROOMS]

for room in all_rooms:
    @room.on("DANMU_MSG")
    async def recv(event):
        print(str(room.room_display_id)+"但其实是"+event["room_display_id"])

if __name__ == "__main__":
    sync(asyncio.gather(*[room.connect() for room in all_rooms]))
```
会发现， room.room_display_id 会一直是all_rooms 里最后一项的 id（此处为 0003）, 说明所有DANMU_MSG都会到最后添加的listener里去。如果针对不同room，需要的功能不同，这会出bug

目前的解决方案是通过event['room_display_id']来区分房间，可用，但并不优雅w

有什么更好的连接方式吗？

**Comment by z0z0r4** [comment]
正确方式就是调 event 来获取吧，显然你在注册了三个监视之后 room 这个变量肯定是对应最后一个

或者注册函数时存一个变量记录下来，索引出 all_rooms 里面对应的 livedanmaku 对象

**Comment by TZFC** [comment]
发现个问题：这么连接之后，一个直播间开播，那个直播间的LIVE事件会被触发多次（观测到的有2-6次不等）。然而DANMU_MSG和PREPARING事件都会正确得只触发一次。这是为什么？看起来像bug。
、、、
@room .on("LIVE")
    async def liveStart(event):
        print(event['room_display_id'])
、、、
此时若直播间0002开播，则会
0002
0002
0002
0002
0002
0002

**Comment by Drelf2018** [comment]
![image](https://github.com/Nemo2011/bilibili-api/assets/41439182/65430f88-62f9-4d18-ad5e-a5f0152ed8c0)

修改代码如上图，可以解决这个“漏洞”。这并不是本库的问题，而是涉及到 `python` 语法相关问题。

```python
for room in all_rooms:
    @room.on("DANMU_MSG")
    async def recv(event):
        print(str(room.room_display_id)+"但其实是"+event["room_display_id"])
```

`for ... in ...` 语句的实质是，遍历列表中的元素，并重复赋值给前面的 `room`。

因此在遍历结束后的 `room` 是列表中最后一个，函数 `recv` 中获取 `room.room_display_id` 实际上是最后一个房间的 `id`

截图中的代码通过调用函数把当前 `room` 闭包在函数里，此时再获取 `__room.room_display_id` 就是正确的值了。

**Comment by TZFC** [comment]
多谢解惑！我明白了

然而这并不能解决LIVE被触发多次，而DANMU_MSG和PREPARING却能正常只触发一次的奇怪现象。我研究下按照这种形式bind之后这个问题是否还存在。

**Comment by Drelf2018** [comment]
多次触发我运行没有这个问题，建议展示你的代码

**Comment by TZFC** [comment]
在这里
https://github.com/TZFC/BiliLiveManager/blob/9ee34ebef06ad2755d9c10fe9a786406de2ce1db/master.py

**Comment by TZFC** [comment]
触发次数看起来是随机的，有时只有1次，有时多至6次。

**Comment by Drelf2018** [comment]
多次测试均无法复现，请下次出现这种情况时记录每个 `LIVE` 事件的触发时间，可能是主播多次开播/推流导致。

**Comment by TZFC** [comment]
嗯，这个我记录了。 对比了每次触发的 'live_start_time'都是一样的，其它项我还在对比，看起来顺序不一样但内容应该是一样的？还在对比。
有没有可能是因为我在做测试的时候直接ctrl+c切断，导致没有把eventloop清理干净，导致有多个bind? 因为看到有issue提到建议一直connect就没有设置任何disconnect的机会点

**Comment by TZFC** [comment]
确认是我的问题了。看来ctrl+c并不会清空监视。
第一遍运行函数为 print("first run")
ctrl+c 切断
第二遍运行改成 print("second run")
会发现开播的时候 
first run
second run
都被打印出来了
暂时的解决方法是在 ctrl+c 切断后重启电脑 （deactivate venv或许足够？还在测试）
更好的做法是设置弹幕指令 disconnect

**Comment by TZFC** [comment]
经过这几天的观测，发现用直播姬开播会发送两次 LIVE。第二次与非直播姬开播相同。第一次的 LIVE 事件缺少 live_time项。
这算bug吗？不确定

**Comment by TZFC** [comment]
例子：
直播姬开播第一次LIVE
```
{'room_display_id': '23808442', 'room_real_id': 23808442, 'type': 'LIVE', 'data': {'cmd': 'LIVE', 'live_key': '427687693693700538', 'voice_background': '', 'sub_session_key': '427687693693700538sub_time:1700218359', 'live_platform': 'pc_link', 'live_model': 0, 'roomid': 23808442}}
```
直播姬开播第二次LIVE
```
{'room_display_id': '23808442', 'room_real_id': 23808442, 'type': 'LIVE', 'data': {'cmd': 'LIVE', 'live_key': '427687693693700538', 'voice_background': '', 'sub_session_key': '427687693693700538sub_time:1700218359', 'live_platform': 'pc_link', 'live_model': 0, 'roomid': 23808442, 'live_time': 1700218359}}
```
其它方式开播唯一一次LIVE
```
{'room_display_id': '23596840', 'room_real_id': 23596840, 'type': 'LIVE', 'data': {'cmd': 'LIVE', 'live_key': '429154897471475496', 'voice_background': '', 'sub_session_key': '429154897471475496sub_time:1700197649', 'live_platform': 'pc', 'live_model': 0, 'roomid': 23596840, 'live_time': 1700197649}}
```

**Comment by TZFC** [comment]
目前我的项目里的逻辑是，如果没有live_time就直接return。我认为有必要在这个库里就直接把没有这项的LIVE忽略掉

**Comment by z0z0r4** [comment]
按道理是有啥返回啥 cmd 的，一般不筛选，而且后期没人监视

**Comment by ProgramRipper** [comment]
这是预期行为。带有 live_time 的 LIVE 是开播，live_time 为 null 的 LIVE 是推流开始。
