### ISSUE TITLE
[提问] 请输入验证码信息

### ISSUE THREAD

**Issue by mcgrady20150318** [Nemo2011/bilibili-api#565]
**Python 版本：** 3.11

**模块版本：** latest

**运行环境：**  MacOS

---

{'name': 'SUBMIT_FAILED', 'data': ({'err': ResponseCodeException('请输入验证码信息')},)}
{'name': 'FAILED', 'data': ({'err': ResponseCodeException('请输入验证码信息')},)}

 今天开始总是报错，sessdata等cookie信息都是和浏览器一致的。

**Comment by z0z0r4** [comment]
去网页版过下验证码 xd

**Comment by mcgrady20150318** [comment]
> 去网页版过下验证码 xd

credential = Credential(sessdata=sessdata, bili_jct=bili_jct, buvid3=buvid3)
credential.raise_for_no_bili_jct() # 判断是否成功
credential.raise_for_no_sessdata()
print("欢迎，", sync(user.get_self_info(credential))['name'], "!")
登陆都是没问题的，之前自动上传视频的时候一直可以用，今天突然就总是被问验证码，其他功能都是正常的。莫非是被封了？

**Comment by z0z0r4** [comment]
你是看不懂吗？去浏览器过验证码

**Comment by mcgrady20150318** [comment]
> 你是看不懂吗？去浏览器过验证码

我用网页过了验证码，不能每次都得手动去过验证码吧？那不然用你这API干啥？！

**Comment by z0z0r4** [comment]
你这么聪明教教我极验的验证码怎么自动化处理，人机验证不自己去浏览器过要你来干嘛

**Comment by z0z0r4** [comment]
解决办法是自己把速率降低点，别直请求加个  sleep

**Comment by mcgrady20150318** [comment]
> 你这么聪明教教我极验的验证码怎么自动化处理，人机验证不自己去浏览器过要你来干嘛

你这交流态度有点让人费解！

不管怎么样，还是感谢你提供的工具，另外audio upload那个功能需求也是我提出的，目前来看也没啥用了。

**Comment by z0z0r4** [comment]
我倒是好奇极验的验证码怎么自动化来过

阿寻思还m

**Comment by mcgrady20150318** [comment]
> 我倒是好奇极验的验证码怎么自动化来过
> 
> 属于是不理解了，爬虫库哪有提供过人机的道理的
> 
> 如果你是视频上传模块触发的根本没法规避，网页版正常提交一大堆视频应该也会触发
> 
> 办法只有队列上传加个 delay

我这边上传视频的频率是40min一个，一直都没问题。这两天导致验证码出现的问题是，咖啡馆的网络不稳定，在传视频的时候一直是无限的upload chunk，估计这样触发了b站的安全机制。所以过来问问大家遇没遇到类似问题。。。。结果你这一上来一顿输出。。。

**Comment by z0z0r4** [comment]
https://github.com/kuresaru/geetest-validator 极验验证码，你如果有兴趣自己破

或者去 biliup 那边找人看看上传风控，这边没人监视的

**Comment by mcgrady20150318** [comment]
> https://github.com/kuresaru/geetest-validator 极验验证码，你如果有兴趣自己破
> 
> 或者去 biliup 那边专做上传找人看看上传风控，这边没人监视的

谢谢。

**Comment by z0z0r4** [comment]
biliup 点击链接加入群聊【超频的开关】：http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=J0rhd5pXweOBNT4lyhba95MZrZQv6XmI&authKey=M
