### ISSUE TITLE
Dynamic模块下单条动态内容请求遭拒

### ISSUE THREAD

**Issue by XiMixxx** [Nemo2011/bilibili-api#569]
dynamic.get_info()函数调用时遭拒，报错：
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：-352，信息：-352。
{'code': -352, 'message': '-352', 'ttl': 1}

我自己的代码中有加入credentials，同时在请求每条动态的内容（get_info）时也设置了time.sleep(10)。
能获取几条动态，但几条之后就会报错-352，推测是B站的反爬变严了。

请问是否有办法解决？

感谢！辛苦！

**Comment by z0z0r4** [comment]
转 https://github.com/Nemo2011/bilibili-api/issues/561
