### ISSUE TITLE
【需求】考虑 Bangumi 模块对部分特殊番剧的基本信息获取适配

### ISSUE THREAD

**Issue by sudoskys** [Nemo2011/bilibili-api#57]
```
Traceback (most recent call last):
.................
    ep = bangumi.Episode(675686)
  File "/home/xxx/miniconda3/envs/biliMonitor/lib/python3.8/site-packages/bilibili_api/bangumi.py", line 212, in __init__
    raise ApiException("未找到番剧信息")
bilibili_api.exceptions.ApiException.ApiException: 未找到番剧信息
```
## 问题描述
在对特殊类型，如`ep675686`进行
```
ep = bangumi.Episode(675686)
print(ep.get_aid())
```
会发生 404 错误

## 测试例
```
from bilibili_api import bangumi, sync
from bilibili_api.bangumi import Bangumi
async def main():
    ep = bangumi.Episode(675686)
    # 打印 bv 号674245
    print(ep.get_aid())
sync(main())
```

ep 对应页面不可访问，match取空
```
pattern = re.compile(r"window.__INITIAL_STATE__=(\{.*?\});")
match = re.search(pattern, content)
```

但是请观察以下 Api
[原始Api](https://api.bilibili.com/pgc/view/web/season?ep_id=675686) 
[子Api](https://bangumi.bilibili.com/view/web_api/season?ep_id=675686)

利用子 Api ，不可访问的 ep 剧集 所属番剧信息也是可以得到的，是否可以改善 Bangumi ?

**Comment by sudoskys** [comment]
搞错了，ep_id 参数完全不起作用，获取的是ep对应的概览？

**Comment by Nemo2011** [comment]
<img width="1475" alt="test" src="https://user-images.githubusercontent.com/91071485/190112528-4f9fc11b-dba8-48a5-bf7e-d9461d319ac3.png">

**Comment by sudoskys** [comment]
> <img alt="test" width="1475" src="https://user-images.githubusercontent.com/91071485/190112528-4f9fc11b-dba8-48a5-bf7e-d9461d319ac3.png">

但是基本信息还是可以访问。

例如 https://www.bilibili.com/bangumi/media/md28338523 这种页面，传入相应的 ss 号码或 ep 号会发生错误，也就获取不到这个页面上的剧集。
（因为需要 ss 传参的Api对于这种番剧并不可用）

主要问题是，如果是大陆不存在的ep号，就获取不到 media 页面上公开的 信息
