### ISSUE TITLE
[提问] 视频在线人数监测的计算方法

### ISSUE THREAD

**Issue by 30000lightyears** [Nemo2011/bilibili-api#572]
**Python 版本：** 3.11

**模块版本：** 15.5.1

**运行环境：** Windows

---

在监测视频在线人数算法时，发现回传数据与b站显示数据相差较大，代码是文档中提供的例程
<img width="676" alt="image" src="https://github.com/Nemo2011/bilibili-api/assets/66123770/e544a60d-c84d-40f1-bc14-fa0d7972bcd2">
<img width="841" alt="image" src="https://github.com/Nemo2011/bilibili-api/assets/66123770/1f9b0148-2921-42fd-b2dc-11315ca794e0">

**Comment by blyc** [comment]
怀疑该方法已被B站弃用，现在B站使用的获取在线人数方法为http轮询，
请求示例：https://api.bilibili.com/x/player/online/total?bvid=BV1zC4y1j7BY&cid=1336344014
BAC参考：https://socialsisteryi.github.io/bilibili-API-collect/docs/video/online.html#%E8%8E%B7%E5%8F%96%E8%A7%86%E9%A2%91%E5%9C%A8%E7%BA%BF%E4%BA%BA%E6%95%B0-web%E7%AB%AF

**Comment by 30000lightyears** [comment]
OK，感谢您

**Comment by z0z0r4** [comment]
fixing

**Comment by z0z0r4** [comment]
勉强还算准，不清楚，你那应该是B站 redis 之类缓存的原因，至于网页版是在用哪个不清楚

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/a861eff2-2dda-4b16-9e13-d18b4e405337)


会给新接口新增一个单独的封装

**Comment by z0z0r4** [comment]
明白了...这哪来的误差，就是准的，蚌

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/1ceb1724-8dca-46c9-bb18-da7920303ded)


https://github.com/z0z0r4/bilibili-api/commit/dc449d97e8baa3b93741a98936b1ed06b34039f7
