### ISSUE TITLE
[提问] 上传视频，提交报错：系统升级中，敬请谅解

### ISSUE THREAD

**Issue by l-qiang** [Nemo2011/bilibili-api#574]
**Python 版本：** 3.11

**模块版本：** 16.1.1

**运行环境：** Windows 

---

`{'name': 'FAILED', 'data': ({'err': ResponseCodeException('系统升级中，敬请谅解')},)}`

> bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：21171，信息：系统升级中，敬请谅解。
> {'code': 21171, 'message': '系统升级中，敬请谅解', 'ttl': 1}

**Comment by z0z0r4** [comment]
看不懂，是B站真在维护？

**Comment by l-qiang** [comment]
> 看不懂，是B站真在维护？
没有维护，网页是可以正常上传的

**Comment by l-qiang** [comment]
> 看不懂，是B站真在维护？

没有维护，B站网页可以正常上传

**Comment by z0z0r4** [comment]
你等我周末看看，把示例发上来先

**Comment by l-qiang** [comment]
`
        paths = 'D:/autodownload/20231120/xxx/14.mkv'
        folder, filename = os.path.split(path)
        os.chdir(folder)
       # 下面是视频剪切逻辑
        v = Video(filename, job_meta.ss, job_meta.ds)
        if job_meta.is_cut0():
            v_folder = v.cut0()
        else:
            v_folder = v.cut()
        filenames = os.listdir(v_folder)
        os.chdir(v_folder)
        # 上传再这里
        bili.upload(job_meta.v_name, v_folder, filenames)
`
`
import os.path

from bilibili_api import Credential, sync, video_uploader


class Bili(object):
    __slots__ = '__credential'

    def __init__(self, sessdata, bili_jct, buvid3, dedeuserid, ac_time_value):
        self.__credential = Credential(sessdata=sessdata, bili_jct=bili_jct, buvid3=buvid3, dedeuserid=dedeuserid,
                                       ac_time_value=ac_time_value)

    def refresh(self):
        if sync(self.__credential.check_refresh()):
            sync(self.__credential.refresh())
        return self.__credential

    def upload(self, name, num, videos: list[str]):
        sync(self.__async_upload(name, num, videos))

    async def __async_upload(self, name, num, videos: list[str]):
        meta = {
            "act_reserve_create": 0,
            "copyright": 1,
            "source": "",
            "desc": "",
            "desc_format_id": 0,
            "dynamic": "",
            "interactive": 0,
            "no_reprint": 1,
            "open_elec": 0,
            "origin_state": 0,
            "subtitles": {
                "lan": "",
                "open": 0
            },
            "tag": f"{name}",
            "tid": 71,
            "title": f"{name}{num}",
            "up_close_danmaku": False,
            "up_close_reply": False,
            "up_selection_reply": False,
            "dtime": 0
        }
        pages = []
        for video in videos:
            n, ext = os.path.splitext(video)
            pages.append(video_uploader.VideoUploaderPage(path=video, title=n, description=''))
        uploader = video_uploader.VideoUploader(pages, meta, self.__credential, cover='')

        @uploader.on("__ALL__")
        async def ev(data):
            print(data)

        await uploader.start()

`

**Comment by l-qiang** [comment]
下载部分暂时使用biliup替换，这个问题不着急

**Comment by z0z0r4** [comment]
盲猜分区id错了，纯猜

**Comment by l-qiang** [comment]
> 盲猜分区id错了，纯猜

算了，就这样吧，感谢你的回复
