### ISSUE TITLE
[提问] utils下的解析器如何解析登录信息

### ISSUE THREAD

**Issue by nooblong** [Nemo2011/bilibili-api#583]
**Python 版本：** 3.11.5

**模块版本：** main

**运行环境：** Windows

---

我试过这样：
{{urlpy}}/channel_series.ChannelSeries(id_=1284839,type_=channel_series.ChannelSeriesType.SEASON:parse).get_meta()?credential=Credential(bili_jct={{bili_jct}},buvid3={{buvid3}},sessdata={{sessdata}})

也试过这样：
{{urlpy}}/channel_series.ChannelSeries(id_=1284839,type_=channel_series.ChannelSeriesType.SEASON:parse,credential=Credential(bili_jct={{bili_jct}},buvid3={{buvid3}},sessdata={{sessdata}}):parse).get_meta()

发现都不行

还发现解析credential类时，sessdata存在'%2C'时会被解析器解析逗号而当成多个字段，导致解析不到完整的sessdata。

我该怎么去解析需要credential参数的类

**Comment by Drelf2018** [comment]
将所有 `%2C` 替换为 `%252C`

其中 `%25` 含义是 `%` 的 `html` 转义，使得后端接收到的转义后字符仍为 `%2C`

**Comment by Drelf2018** [comment]
此外使用链接时应为如下格式

```
/channel_series.ChannelSeries(id_=1284839,type_=channel_series.ChannelSeriesType.SEASON:parse,credential=credential).get_meta()?credential=Credential(...)
```
