### ISSUE TITLE
[提问] get_comments()中的oid参数该如何获取

### ISSUE THREAD

**Issue by Feng-Jay** [Nemo2011/bilibili-api#586]
**Python 版本：** 3.9.10

**模块版本：** 16.1.1

**运行环境：** MacOS

---
在文档中comment部分对oid的说明如下:
>关于资源 ID（oid）的一些示例（{}部分为应该传入的参数）。
>视频：AV 号：av{170001}。
>专栏：cv{9762979}。
>动态（画册类型）：{116859542}。
>动态（纯文本）：{497080393649439253}。

请问现在视频以BV开头，应该如何获得oid呢？

**Comment by blyc** [comment]
理论上大部分接口获取视频信息时候同时也会有`aid`字段的（字段名不确定，但是会有av号），这种可以直接用

或者如果确实只有bv号的话，`video.Video(bvid='BV1PN411j7eR').get_aid()`获取一下就是了

**Comment by Feng-Jay** [comment]
好的好的，感谢回答 🌞
