### ISSUE TITLE
[漏洞] 无法刷新token

### ISSUE THREAD

**Issue by Marrylatiao** [Nemo2011/bilibili-api#592]
**Python 版本：** 3.10.13

**模块版本：** 16.1.1

**运行环境：** MacOS

**模块路径：** `bilibili_api.credential`

**解释器：** cpython / pypi / jython

**报错信息：**

```
  File "/python3.10/site-packages/bilibili_api/credential.py", line 51, in refresh
    new_cred: Credential = await refresh_cookies(self)
  File "/python3.10/site-packages/bilibili_api/credential.py", line 144, in refresh_cookies
    refresh_csrf = await get_refresh_csrf(credential)
  File "/python3.10/site-packages/bilibili_api/credential.py", line 128, in get_refresh_csrf
    raise Exception("获取刷新 Cookies 的 csrf 失败。")
Exception: 获取刷新 Cookies 的 csrf 失败。
```

---

构造的token信息包含这些,按照文档说明应该是可以刷新token, 但是刷新会报错
```
credential = Credential(
    sessdata="xxx",
    bili_jct="xxx",
    buvid3="xxx",
    dedeuserid="xxx",
    ac_time_value="xxx")
```

**Comment by TZFC** [comment]
+1 dev分支也有这个错误，从今天开始的

**Comment by TZFC** [comment]
> **Python 版本：** 3.10.13
> 
> **模块版本：** 16.1.1
> 
> **运行环境：** MacOS
> 
> **模块路径：** `bilibili_api.credential`
> 
> **解释器：** cpython / pypi / jython
> 
> **报错信息：**
> 
> ```
>   File "/python3.10/site-packages/bilibili_api/credential.py", line 51, in refresh
>     new_cred: Credential = await refresh_cookies(self)
>   File "/python3.10/site-packages/bilibili_api/credential.py", line 144, in refresh_cookies
>     refresh_csrf = await get_refresh_csrf(credential)
>   File "/python3.10/site-packages/bilibili_api/credential.py", line 128, in get_refresh_csrf
>     raise Exception("获取刷新 Cookies 的 csrf 失败。")
> Exception: 获取刷新 Cookies 的 csrf 失败。
> ```
> 
> 构造的token信息包含这些,按照文档说明应该是可以刷新token, 但是刷新会报错
> 
> ```
> credential = Credential(
>     sessdata="xxx",
>     bili_jct="xxx",
>     buvid3="xxx",
>     dedeuserid="xxx",
>     ac_time_value="xxx")
> ```

这个报错可以使用dev分支解决

**Comment by TZFC** [comment]
试了下dev回退到6个commit之前是没问题的。

**Comment by blyc** [comment]
https://github.com/Nemo2011/bilibili-api/pull/593/files

可否测试下根据该提交增加headers后是否修复

**Comment by z0z0r4** [comment]
> 修复了，感谢！另：import 的时候报错syntax error. bilibili_api/ass.py 196行少了半个括号
> 
> ```
> cid = await v._Video__get_cid_by_index(page)
> ```

dev 分支没看到

https://github.com/Nemo2011/bilibili-api/blob/11c33b16003f3111684421fb9ad4cbea5833ef18/bilibili_api/ass.py#L196

**Comment by z0z0r4** [comment]
`pip install bilibili-api-dev --upgrade`

**Comment by nooblong** [comment]
dev分支解决了《获取刷新 Cookies 的 csrf 失败。》，但是还有《correspondPath过期或错误。》

> `pip install bilibili-api-dev --upgrade`
