### ISSUE TITLE
函数名错误

### ISSUE THREAD

**Issue by kaixinol** [Nemo2011/bilibili-api#597]
https://github.com/Nemo2011/bilibili-api/blob/11c33b16003f3111684421fb9ad4cbea5833ef18/bilibili_api/hot.py#L31
https://github.com/Nemo2011/bilibili-api/blob/11c33b16003f3111684421fb9ad4cbea5833ef18/bilibili_api/rank.py#L235
`weakly`应该更名为`weekly`

**Comment by z0z0r4** [comment]
逆天，改了，哪里的 weakly

https://github.com/Nemo2011/bilibili-api/commit/dce9402fe691b1910a841234386b1cc75729b129
