### ISSUE TITLE
[提问] 如何下载视频片段？

### ISSUE THREAD

**Issue by TZFC** [Nemo2011/bilibili-api#602]
**Python 版本：** 3.11.6

**模块版本：** dev

**运行环境：** Linux

---

我想实现下载视频片段的功能。需求来自直播切片，下载完整的好几小时录播导入剪辑软件对网络和电脑都是没必要的压力。

看了[示例代码](https://github.com/Nemo2011/bilibili-api/blob/main/docs/examples/video.md#%E7%A4%BA%E4%BE%8B%E4%B8%8B%E8%BD%BD%E8%A7%86%E9%A2%91)， 感觉大概应该在获取到的url上添加额外的参数？类似视频精准空降是的"t=78.7”? 然而直接附上“&t=78.7”并没有从第78.7秒开始，参数名称不一样。

观察到访问精准空降链接时，“78.7”这个值始终出现在 referer 里面，于是尝试在 download_url 时 
```
HEADERS["Referer"]="https://www.bilibili.com/video/BV1Zp4y1T7iu/?t=78.7"
```
然而这么做并没有任何作用，还是把视频完整得下载下来了

请问应该怎么达成从视频中途下载的效果呢？

另外，resp = await sess.get(url) 似乎会直接把视频下载完整后再return？有没有什么办法可以在下载到某个时间点打断呢？

**Comment by TZFC** [comment]
我的完整代码：[bv2video.py](https://github.com/TZFC/bv2video/blob/d04b8945e7c8e80f58a8cf3b3aeaa26526f5dbc8/bv2video.py)

**Comment by z0z0r4** [comment]
你得参考web端下载片段m4s，周末再看看

**Comment by z0z0r4** [comment]
评价是太麻烦了...做不到，我不了解dash规范，拿到了segment index也不会用

**Comment by z0z0r4** [comment]
你可以直接用 yt-dlp 来下载指定片段，具体好像是调的 ffmpeg 看不懂

`yt-dlp https://www.bilibili.com/video/BV1du4y1K7Di --download-section "*00:01:30-00:02:38"`
