### ISSUE TITLE
[提问] 使用二维码登录失败

### ISSUE THREAD

**Issue by iconFehu** [Nemo2011/bilibili-api#622]
**Python 版本：** 3.12.1

**模块版本：** 16.1.1（dev）

**运行环境：** Windows

---

在使用dev分支已传入credential的情况下无法登录（扫码后点击确认登录无反应）
当前设置的HTTP 客户端为HTTPClient.AIOHTTP

**Comment by iconFehu** [comment]
@Nemo2011 有没有联系方式，整个管理员呗，不忙的时候可以帮忙维护

**Comment by Aiyu-awa** [comment]
> @Nemo2011 有没有联系方式，整个管理员呗，不忙的时候可以帮忙维护

交pr

**Comment by z0z0r4** [comment]
个人认为不负责的管理员比接单跑路更难以接受，还得收拾烂摊子=。=

**Comment by blyc** [comment]
一点日志和代码都没有啊（倒地）

**Comment by z0z0r4** [comment]
dev fixed
