### ISSUE TITLE
[漏洞] update_qrcode_data无法使用

### ISSUE THREAD

**Issue by secrectFG** [Nemo2011/bilibili-api#627]
**Python 版本：** 3.10.13

**模块版本：** 16.1.1

**运行环境：** Windows

**模块路径：** `bilibili_api.login`

**解释器：** cpython / pypi / jython

**报错信息：update_qrcode_data 函数报错，<Response [412 Precondition Failed]>，需要加入header参赛，自己测试加入后就不会报错

**Comment by blyc** [comment]
尝试用dev版本再次测试
https://github.com/Nemo2011/bilibili-api/issues/588#issuecomment-1854024521
