### ISSUE TITLE
[漏洞] send_msg方法返回成功，但没发送

### ISSUE THREAD

**Issue by JiaLeDe** [Nemo2011/bilibili-api#631]
当前最新的dev版本中，使用send_msg方法：sync(session.send_msg(credential, 352869824, '1',"nihao"))。返回成功，但是并没有发送，在自己的消息中也看不到

**Comment by blyc** [comment]
直接通过网页发送能发出去吗？（现在有未互动一条私信限制，先排除这个可能）

**Comment by z0z0r4** [comment]
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/4e4c394c-efab-4a0c-97ef-92d8482ee02a)

我这边能正常发送，以及限制会触发报错的

`接口返回错误代码：21047，信息：你最多发送1条消息，对方回复或者关注你后可以继续发消息~。`

**Comment by blyc** [comment]
测试同样能发送

以及，msg_type直接传字符串1居然能发送吗？我测试直接报错了
![图片](https://github.com/Nemo2011/bilibili-api/assets/34291620/c7f4460a-d749-44ba-a59d-94e343249e87)

**Comment by kizkdaisuki** [comment]
这个发送数据类型的type写错了

**Comment by z0z0r4** [comment]
> 这个发送数据类型的type写错了

确实，但咋没报错...

**Comment by kizkdaisuki** [comment]
> > 这个发送数据类型的type写错了
> 
> 确实，但咋没报错...

确实按照这个代码逻辑来说应该会返回 信息类型不支持
![image](https://github.com/Nemo2011/bilibili-api/assets/96269873/e708112c-fc3c-4596-964a-8d1409d4b687)
