### ISSUE TITLE
[提问] {获取评论只能获取到第一页}

### ISSUE THREAD

**Issue by liuranranranran** [Nemo2011/bilibili-api#639]
**Python 版本：** 3.9

**模块版本：** 9.1.0

**运行环境：** Windows 

---

在调用comment.get_comments时第一页没有问题，但当页数为2及以上时返回的comments为空（视频实际评论多于一页的数量）
调用如下：
comments = await comment.get_comments(oid=av_number, type_=ResourceType.VIDEO,  page_index=page)
仅当page=1时能正确返回comments

{'assist': 0,
 'blacklist': 0,
 'config': {'read_only': False, 'show_up_flag': False, 'showtopic': 0},
 'control': {'answer_guide_android_url': '',
             'answer_guide_icon_url': '',
             'answer_guide_ios_url': '',
             'answer_guide_text': '',
             'bg_text': '',
             'child_input_text': '',
             'disable_jump_emote': False,
             'empty_page': None,
             'enable_charged': False,
             'enable_cm_biz_helper': False,
             'giveup_input_text': '',
             'input_disable': False,
             'preload_resources': None,
             'root_input_text': '',
             'screenshot_icon_state': 0,
             'show_text': '',
             'show_type': 0,
             'upload_picture_icon_state': 0,
             'web_selection': False},
 'folder': {'has_folded': False, 'is_folded': False, 'rule': ''},
 'mode': 0,
 'page': {'acount': 0, 'count': 0, 'num': 0, 'size': 0},
 'replies': None,
 'support_mode': None,
 'top': None,
 'upper': {'mid': 0, 'top': None, 'vote': None},
 'vote': 0}
![image](https://github.com/Nemo2011/bilibili-api/assets/75381945/a5f42b1d-c25d-4b04-8827-b366089b72b3)

**Comment by Nemo2011** [comment]
https://github.com/Nemo2011/bilibili-api/blob/11c33b16003f3111684421fb9ad4cbea5833ef18/bilibili_api/comment.py#L380-L390

https://github.com/Nemo2011/bilibili-api/blob/11c33b16003f3111684421fb9ad4cbea5833ef18/bilibili_api/comment.py#L414-L424

**Comment by liuranranranran** [comment]
> https://github.com/Nemo2011/bilibili-api/blob/11c33b16003f3111684421fb9ad4cbea5833ef18/bilibili_api/comment.py#L380-L390
> 
> https://github.com/Nemo2011/bilibili-api/blob/11c33b16003f3111684421fb9ad4cbea5833ef18/bilibili_api/comment.py#L414-L424

感谢您的答复！我在查看文档示例之前使用了credential参数，当时也是只能获取一页，我刚刚收到回复后去更新了该参数，又获取到了全部评论，事实上我之前也成功获取到全部评论过，但是一次过后常常就出现只能获取一页，请问这个有什么讲究吗，多久更新一次？

**Comment by z0z0r4** [comment]
不存在讲究，评论不给凭据只能拿到一页，那次纯狗运=。=

**Comment by liuranranranran** [comment]
> 不存在讲究，评论不给凭据只能拿到一页，那次纯狗运=。=

我的意思是我之前使用了也会有只给一页的情况出现ಥ_ಥ
