### ISSUE TITLE
[提问] {有没有方法直接获取mp4}

### ISSUE THREAD

**Issue by dsgler** [Nemo2011/bilibili-api#644]
用VideoDownloadURLDataDetecter 找出来的streams好像都是m4s，需要用ffmpeg合并音频和视频。
有没有方法直接获取mp4 的url(我是懒狗）。

**Comment by Drelf2018** [comment]
https://github.com/Nemo2011/bilibili-api/blob/13c88608214e6735c92088c8a47cd7646352af38/bilibili_api/video.py#L396-L450

调用时填入 `html5=1` ，该方法可以获取到 `.mp4` 链接，缺点是画质较低。

```python
r = await get_download_url(html5=1)
print(r.durl)
```

**Comment by dsgler** [comment]
我发现不重新编码而是直接copy的话会快很多
ffmpeg -i audio_temp.m4s -i video_temp.m4s  -c:v copy -codec copy out.mp4   
大小也小了很多（不过我的破手机不支持av1硬解就是了）

**Comment by z0z0r4** [comment]
> 我发现不重新编码而是直接copy的话会快很多 ffmpeg -i audio_temp.m4s -i video_temp.m4s -c:v copy -codec copy out.mp4 大小也小了很多（不过我的破手机不支持av1硬解就是了）

你可以选不是 av1 的流
