### ISSUE TITLE
[需求] 消息模块收到的赞支持查询指定 card 的 like_detail

### ISSUE THREAD

**Issue by Huxzhi** [Nemo2011/bilibili-api#645]
b站会通知最近哪些人给你的视频点赞，想从这里入手，不是完整的列表，最近几个应该还能看到的

api 是不是没写 查看收到的赞的一条详细信息

https://github.com/Nemo2011/bilibili-api/blob/13c88608214e6735c92088c8a47cd7646352af38/bilibili_api/data/api/session.json#L47C1-L52C9

**Comment by Drelf2018** [comment]
https://github.com/Nemo2011/bilibili-api/blob/13c88608214e6735c92088c8a47cd7646352af38/bilibili_api/session.py#L155-L173

**Comment by Huxzhi** [comment]
谢谢

last_id (Optional, int) 最后一个 ID 
  
like_time (Optional, int) 最后一个点赞发送时间 

这两个参数不理解什么意思，

get_like = await session.get_likes ( credential=credential)
获得了的是最近所有消息，但是只有5条，而且不是时间顺序

比如，我点开收到的赞，其中一条详细信息，F12看到，我就想要 其中 item 的 user 的 mid ，怎么能获取这个response

https://api.bilibili.com/x/msgfeed/like_detail?card_id=44244345455349&last_view_at=0&pn=1&build=0&mobi_app=web

![image](https://github.com/Nemo2011/bilibili-api/assets/49866441/f366b490-55c4-4de4-b99e-e02857aa2354)

只需要一个视频的的点赞记录

**Comment by z0z0r4** [comment]
这操作可以有，具体对应 card 的信息加个 feature 吧，我寒假看看做

**Comment by z0z0r4** [comment]
这是链式查询

last_id (Optional, int) 最后一个 ID

like_time (Optional, int) 最后一个点赞发送时间

代表你上一次请求拿到的最后一个 card，填进去再请求就可以拿到下一页的

**Comment by z0z0r4** [comment]
只需要一个视频的的点赞记录的话，你可以先就着那个 like_detail 用

**Comment by z0z0r4** [comment]
~~虽然我认为在评论区回复这种事并不咋地，无意义的 bot 污染评论区环境，私信回复还能理解~~

**Comment by Huxzhi** [comment]
哦哦，懂了，但是这个是我从 浏览器看到的，不会结合 这个项目一起用，python只学了皮毛，我之前学js的

项目大概是 restFul分隔 的 api 信息是 在 data 里面放着，从data里面读取api接口，然后去访问，再返回信息是吗，
如果
我想直接 拼凑 url ，再携带用户凭证，能做到吗，

谢谢

**Comment by Huxzhi** [comment]
> ~虽然我认为在评论区回复这种事并不咋地，无意义的 bot 污染评论区环境，私信回复还能理解~

只是比喻，我做了一个查询接口，用户想要查询的话，在评论区回复就好了，我就返回数据库的信息，
如果他点赞了，我就感谢支持，没点赞，就求一个赞，

只要最近的几个点赞信息就行了，我每隔20分钟就运行一次，也不需要全部

**Comment by z0z0r4** [comment]
> > ~虽然我认为在评论区回复这种事并不咋地，无意义的 bot 污染评论区环境，私信回复还能理解~
> 
> 只是比喻，我做了一个查询接口，用户想要查询的话，在评论区回复就好了，我就返回数据库的信息， 如果他点赞了，我就感谢支持，没点赞，就求一个赞，
> 
> 只要最近的几个点赞信息就行了，我每隔20分钟就运行一次，也不需要全部

你这种很容易被阿瓦隆封的，不清楚
