### ISSUE TITLE
[需求] 提供 TV 登录方式

### ISSUE THREAD

**Issue by Huxzhi** [Nemo2011/bilibili-api#649]
感觉登陆经常掉，差不多两天掉一次，

看文档说明，还可以自动刷新是吗

或者有没有其他方式可以保持登陆状态

小电视登陆
https://github.com/XiaoMiku01/fansMedalHelper

**Comment by z0z0r4** [comment]
> 这样cookie 两个就不冲突了

提供多种登录方式？这是什么意思

**Comment by z0z0r4** [comment]
> 或者有没有其他方式可以保持登陆状态

不要再在其他地方登录，一般只能这样吧

**Comment by Huxzhi** [comment]
> > 这样cookie 两个就不冲突了
> 
> 提供多种登录方式？这是什么意思

现在用的是 浏览器的cookie吧 ，再用浏览器看b站， 会导致py的脚本掉线

我看到其他登陆方式，比如 哔哩哔哩小电视TV 登录，再用浏览器看B站 也不会导致py脚本掉线

**Comment by z0z0r4** [comment]
> > > 这样cookie 两个就不冲突了
> > 
> > 
> > 提供多种登录方式？这是什么意思
> 
> 现在用的是 浏览器的cookie吧 ，再用浏览器看b站， 会导致py的脚本掉线
> 
> 我看到其他登陆方式，比如 哔哩哔哩小电视TV 登录，再用浏览器看B站 也不会导致py脚本掉线

TV，APP这些登录方式的appkey好像很经常改吧？登录了能用多久你了解吗

**Comment by z0z0r4** [comment]
> <html><body>

expires_in | num | 有效时间 | 默认：15552000秒，等于180天
-- | -- | -- | --



</body>
</html>

**Comment by Huxzhi** [comment]
这样啊，
> TV，APP这些登录方式的appkey好像很经常改 
这点没意识到
之前用了这个的粉丝牌打卡脚本，然后每日discord通知，持续了100多天，然后通知没了，不知道是梯子坏了，还是其他坏了
https://github.com/XiaoMiku01/fansMedalHelper

对的，我也是在看这个文档 的内容
https://socialsisteryi.github.io/bilibili-API-collect/docs/login/login_action/QR.html#%E7%94%B3%E8%AF%B7%E4%BA%8C%E7%BB%B4%E7%A0%81-web%E7%AB%AF

**Comment by Huxzhi** [comment]
目前 登录凭证感觉 有点困难，还在找文档看，

其他一下restFUl风格的URL 的api 感觉会容易一点，按F12 找起网络请求就好了

**Comment by z0z0r4** [comment]
其实没啥难的，就是得把这坨接口验证加个鉴权方式...

只是登录的话示例一堆

https://github.com/XiaoMiku01/fansMedalHelper/blob/master/logintool/login.go

我周六安排下:) 有一天假期，没搞完就 1/24

**Comment by Huxzhi** [comment]
谢谢 ，我又看了一下文档，好像工程会有点大， web 和 app 链接和认证参数都不一样

以给视频点赞为例

点赞视频（web端） https://api.bilibili.com/x/web-interface/archive/like  认证方式：仅可Cookie（SESSDATA）

点赞视频（APP端）https://app.bilibili.com/x/v2/view/like  认证方式：  access_key   APP 登录 Token

**Comment by z0z0r4** [comment]
> 谢谢 ，我又看了一下文档，好像工程会有点大， web 和 app 链接和认证参数都不一样
> 
> 以给视频点赞为例
> 
> 点赞视频（web端） https://api.bilibili.com/x/web-interface/archive/like 认证方式：仅可Cookie（SESSDATA）
> 
> 点赞视频（APP端）https://app.bilibili.com/x/v2/view/like 认证方式： access_key APP 登录 Token

我不太清楚，但返回示例里面提供的 `cookie_info` 能直接拿去给 sessdata 模式的用吗？

https://socialsisteryi.github.io/bilibili-API-collect/docs/login/login_action/QR.html#%E6%89%AB%E7%A0%81%E7%99%BB%E5%BD%95-tv%E7%AB%AF

如果可以就没啥工作量

**Comment by Huxzhi** [comment]
我还要再测试一下，

给视频点赞可以
```
~ curl 'https://app.bilibili.com/x/v2/view/like' \
--data-urlencode 'access_key=xxxx' \
--data-urlencode 'aid=79677524' \
--data-urlencode 'like=0'
{"code":0,"message":"0","ttl":1,"data":{"toast":"get！视频也许更多人能看见！"}}%    
```

发送评论不可以，还需要搞一个签名，但是被破解了。https://github.com/XiaoMiku01/fansMedalHelper 它可以做到，我在看源码研究

>  https://socialsisteryi.github.io/bilibili-API-collect/docs/login/login_action/QR.html#appkey-%E5%8F%AF%E7%94%A8%E5%88%97%E8%A1%A8 

> 通过某一组 APPKEY/APPSEC 获取到的 access_token，当接口需要 sign 签名时也只能使用该组 APPKEY/APPSEC，否则出现 { code: -663, message: '鉴权失败，请联系账号组', ttl: 1 } 错误。

```
➜  ~ curl 'https://api.bilibili.com/x/v2/reply/add' \
--data-urlencode 'type=1' \
--data-urlencode 'oid=243322853' \
--data-urlencode 'message=666[泠鸢yousa_awsl]' \
--data-urlencode 'plat=1' \
--data-urlencode 'access_key=xxxxxxx'
{"code":-663,"message":"鉴权失败，请联系账号组","ttl":1}% 
```

**Comment by z0z0r4** [comment]
搞定了，但只是从 TV 登录拿 cookie_info 暂时没余力做 APP 鉴权

```
c = login.login_with_tv_qrcode_term()
print(await user.get_self_info(credential=c))
```

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/pull/654

**Comment by Huxzhi** [comment]
> 搞定了，但只是从 TV 登录拿 cookie_info 暂时没余力做 APP 鉴权
> 
> 见 `login_with_app` 分支（其实应该叫 `login_with_tv` 的...
> 
> ```
> c = login.login_with_tv_qrcode_term()
> print(await user.get_self_info(credential=c))
> ```

谢谢🙏，这个access_key  和  sign 都搞定了，应该不需要其他的了吧 。评论区 的 接口是通用的，就不用改了。app和web 有部分是通用，也有不通用的

签名与鉴权有什么区别吗


```py


def app_signature(params: dict) -> dict:
    # 这个 APP 签名应该是放在 network 才对的，但暂时没空做 APP 签名，先凑合，咕咕咕
    appkey = "4409e2ce8ffd12b8"
    appsec = "59b43e04ad6965f34319062b478f83dd"
    params["appkey"] = appkey
    params = dict(sorted(params.items()))
    params["sign"] = hashlib.md5(
        (urllib.parse.urlencode(params) + appsec).encode("utf-8")
    ).hexdigest()
    return params


```

**Comment by Huxzhi** [comment]
> 这个 APP 签名应该是放在 network 才对的，但暂时没空做 APP 签名，先凑合，咕咕咕

还是说，这个签名 如果写的更通用，应该放在 请求拦截器的位置，所有app的请求都要经过拦截器的转换

**Comment by z0z0r4** [comment]
签名和鉴权没啥不同的，只是我随便叫而已...

只是提供 tv 登录很简单，但 tv 登录没法像 web 用 ac_time_value 来刷新，虽然不知道有没有人逆向过 app 的凭据刷新

如果想只在 credential 提供 access_key 就能直接用，那就得区分不能用 access_key 的接口，工作量不小

**Comment by z0z0r4** [comment]
16.2.0 实现
