### ISSUE TITLE
[需求] search 功能增强相关

### ISSUE THREAD

**Issue by LianXiaoxiang** [Nemo2011/bilibili-api#650]
**Python 版本：** 3.10.1

**模块版本：最新版

**运行环境：** Windows

关于search接口有没有类似于网页直接搜索支持带pageSize的版本 目前搜索没有分页 感觉搜索出来的接口跟在网页上看到的也不太一样

在此处写正文

**Comment by z0z0r4** [comment]
误触 close 了

虽然 search 模块很明显少了很多筛选条件，但很明显有分页参数

https://github.com/Nemo2011/bilibili-api/blob/13c88608214e6735c92088c8a47cd7646352af38/bilibili_api/search.py#L153-L167

**Comment by z0z0r4** [comment]
pagesize 是每页数量吧...

**Comment by z0z0r4** [comment]
Enhancement: 需要增加筛选参数

**Comment by LianXiaoxiang** [comment]
> pagesize 是每页数量吧...

是的 我觉得可以参考https://api.bilibili.com/x/web-interface/search/type这个接口 最多支持一次查询40条数据 文档里面的https://nemo2011.github.io/bilibili-api/#/examples/comment获取评论案例有点问题 不知道是不是api改了 第二次循环c['replies']变成了None

**Comment by z0z0r4** [comment]
> > pagesize 是每页数量吧...
> 
> 是的 我觉得可以参考[https://api.bilibili.com/x/web-interface/search/type这个接口](https://api.bilibili.com/x/web-interface/search/type%E8%BF%99%E4%B8%AA%E6%8E%A5%E5%8F%A3) 最多支持一次查询40条数据 文档里面的[https://nemo2011.github.io/bilibili-api/#/examples/comment获取评论案例](https://nemo2011.github.io/bilibili-api/#/examples/comment%E8%8E%B7%E5%8F%96%E8%AF%84%E8%AE%BA%E6%A1%88%E4%BE%8B) 有点问题 不知道是不是api改了 第二次循环c['replies']变成了None

需要提供 credential，看来是忘改了

**Comment by LianXiaoxiang** [comment]
> > > pagesize 是每页数量吧...
> > 
> > 
> > 是的 我觉得可以参考[https://api.bilibili.com/x/web-interface/search/type这个接口](https://api.bilibili.com/x/web-interface/search/type%E8%BF%99%E4%B8%AA%E6%8E%A5%E5%8F%A3) 最多支持一次查询40条数据 文档里面的[https://nemo2011.github.io/bilibili-api/#/examples/comment获取评论案例](https://nemo2011.github.io/bilibili-api/#/examples/comment%E8%8E%B7%E5%8F%96%E8%AF%84%E8%AE%BA%E6%A1%88%E4%BE%8B) 有点问题 不知道是不是api改了 第二次循环c['replies']变成了None
> 
> 需要提供 credential，看来是忘改了
具体应该如何操作呢？

**Comment by LianXiaoxiang** [comment]
学会了 谢谢

**Comment by z0z0r4** [comment]
> 虽然 search 模块很明显少了很多筛选条件，但很明显有分页参数

不对，根本没少啥参数吧？？就少了个 page_size

**Comment by z0z0r4** [comment]
而且这个参数似乎加进去完全没效果...只有 type 的才有效果

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/3cd08315-8b18-44f9-ba5c-d20bd44d4776)


![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/3cd08315-8b18-44f9-ba5c-d20bd44d4776)

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/pull/654/commits/244732145b035329007b1882d7eaa4cc648ad8d3
