### ISSUE TITLE
[提问] -412代理应该如何配置嘞 

### ISSUE THREAD

**Issue by LianXiaoxiang** [Nemo2011/bilibili-api#656]
不上很明白代理应该如何配置?有没有相关文献啊

**Comment by LianXiaoxiang** [comment]
获取评论老是-412 有没有参数可以控制请求频率嘞

**Comment by z0z0r4** [comment]
自己设置 delay...你每次请求等等就行了

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/blob/13c88608214e6735c92088c8a47cd7646352af38/bilibili_api/settings.py#L9-L18

**Comment by z0z0r4** [comment]
> > 自己设置 delay...你每次请求等等就行了
> 
> 现在的评论api好像换了

猜你想说 get_comment_lazy，我才补的

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/issues/658
