### ISSUE TITLE
`get_comments_lazy` -403

### ISSUE THREAD

**Issue by LianXiaoxiang** [Nemo2011/bilibili-api#658]
![image](https://github.com/Nemo2011/bilibili-api/assets/105619736/80948950-34b1-475d-8b1d-82d96029e8cd)

![image](https://github.com/Nemo2011/bilibili-api/assets/105619736/36100034-2e56-4314-a519-52a072f629d3)

**Comment by Nemo2011** [comment]
尝试 `get_comments_lazy`

**Comment by z0z0r4** [comment]
> 尝试 `get_comments_lazy`

我看得加个惯例，旧接口加个 warning 才行...

**Comment by LianXiaoxiang** [comment]
> > 尝试 `get_comments_lazy`
> 
> 我看得加个惯例，旧接口加个 warning 才行...

可以 我用get_comments_lazy也遇见了一个问题
![image](https://github.com/Nemo2011/bilibili-api/assets/105619736/47f8eb20-bb7a-4318-8e50-4c0c2834156b)
![image](https://github.com/Nemo2011/bilibili-api/assets/105619736/51233578-b951-4686-8945-18ea822c9d05)
会有这样的一个报错

**Comment by LianXiaoxiang** [comment]
> 尝试 `get_comments_lazy`

尝试了 不太明白应该怎么写 感觉参数没给对一样 什么重试达到最大次数 
![image](https://github.com/Nemo2011/bilibili-api/assets/105619736/3e9680f4-4bcd-4445-b25b-94f59b16dfa3)

**Comment by LianXiaoxiang** [comment]
> > 尝试 `get_comments_lazy`
> 
> 我看得加个惯例，旧接口加个 warning 才行...

真的很需要一个惯例 跪求大佬写个文档

**Comment by z0z0r4** [comment]
能不能给这 repo 训练个 gpt 啊...

**Comment by LianXiaoxiang** [comment]
> 能不能给这 repo 训练个 gpt 啊...

我现在用的原生的 不用cookie 通过js反向解析 可以拿评论了

**Comment by z0z0r4** [comment]
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/d7db8a99-46df-4cf7-849e-9b2bc6dd7ca6)

正在排查...我猜有奇怪的参数

**Comment by z0z0r4** [comment]
wbi 无妨，估计是 cookie 部分

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/5d678160-f853-47a4-8e1f-d1bf4818e587)

**Comment by z0z0r4** [comment]
你咋样我无所谓，我只是找出原因而已=..  =

**Comment by LianXiaoxiang** [comment]
主要是我可能不太明白这个函数这么用吧

**Comment by z0z0r4** [comment]
`pagination_str` python url转码这边有屎，我实在不想碰了，用 bac 的 `next` 参数吧...

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/1459d22b-0b7e-4f8e-ad89-dde12b28038c)

记得上次也是这玩意
