### ISSUE TITLE
【提问】没有预料的 Ajax 请求重定向和无 code 字段Api相关

### ISSUE THREAD

**Issue by sudoskys** [Nemo2011/bilibili-api#66]
**Python 版本：** 3.10

**模块版本：** [dev](https://github.com/Nemo2011/bilibili-api/tree/f7eed0762bd56f12e37cc4484328cb5496af353f)

**运行环境：** Linux

---

### 关于 `getSubList` API

http://space.bilibili.com/ajax/tags/getSubList

**url 参数：**

| 参数名 | 类型 | 内容 | 必要性 | 备注 |
| --- | --- | --- | --- | --- |
| mid | num | 目标用户 UID | 必要 |  |

在 查询用户关注的 TAG 的相关Api中， ajax 重定向没有被 预定的工具库处理，另外处理后也因为没有 code 字段不能被解析。

### Log

暂时没有

**Comment by sudoskys** [comment]
嗯？怎么看错了，不是ajax

**Comment by Nemo2011** [comment]
这个用 get_session() 来 request

```
sess = get_session()
resp = sess.request(
....
)
return json.loads(resp.text)["data"]
```
