### ISSUE TITLE
[提问] 如何搜索超过1000条结果？

### ISSUE THREAD

**Issue by tomriddle1234** [Nemo2011/bilibili-api#670]
**Python 版本：** 3.10

**模块版本：** 16.1.1

**运行环境：** Windows

---

请问目前的search.search_by_type()每次仅能返回50页，每页20项，一共1000项，如果想获得更多数据怎么做？

**Comment by tomriddle1234** [comment]
感谢，可以获取42个*42页 数据吗？自己改page_size?

**Comment by z0z0r4** [comment]
> 感谢，可以获取42个*42页 数据吗？自己改page_size?

我不清楚...你试试看嘛，我只是看网页端最多就这么多
