### ISSUE TITLE
[需求]可否添加一个获取粉丝用户头像的API？

### ISSUE THREAD

**Issue by Twilight233333** [Nemo2011/bilibili-api#682]
网上找到的代码好像都需要B站官方API注册才能获取到头像信息，不知道到了能否做出这个API！非常感谢！

**Comment by z0z0r4** [comment]
你可以看看这里有没有获取粉丝列表的接口，这里面会提供头像的 URL

~~我在高速没法查文档~~

**Comment by Twilight233333** [comment]
收到！谢谢大佬回复！我是新手小白我再仔细找找！

**Comment by z0z0r4** [comment]
找到了，是这一段

https://github.com/Nemo2011/bilibili-api/blob/a0474871bbbc0cc1b85dcae6e8fa0c33035ef279/bilibili_api/user.py#L774

https://github.com/Nemo2011/bilibili-api/blob/a0474871bbbc0cc1b85dcae6e8fa0c33035ef279/docs/examples/user.md?plain=1#L86 这里有教你怎么拿到列表

**Comment by Twilight233333** [comment]
收到！！！非常感谢！
