### ISSUE TITLE
[提问] {别人@我后，我如何获得@的来源，也就是从对应视频的bvid}

### ISSUE THREAD

**Issue by nickyi1990** [Nemo2011/bilibili-api#685]
如标题

**Comment by z0z0r4** [comment]
看文档，获取@消息的部分，我不信返回值里没提供 oid

你是在返回值里没找到还是咋

**Comment by Nemo2011** [comment]
别人@你是通过消息发送的，去 `session` 里面找

**Comment by nickyi1990** [comment]
> 看文档，获取@消息的部分，我不信返回值里没提供 oid
> 
> 你是在返回值里没找到还是咋

要么是藏的很深，要么是文档比较晦涩，确实没搜到
网页：https://nemo2011.github.io/bilibili-api/#/modules/dynamic?id=def-add_at

![image](https://github.com/Nemo2011/bilibili-api/assets/13381684/ceeabb39-21b5-46fb-971f-ef73b921832c)

**Comment by nickyi1990** [comment]
> 别人@你是通过消息发送的，去 `session` 里面找

👌🏻，我试试，thanks
