### ISSUE TITLE
[BUG] cookies 刷新报错

### ISSUE THREAD

**Issue by gongdananyou** [Nemo2011/bilibili-api#687]
**Python 版本：** 3.11.5

**模块版本：** 最新dev分支

**运行环境：** Windows

---

执行刷新函数的时候，抛出了异常
```
Traceback (most recent call last):
  File "e:\Project\bili\bili.py", line 90, in <module>
    check_login()
  File "e:\Project\bili\bili.py", line 43, in check_login
    sync(credential.refresh())
  File "C:\Users\Asaka\.conda\envs\bili\Lib\site-packages\bilibili_api_dev-17.0.0-py3.11.egg\bilibili_api\utils\sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asaka\.conda\envs\bili\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Asaka\.conda\envs\bili\Lib\site-packages\bilibili_api_dev-17.0.0-py3.11.egg\bilibili_api\credential.py", line 51, in refresh
    new_cred: Credential = await refresh_cookies(self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asaka\.conda\envs\bili\Lib\site-packages\bilibili_api_dev-17.0.0-py3.11.egg\bilibili_api\credential.py", line 144, in refresh_cookies
    refresh_csrf = await get_refresh_csrf(credential)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asaka\.conda\envs\bili\Lib\site-packages\bilibili_api_dev-17.0.0-py3.11.egg\bilibili_api\credential.py", line 122, in get_refresh_csrf
    raise Exception("correspondPath 过期或错误。")
Exception: correspondPath 过期或错误。
```
是否B站更新了接口？

**Comment by gongdananyou** [comment]
> 刷新频率太低，我改成每6小时刷新一次解决了

可是我写的是三小时执行一次刷新

**Comment by z0z0r4** [comment]
我这边也过期了，确认是有问题

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/1fe4a312-5d7a-437c-ae20-ebc53b82a037)

**Comment by z0z0r4** [comment]
很遗憾我这边复现不出来了...

![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/316449f3-9036-4628-8c38-0507d9360f14)

**Comment by gongdananyou** [comment]
> 很遗憾我这边复现不出来了...暂时搁置，BAC 那边也没听说
> 
> ![image](https://private-user-images.githubusercontent.com/78744121/307572840-316449f3-9036-4628-8c38-0507d9360f14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NTUzODQsIm5iZiI6MTcwODg1NTA4NCwicGF0aCI6Ii83ODc0NDEyMS8zMDc1NzI4NDAtMzE2NDQ5ZjMtOTAzNi00NjI4LThjMzgtMDUwN2Q5MzYwZjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDA5NTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MmFiMjJjYmI5ODdiZjAxODliZjZkYTM3NzY4ZWI4MDVhNDA4NDIzM2ExNjMzNDI1NWNiYTE1NDAxYWUwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5JAbT62rLoiybhu5dX4nnOxweIzHyP0OlVfGe6_zCXA)

![Snipaste_2024-02-25_17-56-30](https://github.com/Nemo2011/bilibili-api/assets/60178803/ce569978-de48-40fc-9704-96b6d5452920)

不知道是否有用错版本，我pull应该是最新的dev，我直接刷新是报错的

**Comment by 17yjgao** [comment]
> > 很遗憾我这边复现不出来了...暂时搁置，BAC 那边也没听说
> > ![image](https://private-user-images.githubusercontent.com/78744121/307572840-316449f3-9036-4628-8c38-0507d9360f14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NTUzODQsIm5iZiI6MTcwODg1NTA4NCwicGF0aCI6Ii83ODc0NDEyMS8zMDc1NzI4NDAtMzE2NDQ5ZjMtOTAzNi00NjI4LThjMzgtMDUwN2Q5MzYwZjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDA5NTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MmFiMjJjYmI5ODdiZjAxODliZjZkYTM3NzY4ZWI4MDVhNDA4NDIzM2ExNjMzNDI1NWNiYTE1NDAxYWUwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5JAbT62rLoiybhu5dX4nnOxweIzHyP0OlVfGe6_zCXA)
> 
> ![Snipaste_2024-02-25_17-56-30](https://private-user-images.githubusercontent.com/60178803/307581695-ce569978-de48-40fc-9704-96b6d5452920.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NTkwMTksIm5iZiI6MTcwODg1ODcxOSwicGF0aCI6Ii82MDE3ODgwMy8zMDc1ODE2OTUtY2U1Njk5NzgtZGU0OC00MGZjLTk3MDQtOTZiNmQ1NDUyOTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDEwNTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZmY1NGYyNDFmZjBkNDViOWFiZWNhNzFiMDI4ODVmN2Q2N2YyMjhlY2Q2YzVlNzk5YmQ5NDQ2MWMzMjBlY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KPIPl_Q1KzBbYDQM1vdpmw8nzMcPLMupthTIbBly7dE)
> 
> 不知道是否有用错版本，我pull应该是最新的dev，我直接刷新是报错的

我用的也是dev，之前直接刷新也报错，后面我在`credential.check_refresh() == True` 刷之后就好了，然后六小时检查一次

**Comment by gongdananyou** [comment]
> > > 很遗憾我这边复现不出来了...暂时搁置，BAC 那边也没听说
> > > ![image](https://private-user-images.githubusercontent.com/78744121/307572840-316449f3-9036-4628-8c38-0507d9360f14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NTUzODQsIm5iZiI6MTcwODg1NTA4NCwicGF0aCI6Ii83ODc0NDEyMS8zMDc1NzI4NDAtMzE2NDQ5ZjMtOTAzNi00NjI4LThjMzgtMDUwN2Q5MzYwZjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDA5NTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MmFiMjJjYmI5ODdiZjAxODliZjZkYTM3NzY4ZWI4MDVhNDA4NDIzM2ExNjMzNDI1NWNiYTE1NDAxYWUwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5JAbT62rLoiybhu5dX4nnOxweIzHyP0OlVfGe6_zCXA)
> > 
> > 
> > ![Snipaste_2024-02-25_17-56-30](https://private-user-images.githubusercontent.com/60178803/307581695-ce569978-de48-40fc-9704-96b6d5452920.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NTkwMTksIm5iZiI6MTcwODg1ODcxOSwicGF0aCI6Ii82MDE3ODgwMy8zMDc1ODE2OTUtY2U1Njk5NzgtZGU0OC00MGZjLTk3MDQtOTZiNmQ1NDUyOTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDEwNTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZmY1NGYyNDFmZjBkNDViOWFiZWNhNzFiMDI4ODVmN2Q2N2YyMjhlY2Q2YzVlNzk5YmQ5NDQ2MWMzMjBlY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KPIPl_Q1KzBbYDQM1vdpmw8nzMcPLMupthTIbBly7dE)
> > 不知道是否有用错版本，我pull应该是最新的dev，我直接刷新是报错的
> 
> 我用的也是dev，之前直接刷新也报错，后面我在`credential.check_refresh() == True` 之后刷就好了，然后六小时检查一次

![image](https://github.com/Nemo2011/bilibili-api/assets/60178803/bf4505b4-ab43-4335-8382-13775355b393)


意思是只能是需要refresh的时候才能执行?我一开始的程序也是在这个判断之后刷新的，不过也是报错。

**Comment by 17yjgao** [comment]
![图片](https://github.com/Nemo2011/bilibili-api/assets/31804351/fe803767-bc0a-4114-b82e-1cae51849cad)
我24号还刷新成功了

**Comment by gongdananyou** [comment]
> ![图片](https://private-user-images.githubusercontent.com/31804351/307589313-fe803767-bc0a-4114-b82e-1cae51849cad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NjM4NTgsIm5iZiI6MTcwODg2MzU1OCwicGF0aCI6Ii8zMTgwNDM1MS8zMDc1ODkzMTMtZmU4MDM3NjctYmMwYS00MTE0LWI4MmUtMWNhZTUxODQ5Y2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDEyMTkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZjEzYzFjN2Y2OWRjODIzZGU1MDZmZjVlNTFkODg5YmM5OTlkZmVmOTIyZTU1NDc3YTVkYjM3NDA4YTg0N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yAIJABlRmqvt44QqfosE-eRNgDzkjX-yTUY085hslmg) 我24号还刷新成功了

我看上面，一开始 @z0z0r4 也是刷新失败了，然后后面就不能复现，我也写了个一样的测试，我是无法刷新，难不成是我账号有问题？

**Comment by z0z0r4** [comment]
老实说我不清楚，你看看我 refer 的那个 BAC 的那个 issue，试试里面的示例

**Comment by z0z0r4** [comment]
> > > 很遗憾我这边复现不出来了...暂时搁置，BAC 那边也没听说
> > > ![image](https://private-user-images.githubusercontent.com/78744121/307572840-316449f3-9036-4628-8c38-0507d9360f14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NTUzODQsIm5iZiI6MTcwODg1NTA4NCwicGF0aCI6Ii83ODc0NDEyMS8zMDc1NzI4NDAtMzE2NDQ5ZjMtOTAzNi00NjI4LThjMzgtMDUwN2Q5MzYwZjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDA5NTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MmFiMjJjYmI5ODdiZjAxODliZjZkYTM3NzY4ZWI4MDVhNDA4NDIzM2ExNjMzNDI1NWNiYTE1NDAxYWUwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5JAbT62rLoiybhu5dX4nnOxweIzHyP0OlVfGe6_zCXA)
> > 
> > 
> > ![Snipaste_2024-02-25_17-56-30](https://private-user-images.githubusercontent.com/60178803/307581695-ce569978-de48-40fc-9704-96b6d5452920.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NTkwMTksIm5iZiI6MTcwODg1ODcxOSwicGF0aCI6Ii82MDE3ODgwMy8zMDc1ODE2OTUtY2U1Njk5NzgtZGU0OC00MGZjLTk3MDQtOTZiNmQ1NDUyOTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDEwNTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZmY1NGYyNDFmZjBkNDViOWFiZWNhNzFiMDI4ODVmN2Q2N2YyMjhlY2Q2YzVlNzk5YmQ5NDQ2MWMzMjBlY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KPIPl_Q1KzBbYDQM1vdpmw8nzMcPLMupthTIbBly7dE)
> > 不知道是否有用错版本，我pull应该是最新的dev，我直接刷新是报错的
> 
> 我用的也是dev，之前直接刷新也报错，后面我在`credential.check_refresh() == True` 之后刷就好了，然后六小时检查一次

不存在这个说法吧

**Comment by gongdananyou** [comment]
> 老实说我不清楚，你看看我 refer 的那个 BAC 的那个 issue，试试里面的示例
> 
> 我不确定是这边的实现有瑕疵还是改了
> 
> [SocialSisterYi/bilibili-API-collect#976](https://github.com/SocialSisterYi/bilibili-API-collect/issues/976)

看了下另一边有提到时间是否正确，我发现时间确实快了一点，同步时间后运行正常了，感谢

**Comment by z0z0r4** [comment]
原来是时间问题吗...难道报错前得同步下时间确认下原因？
