### ISSUE TITLE
视频上传接口风控收紧

### ISSUE THREAD

**Issue by chi1st** [Nemo2011/bilibili-api#690]
---

之前发布视频，30秒发一个不会被封，目前改成五分钟发一次，大概发到三十多个的时候就会被封
接口返回：
接口返回错误代码：21515，信息：经检测存在批量作弊投稿等破坏平台秩序的行为，为保证社区创作公平予以处理，如果对判定结果有异议，可提交在线申诉。。

**Comment by z0z0r4** [comment]
这没办法的，手动也一样，不处理
