### ISSUE TITLE
[提问]上传视频遇到问题 AttributeError: 'NoneType' object has no attribute '__dict__'. Did you mean: '__dir__'?

### ISSUE THREAD

**Issue by RickyCui010** [Nemo2011/bilibili-api#698]
**Python 版本：** 3.10

**模块版本：** 16.2.0

**运行环境：** Windows

---
按照文档给的案例上传视频，credential和视频封面，视频文件都修改了，但是遇见这个问题
AttributeError: 'NoneType' object has no attribute '__dict__'. Did you mean: '__dir__'?

**Comment by z0z0r4** [comment]
发下代码

**Comment by RickyCui010** [comment]
> 发下代码

> 发下代码

from bilibili_api import sync, video_uploader, Credential

SESSDATA = ".........................."
BILI_JCT =  ".........................."
BUVID3 =  ".........................."

async def main():
    credential = Credential(sessdata=SESSDATA, bili_jct=BILI_JCT, buvid3=BUVID3)

    vu_meta = video_uploader.VideoMeta(tid=130,
    title='title',
    tags=['音乐综合', '音乐'],
    desc='',
    cover="cover.png",
    no_reprint=True
    )
    page = video_uploader.VideoUploaderPage(
        path = 'video.mp4',
        title = '标题',
        description='简介',
    )
    uploader = video_uploader.VideoUploader([page], vu_meta, credential, line=video_uploader.Lines.QN) # 选择七牛线路，不选则自动测速选择最优线路


    @uploader.on("__ALL__")
    async def ev(data):
        print(data)

    await uploader.start()


sync(main())

**Comment by RickyCui010** [comment]
> 发下代码

from bilibili_api import sync, video_uploader, Credential

SESSDATA = ".........................."
BILI_JCT =  ".........................."
BUVID3 =  ".........................."

async def main():
    credential = Credential(sessdata=SESSDATA, bili_jct=BILI_JCT, buvid3=BUVID3)

    vu_meta = video_uploader.VideoMeta(tid=130,
                                       title='title',
                                       tags=['音乐综合', '音乐'],
                                       desc='',
                                       cover="cover.png",
                                       no_reprint=True
                                      )
    page = video_uploader.VideoUploaderPage(
        path = 'video.mp4',
        title = '标题',
        description='简介',
    )
    uploader = video_uploader.VideoUploader([page], vu_meta, credential, line=video_uploader.Lines.QN) # 选择七牛线路，不选则自动测速选择最优线路


    @uploader.on("__ALL__")
    async def ev(data):
        print(data)

    await uploader.start()


sync(main())

**Comment by RickyCui010** [comment]
> 发下代码

···python
from bilibili_api import sync, video_uploader, Credential

SESSDATA = ".........................."
BILI_JCT =  ".........................."
BUVID3 =  ".........................."

async def main():
    credential = Credential(sessdata=SESSDATA, bili_jct=BILI_JCT, buvid3=BUVID3)

    vu_meta = video_uploader.VideoMeta(tid=130,
                                       title='title',
                                       tags=['音乐综合', '音乐'],
                                       desc='',
                                       cover="cover.png",
                                       no_reprint=True
                                      )
    page = video_uploader.VideoUploaderPage(
        path = 'video.mp4',
        title = '标题',
        description='简介',
    )
    uploader = video_uploader.VideoUploader([page], vu_meta, credential, line=video_uploader.Lines.QN) # 选择七牛线路，不选则自动测速选择最优线路


    @uploader.on("__ALL__")
    async def ev(data):
        print(data)

    await uploader.start()


sync(main())

**Comment by RickyCui010** [comment]
> 发下代码
`from bilibili_api import sync, video_uploader, Credential

SESSDATA = ".........................."
BILI_JCT =  ".........................."
BUVID3 =  ".........................."

async def main():
    credential = Credential(sessdata=SESSDATA, bili_jct=BILI_JCT, buvid3=BUVID3)

    vu_meta = video_uploader.VideoMeta(tid=130,
                                       title='title',
                                       tags=['音乐综合', '音乐'],
                                       desc='',
                                       cover="cover.png",
                                       no_reprint=True
                                      )
    page = video_uploader.VideoUploaderPage(
        path = 'video.mp4',
        title = '标题',
        description='简介',
    )
    uploader = video_uploader.VideoUploader([page], vu_meta, credential, line=video_uploader.Lines.QN) # 选择七牛线路，不选则自动测速选择最优线路


    @uploader.on("__ALL__")
    async def ev(data):
        print(data)

    await uploader.start()


sync(main())`

**Comment by RickyCui010** [comment]
```
from bilibili_api import sync, video_uploader, Credential

SESSDATA = ".........................."
BILI_JCT =  ".........................."
BUVID3 =  ".........................."

async def main():
    credential = Credential(sessdata=SESSDATA, bili_jct=BILI_JCT, buvid3=BUVID3)

    vu_meta = video_uploader.VideoMeta(tid=130,
                                       title='title',
                                       tags=['音乐综合', '音乐'],
                                       desc='',
                                       cover="cover.png",
                                       no_reprint=True
                                      )
    page = video_uploader.VideoUploaderPage(
        path = 'video.mp4',
        title = '标题',
        description='简介',
    )
    uploader = video_uploader.VideoUploader([page], vu_meta, credential, line=video_uploader.Lines.QN) # 选择七牛线路，不选则自动测速选择最优线路


    @uploader.on("__ALL__")
    async def ev(data):
        print(data)

    await uploader.start()

sync(main())
```

**Comment by RickyCui010** [comment]
> 发下代码

```
from bilibili_api import sync, video_uploader, Credential

SESSDATA = ".........................."
BILI_JCT =  ".........................."
BUVID3 =  ".........................."

async def main():
    credential = Credential(sessdata=SESSDATA, bili_jct=BILI_JCT, buvid3=BUVID3)

    vu_meta = video_uploader.VideoMeta(tid=130,
                                       title='title',
                                       tags=['音乐综合', '音乐'],
                                       desc='',
                                       cover="cover.png",
                                       no_reprint=True
                                      )
    page = video_uploader.VideoUploaderPage(
        path = 'video.mp4',
        title = '标题',
        description='简介',
    )
    uploader = video_uploader.VideoUploader([page], vu_meta, credential, line=video_uploader.Lines.QN) # 选择七牛线路，不选则自动测速选择最优线路


    @uploader.on("__ALL__")
    async def ev(data):
        print(data)

    await uploader.start()


sync(main())
```

**Comment by RickyCui010** [comment]
> 发下代码

```python
from bilibili_api import sync, video_uploader, Credential

SESSDATA = ".........................."
BILI_JCT =  ".........................."
BUVID3 =  ".........................."

async def main():
    credential = Credential(sessdata=SESSDATA, bili_jct=BILI_JCT, buvid3=BUVID3)

    vu_meta = video_uploader.VideoMeta(tid=130,
                                       title='title',
                                       tags=['音乐综合', '音乐'],
                                       desc='',
                                       cover="cover.png",
                                       no_reprint=True
                                      )
    page = video_uploader.VideoUploaderPage(
        path = 'video.mp4',
        title = '标题',
        description='简介',
    )
    uploader = video_uploader.VideoUploader([page], vu_meta, credential, line=video_uploader.Lines.QN) # 选择七牛线路，不选则自动测速选择最优线路


    @uploader.on("__ALL__")
    async def ev(data):
        print(data)

    await uploader.start()


sync(main())
```

**Comment by Nemo2011** [comment]
https://github.com/Nemo2011/bilibili-api/blob/a0474871bbbc0cc1b85dcae6e8fa0c33035ef279/bilibili_api/video_uploader.py#L583

**Comment by z0z0r4** [comment]
不清楚但好像是我的锅.jpg 但我在校没法改

**Comment by RickyCui010** [comment]
> 不清楚但好像是我的锅.jpg 但我在校没法改

那哪个版本可以运行呢

**Comment by z0z0r4** [comment]
你不用 meta，直接传json大概就能吧

**Comment by RickyCui010** [comment]
ok了，现在可以了,原来的 "porder": self.porder.__dict__(), 这一行删除
```python
class VideoMeta:
    # ... 其他代码 ...

    def __dict__(self) -> dict:
        meta = {
            # ... 其他属性 ...
            #原来的 "porder": self.porder.__dict__(), 这一行删除
        }
        # 确保 porder 不是 None
        if self.porder is not None:
            meta["porder"] = self.porder.__dict__()

        # ... 其他代码 ...
        return meta
```

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/commit/0272d9ceb20c799cd5dfb77bc795a9d1943ae6aa
