### ISSUE TITLE
用户中的get_user_info()方法好像请求不到数据了，{'code': -404, 'message': '啥都木有', 'ttl': 1}

### ISSUE THREAD

**Issue by leiting2333** [Nemo2011/bilibili-api#701]
![image](https://github.com/Nemo2011/bilibili-api/assets/80498048/4b60003a-738c-4e84-a48e-ed10d167957d)

**Comment by Nemo2011** [comment]
<img width="1476" alt="image" src="https://github.com/Nemo2011/bilibili-api/assets/91071485/af91b7eb-6dd5-44ba-8925-784840fb247d">

**Comment by leiting2333** [comment]
啊啊啊，这个小问题我竟然没注意到，呜呜呜。是我脑子糊涂了，感谢大佬抽空给我这个小白解答问题。红豆泥阿里嘎多！
