### ISSUE TITLE
【建议】ResponseCodeException未能返回全部有效信息

### ISSUE THREAD

**Issue by ghost** [Nemo2011/bilibili-api#72]
在测试submit_subtitle这个函数时，网页会返回一些错误原因，但是ResponseCodeException并没有提取/返回所有有效信息，导致排查困难。
比如，经常收到报错：

> 接口返回错误代码：79014，信息：字幕超过限制。

但是网页返回的其实包含了其他有效信息：

> {'code': 79014, 'message': '字幕超过限制', 'ttl': 1, 'data': [{'line': 580, 'error_msg': '字幕时间点超过视频时间长度'}]}

在代码中如果加上self.raw就可以返回全部信息。
https://github.com/Nemo2011/bilibili-api/blob/2c6f8da82397aaeec8517665617e747f37887399/bilibili_api/exceptions/ResponseCodeException.py#L10-L29

**另外，关于字幕的操作，目前只有提交字幕这一个api，是否可以增加其他操作字幕的api，比如查看/退回/删除等**？
**感谢！**

**Comment by Nemo2011** [comment]
改了一下，ResponseCodeException 发出的时候会显示 `self.raw` 展示详细信息了。
