### ISSUE TITLE
[代理ip] 添加settings.proxy = "http://your-proxy.com" 后 一直请求报CHUNK_FAILED

### ISSUE THREAD

**Issue by smilemilk1992** [Nemo2011/bilibili-api#727]
{'name': 'PREUPLOAD', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>},)}
{'name': 'PRE_PAGE', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 5},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 31457280, 'chunk_number': 3, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 41943040, 'chunk_number': 4, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 5},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 31457280, 'chunk_number': 3, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 41943040, 'chunk_number': 4, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 31457280, 'chunk_number': 3, 'total_chunk_count': 5},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 31457280, 'chunk_number': 3, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 41943040, 'chunk_number': 4, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 5},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 41943040, 'chunk_number': 4, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 31457280, 'chunk_number': 3, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 41943040, 'chunk_number': 4, 'total_chunk_count': 5},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 31457280, 'chunk_number': 3, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 41943040, 'chunk_number': 4, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 5},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 31457280, 'chunk_number': 3, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 41943040, 'chunk_number': 4, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 5},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 31457280, 'chunk_number': 3, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 41943040, 'chunk_number': 4, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 31457280, 'chunk_number': 3, 'total_chunk_count': 5},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 31457280, 'chunk_number': 3, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 41943040, 'chunk_number': 4, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 5},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 41943040, 'chunk_number': 4, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 31457280, 'chunk_number': 3, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 41943040, 'chunk_number': 4, 'total_chunk_count': 5},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 31457280, 'chunk_number': 3, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 41943040, 'chunk_number': 4, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 5},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 31457280, 'chunk_number': 3, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 41943040, 'chunk_number': 4, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 5},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 31457280, 'chunk_number': 3, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 41943040, 'chunk_number': 4, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 31457280, 'chunk_number': 3, 'total_chunk_count': 5},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 31457280, 'chunk_number': 3, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 41943040, 'chunk_number': 4, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 5},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 0, 'chunk_number': 0, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 10485760, 'chunk_number': 1, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'CHUNK_FAILED', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 41943040, 'chunk_number': 4, 'total_chunk_count': 5, 'info': ''},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 20971520, 'chunk_number': 2, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 31457280, 'chunk_number': 3, 'total_chunk_count': 5},)}
{'name': 'PRE_CHUNK', 'data': ({'page': <bilibili_api.video_uploader.VideoUploaderPage object at 0x10fa7d9d0>, 'offset': 41943040, 'chunk_number': 4, 'total_chunk_count': 5},)}
。。。。。。

**Comment by z0z0r4** [comment]
虽然没环境复现，但 `chunk_failed` 没有意义...得调试看看具体是啥报错

**Comment by z0z0r4** [comment]
已沟通，无法本地复现
批量上传视频牟利请使用其他工具，如 biliup-rs 等
