### ISSUE TITLE
[提问] Bilibili API将废弃UID转向使用open_id的支持问题

### ISSUE THREAD

**Issue by oldip** [Nemo2011/bilibili-api#728]
**Python 版本：** 3.11.5

**模块版本：** bilibili-api-python 16.2.0

**运行环境：** Windows

---
嘿，维护bilibili-api-python的朋友们，

看到Bilibili的API更新了，4月25日后UID就要退出历史舞台，open_id要开始大展拳脚了。我一直在用你们的库来做开发，目前库里似乎还没提到open_id的适配。

如果你们已经有更新计划，那太好了，直接把我的issue关了当我啥都没说。如果还在计划中，我只想跟你们提个醒。万一有更新的时间表，透露一二也是极好的，这样我也能同步我的开发节奏。

感谢啦，期待回音！

编码快乐哦！

哔哩哔哩 -(゜-゜)つロ 乾杯~

官方通知链接：https://www.bilibili.com/opus/911220549299994641
![image](https://github.com/Nemo2011/bilibili-api/assets/50076590/09f70dcf-c887-4a2e-8edd-78406f3cd739)

**Comment by z0z0r4** [comment]
这就是最近直播一直有 issue 的原因吗？...

了解，但没人修...

**Comment by z0z0r4** [comment]
小丑l...没看清，这只是开放平台的修改，无关这边

**Comment by oldip** [comment]
@z0z0r4 但是4月15号全面废弃uid捏

**Comment by z0z0r4** [comment]
> @z0z0r4 但是4月15号全面废弃uid捏

我不太清楚...
