### ISSUE TITLE
[提问] 二级评论第二页无法抓取

### ISSUE THREAD

**Issue by xu1970** [Nemo2011/bilibili-api#745]
**Python 版本：** 3.9.3

**模块版本：** 16.2.0

**运行环境：** MacOS

所有一级评论以及二级评论的第一页都可以顺利抓取。有credential。但是二级评论第二页以及后面都返回空值，没有报错。比如某视频某一级评论有10页回复，95条二级评论

<img width="984" alt="Screenshot 2024-04-18 at 7 53 18 PM" src="https://github.com/Nemo2011/bilibili-api/assets/167485858/44ef853c-7d74-4cab-957c-4ffe96bfbe3f">

第二页就只能返回这个

<img width="986" alt="Screenshot 2024-04-18 at 7 54 38 PM" src="https://github.com/Nemo2011/bilibili-api/assets/167485858/93b19a06-e12c-48c1-9cb3-ed85e7ff71a6">

请问这是什么状况？要怎么调整呢？谢谢！

**Comment by z0z0r4** [comment]
commentresourcetyoe不是这样设置的，是不是这个原因我不清楚没测试

https://github.com/Nemo2011/bilibili-api/blob/d65a6910699f1ac28dd96688b74af3eec910c014/bilibili_api/comment.py#L26-L49
