### ISSUE TITLE
[提问] 400页以后的评论抓取报错

### ISSUE THREAD

**Issue by xu1970** [Nemo2011/bilibili-api#747]
**Python 版本：**  3.9.3

**模块版本：**  16.2.0

**运行环境：**  MacOS

---

一级评论前400页都正常，到401页就报错，请问是什么缘故呢？报的错是

> 接口返回错误代码：-400，信息：pn out of bounds。

但问题是，视频评论总数在15000以上，理论上应该没有抓完。试了几个评论数差不多的视频，都是在401页报错的。比如这个
```python
c = await comment.get_comments(56728862, comment.CommentResourceType.VIDEO, 400, credential=credential)
print(c['page']['count'])
```

    22120

```python
c = await comment.get_comments(56728862, comment.CommentResourceType.VIDEO, 401, credential=credential)

```

    ---------------------------------------------------------------------------

    ResponseCodeException                     Traceback (most recent call last)

    Cell In[97], line 1
    ----> 1 c = await comment.get_comments(56728862, comment.CommentResourceType.VIDEO, 401, credential=credential)

    File ~/anaconda3/lib/python3.11/site-packages/bilibili_api/comment.py:411, in get_comments(oid, type_, page_index, order, credential)
        409 api = API["comment"]["get"]
        410 params = {"pn": page_index, "type": type_.value, "oid": oid, "sort": order.value}
    --> 411 return await Api(**api, credential=credential).update_params(**params).result

    File ~/anaconda3/lib/python3.11/site-packages/bilibili_api/utils/network.py:273, in Api.result(self)
        267 """
        268 异步获取请求结果
        269 
        270 `self.__result` 用来暂存数据 参数不变时获取结果不变
        271 """
        272 if self.__result is None:
    --> 273     self.__result = await self.request()
        274 return self.__result

    File ~/anaconda3/lib/python3.11/site-packages/bilibili_api/utils/network.py:173, in retry.<locals>.wrapper.<locals>.inner(*args, **kwargs)
        171 loop -= 1
        172 try:
    --> 173     return await func(*args, **kwargs)
        174 except json.decoder.JSONDecodeError:
        175     # json 解析错误 说明数据获取有误 再给次机会
        176     continue

    File ~/anaconda3/lib/python3.11/site-packages/bilibili_api/utils/network.py:558, in Api.request(self, raw, **kwargs)
        556 except aiohttp.ClientResponseError as e:
        557     raise NetworkException(e.status, e.message)
    --> 558 real_data = self._process_response(
        559     resp, await self._get_resp_text(resp), raw=raw
        560 )
        561 return real_data

    File ~/anaconda3/lib/python3.11/site-packages/bilibili_api/utils/network.py:603, in Api._process_response(self, resp, resp_text, raw)
        601         if msg is None:
        602             msg = "接口未返回错误信息"
    --> 603         raise ResponseCodeException(code, msg, resp_data)
        604 elif OK != 1:
        605     raise ResponseCodeException(-1, "API 返回数据 OK 不为 1", resp_data)

    ResponseCodeException: 接口返回错误代码：-400，信息：pn out of bounds。
    {'code': -400, 'message': 'pn out of bounds', 'ttl': 1}

**Comment by z0z0r4** [comment]
**pn out of bounds**

**Comment by z0z0r4** [comment]
以及顺便问问，这个报错显示是怎么做到的？感觉好方便

**Comment by xu1970** [comment]
> **pn out of bounds** 说明B站不提供400+页数的评论

是不给我提供还是说不给任何人提供？跟我的IP地址有关系么？如果有个管理员权限的账号，可以抓取后面的评论么？


> 以及顺便问问，这个报错显示是怎么做到的？感觉好方便

Markdown啦，开头```python然后新开一行贴代码就可以的。

**Comment by z0z0r4** [comment]
> > **pn out of bounds** 说明B站不提供400+页数的评论
> 
> 是不给我提供还是说不给任何人提供？跟我的IP地址有关系么？如果有个管理员权限的账号，可以抓取后面的评论么？
> 
> > 以及顺便问问，这个报错显示是怎么做到的？感觉好方便
> 
> Markdown啦，开头```python然后新开一行贴代码就可以的。

不清楚，没试过

我说 python 的 traceback，怎么会显示报错行上下文的
