### ISSUE TITLE
【提问】{扫码登录获取uuid(cookie)}

### ISSUE THREAD

**Issue by ShiinaMono** [Nemo2011/bilibili-api#75]
刚接触爬虫，目前扫码登录仅能获取uid，sessdata以及bilijct等，有大佬教一下通过扫码登录获取uuid的思路吗(谢了

**Comment by Nemo2011** [comment]
uuid 是随机生成的，代码里面没有一定需要 uuid 的 API，用 `uuid.uuid1()` 就可以了。

**Comment by ShiinaMono** [comment]
谢谢，解决了🤣
