### ISSUE TITLE
[提问] 下载视频 怎么选择想要的清晰度？

### ISSUE THREAD

**Issue by JasonWeiCHN** [Nemo2011/bilibili-api#758]
**Python 版本：** 3.x.y

**模块版本：** x.y.z

**运行环境：** Windows / Linux / MacOS

---

下载视频 怎么选择想要的清晰度？

**Comment by z0z0r4** [comment]
提供你当前的代码

**Comment by JasonWeiCHN** [comment]
@z0z0r4 
你好，我直接用的官方文档的代码

`
import asyncio
from bilibili_api import video, Credential, HEADERS
import httpx
import os

SESSDATA = ""
BILI_JCT = ""
BUVID3 = ""

# FFMPEG 路径，查看：http://ffmpeg.org/
FFMPEG_PATH = r"F:/ffmpeg/bin/ffmpeg.exe"

async def download_url(url: str, out: str, info: str):
    # 下载函数
    async with httpx.AsyncClient(headers=HEADERS) as sess:
        resp = await sess.get(url)
        length = resp.headers.get('content-length')
        with open(out, 'wb') as f:
            process = 0
            for chunk in resp.iter_bytes(1024):
                if not chunk:
                    break

                process += len(chunk)
                # print(f'下载 {info} {process} / {length}')
                f.write(chunk)

async def main():
    # 实例化 Credential 类
    credential = Credential(sessdata=SESSDATA, bili_jct=BILI_JCT, buvid3=BUVID3)
    # 实例化 Video 类
    v = video.Video(bvid="BV1sw4m1m7iQ", credential=credential)
    # 获取视频下载链接
    download_url_data = await v.get_download_url(0)
    # 解析视频下载信息
    detecter = video.VideoDownloadURLDataDetecter(data=download_url_data)
    streams = detecter.detect_best_streams(audio_min_quality=video.AudioQuality._64K)
    # 有 MP4 流 / FLV 流两种可能
    if detecter.check_flv_stream() == True:
        # FLV 流下载
        await download_url(streams[0].url, "flv_temp.flv", "FLV 音视频流")
        # 转换文件格式
        os.system(f'{FFMPEG_PATH} -i flv_temp.flv video.mp4')
        # 删除临时文件
        os.remove("flv_temp.flv")
    else:
        # MP4 流下载
        await download_url(streams[0].url, "video_temp.m4s", "视频流")
        await download_url(streams[1].url, "audio_temp.m4s", "音频流")

        # 混流
        result = os.system(f'{FFMPEG_PATH} -i video_temp.m4s -i audio_temp.m4s -vcodec copy -acodec copy video.mp4')

        # 检查混流操作的结果
        if result != 0:
            print("混流操作失败！")
        else:
            print("混流操作成功！")

        print("当前工作目录:", os.getcwd())

        # 删除临时文件
        os.remove("video_temp.m4s")
        os.remove("audio_temp.m4s")

    print('已下载为：video.mp4')

if __name__ == '__main__':
    # 主入口
    asyncio.get_event_loop().run_until_complete(main())
`

**Comment by z0z0r4** [comment]
在stream 里面选择你要的分辨率下载

**Comment by JasonWeiCHN** [comment]
@z0z0r4 
> 在stream 里面选择你要的分辨率下载

streams 里 只有两个结果
我尝试改了detect_best_streams 的各个参数，还是没找到正确的方法

**Comment by z0z0r4** [comment]
sorry 我搞错了，如果你是选择 best 的话当然只有视频流和音频流

**Comment by z0z0r4** [comment]
你应该用 detect_all

**Comment by JasonWeiCHN** [comment]
> 你应该用 detect_all

非常感谢
