### ISSUE TITLE
[提问] {直播间弹幕被禁}

### ISSUE THREAD

**Issue by oldip** [Nemo2011/bilibili-api#769]
**Python 版本：** 3.11.5

**模块版本：** 16.2.1

**运行环境：** Windows

---

刚刚突然发现机器人不能说话，但投喂礼物正常，没有任何错误消息，然后进行研究发现手机端或者电脑端的互动指令可以发送，只有普通打字不行，发送是200成功的，preview说我所在的地区无法发言，code: 0
![image](https://github.com/Nemo2011/bilibili-api/assets/50076590/a0f38b4c-1053-455e-800c-a97139cfba58)
![image](https://github.com/Nemo2011/bilibili-api/assets/50076590/b59c2066-2814-4a5e-9f6d-94ac0cac483e)
![image](https://github.com/Nemo2011/bilibili-api/assets/50076590/3886a8fc-6f4c-4f7a-bcfd-2cc52a5f496e)
![image](https://github.com/Nemo2011/bilibili-api/assets/50076590/a926b942-3fd1-4e19-931b-5b4a8caf41ae)

如果是互动弹幕点击发送是另一条api，则可以发送
![image](https://github.com/Nemo2011/bilibili-api/assets/50076590/055da3b1-e823-4148-bbd7-3a1fa4a4ae79)
![image](https://github.com/Nemo2011/bilibili-api/assets/50076590/d36c705b-36ed-44b5-9fa5-49ec4dea099b)
![image](https://github.com/Nemo2011/bilibili-api/assets/50076590/13e2c31d-faa0-4e93-8170-8557d364825d)
![image](https://github.com/Nemo2011/bilibili-api/assets/50076590/c3437015-a3a6-42f4-81cd-28fde91f0409)

是被封了吗？还能解封吗？

**Comment by oldip** [comment]
不是，和代理无关，身边大部分用这个脚本的都中招了，询问客服得到的回覆是在升级，但中招的都是使用脚本的，我怀疑是被发现，封禁了
![bd2382669cc96b78ad0116dfa6fa634](https://github.com/Nemo2011/bilibili-api/assets/50076590/3e027e7b-417f-4e49-a08e-a715222f91ca)

**Comment by oldip** [comment]
更新说明，现在手机端也不能发消息了

**Comment by z0z0r4** [comment]
> 使用脚本的

光这个我也不知道你啥情况，提供下代码等基本信息

我也没在 bac 听过有你这样情况的，你说都封了我也没案例可参考

**Comment by z0z0r4** [comment]
建议去 https://github.com/SocialSisterYi/bilibili-API-collect/discussions/new?category=general 开个 discussion

**Comment by oldip** [comment]
好了，估计是敏感时期不让海外用户发弹幕而已

**Comment by z0z0r4** [comment]
那你说和代理无关？浪费时间，我以为你国内😓

**Comment by oldip** [comment]
> 那你说和代理无关？浪费时间，我以为你国内😓

因为我关掉代理试过没用，也试过用国内ip也没用，而且一开始手机没开代理在海外还是可以发送消息，只有电脑不行，所以我当时觉得和代理无关。
之后我在网上看见有其他人也会如此，我就开始研究电脑发送过去的packet，发现bilibili不吃IPv6，用IPv6他会当做韩国的IPv4，之后我又用大陆IPv4测试，成功发送消息，晚上回到家想让电脑连着国内IPv4 vpn，在搞的途中b站已经让我说话了

**Comment by z0z0r4** [comment]
你在海外是吧...那对B站来说就等价于开了代理...算了不管了

**Comment by Z15hawn** [comment]
> 你在海外是吧...那对B站来说就等价于开了代理...算了不管了

但是我在国内 我刚看了一下 还是没法回复

**Comment by Z15hawn** [comment]
这是send_danmaku返回的result:

`{'mode_info': {'mode': 0, 'show_player_type': 0, 'extra': '{"send_from_me":true,"mode":0,"color":16777215,"dm_type":0,"font_size":25,"player_mode":1,"show_player_type":0,"content":"04！","user_hash":"975950708","emoticon_unique":"","bulge_display":0,"recommend_score":5,"main_state_dm_color":"","objective_state_dm_color":"","direction":0,"pk_direction":0,"quartet_direction":0,"anniversary_crowd":0,"yeah_space_type":"","yeah_space_url":"","jump_to_url":"","space_type":"","space_url":"","animation":{},"emots":null,"is_audited":false,"id_str":"5e7c698f623dca970a24152f3b66613154","icon":null,"show_reply":true,"reply_mid":0,"reply_uname":"","reply_uname_color":"","reply_is_mystery":false,"hit_combo":0}', 'user': {'uid': 3493140270942635, 'base': {'name': '碎觉不流口水BOT', 'face': 'https://i2.hdslb.com/bfs/face/2af3ceb21d55505eb880b1477c16f6c720f23f94.jpg', 'name_color': 0, 'is_mystery': False, 'risk_ctrl_info': None, 'origin_info': {'name': '碎觉不流口水BOT', 'face': 'https://i2.hdslb.com/bfs/face/2af3ceb21d55505eb880b1477c16f6c720f23f94.jpg'}, 'official_info': {'role': 0, 'title': '', 'desc': '', 'type': -1}, 'name_color_str': ''}, 'medal': None, 'wealth': None, 'title': None, 'guard': None, 'uhead_frame': None, 'guard_leader': {'is_guard_leader': False}}}, 'dm_v2': None}`


> 你在海外是吧...那对B站来说就等价于开了代理...算了不管了
