### ISSUE TITLE
[提问] {session.send_msg发送消息,能在本地看到消息记录,但是对方却没有收到消息}

### ISSUE THREAD

**Issue by lion9652775** [Nemo2011/bilibili-api#771]
**Python 版本：** 3.12

**模块版本：** v16.2.0

**运行环境：** Windows 

---

# 这是测试函数
async def test1():
    """
    :return:
    """
    credential = Credential(
        sessdata="xxxxxxxxxxxxxxxxxxxxx",
        bili_jct="xxxxxxxxxxxxxx", buvid3="xxxxxxxxxxxxxxxxxxxxx",
        dedeuserid="xxxxxxxxxxxxxxxxxxxx")

    try:
        info = await session.send_msg(credential, 631486536, session.EventType.TEXT, '你好呀')
        # 打印信息
        print('info:', info)
    except Exception as e:
        print('出现异常,', str(e))

# 结果显示
info: {'msg_key': 7379969037453279067, 'msg_content': '{"content": "\\u4f60\\u597d\\u5440"}', 'key_hit_infos': {}}

消息记录
![1](https://github.com/Nemo2011/bilibili-api/assets/162133938/aec1cf7c-e82f-499c-9796-07deeea86e3f)

但是其实还是可以发送私信，手动发送的才是真正可以传达到对面的私信
![2](https://github.com/Nemo2011/bilibili-api/assets/162133938/44289ece-faaa-4b00-9953-9c9714259f40)

我不理解为什么会这样?

**Comment by Drelf2018** [comment]
应该就是因为这个“只能发送一条消息”导致的

**Comment by lion9652775** [comment]
这个要怎么解决呢?还需要调其它接口吗

**Comment by z0z0r4** [comment]
> 这个要怎么解决呢?还需要调其它接口吗

你网页不能发的，这里当然也不能，无解

**Comment by lion9652775** [comment]
网页发送是没有问题的.你没有搞明白我的意思。你调用这个接口发送消息，这个消息只是在你本地发送了，有消息记录，但是对面并没有收到

**Comment by z0z0r4** [comment]
有没有可能，不管你是在网页发送的还是调用接口发送的，只要依旧是 `只能发送一条消息`，对方都收不到，只有你在尝试发送，有无消息记录根本无所谓

**Comment by lion9652775** [comment]
> 有没有可能，不管你是在网页发送的还是调用接口发送的，只要依旧是 `只能发送一条消息`，对方都收不到，只有你在尝试发送，有无消息记录根本无所谓

这个可以通过网页再次发送消息来确认。如果是确实已经发送了一条消息，再次发送，网页会有提示的。
![Uploading 3.png…]()

**Comment by lion9652775** [comment]
![Uploading 3.png…]()

**Comment by z0z0r4** [comment]
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/1043f431-6d44-48a0-b2b3-7330972226da)

**Comment by lion9652775** [comment]
![Uploading 3.png…]()

**Comment by lion9652775** [comment]
![Uploading 3.png…]()

**Comment by lion9652775** [comment]
![3](https://github.com/Nemo2011/bilibili-api/assets/162133938/e3ad6d54-4522-47f9-bbfd-d3b0cfe252a4)

**Comment by lion9652775** [comment]
问题解决:必须先调用fetch_session_msgs，再调用send_msg，才能够保证成功发送

**Comment by M4cr0-storm** [comment]
2024年9月18日测试，给陌生人发消息无法发送成功，先调用fetch_session_msgs，再调用send_msg也不行

**Comment by lenual** [comment]
> 2024年9月18日测试，给陌生人发消息无法发送成功，先调用fetch_session_msgs，再调用send_msg也不行

2024年10月7日测试，一样也不行

**Comment by tianyu365** [comment]
> 2024年9月18日测试，给陌生人发消息无法发送成功，先调用fetch_session_msgs，再调用send_msg也不行

2024年10月17日测试，一样也不行
