### ISSUE TITLE
【提问】{B站上传视频报错，Code 21150,投稿入口升级中，请重新编辑稿件}

### ISSUE THREAD

**Issue by XUAN-CSU** [Nemo2011/bilibili-api#78]
**Python 版本：** 3.9

**模块版本：** 12.5.1

**运行环境：** Linux

---

[return_information.txt](https://github.com/Nemo2011/bilibili-api/files/9646818/return_information.txt)

github_code.txt是源代码，return_information.txt是返回的结果，因为这个错误卡一天了，可以帮忙看看吗？非常感谢。

**Comment by XUAN-CSU** [comment]
#coding=UTF-8
import asyncio
from bilibili_api import sync, video_uploader, Credential

async def main():
	wlc_credential = Credential(sessdata="xxxx", bili_jct="xxxx", buvid3="xxxx",dedeuserid="xxxx")
	wlc_meta = {
        "act_reserve_create": 0,
        "copyright": 1,
        "source": '',
        "cover": '',
        "desc": 'desc_test',
        "desc_format_id": 0,
        "dynamic": 'dynamic_test',
        "interactive": 0,
        "no_reprint": 0,
        "open_elec": 0,
        "origin_state": 0,
        "subtitles": {
            "lan": '',
            "open": 0 
        },
        "tag": 'VOA,English',
        "tid": 174,
        "title": 'VOA',
        "up_close_danmaku": True,
        "up_close_reply": True,
        "up_selection_reply": False,
        "videos": []
	}
    
	wlc_page0 = video_uploader.VideoUploaderPage(path='VOA_202209240900.mp4', title='123')

	uploader = video_uploader.VideoUploader(pages=[wlc_page0], meta=wlc_meta, credential=wlc_credential)

	@uploader.on("__ALL__")
	async def ev(data):
		print(data)

	await uploader.start()




#if __name__ == '__main__':
    #asyncio.get_event_loop().run_until_complete(main())


sync(main())

**Comment by XUAN-CSU** [comment]
上面是我的代码，我想请问下是由于B站的API接口在变换使得我不能成功上传吗？

**Comment by Nemo2011** [comment]
不确定。有可能就是这个接口废了。有必要调查一下。

**Comment by XUAN-CSU** [comment]
> 不确定。有可能就是这个接口废了。有必要调查一下。

谢谢回答，我个人觉得也是这个接口的原因，对了，我用过bilibili_uploader的库同样是上传文件，也是Code21150,投稿入口升级中，请重新编辑稿件。
