### ISSUE TITLE
封面不合法

### ISSUE THREAD

**Issue by farjar** [Nemo2011/bilibili-api#782]
**Python 版本：Python 3.11.9 (main, May 23 2024, 01:11:37) [GCC 13.2.1 20240309] on linux

**模块版本：bilibili-api-python==16.2.0

**运行环境：Linux

---

raise ValueError(f"封面不合法 {self.cover.__repr__()}")
ValueError: 封面不合法 Picture(height='720', width='1280', imageType='png', size=949, url='file://./downloads/UNIV-KEEP IT LUV-1ST SINGLE ALBUM Keep it luv.PNG')，用JPEG和PNG都试过了，都报一样的错误

**Comment by z0z0r4** [comment]
`Picture.from_file(path="./downloads/UNIV-KEEP IT LUV-1ST SINGLE ALBUM Keep it luv.PNG')`

**Comment by farjar** [comment]
不懂额，要改哪里？

**Comment by z0z0r4** [comment]
> 不懂额，要改哪里？

别把路径写 url 试试看…用 from_file 加载

**Comment by farjar** [comment]
> > 不懂额，要改哪里？
> 
> 别把路径写 url 试试看…用 from_file 加载
有具体的吗，cover=from_file ...这个提示不对额

**Comment by farjar** [comment]
> > 不懂额，要改哪里？
> 
> 别把路径写 url 试试看…用 from_file 加载

有具体的吗，cover=from_file ...这个提示不对额

**Comment by z0z0r4** [comment]
wtf

**Comment by z0z0r4** [comment]
`cover=Picture.from_file(path="./downloads/UNIV-KEEP IT LUV-1ST SINGLE ALBUM Keep it luv.PNG')`

**Comment by farjar** [comment]
> `cover=Picture.from_file(path="./downloads/UNIV-KEEP IT LUV-1ST SINGLE ALBUM Keep it luv.PNG')`
> 
> 这样你能理解了吗

in uploadBilibili
    cover=Picture.from_file(path=video_meta['cover']), 
          ^^^^^^^
NameError: name 'Picture' is not defined

**Comment by farjar** [comment]
改用json传参没问题

**Comment by Alkaid-C** [comment]
> `cover=Picture.from_file(path="./downloads/UNIV-KEEP IT LUV-1ST SINGLE ALBUM Keep it luv.PNG')`
> 
> 这样你能理解了吗

等下，请问Picture是哪个库？
