### ISSUE TITLE
[提问] 哔站网页会定期刷新session，是否有类似api可以调用

### ISSUE THREAD

**Issue by gaonan1212** [Nemo2011/bilibili-api#786]
**Python 版本：** 3.10.11

**模块版本：** -

**运行环境：** Linux

---
主要需求是服务器上执行，避免手动操作登录相关的操作，是否有类似api能用老session拿到新session，保证credential一直可用

**Comment by z0z0r4** [comment]
自己看文档刷新 cookie

**Comment by gaonan1212** [comment]
> 自己看文档刷新 cookie

抱歉没仔细看，谢谢了
