### ISSUE TITLE
提问：动态评论发不出去

### ISSUE THREAD

**Issue by Naxrin** [Nemo2011/bilibili-api#83]
**Python 版本：** 3.10

**模块版本：** x.x.x

**运行环境：** Windows / Linux / MacOS

---

资源类型改成VIDEO，oid改成某某av号是能成功的，但是评论动态不行。（oid填的是动态页的t.bilibili.com/和?spm_id_from...之间的一串数，字符串和int值都试过）

报错内容：
接口返回错误代码：-404，信息：啥都木有。
{'code': -404, 'message': '啥都木有', 'ttl': 1, 'data': None}

代码内容：
#coding=gbk
from bilibili_api import login, user, sync,comment
print("请登录：")
credential = login.login_with_qrcode()
try:
    credential.raise_for_no_bili_jct() # 判断是否成功
    credential.raise_for_no_sessdata() # 判断是否成功
except:
    print("登陆失败。。。")
    exit()
print("欢迎，", sync(user.get_self_info(credential))['name'], "!")

text=r"text"

async def main():
    c = await comment.send_comment(text=text,oid='xxx' ,type_=comment.CommentResourceType.DYNAMIC,credential=credential)
    print('success')
sync(main())

**Comment by Nemo2011** [comment]
是画册动态吗

**Comment by Naxrin** [comment]
> 是画册动态吗

不是，是只有文字没有图的动态。画册还没试过

**Comment by Nemo2011** [comment]
能展示一下 oid 吗，我尝试一下

**Comment by Naxrin** [comment]
> 能展示一下 oid 吗，我尝试一下

我刚重新试了一遍才注意到试验动态是带图的，不好意思犯傻了
