### ISSUE TITLE
我很好奇为什么VPN会导致解码错误

### ISSUE THREAD

**Issue by blueOf** [Nemo2011/bilibili-api#85]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 73: invalid start byte

代码:
import asyncio
from bilibili_api import video

async def main():
    # 实例化 Video 类
    v = video.Video(bvid="BV1uv411q7Mv")
    # 获取信息
    info = await v.get_info()
    # 打印信息
    print(info)

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())

**Comment by Nemo2011** [comment]
你试一下用 requests 访问网站能不能正常获取源代码？

**Comment by blueOf** [comment]
确实 开了vpn request也请求失败 我去找找解决方法

**Comment by blueOf** [comment]
还是代理的问题 解决方法要么加一个代理参数 
要么代理参数设置为null

**Comment by z0z0r4** [comment]
你的代理设置有问题吧，建议发出来看看
**或者梯子本身太烂**
