### ISSUE TITLE
【提问】直播弹幕类接口可能有问题

### ISSUE THREAD

**Issue by cabinary** [Nemo2011/bilibili-api#86]
**Python 版本：** 3.8

**模块版本：** 12.5.2

**运行环境：** Linux

---

今天在使用LiveDanmuku时突然发现卡在了获取真实房间号 stderr.log：
[2022-10-08 13:12:40,289][WARNING]创建主数据库容器成功
[2022-10-08 13:12:40,718][WARNING]创建缓存数据库容器成功
[2022-10-08 13:12:40,784][WARNING]获取用户-----------会话成功
[-----------][2022-10-08 13:12:40,790][INFO] 准备连接直播间 --------
[-----------][2022-10-08 13:12:40,791][DEBUG] 正在获取真实房间号

在怀疑是不是存在接口更新导致失效，还是说ip被墙这种，但是测试过的其他api一律有效，唯独卡死在这里的获取。

**Comment by Nemo2011** [comment]
我这里测试成功的啊。你的房号是多少？

**Comment by cabinary** [comment]
> 我这里测试成功的啊。你的房号是多少？

我明白了，我用了一个比较低级的方式来对一组事件做等待。结果就是另外一个Task阻塞了live的Task。
