### ISSUE TITLE
获取用户关注列表和粉丝列表的两个建议

### ISSUE THREAD

**Issue by niu541412** [Nemo2011/bilibili-api#97]
感谢继续维护开发这个项目啊，好用，提个功能上的建议

1. 另一个获取关注列表的接口
接口参考 https://github.com/SocialSisterYi/bilibili-API-collect/pull/521
此接口的好处是可以获取到隐藏关注列表的用户的关注，不知道是否长期有效。
可以考虑优先用原接口，如果检测到用户设置了隐藏，就根据get_followings的参数是否用第二个接口再次尝试。

2. user模块get_followings和get_followers需要ps参数
虽然只能获取到前5页，不过ps参数决定每页返回的用户数目，所以最多可以返回5*50=250个用户。
不加ps参数的话，只能获取到100个。
同时，get_all_followings里面也可以改一下

**Comment by Nemo2011** [comment]
get_all_followings 可以直接获取全部的关注
