### ISSUE TITLE
【提问】如何才能增加观看直播时长

### ISSUE THREAD

**Issue by xtherk** [Nemo2011/bilibili-api#98]
是这样的, 个人闲时会玩玩OW这个游戏，官方OWL联赛会根据观看时长赠送皮肤，个人又没有那么多时间挂时长，于是想写个脚本仍服务器上挂一下，无论怎样都不会增加时长，请问B站增加观看时长的api有了解吗，个人可以自行添加。 
我翻了下B站直播相关的油猴脚本有调用`heartbeat/webHeartBeat`这个api的，我增加了一下发现没有什么用。

下面是主要逻辑

```py
credential = Credential(sessdata, bili_jct, buvid3, dedeuserid)

room_id = xxxx
room = live.LiveRoom(room_id, credential)
sync(room.get_user_info_in_room())
room_info = sync(room.get_room_info())
print(f"进入{room_info['anchor_info']['base_info']['uname']}直播间, 标题【{room_info['room_info']['title']}】")
sync(room.get_room_play_info_v2(live_qn=live.ScreenResolution.FLUENCY))
danmaku = live.LiveDanmaku(room_id, False, credential)


@danmaku.on("ALL")
async def danmaku_all(event):
    pass
    # print(event)


def heartbeat():
    while True:
        sync(room.get_room_info())
        # 包装的 webHeartBeat 这个api
        print(sync(room.heartbeat()))
        time.sleep(60)


threading.Thread(target=heartbeat).start()
sync(danmaku.connect())
```

**Comment by Nemo2011** [comment]
LiveDanmaku 能自动发送心跳包

**Comment by xtherk** [comment]
> LiveDanmaku 能自动发送心跳包

我有看到，但是确实不增加直播观看时长。所以F12看了一下请求发现有调用webHeartBeat 这个接口，所以加上试试

**Comment by Nemo2011** [comment]
要不先展示一下你自己写心跳包函数

**Comment by xtherk** [comment]
> 要不先展示一下你自己写心跳包函数

抱歉，下班回家了，电脑在公司里，明早我贴截图

**Comment by xtherk** [comment]
![image](https://user-images.githubusercontent.com/33031194/199863421-ab1c9158-ae9c-41cb-a7b0-3dcb3d15e0ad.png)

![1667524185424](https://user-images.githubusercontent.com/33031194/199863687-9cc373e7-3fb2-4806-892c-1f85e16942da.jpg)

**Comment by xtherk** [comment]
`60|76|1|0` 这个参数 第一个参数是心跳间隔，第二个参数是直播间id (我看浏览器里用的是display_id，我用的是真实id，不知道是不是这个原因)，第三个和第四个参数不清楚，写死了

**Comment by Nemo2011** [comment]
display_id 用 `self.room_display_id` 试一试

**Comment by Nemo2011** [comment]
self.__get_ruid 不是 display_id

**Comment by xtherk** [comment]
> self.__get_ruid 不是 display_id

ruid是真实id， display_id是显示id， 我都试过了 都不行的

**Comment by Nemo2011** [comment]
那就是房间的长号了。一个房间有三个号：显示id(display_id), 真实id(ruid), 真实房号。

``` python
room_id = (await self.get_room_play_info())["room_id"]
```

把直播间 id 的值换成上面代码的 room_id，再试一下。

**Comment by Nemo2011** [comment]
``` python
async def heartbeat(setf, interval)
self. credential. raise_for_no_sessdata ( )
api =
str(base64.b64encode (f" {interval} I {await . encode ("utf-8")),
hb =
data -
"Utf-8")
return await request(
" heartbeat" :
data-data,
credential-self. credential
```

**Comment by xtherk** [comment]
> 那就是房间的长号了。一个房间有三个号：显示id(display_id), 真实id(ruid), 真实房号。
> 
> ```python
> room_id = (await self.get_room_play_info())["room_id"]
> ```
> 
> 把直播间 id 的值换成上面代码的 room_id，再试一下。

好的，活动现在没了，等有活动的时候我试一下，主要我看web接口里传的值就是display_id

**Comment by Nemo2011** [comment]
先把这部分功能加上

**Comment by Nemo2011** [comment]
`dev` 仓库把原来的心跳包发送间隔时间换成了 60 秒（原来 30 秒），再试一试

**Comment by xtherk** [comment]
> `dev` 仓库把原来的心跳包发送间隔时间换成了 60 秒（原来 30 秒），还没测试

好的 感谢，最近比赛结束了，活动也跟着结束了。 等再有活动我试试，不知道其他游戏分区有这种时长活动不，等我找找

**Comment by Nemo2011** [comment]
鞭一下尸 心跳包当时的代码其实有问题 需要传入的真实房间 id 不是 ruid，这是当时模块对直播功能相关的认知问题，应该使用 get_room_id 获取真实房间 id。
