### ISSUE TITLE
channel.json文件包含的分区信息有些过期了

### ISSUE THREAD

**Issue by niu541412** [Nemo2011/bilibili-api#99]
https://github.com/Nemo2011/bilibili-api/blob/main/bilibili_api/data/channel.json
包含的分区信息有些旧了。

最新版的主页可以考虑用
https://s1.hdslb.com/bfs/static/laputa-home/client/assets/index.6d9f1875.js
这个文件内的_t[channellist]变量转换。不过和以前的字典的键值有些减少。

**Comment by Nemo2011** [comment]
重新整理一下
